--liquibase formatted sql
--changeset vivek.subramanya@impactanalytics.co:alerts_product_level_MTP-20674 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--inventory_smart.alerts_product_level definition

CREATE TABLE inventory_smart.alerts_product_level (
	article varchar NOT NULL,
	l0_name varchar NOT NULL,
	l1_name varchar NOT NULL,
	l2_name varchar NOT NULL,
	l3_name varchar NOT NULL,
	l4_name varchar NOT NULL,
	dtc_year varchar NULL,
	pfs_year varchar NULL,
	dtc_season varchar NULL,
	pfs_season varchar NULL,
	brand varchar NULL,
	product_description varchar NULL,
	style_color_id varchar NOT NULL,
	dc_flag int4 NULL,
	excs_flg int4 NULL,
	shrtfl_flg int4 NULL,
	stckout_flg int4 NULL,
	oh float4 NULL,
	it float4 NULL,
	oo float4 NULL,
	lw_units float4 NULL,
	lw_revenue float4 NULL,
	lw_margin float4 NULL,
	lw_gm_perc float4 NULL,
	promo_percentage float4 NULL,
	wos float4 NULL,
	size_integrity float4 NULL,
	week_to_date_sales float4 NULL,
	last_day_sales float4 NULL,
	oh_dc float4 NULL,
	sales_1_ago float4 NULL,
	sales_2_ago float4 NULL,
	sales_3_ago float4 NULL,
	sales_4_ago float4 NULL,
	sales_5_ago float4 NULL,
	sales_6_ago float4 NULL,
	sales_7_ago float4 NULL,
	sales_8_ago float4 NULL,
	aur float4 NULL,
	excs_is_resolved int4 NULL,
	shrtfl_is_resolved int4 NULL,
	stckout_is_resolved int4 NULL,
	CONSTRAINT alerts_product_level_pk PRIMARY KEY (article)
);
