import agGridColumnFormatter from "core/Utils/agGrid/column-formatter";
import { useEffect, useState } from "react";
import AgGridComponent from "core/Utils/agGrid";
import { useStyles } from "./style.js";

const TestPivotTable = () => {
  let [columnData, setColumnData] = useState([]);
  let [rowData, setRowData] = useState([]);
  const classes = useStyles();

  useEffect(() => {
    let columnConfig = [
      {
        column_name: "advanced_search",
        tab_code: 0,
        search_preference: {
          range: [],
          search: [],
        },
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "SKU ID",
        column_name: "product_id",
        dimension: "Product",
        type: "number",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "Dep",
        column_name: "department",
        dimension: "Product",
        type: "string",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "Class",
        column_name: "class",
        dimension: "Product",
        type: "string",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "Weeks",
        column_name: "week",
        dimension: "Product",
        type: "string",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "Month",
        column_name: "month",
        dimension: "Product",
        type: "string",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "Year",
        column_name: "year",
        dimension: "Product",
        type: "string",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "Revenue",
        column_name: "revenue",
        dimension: "Product",
        type: "number",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "Inventory",
        column_name: "inventory",
        dimension: "Product",
        type: "number",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
      {
        sub_headers: [],
        tc_code: 504,
        label: "OOS - Flag",
        column_name: "oos_flag",
        dimension: "Product",
        type: "number",
        is_frozen: false,
        is_editable: false,
        is_aggregated: false,
        order_of_display: 1,
        is_hidden: false,
        is_required: false,
        tc_mapping_code: "200030",
        aggregate_type: "",
        formatter: "",
        is_row_span: false,
        footer: "",
        is_searchable: true,
        extra: {},
        is_sortable: true,
        width: 200,
        is_deleted: false,
        is_master_group: false,
      },
    ];
    // let columnConfig = [
    //   {
    //     column_name: "year",
    //     label: "year",
    //     width: 200,
    //   },
    //   {
    //     column_name: "values_label",
    //     label: "Values",
    //     width: 200,
    //   },
    //   {
    //     column_name: "value",
    //     label: "",
    //     width: 200,
    //   },
    // ];
    let columnInfo = agGridColumnFormatter(
      columnConfig,
      {},
      {},
      false,
      null,
      false
    );
    setColumnData(columnInfo);
    let rowConfig = [
      {
        product_id: 134143,
        department: "D1",
        class: "C1",
        revenue: 4499,
        inventory: 87,
        oos_flag: 1,
        week: "FW 1",
        month: "M 1",
        year: "2022",
      },
      {
        product_id: 124123,
        department: "D1",
        class: "C2",
        revenue: 1870,
        inventory: 75,
        oos_flag: 1,
        week: "FW 2",
        month: "M 1",
        year: "2022",
      },
      {
        product_id: 214,
        department: "D1",
        class: "C3",
        revenue: 3549,
        inventory: 66,
        oos_flag: 1,
        week: "FW 3",
        month: "M 1",
        year: "2022",
      },
      {
        product_id: 123,
        department: "D2",
        class: "C4",
        revenue: 1465,
        inventory: 90,
        oos_flag: 0,
        week: "FW 4",
        month: "M 1",
        year: "2022",
      },
      {
        product_id: 124124,
        department: "D2",
        class: "C5",
        revenue: 2296,
        inventory: 77,
        oos_flag: 0,
        week: "FW 5",
        month: "M 2",
        year: "2022",
      },
      {
        product_id: 1231,
        department: "D2",
        class: "C6",
        revenue: 1403,
        inventory: 69,
        oos_flag: 0,
        week: "FW 6",
        month: "M 2",
        year: "2022",
      },
      {
        product_id: 13214,
        department: "D3",
        class: "C7",
        revenue: 2091,
        inventory: 65,
        oos_flag: 1,
        week: "FW 7",
        month: "M 2",
        year: "2022",
      },
      {
        product_id: 123213,
        department: "D3",
        class: "C8",
        revenue: 4662,
        inventory: 85,
        oos_flag: 1,
        week: "FW 8",
        month: "M 2",
        year: "2022",
      },
      {
        product_id: 123124,
        department: "D1",
        class: "C1",
        revenue: 4499,
        inventory: 87,
        oos_flag: 1,
        week: "FW 1",
        month: "M 1",
        year: "2021",
      },
      {
        product_id: 12312,
        department: "D1",
        class: "C2",
        revenue: 1870,
        inventory: 75,
        oos_flag: 1,
        week: "FW 2",
        month: "M 1",
        year: "2021",
      },
      {
        product_id: 421,
        department: "D1",
        class: "C3",
        revenue: 3549,
        inventory: 66,
        oos_flag: 1,
        week: "FW 3",
        month: "M 1",
        year: "2021",
      },
      {
        product_id: 123124213,
        department: "D2",
        class: "C4",
        revenue: 1465,
        inventory: 90,
        oos_flag: 0,
        week: "FW 4",
        month: "M 1",
        year: "2021",
      },
      {
        product_id: 12312421,
        department: "D2",
        class: "C5",
        revenue: 2296,
        inventory: 77,
        oos_flag: 0,
        week: "FW 5",
        month: "M 2",
        year: "2021",
      },
      {
        product_id: 213124,
        department: "D2",
        class: "C6",
        revenue: 1403,
        inventory: 69,
        oos_flag: 0,
        week: "FW 6",
        month: "M 2",
        year: "2021",
      },
      {
        product_id: 12312321,
        department: "D3",
        class: "C7",
        revenue: 2091,
        inventory: 65,
        oos_flag: 1,
        week: "FW 7",
        month: "M 2",
        year: "2021",
      },
      {
        product_id: 321422,
        department: "D3",
        class: "C8",
        revenue: 4662,
        inventory: 85,
        oos_flag: 1,
        week: "FW 8",
        month: "M 2",
        year: "2021",
      },
    ];

    // let rowConfig = [
    //   {
    //     value: 21835,
    //     values_label: "Sum of revenue",
    //     year: "2022",
    //   },
    //   {
    //     value: 614,
    //     values_label: "Sum of inventory",
    //     year: "",
    //   },
    //   {
    //     value: 21835,
    //     values_label: "Sum of revenue",
    //     year: "2021",
    //   },
    //   {
    //     value: 614,
    //     values_label: "Sum of inventory",
    //     year: "",
    //   },
    // ];
    setRowData(rowConfig);
  }, []);

  return (
    <div className={classes.container}>
      <p>
        <strong>Pivot Testing Table :</strong>
      </p>
      <AgGridComponent
        columns={columnData}
        rowdata={rowData}
        pagination={true}
        uniqueRowId="product_id"
        sizeColumnsToFitFlag
        adjustTableHeight
        groupIncludeTotalFooter={true}
        groupIncludeFooter={true}
        enablePivot={true}
      />
    </div>
  );
};

export default TestPivotTable;
