-- liquibase formatted sql
-- changeset shrinidhi.choragi@impactanalytics.co:store_attributes_filter stripComments:false splitStatements:false context: db_sync labels:store_attributes_filter
-- comment: initial changeset for store_attributes_filter

-- "global".store_attributes_filter definition
-- DROP TABLE "global".store_attributes_filter;

CREATE TABLE "global".store_attributes_filter (
	store_code varchar NOT NULL,
	store_name varchar NOT NULL,
	store_description text NULL,
	active bool NOT NULL,
	special_classification varchar NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	dc_code int4 NULL,
	fc_code int4 NULL,
	is_deleted bool NULL,
	s0_name varchar NOT NULL,
	s1_name varchar NULL,
	account varchar NULL,
	active_flg bool NULL,
	active_store_status bool NULL,
	ad_market varchar NULL,
	business varchar NULL,
	ca_northern varchar NULL,
	ca_northern_imputed varchar NULL,
	capacity_cd varchar NULL,
	capacity_dsc varchar NULL,
	ca_region varchar NULL,
	ca_region_imputed varchar NULL,
	ca_store_size int8 NULL,
	ca_store_size_imputed int8 NULL,
	ca_store_type varchar NULL,
	ca_store_type_imputed varchar NULL,
	category varchar NULL,
	center_format_type varchar NULL,
	center_format_type_imputed varchar NULL,
	channel varchar NOT NULL,
	city varchar NULL,
	climate varchar NULL,
	close_date date NULL,
	closed_reason varchar NULL,
	country varchar NOT NULL,
	dc_name varchar NULL,
	dc_store_transit_time int8 NULL,
	district varchar NULL,
	fall_climate_cd varchar NULL,
	fall_climate_dsc varchar NULL,
	gl_company_id int8 NULL,
	gl_location_number varchar NULL,
	international_store varchar NULL,
	last_update date NULL,
	latitude float8 NULL,
	load_date date NULL,
	location_id int8 NULL,
	location_type int8 NULL,
	longitude float8 NULL,
	mall_name varchar NULL,
	ofc_stores varchar NULL,
	old_store_code varchar NULL,
	omni_eligiblity_flag int8 NULL,
	open_date date NULL,
	open_to_receive_date date NULL,
	phone varchar NULL,
	precipitation varchar NULL,
	q_brand_desc varchar NULL,
	q_brand_dnum varchar NULL,
	q_brand_id int8 NULL,
	q_brand_sdesc varchar NULL,
	q_brand_snum varchar NULL,
	q_chain_desc varchar NULL,
	q_chain_dnum varchar NULL,
	q_chain_id int8 NULL,
	q_chain_sdesc varchar NULL,
	q_chain_snum varchar NULL,
	q_chnl_dnum int8 NULL,
	q_chnl_id int8 NULL,
	q_chnl_sdesc varchar NULL,
	q_chnl_snum int8 NULL,
	q_dc_desc varchar NULL,
	q_dc_dnum varchar NULL,
	q_dc_id int8 NULL,
	q_dc_snum varchar NULL,
	q_dst_dnum varchar NULL,
	q_dst_id int8 NULL,
	q_dst_snum varchar NULL,
	q_rgn_dnum varchar NULL,
	q_rgn_id int8 NULL,
	q_rgn_snum varchar NULL,
	q_sbs_store_desc varchar NULL,
	q_sbs_store_num varchar NULL,
	q_str_addr1 varchar NULL,
	q_str_addr2 varchar NULL,
	q_str_cmp_dt date NULL,
	q_str_dnum varchar NULL,
	q_str_grade varchar NULL,
	q_str_id varchar NOT NULL,
	q_str_sdesc varchar NULL,
	q_str_selling_flg int8 NULL,
	q_str_sls_sqft int8 NULL,
	q_str_snum varchar NULL,
	q_str_status varchar NULL,
	q_zone_desc varchar NULL,
	q_zone_id varchar NULL,
	region varchar NULL,
	region_imputed varchar NULL,
	rtl_district_states varchar NULL,
	rtl_store_category_dsc varchar NULL,
	shrinkage_factor float8 NULL,
	source_id varchar NULL,
	spring_climate_cd varchar NULL,
	spring_climate_desc varchar NULL,
	state varchar NULL,
	store_capacity int8 NULL,
	store_comp_flag int8 NULL,
	store_concept varchar NULL,
	store_type varchar NULL,
	sub_channel varchar NOT NULL,
	summer_climate_cd varchar NULL,
	summer_climate_desc varchar NULL,
	traffic_cmp_dt date NULL,
	volume_cd varchar NULL,
	volume_dsc varchar NULL,
	winter_climate_cd varchar NULL,
	winter_climate_desc varchar NULL,
	zipcode varchar NULL,
	CONSTRAINT store_attributes_filter_pk PRIMARY KEY (store_code),
	CONSTRAINT store_attributes_filter_fk FOREIGN KEY (store_code) REFERENCES "global".store_master(store_code) ON DELETE CASCADE
);