import { makeStyles } from "@mui/styles";

const rem = (px) => `${px / 16}rem`;

export const useStyles = makeStyles(() => ({
  pannelContainer: {
    padding: "16px",
    background: "#fff",
    borderRadius: "8px",
  },
  flex_1: {
    flex: 1,
  },
  subMetricLabelStyles: {
    color: "#8E8E93",
    fontFamily: "Manrope",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "18px",
    marginBottom: "2px",
    width: "100px",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  },
  subMetricsValueStyles: {
    fontFamily: "Manrope",
    fontWeight: "600",
    fontSize: "14px",
    color: "#1F2B4D",
  },
  trendTextStyles: {
    fontFamily: "Manrope",
    fontSize: "0.70rem",
    maxWidth: "14ch",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    fontWeight: 600,
    opacity: 0.85,
  },
  cardStyles_WithSubMetrics: {
    width: "auto",
    height: "100px",
    borderRadius: "8px",
    boxShadow: "0px 0px 1.2px 0px rgba(0, 0, 0, 0.25)",
    padding: "12px",
  },
  cardStyles_WithNoSubMetrics: {
    width: "auto",
    height: "auto",
    borderRadius: "8px",
    boxShadow: "0px 0px 1.2px 0px rgba(0, 0, 0, 0.25)",
    padding: "16px 20px",
  },

  flexContainerStyles: {
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    alignItems: "center",
  },
  flexItemStyles: {
    display: "flex",
    alignItems: "center",
    height: "30px",
  },
  titleSubTitleFlex: {
    display: "flex",
    flexDirection: "column",
    marginTop: "5px",
  },
  marginTop_10: {
    marginTop: "10px",
  },
  marginRight_10: {
    marginRight: "10px",
  },
  marginLeft_4: {
    marginLeft: "4px",
  },
  flex_center: {
    display: "flex",
    alignItems: "center",
  },
  flex_column: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  icon_container: {
    flexBasis: "20%",
    marginRight: "1.25rem",
  },
  metricStyles: {
    backgroundColor: "#08BD80",
    color: "white",
    padding: "1px 8px",
    borderRadius: "4px",
    fontFamily: "Manrope",
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    maxHeight: "25px",
  },
  withSubMetricsNoSubTitleTitleStyles: {
    fontFamily: "Manrope",
    fontSize: "16px",
    fontWeight: "600",
    lineHeight: "24px",
    color: "#0D152C",
    width: "200px",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    marginTop: "-5px",
  },
  withSubMetricWithSubTitleTitleStyles: {
    fontFamily: "Manrope",
    fontSize: "16px",
    fontWeight: "600",
    lineHeight: "24px",
    color: "#0D152C",
    width: "200px",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    marginTop: "-5px",
  },
  withSubMetircsSubtitleStyles: {
    fontFamily: "Manrope",
    fontSize: "12px",
    lineHeight: "24px",
    color: "#758490",
    width: "200px",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    marginTop: "-6px",
  },
  noSubMetricsFlexContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    minWidth: "250px",
  },
  noSubMetricsLabelStyles: {
    color: "#1f2a4d",
    fontFamily: "Manrope",
    fontSize: "15px",
    textOverflow: "ellipsis",
    overflow: "hidden",
    wordWrap: "break-word",
    fontWeight: 400,
  },
  noSubMertricsValueStyles: {
    color: "#1D1D1D",
    fontFamily: "Manrope",
    fontSize: "16px",
    overflow: "hidden",
    fontWeight: 600,
    textOverflow: "ellipsis",
  },
  noSubMetricsUnitsStyle: {
    fontFamily: "Manrope",
    fontSize: "14px",
    color: "#758490",
    wordWrap: "break-word",
    fontWeight: 400,
    letterSpacing: "0.14px",
    textTransform: "lowercase",
  },
  flex_row: {
    display: "flex",
    alignItems: "end",
    gap: "2px",
  },
  expandButtonStyles: {
    width: rem(30),
    height: rem(30),
    borderRadius: "4px",
    padding: "0px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid #4259ee",
    minWidth: "unset",
    color: "#4259ee",
  },
  upTrendStyles: {
    marginLeft: "2px",
    color: "#24A148",
  },
  downTrendStyles: {
    marginLeft: "2px",
    color: "#DA1E28",
  },
  panelHeaderTestStyles: {
    fontSize: "14px",
    fontFamily: "Manrope",
    fontWeight: "bold",
  },
  singleSubMetricContainerStyles: {
    display: "flex",
    flexDirection: "column-reverse",
    alignItems: "flex-start",
    marginTop: "10px",
    marginLeft: "4px",
  },
  expandedPanelContainerStyles: {
    display: "flex",
    flexWrap: "wrap",
    gap: "20px",
    padding: "8px ",
    width: "100%",
  },
  nonExpandedContainerStyles: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    padding: "8px 0",
    width: "100%",
    overflowX: "auto",
    scrollBehavior: "smooth",
    scrollbarWidth: "none",
    paddingLeft: "2px",
  },
  navigationButtonStyles: {
    fontSize: "2rem",
    padding: 0,
    height: "30px",
    width: "30px",
    borderRadius: "50%",
    border: "0.8px solid #758490",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  cardComponentContainerStyles: {
    display: "flex",
    overflowX: "auto",
    scrollBehavior: "smooth",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
    flexGrow: 1,
    gap: "20px",
    padding: "10px 2px",
  },

  svgNoSubMetricsContainer: {
    width: "45px",
    height: "45px",
    padding: "5px",
    borderRadius: "8px",
  },
  svgSubMetricsContainer: {
    borderRadius: "8px",
    width: "30px",
    height: "30px",
    padding: "5px",
    marginRight: "8px",
  },

  rightAlignedContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "8px",
  },
  rightAlignedActualRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rightAlignedActualLabel: {
    fontSize: "14px",
    color: "#333",
    fontWeight: 600,
  },
  rightAlignedActualValue: {
    fontSize: "18px",
    fontWeight: 700,
  },
  rightAlignedComparisonRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  },
  rightAlignedComparisonLabel: {
    fontSize: "12px",
    color: "#666",
    width: "160px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  rightAlignedComparisonValues: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flex: 1,
    justifyContent: "flex-end",
  },
  rightAlignedForecastValue: {
    fontSize: "14px",
    color: "#333",
    width: "90px",
    textAlign: "right",
    flexShrink: 0,
  },
  rightAlignedArrowContainer: {
    width: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  rightAlignedDifferenceText: {
    fontSize: "12px",
    width: "140px",
    textAlign: "left",
    flexShrink: 0,
  },
  rightAlignedPositive: {
    color: "#4caf50",
  },
  rightAlignedNegative: {
    color: "#f44336",
  },
  rightAlignedArrowIcon: {
    fontSize: "16px",
  },
  verticalSeparator: {
    display: "inline-block",
    height: "16px",
    width: "1px",
    backgroundColor: "#d9dde7",
  },

  dummyIcon: {
    marginLeft: "-10px",
  },
}));
