import { INVENTORY_SUBMODULES_NAMES } from "modules/inventorysmart/constants-inventorysmart/stringConstants";

const {
  INVENTORY_STORE_CONSTRAINTS,
  INVENTORY_STORE_GRADE_CONSTRAINTS,
  INVENTORY_STORE_GROUP_CONSTRAINTS,
  OMS_ORDER_STATUS,
  OMS_ORDER_DELIVERY,
  OMS_ORDER_ORDERING,
  OMS_ORDER_SAFETY_STOCK,
  OMS_ORDER_POLICY,
  OMS_VENDOR_DC_POLICY,
  OMS_PO_CONVERSION,
  OMS_RULES_CONSTRAINTS,
  INVENTORY_USER_RESERVE,
  INVENTORY_SMA,
  OMS_SHIPMENT_CONSTRAINTS,
} = INVENTORY_SUBMODULES_NAMES;

export const tabModulePermissionMap = {
  store_allocations: [
    INVENTORY_STORE_CONSTRAINTS,
    INVENTORY_STORE_GRADE_CONSTRAINTS,
    INVENTORY_STORE_GROUP_CONSTRAINTS,
    INVENTORY_USER_RESERVE,
  ],
  constraints_oms: [
    OMS_ORDER_STATUS,
    OMS_ORDER_DELIVERY,
    OMS_ORDER_ORDERING,
    OMS_ORDER_SAFETY_STOCK,
    OMS_ORDER_POLICY,
    OMS_VENDOR_DC_POLICY,
    OMS_PO_CONVERSION,
    OMS_RULES_CONSTRAINTS,
    OMS_SHIPMENT_CONSTRAINTS,
  ],
  user_reserve: [INVENTORY_USER_RESERVE],
  sma: [INVENTORY_SMA],
  dc_transfer: [
    INVENTORY_SUBMODULES_NAMES.INVENTORY_DC_TRANSFER_CONSTRAINTS,
    INVENTORY_SUBMODULES_NAMES.INVENTORY_DC_SERVICE_LEVELS,
  ],
};

export const omsTabModulePermissionMap = {
  constraints_status: [OMS_ORDER_STATUS],
  constraints_delivery: [OMS_ORDER_DELIVERY],
  constraints_ordering: [OMS_ORDER_ORDERING],
  constraints_safety_stock: [OMS_ORDER_SAFETY_STOCK],
  constraints_order_policy: [OMS_ORDER_POLICY],
  constraints_vendor_dc_policy: [OMS_VENDOR_DC_POLICY],
  constraints_po_conversion: [OMS_PO_CONVERSION],
  vendor_constraints: [OMS_RULES_CONSTRAINTS],
  shipment_constraints: [OMS_SHIPMENT_CONSTRAINTS],
};
