--liquibase formatted sql
--changeset liquibase:product_master stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for product_master

CREATE TABLE IF NOT EXISTS "price_promo".product_master (
	active bool NULL,
	age_month_bucket text NULL,
	brand varchar(200) NULL,
	brand_cid int4 NULL,
	brand_cuq varchar(200) NULL,
	brand_id int4 NULL,
	clearance_indicator int4 NULL,
	cost float4 NULL,
	cost_usd float4 NULL,
	currency_id int4 NULL,
	current_price float4 NULL,
	current_price_with_vat float4 NULL,
	ecom_age int4 NULL,
	endcap_flag varchar(200) NULL,
	eol_flag varchar(200) NULL,
	hierarchy_id int4 NULL,
	imap varchar(200) NULL,
	is_active int4 NULL,
	it int4 NULL,
	kvi_indicator int4 NULL,
	l0_cid int4 NULL,
	l0_cuq text NULL,
	l0_id int4 NULL,
	l0_name text NULL,
	l1_cid int4 NULL,
	l1_cuq text NULL,
	l1_id int4 NULL,
	l1_name text NULL,
	l2_cid int4 NULL,
	l2_cuq text NULL,
	l2_id int4 NULL,
	l2_name text NULL,
	l3_cid int4 NULL,
	l3_cuq text NULL,
	l3_id int4 NULL,
	l3_name text NULL,
	l4_cid int4 NULL,
	l4_cuq text NULL,
	l4_id int4 NULL,
	l4_name text NULL,
	l5_cid int4 NULL,
	l5_cuq text NULL,
	l5_id int4 NULL,
	l5_name text NULL,
	l6_cid int4 NULL,
	l6_cuq text NULL,
	l6_id int4 NULL,
	l6_name text NULL,
	last_sold varchar(200) NULL,
	launch_date varchar(200) NULL,
	launch_price int4 NULL,
	lifecycle text NULL,
	lifecycle_indicator varchar(200) NULL,
	lifecycle_indicator_id varchar(200) NULL,
	manufacturer varchar(200) NULL,
	manufacturer_cid int4 NULL,
	manufacturer_cuq varchar(200) NULL,
	manufacturer_id int4 NULL,
	map varchar(200) NULL,
	max_age int4 NULL,
	merchandiser varchar(200) NULL,
	merchandiser_cid int4 NULL,
	merchandiser_cuq varchar(200) NULL,
	merchandiser_id int4 NULL,
	merchant_mail_id varchar(200) NULL,
	movement int4 NULL,
	msrp float4 NULL,
	msrp_with_vat float4 NULL,
	oh int4 NULL,
	oo int4 NULL,
	original_uom varchar(200) NULL,
	preferred_brand bool NULL,
	price_bucket varchar(200) NULL,
	price_bucket_cid varchar(200) NULL,
	primary_upc int4 NULL,
	product_cuq text NULL,
	product_description varchar(200) NULL,
	product_id int8 NULL,
	product_name text NULL,
	promo_base_price float8 NULL,
	promo_base_price_valid_from date NULL,
	promo_base_price_valid_to date NULL,
	psp_store_count varchar(200) NULL,
	pspd_cost varchar(200) NULL,
	pspd_item varchar(200) NULL,
	size text NULL,
	size_bucket varchar(200) NULL,
	size_bucket_cid int4 NULL,
	size_id int4 NULL,
	status text NULL,
	status_id int4 NULL,
	store_age int4 NULL,
	total_inventory int4 NULL,
	type varchar(200) NULL,
	uam_hierarchy_id varchar(200) NULL,
	uom varchar(200) NULL,
	uom_cid varchar(200) NULL,
	version_code varchar(200) NULL,
	wnw_store_count varchar(200) NULL,
	launch_price_with_vat numeric NULL,
	l7_id int4 NULL,
	l7_name text NULL,
	l7_cid int4 NULL,
	l7_cuq text NULL,
	customer_choice_id int4 NULL,
	customer_choice_description text NULL,
	last_reg_price_bnm int4 NULL,
	last_reg_price_bnm_with_vat int4 NULL,
	last_reg_price_ecom int4 NULL,
	last_reg_price_ecom_with_vat int4 NULL
);

CREATE INDEX product_master_product_id_idx ON price_promo.product_master USING btree (product_id);


--changeset surya.avinash@impactanalytics.co:drop_promo_product_master_table_20251216 stripComments:false splitStatements:false context:Release_1_0 ignore:false labels:product_master
--comment: Drop product_master table to create view with same name

DROP TABLE IF EXISTS price_promo.product_master CASCADE;