// import { allPlatformApps } from "../../../../../src/config/apps-config"
// import { allPlatformApps } from "../../../../config/apps-config";
// import {
//   convertAppsConstantFormat,
//   convertProductAppsConstantFormat,
// } from "./helper-functions";

// const tbClientProductMapping = convertAppsConstantFormat(
//   allPlatformApps["featuredApp"]
// );
const tbConfiguratorDescription = [
  {
    id: "1",
    configurator_description:
      "IA Smart Platform leverages ADA powered \nAI/ML based long range forecasts to \ngenerate merchandising financial \nplans at multiple levels of product hierarchy. \nAlso, generates optimised plans based on \nkey constraints and strategic objectives. \nAlso, generates optimised levels of \nproduct hierarchy. Also, generates \noptimised plans based on key \nconstraints and strategic objectives.",
  },
];
const tbMenu = [
  {
    sl: "1",
    product: "plansmart",
    modules: "module-configurator",
    default: "TRUE",
  },
  {
    sl: "1",
    product: "inventorysmart",
    modules: "module-configurator",
    default: "TRUE",
  },
];

export const COLUMN_DATA_FOR_TABLE_CONFIG = [
  {
    sub_headers: [],
    tc_code: 198,
    label: "Label",
    column_name: "label",
    dimension: "Others",
    type: "str",
    is_frozen: false,
    is_editable: true,
    is_aggregated: true,
    order_of_display: 3,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "71280",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: true,
    extra: {
      labelHirarchy: "false",
    },
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Column Name",
    column_name: "column_name",
    dimension: "Others",
    type: "str",
    is_frozen: false,
    is_editable: false,
    is_aggregated: false,
    order_of_display: 2,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "71268",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Dimension",
    column_name: "dimension",
    dimension: "Others",
    type: "str",
    is_frozen: false,
    is_editable: false,
    is_aggregated: false,
    order_of_display: 1,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "71279",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Type",
    column_name: "type",
    dimension: "Others",
    type: "str",
    is_frozen: false,
    is_editable: false,
    is_aggregated: false,
    order_of_display: 6,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "7271",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },

  {
    sub_headers: [],
    tc_code: 198,
    label: "Editable",
    column_name: "is_editable",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 4,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "727227",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Searchable",
    column_name: "is_searchable",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 4,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "727227",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Sortable",
    column_name: "is_sortable",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 4,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "727227",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Hidden",
    column_name: "is_hidden",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 4,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "727227",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Freeze",
    column_name: "is_frozen",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 4,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "727227",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
];

export const COLUMN_DATA_FOR_FILTER_CONFIG = [
  {
    sub_headers: [],
    tc_code: 198,
    label: "Dimension",
    column_name: "dimension",
    dimension: "Others",
    type: "str",
    is_frozen: false,
    is_editable: false,
    is_aggregated: false,
    order_of_display: 1,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "71279",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Column Name",
    column_name: "column_name",
    dimension: "Others",
    type: "list",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 2,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "71268",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {
      dropdownSearchable: "true",
    },
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Label",
    column_name: "label",
    dimension: "Others",
    type: "str",
    is_frozen: false,
    is_editable: true,
    is_aggregated: true,
    order_of_display: 3,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "71280",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: true,
    extra: {
      labelHirarchy: "false",
    },
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Multi Select",
    column_name: "is_multiple_selection",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 4,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "727227",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Functionality",
    column_name: "display_type",
    dimension: "Others",
    type: "list",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 5,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "7270",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Filter Type",
    column_name: "filter_type",
    dimension: "Others",
    type: "list",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 6,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "7271",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Mandatory",
    column_name: "is_mandatory",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 7,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "7272",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Order of Display",
    column_name: "display_order",
    dimension: "Others",
    type: "str",
    is_frozen: false,
    is_editable: false,
    is_aggregated: false,
    order_of_display: 5.0,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "7270",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  // {
  //     "sub_headers": [],
  //     "tc_code": 198,
  //     "label": "Display Order",
  //     "column_name": "display_order",
  //     "dimension": "Others",
  //     "type": "list",
  //     "is_frozen": false,
  //     "is_editable": true,
  //     "is_aggregated": false,
  //     "order_of_display": 8,
  //     "is_hidden": false,
  //     "is_required": true,
  //     "tc_mapping_code": "71274",
  //     "aggregate_type": null,
  //     "formatter": null,
  //     "is_row_span": false,
  //     "footer": null,
  //     "is_searchable": false,
  //     "extra": {},
  //     "is_sortable": true,
  //     "width": 200,
  //     "is_deleted": false,
  //     "is_master_group": false
  // },
  {
    sub_headers: [],
    tc_code: 198,
    label: "Clearable",
    column_name: "is_clearable",
    dimension: "Others",
    type: "ToogleField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 10,
    is_hidden: false,
    is_required: false,
    tc_mapping_code: "71277",
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
];

// const tbProductDescription = convertProductAppsConstantFormat(
//   allPlatformApps["featuredApp"]
// );
export const moduleConfiguratorJSON = {
  // tb_client_product_mapping: tbClientProductMapping,
  tb_configurator_description: tbConfiguratorDescription,
  tb_menu: tbMenu,
  // tb_product_description: tbProductDescription,
};

export const DEFAULT_FILTER_ROW = {
  column_name: "",
  label: "",
  dimension: "product",
  display_type: "dropdown",
  filter_type: "cascaded",
  is_mandatory: false,
  is_multiple_selection: false,
  is_clearable: true,
  disableEditSelection: false,
  _hideSelection: false,
  level: 1,
  range_min: null,
  range_max: null,
  default_value: null,
  is_disabled: false,
  is_required: false,
  extra: {},
  is_deleted: false,
  type: "cascaded",
};

export const ORDERING_PRODUCT = {
  id: 1,
  title: "Ordering",
  product: "Ordering",
  desc: "ordering",
  small_description:
    "Configure Inventory planning for optimised allocation, replenishment & ordering.",
  descriptions:
    "Optimize ordering of inventories through retail allocation that leverages predictive analytics for the greatest accuracy in even the most complex allocation and replenishment businesses. Our solution is highly automatable and accurate using leading edge machine learning models that allow for rapid 'what-if' simulations to ensure the business is making the right decisions.",
  is_subscribed: true,
  url: "ordering",
};

export const PRODUCTS = [
  ORDERING_PRODUCT,
  {
    id: 2,
    title: "Inventory",
    desc: "Inventory",
    small_description:
      "Configure Inventory planning for optimised allocation, replenishment & ordering.",
    product: "Inventory",
  },
];

export const SUBSCRIBED_APPS = [
  {
    application: "MondaySmart",
  },
  {
    application: "Workflow Input Center",
  },
  {
    application: "InventorySmart",
  },
  {
    application: "Master Data View",
  },
  {
    application: "MLOps",
  },
  {
    application: "Module Configurator",
  },
  {
    application: "AssortSmart",
  },
  {
    application: "ItemSmart",
  },
  {
    application: "PlanSmart",
  },
  {
    application: "DataIngestion",
  },
  {
    application: "Application Access Management",
  },
];

export const CONFIGURATOR_CONTENT = {
  title: "IA Smart Configurator",
  description:
    "IA Smart Platform leverages ADA powered AI/ML based long range forecasts to generate merchandising financial plans at multiple levels of product hierarchy. Also, generates optimised plans based on key constraints and strategic objectives. Also, generates optimised levels of product hierarchy. Also, generates optimised plans based on key constraints and strategic objectives.",
  knowMoreText: "Click here to know more about how to use",
  productSectionTitle: "Our Products",
  searchPlaceholder: "Search...",
  searchHelperText: "Enter a valid product name",
  backButtonText: "Back",
  getStartedButtonText: "Get Started",
  knowMoreButtonText: "Know More",
  knowMoreUrl: "https://www.impactanalytics.co/",
  benefitsTitle: "Benefits",
  activeProductDescription:
    "Optimize inventories through retail ordering that leverages predictive analytics for the greatest accuracy in even the most comp",
  activeProductBenefits: [
    "Optimized end-to-end Ordering of Inventory Planning Business friendly defaulting & exception management Automated allocation & replenishments Exhaustive reporting & insights Customized alerts",
  ],
};
