--liquibase formatted sql
--changeset liquibase:product_profile_attributes_filter stripComments:false splitStatements:false context:MTP-55972 labels: MTP-55972
--comment: MTP-55972
--rollback: SELECT 1

-- DROP TABLE IF EXISTS inventory_smart.product_profile_attributes_filter;
CREATE TABLE if NOT exists  inventory_smart.product_profile_attributes_filter (
	pp_code int4 NOT NULL,
	production_method _text NULL,
	drop_ship_ind _text NULL,
	merchandise_brand _text NULL,
	merchandise_category _text NULL,
	metal_color _text NULL,
	metal_type _text NULL,
	planning_ownership _text NULL,
	primary_sub_sku _text NULL,
	product_type _text NULL,
	store_pack_size _text NULL,
	"size" _text NULL,
	vendor_currency _text NULL,
	vendor_name _text NULL,
	vendor_style _text NULL,
	article _text NULL,
	flag _text NULL,
	gender _text NULL,
	is_set _text NULL,
	child_skus _text NULL,
	hierarchy_3 _text NULL,
	hierarchy_2 _text NULL,
	clearance_end_date _text NULL,
	clearance_start_date _text NULL,
	end_date _text NULL,
	launch_date _text NULL,
	hierarchy_1 _text NULL,
	product_cost_price_per_unit _text NULL,
	product_retail_price_per_unit _text NULL,
	supplier_pack_size _text NULL,
	primary_wh _text NULL,
	product_banner _text NULL,
	price_bucket _text NULL,
	product_channel_name _text NULL,
	l1_name _text NULL,
	l2_name _text NULL,
	product_tag _text NULL,
	"ordering" _text NULL,
	sku_grade _text NULL,
	product_final_price_per_unit _text NULL,
	product_bucket_code _text NULL,
	product_channel _text NULL,
	vendor_name_and_number _text NULL,
	dotcom_exclusive _text NULL,
	vendor_code _text NULL,
	brand_currency _text NULL,
	supplier_lead_time _text NULL,
	minimum_order_quantity _text NULL,
	product_banner_orig _text NULL,
	l0_name _text NULL,
	new_sku_flag _text NULL,
	country_origin _text NULL,
	product_description _text NULL,
	"cost" _text NULL,
	product_code _text NULL,
	active _text NULL,
	product_name _text NULL,
	original_price _text NULL,
	receipt_date _text NULL,
	clearance _text NULL,
	price _text NULL,
	updated_at _text NULL,
	created_at _text NULL,
	state _text NULL,
	district _text NULL,
	city _text NULL,
	zipcode _text NULL,
	s0_name _text NULL,
	brand _text NULL,
	division_code _text NULL,
	combo_store _text NULL,
	dc_name _text NULL,
	shop_in_shop _text NULL,
	dma_name _text NULL,
	division_name _text NULL,
	channel _text NULL,
	store_banner _text NULL,
	store_type _text NULL,
	store_grade _text NULL,
	store_code_name _text NULL,
	s1_name _text NULL,
	region _text NULL,
	s2_name _text NULL,
	s3_name _text NULL,
	longitude _text NULL,
	latitude _text NULL,
	close_date _text NULL,
	open_date _text NULL,
	store_size _text NULL,
	store_channel_description _text NULL,
	dc_flag _text NULL,
	fc_flag _text NULL,
    product_access_hierarchy _text NULL,
	CONSTRAINT product_profile_attributes_filter_pkey PRIMARY KEY (pp_code)
);
--changeset laraib.ahmad:product_profile_attributes_filter stripComments:false splitStatements:false context:MTP-55972 labels: MTP-55972
--comment: product_access_hierarchy ,store_access_hierarchy
ALTER TABLE inventory_smart.product_profile_attributes_filter ADD COLUMN IF NOT EXISTS product_access_hierarchy _text NULL;
ALTER TABLE inventory_smart.product_profile_attributes_filter ADD COLUMN IF NOT EXISTS store_access_hierarchy _text NULL;