--liquibase formatted sql
--changeset jaya.khandelwal@impactanalytics.co:get_ly_query_chg4 runOnChange:true stripComments:false splitStatements:false context:Release_1_1 labels:mtp-39831
--comment:  condition to handle final query 
--rollback: SELECT 1
DROP FUNCTION IF EXISTS plan_smart.get_ly_query(p_cols text, p_channels text[], p_product_filter jsonb, p_weeks integer[], p_ly_version integer);
-- DROP FUNCTION plan_smart.get_ly_query(text, _text, jsonb, _int4, int4);

CREATE OR REPLACE FUNCTION plan_smart.get_ly_query(p_cols text, p_channels text[], p_product_filter jsonb, p_weeks integer[], p_ly_version integer)
 RETURNS text
 LANGUAGE plpgsql
AS $function$                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                          
declare                                                                                                                                                                                                                                                                                                                                                                                                      
  v_week           int4;                                                                                                                                                                                                                                                                                                                                                                                     
  v_channel        text;                                                                                                                                                                                                                                                                                                                                                                                     
  v_level_id       int4;                                                                                                                                                                                                                                                                                                                                                                                     
  v_table_name     text;                                                                                                                                                                                                                                                                                                                                                                                     
  v_query_source   text;                                                                                                                                                                                                                                                                                                                                                                                     
  v_query_combine  text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_query_ly       text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_query_lf       text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_query_wf       text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_query_op       text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_query_filter   text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_query_week     text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_hierarchy_code_list text;                                                                                                                                                                                                                                                                                                                                                                                
  v_phf_code_sql   text;                                                                                                                                                                                                                                                                                                                                                                                     
  v_last_actualised_curr_week int;                                                                                                                                                                                                                                                                                                                                                                           
  v_max_weeks_lf_wf_op  int[];                                                                                                                                                                                                                                                                                                                                                                               
  v_max_week_lf     int;
  v_na_weeks_wf_min int;  
  v_na_weeks_lf_min int;
  v_na_weeks_op_min int;                                                                                                                                                                                                                                                                                                                                                                                
  v_max_week_wf     int;                                                                                                                                                                                                                                                                                                                                                                                     
  v_max_week_op     int;                                                                                                                                                                                                                                                                                                                                                                                     
  v_na_weeks_lf     int[];                                                                                                                                                                                                                                                                                                                                                                                   
  v_na_weeks_wf     int[];                                                                                                                                                                                                                                                                                                                                                                                   
  v_na_weeks_op     int[];                                                                                                                                                                                                                                                                                                                                                                                   
  v_weeks_from_ly   int[];                                                                                                                                                                                                                                                                                                                                                                                   
  v_weeks_from_lf   int[];                                                                                                                                                                                                                                                                                                                                                                                   
  v_weeks_from_wf   int[];                                                                                                                                                                                                                                                                                                                                                                                   
  v_weeks_from_op   int[];                                                                                                                                                                                                                                                                                                                                                                                   
  v_weeks_from_zero int[]; 
  v_replace_value_for_plus_100 text;
  v_adj_factor      int;
  v_final_query     text:= ' ';                                                                                                                                                                                                                                                                                                                                                                                                          
begin   
  raise notice '*****get_ly_query******';  	
  if p_ly_version = 6
  then
    v_replace_value_for_plus_100 := '+100';
    v_adj_factor := 100;
  elsif p_ly_version = 7
  then
    v_replace_value_for_plus_100 := '+200';
    v_adj_factor := 200;
  end if;
    
  select plan_table_text, product_hierarchy_filter_level_id                                                                                                                                                                                                                                                                                                                                                  
    into v_table_name, v_level_id                                                                                                                                                                                                                                                                                                                                                                            
    from plan_smart.get_query_source(1, p_ly_version);                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                             
  raise notice 'v_table_name : %', v_table_name;                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                             
  v_query_combine :='                                                                                                                                                                                                                                                                                                                                                                                        
    select                                                                                                                                                                                                                                                                                                                                                                                                   
      p.channel, p.class, p.hierarchy_code, p.current_week plus_100 as current_week,                                                                                                                                                                                                                                                                                                                         
      '|| p_cols || '                                                                                                                                                                                                                                                                                                                                                                                        
    from                                                                                                                                                                                                                                                                                                                                                                                                     
      table_name p                                                                                                                                                                                                                                                                                                                                                                                           
    where                                                                                                                                                                                                                                                                                                                                                                                                    
      current_week = ANY(''{current_week_val}'')';      
    
                                                                                                                                                                                                                                                                                                                                                                                                             
  if cardinality(p_channels) != 0                                                                                                                                                                                                                                                                                                                                                                            
  then                                                                                                                                                                                                                                                                                                                                                                                                       
    v_query_combine:= v_query_combine||'                                                                                                                                                                                                                                                                                                                                                                     
    and                                                                                                                                                                                                                                                                                                                                                                                                      
       channel = ANY(''{"' || array_to_string(p_channels, '","') || '"}'')';                                                                                                                                                                                                                                                                                                                                    
  end if;    
                                                                                                                                                                                                                                                                                                                                                                                                             
  if p_product_filter !='{}'                                                                                                                                                                                                                                                                                                                                                                                 
  then                                                                                                                                                                                                                                                                                                                                                                                                       
    v_query_filter := "plan_smart".form_attribute_table_filters_v2('product_hierarchies', 'hierarchy_code', p_product_filter);                                                                                                                                                                                                                                                                               
    v_phf_code_sql := 'select string_agg(hierarchy_code::text,'','') from ('||v_query_filter|| ' and level = '||v_level_id||') phf';                                                                                                                                                                                                                                                                         
    raise notice '%', v_phf_code_sql;                                                                                                                                                                                                                                                                                                                                                                        
    execute v_phf_code_sql into v_hierarchy_code_list;   
                                                                                                                                                                                                                                                                                                                                                                                                             
    if v_hierarchy_code_list is not null                                                                                                                                                                                                                                                                                                                                                                     
    then                                                                                                                                                                                                                                                                                                                                                                                                     
      v_query_combine := v_query_combine||'                                                                                                                                                                                                                                                                                                                                                                  
    and                                                                                                                                                                                                                                                                                                                                                                                                      
      hierarchy_code = any(''{'||v_hierarchy_code_list||'}'')';                                                                                                                                                                                                                                                                                                                                              
    end if;                                                                                                                                                                                                                                                                                                                                                                                                  
  end if;          


/* default attributes stores compared_week and this is ly compared week
   that is why we add +100 for ly and +200 for lly in below query */                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                             
  select (attribute_value -> 'value')::int + v_adj_factor                                                                                                                                                                                                                                                                                                                                                             
    into v_last_actualised_curr_week                                                                                                                                                                                                                                                                                                                                                                         
    from "global".default_attributes                                                                                                                                                                                                                                                                                                                                                                         
   where attribute_type  = 'actual_refresh_min_week';                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                             
  raise notice 'v_last_actualised_week=%',v_last_actualised_curr_week;                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                             
  --Find non actualised weeks and assume them being in LF table                                                                                                                                                                                                                                                                                                                                              
  select array_agg(week-v_adj_factor)                                                                                                                                                                                                                                                                                                                                                                                 
    into v_na_weeks_lf                                                                                                                                                                                                                                                                                                                                                                                       
    from unnest(p_weeks) week                                                                                                                                                                                                                                                                                                                                                                                
   where week > v_last_actualised_curr_week;   
   raise notice 'v_na_weeks_lf=%',v_na_weeks_lf;


                                                                                                                                                                                                                                                                                                                                                                                                             
  if cardinality(v_na_weeks_lf) <> 0                                                                                                                                                                                                                                                                                                                                                                    
  then                                                                                                                                                                                                                                                                                                                                                                                                       
    select                                                                                                                                                                                                                                                                                                                                                                                                   
      array_agg(week)                                                                                                                                                                                                                                                                                                                                                                                        
    into                                                                                                                                                                                                                                                                                                                                                                                                     
      v_weeks_from_ly                                                                                                                                                                                                                                                                                                                                                                                        
    from                                                                                                                                                                                                                                                                                                                                                                                                     
      (select unnest(p_weeks) week                                                                                                                                                                                                                                                                                                                                                                           
       except                                                                                                                                                                                                                                                                                                                                                                                                
       select unnest(v_na_weeks_lf)+ v_adj_factor                                                                                                                                                                                                                                                                                                                                                                      
       order by 1                                                                                                                                                                                                                                                                                                                                                                                            
      ) a;                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                             
    raise notice 'current weeks from ly=%',v_weeks_from_ly;                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                             
    if v_weeks_from_ly is not null                                                                                                                                                                                                                                                                                                                                                                           
    then                                                                                                                                                                                                                                                                                                                                                                                                     
      v_query_ly := replace(replace(v_query_combine,'plus_100',' '),'table_name',v_table_name);                                                                                                                                                                                                                                                                                                              
      v_query_ly := replace(v_query_ly,'current_week_val',array_to_string(v_weeks_from_ly,','));                                                                                                                                                                                                                                                                                                             
    end if;                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                             
    select *                                                                                                                                                                                                                                                                                                                                                                                                 
      into v_max_weeks_lf_wf_op                                                                                                                                                                                                                                                                                                                                                                              
      from plan_smart.get_missing_ly_weeks(p_channels,p_product_filter);                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                             
    v_max_week_lf := v_max_weeks_lf_wf_op[1];                                                                                                                                                                                                                                                                                                                                                                
    v_max_week_wf := v_max_weeks_lf_wf_op[2];                                                                                                                                                                                                                                                                                                                                                                
    v_max_week_op := v_max_weeks_lf_wf_op[3];                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                             
    raise notice 'v_max_week_lf=%',v_max_week_lf;                                                                                                                                                                                                                                                                                                                                                            
    raise notice 'v_max_week_wf=%',v_max_week_wf;                                                                                                                                                                                                                                                                                                                                                            
    raise notice 'v_max_week_op=%',v_max_week_op; 

    select 
      min(element) as element
    into
      v_na_weeks_lf_min
    from 
      ( select unnest(v_na_weeks_lf) as element) a;
    raise notice ' v_na_weeks_lf_min=%', v_na_weeks_lf_min;
                                                                                                                                                                                                                                                                                                                                                           
    
    if v_max_week_lf is not null and v_max_week_lf >= v_na_weeks_lf_min 
    then                                                                                                                                                                                                                                                                                                                                                                                                        
      select array_agg(week)                                                                                                                                                                                                                                                                                                                                                                                   
        into v_na_weeks_wf                                                                                                                                                                                                                                                                                                                                                                                     
        from unnest(v_na_weeks_lf) week                                                                                                                                                                                                                                                                                                                                                                        
       where week > v_max_week_lf;  
        --raise notice 'v_na_weeks_wf=%',v_na_weeks_wf;
   
      select array(select unnest(v_na_weeks_lf) except select unnest(v_na_weeks_wf) order by 1)                                                                                                                                                                                                                                                                                                                
        into v_weeks_from_lf;                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                             
      v_query_lf := replace(replace(v_query_combine,'plus_100',v_replace_value_for_plus_100),'table_name','plan_smart.lf_master_1');                                                                                                                                                                                                                                                                                               
      v_query_lf := replace(v_query_lf,'current_week_val',array_to_string(v_weeks_from_lf,','));                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                             
      raise notice 'non actualised current weeks from LF(as LY)=%',v_na_weeks_lf;   
    else
      v_na_weeks_wf := v_na_weeks_lf;                                                                                                                                                                                                                                                                                                                         
    end if;
     raise notice 'v_na_weeks_wf=%',v_na_weeks_wf;

	select 
     min(element) as element
    into
     v_na_weeks_wf_min
	from ( select unnest(v_na_weeks_wf) as element) a;
    raise notice ' v_na_weeks_wf_min=%', v_na_weeks_wf_min;
                                                                                                                                                                                                                                                                                                                                                                                                        
    if cardinality(v_na_weeks_wf) <> 0                                                                                                                                                                                                                                                                                                                                                                       
    then
      if v_max_week_wf is not null and v_max_week_wf >= v_na_weeks_wf_min  
      then                                                                                                                                                                                                                                                                                                                                                                                                   
        select array_agg(week)                                                                                                                                                                                                                                                                                                                                                                                 
          into v_na_weeks_op                                                                                                                                                                                                                                                                                                                                                                                     
          from unnest(v_na_weeks_wf) week                                                                                                                                                                                                                                                                                                                                                                        
         where week > v_max_week_wf;                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                             
         select array(select unnest(v_na_weeks_wf) except select unnest(v_na_weeks_op) order by 1)                                                                                                                                                                                                                                                                                                              
         into v_weeks_from_wf;                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                             
         raise notice 'non actualised current weeks from WF(as LY)=%',v_na_weeks_wf;                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                             
         v_query_wf := replace(replace(v_query_combine,'plus_100',v_replace_value_for_plus_100),'table_name','plan_smart.wf_master_1');                                                                                                                                                                                                                                                                                              
         v_query_wf := replace(v_query_wf,'current_week_val',array_to_string(v_weeks_from_wf,','));                                                                                                                                                                                                                                                                                                              
      else
         v_na_weeks_op := v_na_weeks_wf;
      end if;

   	  select 
        min(element) as element
      into
        v_na_weeks_op_min
	  from 
        ( select unnest(v_na_weeks_op) as element) a;
      raise notice ' v_na_weeks_op_min=%', v_na_weeks_op_min;

                                                                                                                                                                                                                                                                                                                                                                                                       
     if cardinality(v_na_weeks_op) <> 0                                                                                                                                                                                                                                                                                                                                                                      
     then
       if v_max_week_op is not null and v_max_week_op >= v_na_weeks_op_min 
       then                                                                                                                                                                                                                                                                                                                                                                                                    
         select array_agg(week)                                                                                                                                                                                                                                                                                                                                                                                
           into v_weeks_from_zero                                                                                                                                                                                                                                                                                                                                                                              
           from unnest(v_na_weeks_op) week                                                                                                                                                                                                                                                                                                                                                                     
          where week > v_max_week_op;                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                             
         select array(select unnest(v_na_weeks_op) except select unnest(v_weeks_from_zero) order by 1)                                                                                                                                                                                                                                                                                                         
           into v_weeks_from_op;                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                             
         v_query_op := replace(replace(v_query_combine,'plus_100',v_replace_value_for_plus_100),'table_name','plan_smart.op_master_1');                                                                                                                                                                                                                                                                                            
         v_query_op := replace(v_query_op,'current_week_val',array_to_string(v_weeks_from_op,','));                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                             
         raise notice 'non actualised current weeks from OP(as LY)=%',v_na_weeks_wf;                                                                                                                                                                                                                                                                                                                           
       else
         v_weeks_from_zero := v_na_weeks_op;
       end if; 
                                                                                                                                                                                                                                                                                                                                                                                                    
       if cardinality(v_weeks_from_zero) is not null --<> 0                                                                                                                                                                                                                                                                                                                                                                
       then                                                                                                                                                                                                                                                                                                                                                                                                  
         null;                                                                                                                                                                                                                                                                                                                                                                                               
       end if;                                                                                                                                                                                                                                                                                                                                                                                              
     end if;                                                                                                                                                                                                                                                                                                                                                                                                 
    end if;                                                                                                                                                                                                                                                                                                                                                                                                  
  else                                                                                                                                                                                                                                                                                                                                                                                                       
    v_query_ly := replace(replace(v_query_combine,'plus_100',' '),'table_name',v_table_name);                                                                                                                                                                                                                                                                                                                
    v_query_ly := replace(v_query_ly,'current_week_val',array_to_string(p_weeks,','));                                                                                                                                                                                                                                                                                                                       
  end if;                                                                                                                                                                                                                                                                                                                                                                                                    
  
                                                                                                                                                                                                                                                                                                                                                                                                           
  raise notice 'v_query_ly=%',v_query_ly;                                                                                                                                                                                                                                                                                                                                                                    
  raise notice 'v_query_lf=%',v_query_lf;                                                                                                                                                                                                                                                                                                                                                                    
  raise notice 'v_query_wf=%',v_query_wf;                                                                                                                                                                                                                                                                                                                                                                    
  raise notice 'v_query_op=%',v_query_op;
    

  IF v_query_ly <> ' ' THEN
     v_final_query := v_final_query || v_query_ly;
  END IF;

  IF v_query_lf <> ' ' THEN
      IF v_final_query <> ' ' THEN
         v_final_query := v_final_query || ' UNION ALL ';
      END IF;
      v_final_query := v_final_query || v_query_lf;
  END IF;

  IF v_query_wf <> ' ' THEN
      IF v_final_query <> ' ' THEN
          v_final_query := v_final_query || ' UNION ALL ';
      END IF;
      v_final_query := v_final_query || v_query_wf;
  END IF;

  IF v_query_op <> ' ' THEN
      IF v_final_query <> ' ' THEN
            v_final_query := v_final_query || ' UNION ALL ';
      END IF;
      v_final_query := v_final_query || v_query_op;
  END IF;
                                  
  if  v_final_query = ' ' 
  then
     v_final_query := 'select * from plan_smart.ly_master_1 where current_week = 000000';
  end if;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  /*v_query_combine := v_query_ly||                                                                                                                                                                                                                                                                                                                                                                            
                     case when v_query_lf <> ' ' and v_query_ly <> ' ' then ' union all ' else ' ' end||                                                                                                                                                                                                                                                                                                     
                     v_query_lf||                                                                                                                                                                                                                                                                                                                                                                            
                     case when v_query_wf <> ' ' and v_query_lf <> ' ' then ' union all ' else ' ' end||                                                                                                                                                                                                                                                                                                     
                     v_query_wf||                                                                                                                                                                                                                                                                                                                                                                            
                     case when v_query_op <> ' ' and v_query_wf <> ' ' then ' union all ' else ' ' end||                                                                                                                                                                                                                                                                                                     
                     v_query_op; */                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                             
  raise notice 'final_ly_query: %', v_final_query; 
  raise notice '*****get_ly_query******'; 
  RETURN v_final_query;                                                                                                                                                                                                                                                                                                                                                                                    
end                                                                                                                                                                                                                                                                                                                                                                                                          
$function$
;
