--liquibase formatted sql
--changeset hari.krishna :get_itemsmart_version runOnChange:true stripComments:false splitStatements:false context:MTP-72513 labels:MTP-72513
--comment: MTP-57260 added update by and at info
--rollback: SELECT 1
DROP FUNCTION IF EXISTS plan_smart.get_itemsmart_version(p_channels text[], p_product_filter jsonb, p_weeks integer[], p_item_version integer);
CREATE OR REPLACE FUNCTION plan_smart.get_itemsmart_version(p_channels text[], p_product_filter jsonb, p_weeks integer[], p_item_version integer)
 RETURNS text
 LANGUAGE plpgsql
AS $function$                                                                                                                                                                                                                                                                                                                                                                                                    
declare                                                                                                                                                                                                                                                                                                                                                                                                      
  v_week           int4;                                                                                                                                                                                                                                                                                                                                                                                     
  v_channel        text;                                                                                                                                                                                                                                                                                                                                                                                     
  v_level_id       int4;                                                                                                                                                                                                                                                                                                                                                                                     
  v_table_name     text;                                                                                                                                                                                                                                                                                                                                                                                     
  v_query_source   text;                                                                                                                                                                                                                                                                                                                                                                                     
  v_query_combine  text   := ' ';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  v_query_filter   text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_query_week     text   := ' ';                                                                                                                                                                                                                                                                                                                                                                            
  v_hierarchy_code_list text; 
  v_dept_list      text;                                                                                                                                                                                                                                                                                                                                                                              
  v_phf_code_sql   text; 
  v_phf_dept_sql   text; 
  v_item_smart_query text;
begin   

  select plan_table_text, product_hierarchy_filter_level_id                                                                                                                                                                                                                                                                                                                                                  
    into v_table_name, v_level_id                                                                                                                                                                                                                                                                                                                                                                            
    from plan_smart.get_query_source(1, p_item_version);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  raise notice 'v_table_name : %', v_table_name;                                                                                                                                                                                                                                                                                                                                                             
  
  if p_product_filter !='{}'                                                                                                                                                                                                                                                                                                                                                                                 
  then                                                                                                                                                                                                                                                                                                                                                                                                       
    v_query_filter := "plan_smart".form_attribute_table_filters_v2('product_hierarchies', 'hierarchy_code', p_product_filter);      

    v_phf_dept_sql := 'select string_agg(distinct l2_name::text,'','') from ('||v_query_filter|| ' and level = '||v_level_id||') phf';                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                     
    execute v_phf_dept_sql into v_dept_list; 

    v_phf_code_sql := 'select string_agg(hierarchy_code::text,'','') from ('||v_query_filter|| ' and level = '||v_level_id||') phf';                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                        
    execute v_phf_code_sql into v_hierarchy_code_list;   
                                                                                                                                                                                                                                                                                                                                                                                                             
    if v_hierarchy_code_list is not null                                                                                                                                                                                                                                                                                                                                                                     
    then                                                                                                                                                                                                                                                                                                                                                                                                     
      v_query_combine := 'select * from  ('||v_query_combine|| ' 
      hierarchy_code = any(''{'||v_hierarchy_code_list||'}'')';    
    end if;                                                                                                                                                                                                                                                                                                                                                                                                  
  end if; 
                                                                                                                                                                                                                                                                                                                                                                                                             
  v_item_smart_query := format('                                                                                                                                                                                                                                                                                                                                                                                        
    select                                                                                                                                                                                                                                                                                                                                                                                                   
    phf.l0_name,
    phf.l1_name,
    phf.l2_name,
    phf.l3_name,
    wpm.channel,
    wpm.current_week,
    meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.written_air, wpm.written_sales_units)), sum(wpm.written_sales_units)) AS kpi1,
    meta_schema.division(sum(wpm.written_sales_cost), sum(wpm.written_sales_units)) AS kpi2,
    sum(wpm.written_gm_dollar) AS kpi3,
    sum(wpm.written_sales_cost) AS kpi4,
    meta_schema.division(sum(wpm.cancelled_dollars), sum(wpm.cancelled_dollars) + sum(wpm.written_sales_dollars)) AS kpi5,
    meta_schema.division(sum(wpm.cancelled_qty), sum(wpm.cancelled_qty) + sum(wpm.written_sales_units)) AS kpi6,
    meta_schema.division(sum(wpm.cancelled_cost), sum(wpm.cancelled_cost) + sum(wpm.written_sales_cost)) AS kpi7,
    sum(wpm.non_delivered_dollars) AS kpi8,
    meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.wei_age_non_delivered_sales_dollars, wpm.non_delivered_dollars)), sum(wpm.non_delivered_dollars)) AS kpi9,
    sum(wpm.non_delivered_qty) AS kpi11,
    meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.wei_age_non_delivered_units, wpm.non_delivered_qty)), sum(wpm.non_delivered_qty)) AS kpi12,
    sum(wpm.non_delivered_cost) AS kpi14,
    meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.wei_age_non_delivered_costs, wpm.non_delivered_cost)), sum(wpm.non_delivered_cost)) AS kpi15,
    meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.delivered_air, wpm.delivered_net_sales_units)), sum(wpm.delivered_net_sales_units)) AS kpi20,
    sum(wpm.delivered_net_sales_cost) AS kpi21,
    meta_schema.division(sum(wpm.on_order_placed_total), sum(wpm.on_order_placed_total_unit)) AS kpi23,
    meta_schema.division(sum(wpm.on_order_placed_stock), sum(wpm.on_order_placed_stock_unit)) AS kpi24,
    meta_schema.division(sum(wpm.on_order_unplaced_total), sum(wpm.on_order_unplaced_total_unit)) AS kpi26,
    meta_schema.division(sum(wpm.on_order_unplaced_stock), sum(wpm.on_order_unplaced_stock_unit)) AS kpi27,
    meta_schema.division(sum(wpm.inv_adj_cost), sum(wpm.inv_adj_units)) AS kpi29,
    sum(wpm.bop_cost) AS kpi30,
    sum(wpm.bop_units) AS kpi31,
    sum(wpm.written_sales_dollars) AS kpi32,
    sum(wpm.written_sales_units) AS kpi33,
    1::double precision - meta_schema.division(meta_schema.division(sum(wpm.written_sales_dollars), sum(wpm.written_sales_units)), meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.written_air, wpm.written_sales_units)), sum(wpm.written_sales_units))) AS kpi34,
    meta_schema.division(sum(wpm.written_sales_dollars), sum(wpm.written_sales_units)) AS kpi35,
    meta_schema.division(sum(wpm.written_gm_dollar), sum(wpm.written_sales_dollars)) AS kpi36,
    sum(wpm.written_backorder_sales) AS kpi37,
    sum(wpm.written_backorder_sales_units) AS kpi38,
    sum(wpm.cancelled_dollars) AS kpi39,
    sum(wpm.cancelled_qty) AS kpi40,
    sum(wpm.cancelled_cost) AS kpi41,
    sum(wpm.delivered_net_sales_dollars) AS kpi42,
    sum(wpm.delivered_net_sales_units) AS kpi43,
    1::double precision - meta_schema.division(meta_schema.division(sum(wpm.delivered_net_sales_dollars), sum(wpm.delivered_net_sales_units)), meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.delivered_air, wpm.delivered_net_sales_units)), sum(wpm.delivered_net_sales_units))) AS kpi44,
    meta_schema.division(sum(wpm.delivered_net_sales_dollars), sum(wpm.delivered_net_sales_units)) AS kpi45,
    meta_schema.division(sum(wpm.delivered_gm), sum(wpm.delivered_net_sales_dollars)) AS kpi46,
    sum(wpm.delivered_returns_dollars) AS kpi47,
    sum(wpm.delivered_returns_qty) AS kpi48,
    sum(wpm.delivered_returns_cost) AS kpi49,
    sum(wpm.total_receipt_cost) AS kpi50,
    sum(wpm.total_receipt_units) AS kpi51,
    sum(wpm.inv_adj_cost) AS kpi52,
    meta_schema.division(sum(wpm.inv_adj_cost), sum(wpm.bop_cost)) AS kpi53,
    sum(wpm.inv_adj_units) AS kpi54,
    meta_schema.division(sum(wpm.inv_adj_units), sum(wpm.bop_units)) AS kpi55,
    meta_schema.division(sum(wpm.delivered_net_sales_cost), sum(wpm.delivered_net_sales_units)) AS kpi57,
    sum(wpm.delivered_gm) AS kpi58,
    meta_schema.division(sum(wpm.delivered_gm), (sum(wpm.eop_cost) + sum(wpm.bop_cost)) / 2::double precision) AS kpi59,
    meta_schema.division(sum(wpm.delivered_returns_dollars), sum(wpm.delivered_returns_dollars) + sum(wpm.delivered_net_sales_dollars)) AS kpi60,
    meta_schema.division(sum(wpm.delivered_returns_qty), sum(wpm.delivered_returns_qty) + sum(wpm.delivered_net_sales_units)) AS kpi61,
    meta_schema.division(sum(wpm.delivered_returns_cost), sum(wpm.delivered_returns_cost) + sum(wpm.delivered_net_sales_cost)) AS kpi62,
    meta_schema.division(sum(wpm.bop_cost), sum(wpm.bop_units)) AS kpi63,
    sum(wpm.aoh_units) AS kpi64,
    sum(wpm.aoh_cost) AS kpi65,
    sum(wpm.aoh_fwos_units) AS kpi66,
    sum(wpm.aoh_fwos_cost) AS kpi67,
    sum(wpm.atp_units) AS kpi68,
    sum(wpm.atp_fwos_units) AS kpi69,
    sum(wpm.atp_cost) AS kpi70,
    sum(wpm.atp_fwos_cost) AS kpi71,
    sum(wpm.eop_units) AS kpi72,
    sum(wpm.eop_cost) AS kpi73,
    meta_schema.division(sum(wpm.eop_cost), sum(wpm.eop_units)) AS kpi74,
    meta_schema.division(sum(wpm.total_receipt_cost), sum(wpm.total_receipt_units)) AS kpi89,
    sum(wpm.on_order_placed_total) AS kpi92,
    sum(wpm.on_order_placed_stock) AS kpi93,
    sum(wpm.on_order_unplaced_total) AS kpi95,
    sum(wpm.on_order_unplaced_stock) AS kpi96,
    sum(wpm.on_order_placed_total_unit) AS kpi99,
    sum(wpm.on_order_placed_stock_unit) AS kpi100,
    sum(wpm.on_order_unplaced_total_unit) AS kpi102,
    sum(wpm.on_order_unplaced_stock_unit) AS kpi103,
    meta_schema.division(sum(meta_schema.product_of_two_parameters(wpm.written_air, wpm.written_sales_units)), sum(wpm.written_sales_units)) AS kpi106,
    NULL::float AS kpi10,
    NULL::float AS kpi13,
    NULL::float AS kpi16,
    NULL::float AS kpi17,
    NULL::float AS kpi18,
    NULL::float AS kpi19,
    NULL::float AS kpi22,
    NULL::float AS kpi25,
    NULL::float AS kpi28,
    NULL::float AS kpi56,
    NULL::float AS kpi75,
    NULL::float AS kpi76,
    NULL::float AS kpi77,
    NULL::float AS kpi78,
    NULL::float AS kpi79,
    NULL::float AS kpi80,
    NULL::float AS kpi81,
    NULL::float AS kpi82,
    NULL::float AS kpi83,
    NULL::float AS kpi84,
    NULL::float AS kpi85,
    NULL::float AS kpi86,
    NULL::float AS kpi87,
    NULL::float AS kpi88,
    NULL::float AS kpi90,
    NULL::float AS kpi91,
    NULL::float AS kpi94,
    NULL::float AS kpi97,
    NULL::float AS kpi98,
    NULL::float AS kpi101,
    NULL::float AS kpi104,
    NULL::float AS kpi105,
    NULL::float AS kpi107,
    NULL::float AS kpi108,
    NULL::float AS kpi109,
    NULL::float AS kpi110,
    NULL::float AS kpi111,
    NULL::float AS kpi112,
    NULL::float AS kpi113,
    NULL::float AS kpi114,
    NULL::float AS kpi115,
    NULL::float AS kpi116,
    NULL::float AS kpi117,
    NULL::float AS kpi118,
    NULL::float AS kpi119,
    NULL::float AS kpi120,
    NULL::float AS kpi121,
    NULL::float AS kpi122,
    NULL::float AS kpi123,
    NULL::float AS kpi124,
    NULL::float AS kpi125,
    NULL::float AS kpi126,
    NULL::float AS kpi127,
    NULL::float AS kpi128,
    NULL::float AS kpi129,
    NULL::float AS kpi130,
    NULL::float AS kpi131,
    NULL::float AS kpi132,
    NULL::float AS kpi133,
    NULL::float AS kpi134,
    NULL::float AS kpi135,
    NULL::float AS kpi136,
    NULL::float AS kpi137,
    NULL::float AS kpi138,
    NULL::float AS kpi139,
    NULL::float AS kpi140,
    NULL::float AS kpi141,
    NULL::float AS kpi142,
    NULL::float AS kpi143,
    NULL::float AS kpi144,
    NULL::float AS kpi145,
    NULL::float AS kpi146,
    NULL::float AS kpi147,
    NULL::float AS kpi148,
    NULL::float AS kpi149,
    NULL::float AS kpi150,
    NULL::float AS kpi151,
    NULL::float AS kpi152,
    NULL::float AS kpi153,
    NULL::float AS kpi154,
    NULL::float AS kpi155,
    NULL::float AS kpi156,
    NULL::float AS kpi157,
    NULL::float AS kpi158,
    NULL::float AS kpi159,
    NULL::float AS kpi160,
    NULL::float AS kpi161,
    NULL::float AS kpi162,
    NULL::float AS kpi163,
    NULL::float AS kpi164,
    NULL::float AS kpi165,
    NULL::float AS kpi166,
    NULL::float AS kpi167,
    NULL::float AS kpi168,
    NULL::float AS kpi169,
    NULL::float AS kpi170,
    NULL::float AS kpi171,
    NULL::float AS kpi172,
    NULL::float AS kpi173,
    NULL::float AS kpi174,
    NULL::float AS kpi175,
    NULL::float AS kpi176,
    NULL::float AS kpi177,
    NULL::float AS kpi178,
    NULL::float AS kpi179,
    NULL::float AS kpi180,
    NULL::float AS kpi181,
    NULL::float AS kpi182,
    NULL::float AS kpi183,
    NULL::float AS kpi184,
    NULL::float AS kpi185,
    NULL::float AS kpi186,
    NULL::float AS kpi187,
    NULL::float AS kpi188,
    NULL::float AS kpi189,
    NULL::float AS kpi190,
    NULL::float AS kpi191,
    NULL::float AS kpi192,
    NULL::float AS kpi193,
    NULL::float AS kpi194,
    NULL::float AS kpi195,
    NULL::float AS kpi196,
    NULL::float AS kpi197,
    NULL::float AS kpi198,
    NULL::float AS kpi199,
    NULL::float AS kpi200,
    NULL::float AS kpi201,
    NULL::float AS kpi202,
    NULL::float AS kpi203,
    NULL::float AS kpi204,
    NULL::float AS kpi205,
    NULL::float AS kpi206,
    NULL::float AS kpi207,
    NULL::float AS kpi208,
    NULL::float AS kpi209,
    NULL::float AS kpi210,
    NULL::float AS kpi211,
    NULL::float AS kpi212,
    NULL::float AS kpi213,
    NULL::float AS kpi214,
    NULL::float AS kpi215,
    NULL::float AS kpi216,
    NULL::float AS kpi217,
    NULL::float AS kpi218,
    NULL::float AS kpi219,
    NULL::float AS kpi220,
    NULL::float AS kpi221,
    NULL::float AS kpi222,
    NULL::float AS kpi223,
    NULL::float AS kpi224,
    NULL::float AS kpi225,
    NULL::float AS kpi226,
    NULL::float AS kpi227,
    NULL::float AS kpi228,
    NULL::float AS kpi229,
    NULL::float AS kpi230,
    NULL::float AS kpi231,
    NULL::float AS kpi232,
    NULL::float AS kpi233,
    NULL::float AS kpi234,
    NULL::float AS kpi235,
    NULL::float AS kpi236,
    NULL::float AS kpi237,
    NULL::float AS kpi238,
    NULL::float AS kpi239,
    NULL::float AS kpi240,
    NULL::float AS kpi241,
    NULL::float AS kpi242,
    NULL::float AS kpi243,
    NULL::float AS kpi244,
    NULL::float AS kpi245,
    NULL::float AS kpi246,
    NULL::float AS kpi247,
    NULL::float AS kpi248,
    NULL::float AS kpi249,
    NULL::float AS kpi250
  from %s wpm
  JOIN plan_smart.product_hierarchies_filter phf 
    ON wpm.hierarchy_code = phf.hierarchy_code 
   AND phf.level = 6 
   AND phf.active 
   where current_week = ANY(%L)
   %s 
   %s
  GROUP BY 
    phf.l0_name,
    phf.l1_name,
    phf.l2_name,
    phf.l3_name,
    wpm.channel,
    wpm.current_week'
  ,v_table_name
  ,p_weeks
  ,case 
     when cardinality(p_channels) != 0 then ' and channel = ANY(''{"' || array_to_string(p_channels, '","') || '"}'')' 
     else ' ' 
   end
  ,case 
     when v_phf_dept_sql is not null then ' and dept = any(''{'||v_dept_list||'}'')' 
     else ' '
   end
  );
 
  v_item_smart_query := format(
   'select 
    channel ,
	phf.l3_name as class ,
	current_week ,
	phf.hierarchy_code as hierarchy_code,
	kpi1 ,
	kpi2 ,
	kpi3 ,
	kpi4 ,
	kpi5 ,
	kpi6 ,
	kpi7 ,
	kpi8 ,
	kpi9 ,
	kpi10 ,
	kpi11 ,
	kpi12 ,
	kpi13 ,
	kpi14 ,
	kpi15 ,
	kpi16 ,
	kpi17 ,
	kpi18 ,
	kpi19 ,
	kpi20 ,
	kpi21 ,
	kpi22 ,
	kpi23 ,
	kpi24 ,
	kpi25 ,
	kpi26 ,
	kpi27 ,
	kpi28 ,
	kpi29 ,
	kpi30 ,
	kpi31 ,
	kpi32 ,
	kpi33 ,
	kpi34 ,
	kpi35 ,
	kpi36 ,
	kpi37 ,
	kpi38 ,
	kpi39 ,
	kpi40 ,
	kpi41 ,
	kpi42 ,
	kpi43 ,
	kpi44 ,
	kpi45 ,
	kpi46 ,
	kpi47 ,
	kpi48 ,
	kpi49 ,
	kpi50 ,
	kpi51 ,
	kpi52 ,
	kpi53 ,
	kpi54 ,
	kpi55 ,
	kpi56 ,
	kpi57 ,
	kpi58 ,
	kpi59 ,
	kpi60 ,
	kpi61 ,
	kpi62 ,
	kpi63 ,
	kpi64 ,
	kpi65 ,
	kpi66 ,
	kpi67 ,
	kpi68 ,
	kpi69 ,
	kpi70 ,
	kpi71 ,
	kpi72 ,
	kpi73 ,
	kpi74 ,
	kpi75 ,
	kpi76 ,
	kpi77 ,
	kpi78 ,
	kpi79 ,
	kpi80 ,
	kpi81 ,
	kpi82 ,
	kpi83 ,
	kpi84 ,
	kpi85 ,
	kpi86 ,
	kpi87 ,
	kpi88 ,
	kpi89 ,
	kpi90 ,
	kpi91 ,
	kpi92 ,
	kpi93 ,
	kpi94 ,
	kpi95 ,
	kpi96 ,
	kpi97 ,
	kpi98 ,
	kpi99 ,
	kpi100 ,
	kpi101 ,
	kpi102 ,
	kpi103 ,
	kpi104 ,
	kpi105 ,
	kpi106 ,
	kpi107 ,
	kpi108 ,
	kpi109 ,
	kpi110 ,
	kpi111 ,
	kpi112 ,
	kpi113 ,
	kpi114 ,
	kpi115 ,
	kpi116 ,
	kpi117 ,
	kpi118 ,
	kpi119 ,
	kpi120 ,
	kpi121 ,
	kpi122 ,
	kpi123 ,
	kpi124 ,
	kpi125 ,
	kpi126 ,
	kpi127 ,
	kpi128 ,
	kpi129 ,
	kpi130 ,
	kpi131 ,
	kpi132 ,
	kpi133 ,
	kpi134 ,
	kpi135 ,
	kpi136 ,
	kpi137 ,
	kpi138 ,
	kpi139 ,
	kpi140 ,
	kpi141 ,
	kpi142 ,
	kpi143 ,
	kpi144 ,
	kpi145 ,
	kpi146 ,
	kpi147 ,
	kpi148 ,
	kpi149 ,
	kpi150 ,
	kpi151 ,
	kpi152 ,
	kpi153 ,
	kpi154 ,
	kpi155 ,
	kpi156 ,
	kpi157 ,
	kpi158 ,
	kpi159 ,
	kpi160 ,
	kpi161 ,
	kpi162 ,
	kpi163 ,
	kpi164 ,
	kpi165 ,
	kpi166 ,
	kpi167 ,
	kpi168 ,
	kpi169 ,
	kpi170 ,
	kpi171 ,
	kpi172 ,
	kpi173 ,
	kpi174 ,
	kpi175 ,
	kpi176 ,
	kpi177 ,
	kpi178 ,
	kpi179 ,
	kpi180 ,
	kpi181 ,
	kpi182 ,
	kpi183 ,
	kpi184 ,
	kpi185 ,
	kpi186 ,
	kpi187 ,
	kpi188 ,
	kpi189 ,
	kpi190 ,
	kpi191 ,
	kpi192 ,
	kpi193 ,
	kpi194 ,
	kpi195 ,
	kpi196 ,
	kpi197 ,
	kpi198 ,
	kpi199 ,
	kpi200 ,
	kpi201 ,
	kpi202 ,
	kpi203 ,
	kpi204 ,
	kpi205 ,
	kpi206 ,
	kpi207 ,
	kpi208 ,
	kpi209 ,
	kpi210 ,
	kpi211 ,
	kpi212 ,
	kpi213 ,
	kpi214 ,
	kpi215 ,
	kpi216 ,
	kpi217 ,
	kpi218 ,
	kpi219 ,
	kpi220 ,
	kpi221 ,
	kpi222 ,
	kpi223 ,
	kpi224 ,
	kpi225 ,
	kpi226 ,
	kpi227 ,
	kpi228 ,
	kpi229 ,
	kpi230 ,
	kpi231 ,
	kpi232 ,
	kpi233 ,
	kpi234 ,
	kpi235 ,
	kpi236 ,
	kpi237 ,
	kpi238 ,
	kpi239 ,
	kpi240 ,
	kpi241 ,
	kpi242 ,
	kpi243 ,
	kpi244 ,
	kpi245 ,
	kpi246 ,
	kpi247 ,
	kpi248 ,
	kpi249 ,
	kpi250 
    from 
     (%s) op 
    join 
      plan_smart.product_hierarchies_filter phf 
    on 
      op.l0_name=phf.l0_name  
    and 
      op.l1_name=phf.l1_name 
    and 
      op.l2_name=phf.l2_name 
    and
      op.l3_name=phf.l3_name 
    and 
      phf.level = 4 
    AND 
      phf.active',v_item_smart_query);

  raise notice 'v_item_smart_query: %',v_item_smart_query;

  return v_item_smart_query;
end 
$function$
;
