--liquibase formatted sql
--changeset madhumitha@impactanalytics.co:product_attributes_initial_new_01 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial_changeset_for_product_attributes
Drop table if exists "global".product_attributes_filter;
CREATE TABLE IF NOT EXISTS "global".product_attributes_filter (
	product_code varchar NOT NULL,
	product_name varchar NOT NULL,
	product_description text NULL,
	price float8 NULL,
	"cost" float8 NULL,
	original_price float8 NULL,
	active bool DEFAULT true NOT NULL,
	clearance bool DEFAULT false NOT NULL,
	receipt_date date NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	replacement_product_codes _varchar DEFAULT '{}'::character varying[] NULL,
	reference_product_codes _varchar DEFAULT '{}'::character varying[] NULL,
	is_deleted bool DEFAULT false NULL,
	dimensionitem_skey int4 NULL ,
	accessories varchar NULL ,
	ageinweeks float8 NULL ,
	agestandardcode varchar NULL ,
	altassociatedplanningbudgetcode varchar NULL ,
	altassociatedplanningbudgetdescription varchar NULL ,
	annualvsseasonal varchar NULL ,
	applictnembellshmnt varchar NULL ,
	l2_id varchar NULL ,
	l2_name varchar NULL ,
	asiafit varchar NULL ,
	assortfromdate varchar NULL ,
	assorttodate varchar NULL ,
	atfitem int4 NULL ,
	brandcode varchar NULL ,
	branddescription varchar NULL ,
	l1_id varchar NULL ,
	l1_name varchar NULL ,
	caratwt varchar NULL ,
	case_ varchar NULL ,
	cites varchar NULL ,
	clarity varchar NULL ,
	collection varchar NULL ,
	colorcode varchar NULL ,
	colordescription varchar NULL ,
	compitemdesc varchar NULL ,
	countryoforigincode varchar NULL ,
	countryoforigindescription varchar NULL ,
	costingmethod varchar NULL ,
	cruiseline varchar NULL ,
	currentallmarkdownrate float8 NULL ,
	currentallmarkdownrategroup float8 NULL ,
	currentclearanceunitprice float8 NULL ,
	customsreportingdescription varchar NULL ,
	cut varchar NULL ,
	dcafscost float8 NULL ,
	dcafsunits float8 NULL ,
	datecreated varchar NULL ,
	defaultdistributionmethod varchar NULL ,
	defaultitemsettingtype varchar NULL ,
	departmentcode varchar NULL ,
	departmentname varchar NULL ,
	destination varchar NULL ,
	dial varchar NULL ,
	discontinueddate varchar NULL ,
	distributorcode varchar NULL ,
	distributordescription varchar NULL ,
	divisioncode varchar NULL ,
	divisiondescription varchar NULL ,
	dutyfreeitem varchar NULL ,
	ethnicattribute varchar NULL ,
	exclusive varchar NULL ,
	familyid varchar NULL ,
	firstreceiptdate varchar NULL ,
	fishandwildlife varchar NULL ,
	fw varchar NULL ,
	gender varchar NULL ,
	hal varchar NULL ,
	hasdcafs varchar NULL ,
	hazmat varchar NULL ,
	imu float8 NULL ,
	incatalog varchar NULL ,
	inventorypostinggroup varchar NULL ,
	isactiveunassorted varchar NULL ,
	isagingeligible varchar NULL ,
	iscompetitivepricingitem varchar NULL ,
	isonorder varchar NULL ,
	isscsdefaultitem varchar NULL ,
	itinerary varchar NULL ,
	itemcategorycode varchar NULL ,
	itemcategorydescription varchar NULL ,
	itemstatusattr varchar NULL ,
	lastrecdcost float8 NULL ,
	lastreceiptdate varchar NULL ,
	lastreceiptdateforaging varchar NULL ,
	logo varchar NULL ,
	logosilhouette varchar NULL ,
	markdownindexcurrent float8 NULL ,
	material varchar NULL ,
	metal varchar NULL ,
	metalcolor varchar NULL ,
	metalcolordescription varchar NULL ,
	maxassortedvoyenddate varchar NULL ,
	minassortedvoyenddate varchar NULL ,
	maxreserverate float8 NULL ,
	l0_name varchar Not NULL ,
	movementtype varchar NULL ,
	nextreceiptdate varchar NULL ,
	oneofakind varchar NULL ,
	ordermultiple float8 NULL ,
	originalallretail float8 NULL ,
	paytovendor varchar NULL ,
	paymenttermscodedefault varchar NULL ,
	pictureurl varchar NULL ,
	plannercode varchar NULL ,
	plannerdescription varchar NULL ,
	polarized varchar NULL ,
	pricetypecurrent varchar NULL ,
	prioritygroupname varchar NULL ,
	prioritygrouptype varchar NULL ,
	productgroupcode varchar NULL ,
	productgroupdescription varchar NULL ,
	producttype varchar NULL ,
	l3_name varchar NULL ,
	programdescription varchar NULL ,
	programdiscontinued varchar NULL ,
	promotionalpricing varchar NULL ,
	proof varchar NULL ,
	purchaseprice float8 NULL ,
	purchasepricecurrencycode varchar NULL ,
	purchasepriceusd float8 NULL ,
	purchmaxorderqty int4 NULL ,
	purchminorderqty int4 NULL ,
	rolexcategory varchar NULL ,
	rolexgroup varchar NULL ,
	rolexref varchar NULL ,
	salesretailbudgetrankl90d float8 NULL ,
	salesunitofmeasure varchar NULL ,
	scsintxt varchar NULL ,
	shape varchar NULL ,
	ship varchar NULL ,
	shipmentmethodcodedefault varchar NULL ,
	shipspecific varchar NULL ,
	silhouette varchar NULL ,
	sizecode varchar NULL ,
	sizedescription varchar NULL ,
	sizerangeno varchar NULL ,
	skutype varchar NULL ,
	stone varchar NULL ,
	stonecolor varchar NULL ,
	style varchar NULL ,
	stylecolordescriptiontxt varchar NULL ,
	stylecolorsizedescriptiontxt varchar NULL ,
	stylecolorsizeno int4 NULL ,
	stylecolortxt varchar NULL ,
	styledescription varchar NULL ,
	styleno float8 NULL ,
	subclasscode varchar NULL ,
	subclassdescription varchar NULL ,
	subcollection varchar NULL ,
	subprogramcode varchar NULL ,
	subprogramdescription varchar NULL ,
	suggestedretailprice float8 NULL ,
	ticketdescription1 varchar NULL ,
	ticketdescription2 varchar NULL ,
	toprange varchar NULL ,
	transfermultiple int4 NULL ,
	transferorderminquantity int4 NULL ,
	trvlexcl varchar NULL ,
	unallocated varchar NULL ,
	upcdefault varchar NULL ,
	vendorcolor varchar NULL ,
	vendoritemno varchar NULL ,
	vendorlcstart varchar NULL ,
	vendorlcend varchar NULL ,
	vendorname varchar NULL ,
	vendorname2 varchar NULL ,
	vendorno varchar NULL ,
	vendorstyle varchar NULL ,
	weeksagebuckets varchar NULL ,
	writedown varchar NULL ,
	etl_dimension_load_datetime varchar NULL ,
	etl_dimension_update_datetime varchar NULL ,
	etl_hash_columns varchar NULL ,
	l4_name varchar NULL ,
	l4_id varchar NULL ,
	watchlink varchar NULL,
	CONSTRAINT product_attributes_filter_pk PRIMARY KEY (product_code, l0_name),
	CONSTRAINT product_attributes_filter_fk FOREIGN KEY (product_code) REFERENCES "global".product_master(product_code) ON DELETE CASCADE
)
PARTITION BY LIST (l0_name);
CREATE INDEX product_attributes_filter_l0_name_idx ON global.product_attributes_filter USING btree (l0_name);
CREATE INDEX product_attributes_filter_product_code_idx ON global.product_attributes_filter USING btree (product_code);

--changeset ashvin.prasanth@impactanalytics:product_attributes_filter_cols stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: product_attributes_filter missing cols
ALTER TABLE global.product_attributes_filter
ADD column IF NOT EXISTS plansmart_sku_flag varchar NULL ;


--changeset ashvin.prasanth@impactanalytics:product_attributes_filter_cols_01 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: product_attributes_filter missing cols


ALTER TABLE global.product_attributes_filter
    ADD COLUMN IF NOT EXISTS annualvsseasonal varchar,
    ADD COLUMN IF NOT EXISTS l5_description varchar,
    ADD COLUMN IF NOT EXISTS l3_id varchar,
    ADD COLUMN IF NOT EXISTS budgetdescription varchar,
    ADD COLUMN IF NOT EXISTS areadescription varchar,
    ADD COLUMN IF NOT EXISTS l5_id varchar,
    ADD COLUMN IF NOT EXISTS l5_name varchar,
    ADD COLUMN IF NOT EXISTS eligibilityforassort varchar,
    ADD COLUMN IF NOT EXISTS eligibilityforinventory varchar,
    ADD COLUMN IF NOT EXISTS condationallyactive varchar,
    ADD COLUMN IF NOT EXISTS size_name varchar,
    ADD COLUMN IF NOT EXISTS "size" varchar,
    ADD COLUMN IF NOT EXISTS primary_vendor_id varchar,
    ADD COLUMN IF NOT EXISTS primary_vendor_name varchar,
    ADD COLUMN IF NOT EXISTS unit_retail_price float8,
    ADD COLUMN IF NOT EXISTS unit_cost float8,
    ADD COLUMN IF NOT EXISTS launch_date date,
    ADD COLUMN IF NOT EXISTS exit_date date,
    ADD COLUMN IF NOT EXISTS style_name varchar,
    ADD COLUMN IF NOT EXISTS color_name varchar,
    ADD COLUMN IF NOT EXISTS style_id int4,
    ADD COLUMN IF NOT EXISTS color_id varchar,
    ADD COLUMN IF NOT EXISTS article varchar,
    ADD COLUMN IF NOT EXISTS style_color_desc varchar,
    ADD COLUMN IF NOT EXISTS l6_name varchar,
    ADD COLUMN IF NOT EXISTS l7_name varchar,
    ADD COLUMN IF NOT EXISTS plansmart_eligible_flag bool,
    ADD COLUMN IF NOT EXISTS unnumber varchar;

--changeset ashvin.prasanth@impactanalytics:product_attributes_filter_cols_02 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: product_attributes_filter missing cols

ALTER TABLE global.product_attributes_filter
    ADD COLUMN IF NOT EXISTS l8_name varchar;

--changeset priyanshu.agarwala@impactanalytics:product_attributes_filter_cols_02 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: product_attributes_filter datatype change for style_id col
ALTER TABLE global.product_attributes_filter
ALTER COLUMN style_id TYPE varchar
USING style_id::varchar;

  --changeset ashvin.prasanth@impactanalytics:product_attributes_filter_cols_03 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: product_attributes_filter missing cols
ALTER TABLE "global".product_attributes_filter
  ADD COLUMN IF NOT EXISTS product_bucket_code varchar NULL;


  --changeset ashvin.prasanth@impactanalytics:product_attributes_filter_cols_04 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: product_attributes_filter missing cols
ALTER TABLE "global".product_attributes_filter
  ADD COLUMN IF NOT EXISTS supply_flag int4 NULL,
  ADD COLUMN IF NOT EXISTS kidsandfamily varchar NULL;
