--liquibase formatted sql
--changeset pulimallika.teja@impactanalytics.co :assort_smart.plan_l3_opt_master_iap stripComments:false splitStatements:false context:MTP-51802 labels:add_missing_cols
--comment: initial changeset for status_details



CREATE TABLE IF not exists assort_smart.plan_l3_opt_master_iap (
	plan_bud_opt_id serial4 NOT NULL,
	plan_code int4 NOT NULL,
	hierarchy_code int4 NOT NULL,
	season_code int4 NOT NULL,
	channel int4 NOT NULL,
	sub_channel int4 NOT NULL,
	launch_id int4 NOT NULL,
	optimization_level varchar NULL,
	air_ly float8 DEFAULT 0.0 NULL,
	air_ty float8 DEFAULT 0.0 NULL,
	aur_ly float8 DEFAULT 0.0 NULL,
	aur_ty float8 DEFAULT 0.0 NULL,
	imu_ly float8 DEFAULT 0.0 NULL,
	imu_ty float8 DEFAULT 0.0 NULL,
	cogs_ly float8 DEFAULT 0.0 NULL,
	cogs_ty float8 DEFAULT 0.0 NULL,
	msrp_ly float8 DEFAULT 0.0 NULL,
	existing float8 DEFAULT 0.0 NULL,
	budget_ly float8 DEFAULT 0.0 NULL,
	budget_ty float8 DEFAULT 0.0 NULL,
	margin_ly float8 DEFAULT 0.0 NULL,
	revenue_ly float8 DEFAULT 0.0 NULL,
	revenue_ty float8 DEFAULT 0.0 NULL,
	txn_aur_ty float8 DEFAULT 0.0 NULL,
	budget_diff float8 DEFAULT 0.0 NULL,
	new_l3_flag varchar NULL,
	sell_through float8 DEFAULT 0.0 NULL,
	penetration_ly float8 DEFAULT 0.0 NULL,
	penetration_ty float8 DEFAULT 0.0 NULL,
	cost_budget_diff float8 DEFAULT 0.0 NULL,
	penetration_diff float8 DEFAULT 0.0 NULL,
	l2_drop_budget_ly float8 DEFAULT 0.0 NULL,
	l2_drop_budget_ty float8 DEFAULT 0.0 NULL,
	margin_percentage float8 DEFAULT 0.0 NULL,
	receipts_quantity_ly float8 DEFAULT 0.0 NULL,
	receipts_quantity_op float8 DEFAULT 0.0 NULL,
	receipts_quantity_ty float8 DEFAULT 0.0 NULL,
	total_receipts_cost_ly float8 DEFAULT 0.0 NULL,
	total_receipts_cost_ty float8 DEFAULT 0.0 NULL,
	total_available_cost_ly float8 DEFAULT 0.0 NULL,
	total_receipts_price_ty float8 DEFAULT 0.0 NULL,
	store_eligibility_groups varchar NULL,
	total_available_quantity_ly float8 DEFAULT 0.0 NULL,
	compare_type int4 NULL,
	CONSTRAINT plan_l3_opt_master_iap_pkey PRIMARY KEY (plan_bud_opt_id)
);