--liquibase formatted sql
--changeset keerthana.reddy@impactanalytics.co::tb_approval_metrics_local_20251106 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for tb_approval_metrics_local

CREATE TABLE price_markdown.tb_approval_metrics_local (
	strategy_id int4 NULL,
	product_level_id int8 NULL,
	store_level_id int8 NULL,
	pcd_id int4 NULL,
	pcd_start_date date NULL,
	pcd_end_date date NULL,
	channel_info text NULL,
	ia_markdown_type _text NULL,
	fin_markdown_type _text NULL,
	stores_with_inventory int8 NULL,
	status price_markdown."strategy_approval_status_enum" NULL,
	ia_discount float8 NULL,
	fin_discount float8 NULL,
	ia_previous_discount float8 NULL,
	fin_previous_discount float8 NULL,
	ia_pcd_price numeric NULL,
	fin_pcd_price numeric NULL,
	ia_incremental_discount float8 NULL,
	fin_incremental_discount float8 NULL,
	ia_previous_pcd_price numeric NULL,
	fin_previous_pcd_price numeric NULL,
	ia_units float8 NULL,
	fin_units float8 NULL,
	ia_revenue float8 NULL,
	fin_revenue float8 NULL,
	ia_margin float8 NULL,
	fin_margin float8 NULL,
	ia_gm_percent float8 NULL,
	fin_gm_percent float8 NULL,
	ia_sellthrough numeric NULL,
	fin_sellthrough numeric NULL,
	ia_aum numeric NULL,
	fin_aum numeric NULL,
	ia_markdown_spend float8 NULL,
	fin_markdown_spend float8 NULL,
	ia_inventory float8 NULL,
	fin_inventory float8 NULL,
	action_status price_markdown."action_status_enum" NULL,
	ia_previous_markdown_type _text NULL,
	fin_previous_markdown_type _text NULL,
	pcd_number int4 NULL,
	dept _text NULL,
	"class" _text NULL,
	brand _text NULL,
	mfg _text NULL,
	base_price numeric NULL,
	ia_inventory_cost float8 NULL,
	fin_inventory_cost float8 NULL,
	updated_at timestamp NULL,
	age int4 NULL,
	currency_id int8 NULL,
	ia_pcd_price_with_vat float8 NULL,
	fin_pcd_price_with_vat float8 NULL,
	ia_previous_pcd_price_with_vat float8 NULL,
	fin_previous_pcd_price_with_vat float8 NULL,
	ia_revenue_with_vat float8 NULL,
	fin_revenue_with_vat float8 NULL,
	ia_margin_with_vat float8 NULL,
	fin_margin_with_vat float8 NULL,
	ia_aum_with_vat float8 NULL,
	fin_aum_with_vat float8 NULL,
	ia_markdown_spend_with_vat float8 NULL,
	fin_markdown_spend_with_vat float8 NULL,
	base_price_with_vat float8 NULL,
	sub_dept _text NULL
)
PARTITION BY LIST (strategy_id);
CREATE INDEX tb_approval_metrics_local_strategy_id_idx ON price_markdown.tb_approval_metrics_local USING btree (strategy_id, pcd_id, store_level_id, product_level_id);