--liquibase formatted sql
--changeset keerthana.reddy@impactanalytics.co:tb_strategy_item_actuals_global_20251106 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for tb_strategy_item_actuals_global

CREATE TABLE price_markdown.tb_strategy_item_actuals_global (
	strategy_id int4 NULL,
	product_id int4 NULL,
	lw_recommended_offer_percentage float8 NULL,
	lw_clearance_discount float8 NULL,
	lw_effective_price_point float8 NULL,
	lw_sales_units float8 NULL,
	lw_revenue float8 NULL,
	lw_gm_dollar float8 NULL,
	lw_gm_percent numeric NULL,
	lw_aur numeric NULL,
	lw_aum numeric NULL,
	lw_st_percent numeric NULL,
	lw_inventory numeric NULL,
	lw_markdown_dollar float8 NULL,
	till_date_recommended_offer_percentage float8 NULL,
	till_date_clearance_discount float8 NULL,
	till_date_effective_price_point float8 NULL,
	till_date_sales_units float8 NULL,
	till_date_revenue float8 NULL,
	till_date_gm_dollar float8 NULL,
	till_date_gm_percent numeric NULL,
	till_date_aur numeric NULL,
	till_date_aum numeric NULL,
	till_date_st_percent numeric NULL,
	till_date_inventory numeric NULL,
	till_date_markdown_dollar float8 NULL,
	lw_inventory_cost float8 NULL,
	lw_inventory_retail float8 NULL,
	till_date_inventory_cost float8 NULL,
	till_date_inventory_retail float8 NULL,
	currency_id int8 NULL,
	lw_effective_price_point_with_vat float8 NULL,
	lw_revenue_with_vat float8 NULL,
	lw_gm_dollar_with_vat float8 NULL,
	lw_aur_with_vat float8 NULL,
	lw_aum_with_vat float8 NULL,
	lw_markdown_dollar_with_vat float8 NULL,
	lw_inventory_cost_with_vat float8 NULL,
	lw_inventory_retail_with_vat float8 NULL,
	till_date_effective_price_point_with_vat float8 NULL,
	till_date_revenue_with_vat float8 NULL,
	till_date_gm_dollar_with_vat float8 NULL,
	till_date_aur_with_vat float8 NULL,
	till_date_aum_with_vat float8 NULL,
	till_date_markdown_dollar_with_vat float8 NULL,
	till_date_inventory_cost_with_vat float8 NULL,
	till_date_inventory_retail_with_vat float8 NULL
);
CREATE INDEX stg_item_act_global_idx ON price_markdown.tb_strategy_item_actuals_global USING btree (strategy_id, product_id);