--liquibase formatted sql
--changeset aman.lakkoju:alerts_product_store_level_ddl_changes stripComments:false splitStatements:false context:Release_1_0 labels:alerts_product_store_level_ddl_changes
--comment: alerts_product_store_level_ddl_changes

CREATE TABLE IF NOT EXISTS inventory_smart.alerts_product_store_level (
	article text NULL,
	store_code text NULL,
	l0_name text NULL,
	l1_name text NULL,
	l2_name text NULL,
	l3_name text NULL,
	channel text NULL,
	product_type text NULL,
	item_status text NULL,
	store_name text NULL,
	region text NULL,
	state text NULL,
	district text NULL,
	store_format text NULL,
	product_description text NULL,
	dc_flag bool NULL,
	excess float8 NULL,
	shortfall float8 NULL,
	stockout float8 NULL,
	normal float8 NULL,
	oh float8 NULL,
	it float8 NULL,
	oo float8 NULL,
	tot_inv float8 NULL,
	sales_1_ago float8 NULL,
	lw_revenue float8 NULL,
	lw_margin float8 NULL,
	promo_percentage float8 NULL,
	wos_oh float8 NULL,
	wos_oh_it float8 NULL,
	wos_oh_oo_it float8 NULL,
	size_integrity float8 NULL,
	clearance_alert_flag int8 NULL,
	new_product_alert_flag int8 NULL,
	retirement_alert_flag int8 NULL,
	dc_oh float8 NULL,
	dc_oo float8 NULL,
	alert_flag text NULL,
	excs_flg int8 NULL,
	stckout_flg int8 NULL,
	shrtfl_flg int8 NULL,
	clearance_is_resolved int8 NULL,
	new_product_is_resolved int8 NULL,
	stockout_is_resolved int8 NULL,
	shortfall_is_resolved int8 NULL,
	overstock_is_resolved int8 NULL,
	newly_launched_alert_flag int8 NULL,
	launch_date date NULL,
	clearance_date date NULL
);