--liquibase formatted sql
--changeset aman.lakkoju:forecast_alerts_ddl_change stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: forecast_alerts_ddl_change

CREATE TABLE IF NOT EXISTS inventory_smart.forecast_alerts (
	article text NULL,
	l0_name text NULL,
	l1_name text NULL,
	l2_name text NULL,
	l3_name text NULL,
	product_type text NULL,
	item_status text NULL,
	sales_1_ago float8 NULL,
	lw_margin float8 NULL,
	lw_revenue float8 NULL,
	promo_percentage float8 NULL,
	new_product_alert_flag int8 NULL,
	past_4_weeks_actual float8 NULL,
	next_4_weeks_forecast float8 NULL,
	past_4_weeks_forecast float8 NULL,
	past_4_weeks_sales_avg float8 NULL,
	next_4_weeks_forecast_avg float8 NULL,
	mfp_forecast_4weeks float8 NULL,
	new_deviation_alert_flag int8 NULL,
	accuracy_perc float8 NULL,
	forecast_error_perc_alert_flag int8 NULL,
	seasonal_error_perc_alert_flag int8 NULL,
	core_error_perc_alert_flag int8 NULL,
	mfp_deviation_alert_flag int8 NULL,
	mfp_deviation float8 NULL,
	past_4_weeks_sales_deseason_avg int8 NULL,
	next_4_weeks_forecast_deseason_avg int8 NULL,
	forecast_deviation int8 NULL,
	sku_count_deviation int8 NULL,
	store_penetration_deviation int8 NULL,
	discount_deviation int8 NULL,
	msrp_deviation int8 NULL,
	inventory_deviation int8 NULL,
	model_error int8 NULL,
	weekly_sales_ly_avg int8 NULL,
	deviation_ly int8 NULL,
	deviation_recent_ros int8 NULL,
	assumption_mismatch_flag int8 NULL,
	unpredictable_market_shift_flag int8 NULL,
	data_quality_warning_flag int8 NULL,
	new_launch_monitor_flag int8 NULL,
	significant_strategy_change_flag int8 NULL,
	new_deviation_alert_is_resolved int8 NULL,
	forecast_error_perc_is_resolved int8 NULL,
	seasonal_error_perc_is_resolved int8 NULL,
	core_error_perc_is_resolved int8 NULL,
	mfp_deviation_alert_is_resolved int8 NULL,
	assumption_mismatch_is_resolved int8 NULL,
	unpredictable_market_shift_is_resolved int8 NULL,
	data_quality_warning_is_resolved int8 NULL,
	new_launch_monitor_is_resolved int8 NULL,
	significant_strategy_change_is_resolved int8 NULL,
	deviation_type text NULL,
    CONSTRAINT forecast_alerts_pk PRIMARY KEY (article)
);