import { makeStyles } from "@mui/styles";
import colours from "core/Styles/colours";

export const useCreateRuleFlowStyles = makeStyles(() => ({
  contentWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    paddingBottom: "80px",
    marginTop: 0,
  },
  sectionCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "16px",
    backgroundColor: "#FFFFFF",
    borderRadius: "8px",
    padding: "16px",
    width: "100%",
    boxSizing: "border-box",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    width: "100%",
  },
  sectionHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: 0,
  },
  clearAllButton: {
    border: "none !important",
    background: `${colours.softLightGrey} !important`,
    color: `${colours.neutralGrey} !important`,
    "&.Mui-disabled, &:disabled": {
      color: `${colours.neutralText} !important`,
      background: `${colours.greys100} !important`,
      border: "none !important",
    },
  },
  sectionHeaderIcon: {
    width: "20px",
    height: "20px",
    flexShrink: 0,
    display: "block",
  },
  sectionTitle: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 800,
    lineHeight: "21px",
    color: "#0D152C",
    textTransform: "capitalize",
    margin: 0,
  },
  requiredMark: {
    color: "#D32F2F",
    marginLeft: "2px",
  },
  sectionDescription: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "21px",
    color: "#8C95A7",
    margin: 0,
    width: "100%",
  },
  dcFiltersRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "24px",
    alignItems: "flex-start",
    width: "100%",
  },
  dcFilterField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "289px",
    maxWidth: "100%",
    flexShrink: 0,
  },
  mappingTableWrapper: {
    width: "100%",
    minHeight: "400px",
  },
  circularAlert: {
    width: "100%",
    display: "flex",
    "& > *": {
      flex: 1,
      width: "100%",
    },
  },
  setAllPanelBody: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: "8px 0",
  },
  setAllFieldsRow: {
    display: "flex",
    gap: "16px",
    width: "100%",
  },
  setAllField: {
    flex: 1,
    minWidth: 0,
    width: "100%",
  },
  fieldLabel: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    margin: 0,
    textTransform: "capitalize",
  },
  footerRightActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    "& $button": {
      margin: 0,
    },
  },
  stepperToolbar: {
    position: "relative",
    width: "100%",
    marginBottom: "12px",
    padding: "12px 0",
    minHeight: "48px",
  },
  stepperToolbarMain: {
    width: "70%",
    margin: "0 auto",
    display: "flex",
    justifyContent: "center",
  },
  stepperToolbarActions: {
    position: "absolute",
    right: 0,
    top: "50%",
    transform: "translateY(-50%)",
    display: "flex",
    alignItems: "center",
  },
  viewEditIcon: {
    width: "16px",
    height: "16px",
    flexShrink: 0,
    display: "block",
    color: "inherit",
    "& path": {
      fill: "currentColor !important",
    },
  },
  bottomButtonsContainer: {
    position: "fixed",
    zIndex: 10,
    bottom: 0,
    left: "60px",
    width: "calc(100% - 60px)",
    backgroundColor: "#FFFFFF",
    padding: "16px 24px",
    boxSizing: "border-box",
    boxShadow: "0px 0px 18px 5px rgba(0, 0, 0, 0.06)",
  },
  button: {
    margin: "0 5px",
    "&:nth-of-type(1)": {
      marginLeft: 0,
    },
    "&:last-child": {
      marginRight: 0,
    },
  },
}));
