--liquibase formatted sql
--changeset liquibase:ps_reporting_post_hierarchy_datev2 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for ps_reporting_post_hierarchy_datev2

CREATE TABLE price_promo.ps_reporting_post_hierarchy_date (
	promo_id _int4 NOT NULL,
	product_id int8 NOT NULL,
	s0_id int8 NOT NULL,
	s0_name varchar NULL,
	s1_id int8 NOT NULL,
	s1_name varchar NULL,
	"date" date NOT NULL,
	fw int2 NOT NULL,
	fy int2 NOT NULL,
	week_start_date date NOT NULL,
	actual_sales_units float8 DEFAULT 0 NULL,
	finalized_sales_units float8 DEFAULT 0 NULL,
	baseline_sales_units float8 DEFAULT 0 NULL,
	actual_revenue float8 DEFAULT 0 NULL,
	finalized_revenue float8 DEFAULT 0 NULL,
	baseline_revenue float8 DEFAULT 0 NULL,
	actual_margin float8 DEFAULT 0 NULL,
	finalized_margin float8 DEFAULT 0 NULL,
	baseline_margin float8 DEFAULT 0 NULL,
	lw_sales_units float8 DEFAULT 0 NULL,
	lw_revenue float8 DEFAULT 0 NULL,
	lw_margin float8 DEFAULT 0 NULL,
	ly_sales_units float8 DEFAULT 0 NULL,
	ly_revenue float8 DEFAULT 0 NULL,
	ly_margin float8 DEFAULT 0 NULL,
	actual_discount float8 DEFAULT 0 NULL,
	finalized_discount float8 DEFAULT 0 NULL,
	actual_inventory float8 DEFAULT 0 NULL,
	actual_contribution_revenue float8 NULL,
	finalized_contribution_revenue float8 NULL,
	actual_contribution_margin float8 NULL,
	finalized_contribution_margin float8 NULL,
	lw_contribution_revenue float8 NULL,
	lw_contribution_margin float8 NULL,
	ly_contribution_revenue float8 NULL,
	ly_contribution_margin float8 NULL,
	event_id _int4 NULL,
	actual_coupon_spend float8 NULL,
	lw_coupon_spend float8 NULL,
	ly_coupon_spend float8 NULL,
	actual_item_plan_unit float8 NULL,
	actual_item_plan_revenue float8 NULL,
	actual_item_plan_margin float8 NULL,
	ly_item_plan_unit float8 NULL,
	ly_item_plan_revenue float8 NULL,
	ly_item_plan_margin float8 NULL,
	lw_item_plan_unit float8 NULL,
	lw_item_plan_revenue float8 NULL,
	lw_item_plan_margin float8 NULL,
	finalized_spend numeric DEFAULT 0 NULL,
	actual_spend numeric DEFAULT 0 NULL,
	finalized_promo_spend numeric DEFAULT 0 NULL,
	actual_promo_spend numeric DEFAULT 0 NULL,
	finalized_coupon_spend numeric DEFAULT 0 NULL,
	CONSTRAINT product_rep_pkey PRIMARY KEY (product_id, s0_id, s1_id, date)
)
PARTITION BY RANGE (date);
CREATE INDEX product_rep_product_id_idx ON price_promo.ps_reporting_post_hierarchy_date USING btree (product_id);
CREATE INDEX product_rep_s1_id_idx ON price_promo.ps_reporting_post_hierarchy_date USING btree (s1_id);
CREATE INDEX product_rep_s1_id_product_id_idx ON price_promo.ps_reporting_post_hierarchy_date USING btree (s1_id, product_id);