import type { AspectRatioOption } from "./types";

export const ASPECT_RATIOS: AspectRatioOption[] = [
    {
        id: "square-1080",
        label: "Square",
        ratio: "1:1",
        apiRatio: "1:1",
        width: 1080,
        height: 1080,
        downloadWidth: 2160,
        downloadHeight: 2160,
        category: "Square",
        description: "1080x1080, 250x250, 200x200, 120x120, 88x88, 220x220, 358x358",
        subDimensions: [
            { width: 1080, height: 1080, label: "Standard" },
            { width: 250, height: 250, label: "Small" },
            { width: 200, height: 200, label: "Thumbnail" },
            { width: 120, height: 120, label: "Icon" },
            { width: 88, height: 88, label: "Badge" },
            { width: 220, height: 220, label: "Visual Filter" },
            { width: 358, height: 358, label: "PLP Tile" },
        ],
    },
    {
        id: "social-4-5",
        label: "Social Portrait",
        ratio: "4:5",
        apiRatio: "3:4",
        width: 1080,
        height: 1350,
        downloadWidth: 2160,
        downloadHeight: 2700,
        category: "Social Media",
        description: "Instagram, LinkedIn Portrait",
    },
    {
        id: "social-9-16",
        label: "Stories",
        ratio: "9:16",
        apiRatio: "9:16",
        width: 1080,
        height: 1920,
        downloadWidth: 2160,
        downloadHeight: 3840,
        category: "Social Media",
        description: "Stories and Reels",
    },
    {
        id: "social-1-91",
        label: "Social Link",
        ratio: "1.91:1",
        apiRatio: "16:9",
        width: 1200,
        height: 630,
        downloadWidth: 2400,
        downloadHeight: 1260,
        category: "Social Media",
        description: "Facebook/LinkedIn Link Preview",
    },
    {
        id: "common-ads-rectangle",
        label: "Large Rectangle",
        ratio: "1.2:1",
        apiRatio: "4:3",
        width: 336,
        height: 280,
        downloadWidth: 672,
        downloadHeight: 560,
        category: "Common Ads",
        description: "300x250 (Standard), 336x280 (Large)",
        subDimensions: [
            { width: 300, height: 250, label: "Standard Rectangle" },
            { width: 336, height: 280, label: "Large Rectangle" },
        ],
    },
    {
        id: "standard-banner-ads",
        label: "Small Display Ads",
        ratio: "3:1",
        apiRatio: "16:9",
        width: 300,
        height: 100,
        downloadWidth: 600,
        downloadHeight: 200,
        category: "Standard Banners",
        description: "Small Display Ads",
    },
    {
        id: "skyscraper-half-page",
        label: "Half-page Ad",
        ratio: "1:2",
        apiRatio: "9:16",
        width: 300,
        height: 600,
        downloadWidth: 600,
        downloadHeight: 1200,
        category: "Skyscraper",
        description: "Half-page Ad (300x600, 292x601)",
        subDimensions: [
            { width: 300, height: 600, label: "Standard" },
            { width: 292, height: 601, label: "Alternate" },
        ],
    },
    {
        id: "plp-banner-mobile",
        label: "Mobile Banner",
        ratio: "2.64:1",
        apiRatio: "16:9",
        width: 435,
        height: 165,
        downloadWidth: 870,
        downloadHeight: 330,
        category: "Mobile Banner",
        description: "PLP Banner Mobile 435x165",
    },
    {
        id: "tall-tiles-layout",
        label: "Tall Tiles",
        ratio: "0.72:1",
        apiRatio: "3:4",
        width: 288,
        height: 398,
        downloadWidth: 576,
        downloadHeight: 796,
        category: "Tall Tiles",
        description: "Store-page, Featured-tile 288x398",
    },
    {
        id: "unique-widest-multi",
        label: "Unique Widest",
        ratio: "3.14:1",
        apiRatio: "16:9",
        width: 628,
        height: 200,
        downloadWidth: 1256,
        downloadHeight: 400,
        category: "Unique Widest",
        description: "Multi-column-image (2) 628x200",
    },
    {
        id: "unique-wide-multi",
        label: "Unique Wide",
        ratio: "2.05:1",
        apiRatio: "16:9",
        width: 411,
        height: 200,
        downloadWidth: 822,
        downloadHeight: 400,
        category: "Unique Wide",
        description: "Multi-column-image (3) 411x200",
    },
    {
        id: "large-banner-leader",
        label: "Leaderboard",
        ratio: "8.1:1",
        apiRatio: "16:9",
        width: 728,
        height: 90,
        downloadWidth: 1456,
        downloadHeight: 180,
        category: "Upcoming",
        description: "Leaderboard 728x90",
        disabled: true,
        comingSoon: true,
    },
    {
        id: "standard-banner-468",
        label: "Standard Banner",
        ratio: "7.8:1",
        apiRatio: "16:9",
        width: 468,
        height: 60,
        downloadWidth: 936,
        downloadHeight: 120,
        category: "Upcoming",
        description: "Banner 468x60",
        disabled: true,
        comingSoon: true,
    },
    {
        id: "ultra-leader-ads",
        label: "Large Leaderboard",
        ratio: "10.8:1",
        apiRatio: "16:9",
        width: 970,
        height: 90,
        downloadWidth: 1940,
        downloadHeight: 180,
        category: "Upcoming",
        description: "970x90 Large Leaderboard",
        disabled: true,
        comingSoon: true,
    },
    {
        id: "hero-desktop-carousel",
        label: "Hero Carousel",
        ratio: "4.8:1",
        apiRatio: "16:9",
        width: 1920,
        height: 400,
        downloadWidth: 3840,
        downloadHeight: 800,
        category: "Upcoming",
        description: "1920x400 Hero Carousel Desktop",
        disabled: true,
        comingSoon: true,
    },
    {
        id: "plp-banner-desktop",
        label: "PLP Banner",
        ratio: "8.35:1",
        apiRatio: "16:9",
        width: 1920,
        height: 230,
        downloadWidth: 3840,
        downloadHeight: 460,
        category: "Upcoming",
        description: "Landing Page Banner 1920x230",
        disabled: true,
        comingSoon: true,
    },
    {
        id: "skinny-banner-desktop",
        label: "Skinny Banner",
        ratio: "19.2:1",
        apiRatio: "16:9",
        width: 1920,
        height: 100,
        downloadWidth: 3840,
        downloadHeight: 200,
        category: "Upcoming",
        description: "Landing Page Skinny Banner 1920x100",
        disabled: true,
        comingSoon: true,
    },
    {
        id: "skinny-banner-mobile",
        label: "Skinny Mobile",
        ratio: "3.84:1",
        apiRatio: "16:9",
        width: 430,
        height: 112,
        downloadWidth: 860,
        downloadHeight: 224,
        category: "Upcoming",
        description: "Landing Page Skinny Mobile 430x112",
        disabled: true,
        comingSoon: true,
    },
    {
        id: "skyscraper-wide",
        label: "Wide Skyscraper",
        ratio: "4:15",
        apiRatio: "9:16",
        width: 160,
        height: 600,
        downloadWidth: 320,
        downloadHeight: 1200,
        category: "Upcoming",
        description: "Wide Skyscraper Ads",
        disabled: true,
        comingSoon: true,
    },
];
