import { makeStyles } from "@mui/styles";

export const useMinDistributionStyles = makeStyles(() => ({
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    fontFamily: "Manrope",
    paddingBottom: "4px",
  },
  minRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    height: "55px",
  },
  minLabel: {
    margin: 0,
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    whiteSpace: "nowrap",
  },
  required: {
    color: "#E15554",
  },
  minInput: {
    width: "260px",
    minWidth: "260px",
    maxWidth: "260px",
    flexShrink: 0,
    "& .impact_inputbox_container": {
      width: "100% !important",
      maxWidth: "100% !important",
      minWidth: "0 !important",
    },
    "& .impact_inputbox_container .MuiInputBase-root": {
      width: "100% !important",
      minWidth: "0 !important",
      maxWidth: "100% !important",
    },
    "& .impact_inputbox_container .MuiInputBase-root input.MuiInputBase-input": {
      width: "100% !important",
      minWidth: "0 !important",
      maxWidth: "100% !important",
      boxSizing: "border-box",
    },
    "& .impact_inputbox_container_with_icons": {
      width: "100% !important",
      maxWidth: "100% !important",
      minWidth: "0 !important",
    },
    "& .impact_inputbox_container_with_icons .impact-input-wrapper": {
      width: "100% !important",
      minWidth: "0 !important",
      maxWidth: "100% !important",
      boxSizing: "border-box",
    },
    "& .impact_inputbox_container_with_icons .right-input-icon": {
      flexShrink: 0,
    },
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    width: "100%",
    flexShrink: 0,
  },
  sectionTitle: {
    margin: 0,
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "21px",
    color: "#0D152C",
    textTransform: "capitalize",
  },
  chipRow: {
    display: "flex",
    flexWrap: "nowrap",
    gap: "12px",
    alignItems: "center",
    width: "100%",
    overflowX: "auto",
  },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    padding: "6px 12px",
    borderRadius: "12px",
    border: "1px solid #D9DDE7",
    background: "#FFFFFF",
    cursor: "pointer",
    fontFamily: "Manrope",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#60697D",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  chipSelected: {
    borderColor: "#4259EE",
    color: "#4259EE",
  },
  radio: {
    width: "20px",
    height: "20px",
    borderRadius: "999px",
    border: "1.25px solid #D9DDE7",
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  radioSelected: {
    borderColor: "#4259EE",
  },
  radioDot: {
    width: "12.5px",
    height: "12.5px",
    borderRadius: "999px",
    background: "#4259EE",
  },
  optionsBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    width: "100%",
  },
  helpRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    flexShrink: 0,
  },
  helpText: {
    margin: 0,
    flex: 1,
    minWidth: 0,
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#1F2B4D",
    overflow: "visible",
    whiteSpace: "normal",
  },
  infoIconBox: {
    width: 16,
    height: 16,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& svg": {
      width: 16,
      height: 16,
      display: "block",
    },
  },
  previewButton: {
    maxHeight: "32px !important",
    minWidth: "56px",
    padding: "6px 12px !important",
    borderRadius: "8px !important",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  unitsBox: {
    height: "115px",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "16px 8px",
    borderRadius: "8px",
    background: "#F5F6FA",
    boxSizing: "border-box",
  },
  unitsRow: {
    height: "55px",
    display: "flex",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: "6px",
    width: "100%",
  },
  unitsLabel: {
    margin: 0,
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  unitsHint: {
    margin: 0,
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#7A8294",
    whiteSpace: "nowrap",
    flexShrink: 0,
    position: "relative",
    zIndex: 1,
  },
  unitsInput: {
    flex: "0 0 auto",
    width: "fit-content",
    maxWidth: "100%",
  },
  sizeUnitsBox: {
    minHeight: "85px",
    width: "100%",
    display: "grid",
    gridTemplateColumns:
      "max-content max-content max-content minmax(0, 1fr)",
    alignItems: "center",
    columnGap: "6px",
    rowGap: "8px",
    padding: "16px 8px",
    borderRadius: "8px",
    background: "#F5F6FA",
    boxSizing: "border-box",
  },
  sizeSelectLabel: {
    margin: 0,
    marginLeft: "12px",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    whiteSpace: "nowrap",
  },
  sizeSelectControl: {
    minWidth: 0,
    width: "100%",
    maxWidth: "326px",
    "& .ia-select-main-container-v3": {
      width: "100%",
      minWidth: "0 !important",
      maxWidth: "100%",
    },
  },
  sizeSelectDropdown: {
    "& .ia-select-search-box::placeholder, & .ia-select-search-box:focus::placeholder": {
      color: "#B4BAC7 !important",
      opacity: 1,
    },
  },
  divider: {
    width: "100%",
    height: "1px",
    minHeight: "1px",
    background: "#D9DDE7",
    border: 0,
    margin: 0,
    flexShrink: 0,
  },
}));
