import { makeStyles } from "@mui/styles";

export const useLogisticsConfigurationStyles = makeStyles(() => ({
  container: {
    background: "#FFFFFF",
    borderRadius: "8px",
    padding: "16px",
    width: "100%",
    maxWidth: "100%",
    height: "692px",
    boxSizing: "border-box",
    overflow: "hidden",
  },
  sectionsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    columnGap: "16px",
    alignItems: "stretch",
    width: "100%",
    height: "100%",
    minHeight: 0,
  },
  sectionCard: {
    background: "#F5F6FA",
    borderRadius: "12px",
    padding: "16px 0",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    minWidth: 0,
    minHeight: 0,
    width: "100%",
    boxSizing: "border-box",
    height: "100%",
    overflow: "hidden",
  },
  sectionCardEmpty: {
    minHeight: 0,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    minHeight: "32px",
    padding: "0 16px",
    width: "100%",
    boxSizing: "border-box",
    flexShrink: 0,
  },
  sectionHeaderLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flex: 1,
    minWidth: 0,
  },
  /** Drawn at the asset's intrinsic 52x47 so the glyph renders at the 32px the design calls for.
   *  Only the top 32x32 of that canvas is the glyph; the rest is the drop shadow. The negative
   *  margins collapse the layout box down to the glyph and let the shadow overflow, which is how
   *  the design frames it, and which keeps the glyph optically centred against the title and the
   *  Edit button instead of riding 7.5px high. */
  sectionIcon: {
    width: "52px",
    height: "47px",
    margin: "0 -10px -15px",
    flexShrink: 0,
  },
  sectionTitle: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "21px",
    color: "#1F2B4D",
    textTransform: "capitalize",
    minWidth: 0,
  },
  sectionBadge: {
    flexShrink: 0,
  },
  sectionEdit: {
    flexShrink: 0,
  },
  sectionDivider: {
    border: "none",
    borderTop: "1px solid #D9DDE7",
    margin: 0,
    width: "100%",
    flexShrink: 0,
  },
  sectionContent: {
    padding: "0 16px",
    width: "100%",
    boxSizing: "border-box",
    minWidth: 0,
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
  },
  sectionRules: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
  },
  sectionEmpty: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    minHeight: "360px",
    width: "100%",
    "& .impact_emptystate": {
      background: "transparent !important",
      width: "100% !important",
      maxWidth: "100% !important",
    },
  },
  ruleRow: {
    background: "#FFFFFF",
    borderRadius: "12px",
    padding: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
  },
  ruleRowLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flex: 1,
    minWidth: 0,
  },
  ruleRowDrag: {
    width: "24px !important",
    height: "24px !important",
    color: "#7A8294 !important",
    flexShrink: 0,
  },
  ruleRowLabels: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
    flexWrap: "wrap",
  },
  ruleRowLabel: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "21px",
    color: "#1F2B4D",
    textTransform: "capitalize",
    wordBreak: "break-word",
  },
  ruleRowSubLabel: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#7A8294",
    textTransform: "capitalize",
    flexShrink: 0,
  },
  ruleRowValue: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "21px",
    color: "#0D152C",
    textTransform: "capitalize",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  panelBody: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: "16px 0",
    minHeight: 0,
    flex: 1,
    overflow: "hidden",
  },
  panelTabsRow: {
    padding: "0 16px",
    width: "100%",
    boxSizing: "border-box",
    flexShrink: 0,
    // MUI stacks grouped buttons with margin-left:-1px and transparent left borders.
    // Later siblings paint over earlier ones, hiding the gray right-border separators
    // between inactive tabs (selected tabs already win via z-index). Keep earlier
    // buttons above later ones so those separators stay visible.
    "& .ia-buttonGroupButton:nth-child(1)": {
      zIndex: 3,
    },
    "& .ia-buttonGroupButton:nth-child(2)": {
      zIndex: 2,
    },
    "& .ia-buttonGroupButton:nth-child(3)": {
      zIndex: 1,
    },
    "& .ia-buttonGroupButton.ia-buttonGroupButton-selected": {
      zIndex: 4,
    },
  },
  panelContentArea: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: "0 16px",
    width: "100%",
    boxSizing: "border-box",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
  },
  panelSelectRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "16px",
    width: "100%",
    minWidth: 0,
    flexWrap: "wrap",
  },
  panelSelectField: {
    display: "flex",
    alignItems: "flex-start",
    gap: "6px",
    minWidth: 0,
    flex: "1 1 240px",
    maxWidth: "100%",
  },
  panelSelectFieldHidden: {
    display: "none",
  },
  panelSelectLabel: {
    margin: 0,
    paddingTop: "8px",
    fontFamily: "Manrope, sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  panelSelectControl: {
    minWidth: 0,
    flex: 1,
    maxWidth: "100%",
  },
  panelHelperText: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#60697D",
    textTransform: "capitalize",
    textAlign: "right",
    flex: "1 1 160px",
    minWidth: 0,
  },
  panelRulesList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
  },
  panelRuleRow: {
    background: "#FFFFFF",
    borderRadius: "12px",
    padding: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    overflow: "visible",
  },
  panelRuleRowLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: 0,
    flex: 1,
  },
  panelRuleRowLabel: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#1F2B4D",
    textTransform: "capitalize",
  },
  panelRuleRowSubLabel: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#7A8294",
    textTransform: "capitalize",
  },
  panelRuleRowInputGroup: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexShrink: 0,
  },
  panelRuleRowInputLabel: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  panelRuleRowSelect: {
    width: "100px",
    minWidth: "100px",
    maxWidth: "100px",
    flexShrink: 0,
    "& .ia-select-main-container-v3": {
      width: "100px",
      minWidth: "100px",
      maxWidth: "100px",
    },
  },
  panelDistanceCompactInput: {
    width: "84px",
    minWidth: "84px",
    // maxWidth: "120px",
    flexShrink: 0,
    // impact-ui Input defaults to min-width: 240px and (in Firefox)
    // -moz-appearance: textfield, which hides/clips native steppers.
    "& .impact_inputbox_container": {
      width: "100% !important",
      maxWidth: "100% !important",
      minWidth: "0 !important",
    },
    "& .impact_inputbox_container .MuiInputBase-root": {
      width: "100% !important",
      minWidth: "0 !important",
      maxWidth: "100% !important",
    },
    "& .impact_inputbox_container .MuiInputBase-root input.MuiInputBase-input": {
      width: "100% !important",
      minWidth: "0 !important",
      maxWidth: "100% !important",
      textAlign: "left",
      boxSizing: "border-box",
      // Undo impact-ui global: input[type=number] { -moz-appearance: textfield }
      MozAppearance: "number-input !important",
      appearance: "auto !important",
      paddingRight: "2px",
    },
    "& input[type=number]::-webkit-outer-spin-button, & input[type=number]::-webkit-inner-spin-button":
      {
        // Force always-visible steppers (Chrome only shows them on hover by default)
        WebkitAppearance: "inner-spin-button !important",
        opacity: "1 !important",
        display: "inline-block !important",
        margin: "0 0 0 2px",
        height: "20px",
      },
  },
  panelDistanceInputs: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flex: 1,
    minWidth: 0,
  },
  panelDistanceHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    width: "100%",
  },
  panelDistanceHelperText: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#60697D",
    textTransform: "capitalize",
    flex: 1,
  },
  panelDistanceRowLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flex: 1,
    minWidth: 0,
  },
  panelDistanceRowRight: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexShrink: 0,
  },
  panelDistanceDeleteIcon: {
    width: "16px !important",
    height: "16px !important",
    color: "#60697D !important",
  },
  panelWarningBanner: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    alignSelf: "center",
    boxSizing: "border-box",
    minHeight: "36px",
    minWidth: "370px",
    maxWidth: "calc(100% - 32px)",
    background: "#FFF8D5",
    borderRadius: "8px",
    padding: "8px 16px",
    margin: "0 0 16px",
    flexShrink: 0,
  },
  panelWarningIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    "& svg": {
      width: "18px",
      height: "16px",
      display: "block",
    },
  },
  panelWarningText: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#0D152C",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  logisticsConfigPanel: {
    // Figma header: px-16 py-12, white, bottom border. Library defaults to a
    // fixed 40px lavender bar that clips the 32px icon's drop shadow.
    "& .impact_drawer_header": {
      height: "auto",
      padding: "12px 16px",
      boxSizing: "border-box",
      background: "#FFFFFF",
      borderBottom: "1px solid #D9DDE7",
      overflow: "visible",
    },
    "& .impact_drawer_body": {
      // Library footer is position:absolute (56px). Keep the body short enough
      // that the bottom warning banner sits above it — not under it. Header is
      // ~56px with Figma padding (was 40px), so use 112 instead of 100.
      height: "calc(100% - 112px) !important",
      overflow: "hidden",
      padding: "0 !important",
    },
    "& .impact_drawer_heading": {
      display: "flex",
      alignItems: "center",
      minWidth: 0,
    },
  },
  panelTitle: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
  },
  panelTitleText: {
    margin: 0,
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "21px",
    color: "#1F2B4D",
    textTransform: "capitalize",
    minWidth: 0,
  },
  logisticsConfigPanelLayout: {
    background: "#F5F6FA",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    overflow: "hidden",
    minHeight: 0,
    flex: 1,
  },
}));
