--liquibase formatted sql
--changeset liquibase:product_attributes_filter_v2 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for product_attributes_filter_v2

DROP TABLE IF EXISTS "global".product_attributes_filter CASCADE;
CREATE TABLE "global".product_attributes_filter (
	product_code varchar NOT NULL,
	product_name varchar NOT NULL,
	product_description text NULL,
	price float8 NULL,
	"cost" float8 NULL,
	original_price float8 NULL,
	active bool NOT NULL,
	clearance bool NOT NULL,
	receipt_date date NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	replacement_product_codes _varchar NULL,
	reference_product_codes _varchar NULL,
	is_deleted bool NULL,
	buyer_id varchar NULL,
	buyer_description varchar NULL,
	l0_code varchar NOT NULL,
	l0_description varchar NOT NULL,
	l1_code varchar NOT NULL,
	l1_description varchar NOT NULL,
	l2_code varchar NOT NULL,
	l2_description varchar NOT NULL,
	l3_code varchar NOT NULL,
	l3_description varchar NOT NULL,
	vendor_id varchar NULL,
	vendor_description varchar NULL,
	rebranded_item_id varchar NULL,
	pack_size int4 NULL,
	product_status varchar NULL,
	item_clearance_dt varchar NULL,
	launch_date date NULL,
	item_key varchar NULL,
	l0_name varchar NOT NULL,
	l1_name varchar NOT NULL,
	l2_name varchar NOT NULL,
	l3_name varchar NOT NULL,
	item_short_desc varchar NULL,
	item_typ_cd varchar NULL,
	item_typ_nm varchar NULL,
	item_hazardous_cd varchar NULL,
	item_hazardous_cls_cd varchar NULL,
	item_hazardous_sub_cls_cd varchar NULL,
	item_hazardous_property_1_nm varchar NULL,
	item_hazardous_property_2_nm varchar NULL,
	item_hazardous_property_3_nm varchar NULL,
	item_hazardous_un_id_cd varchar NULL,
	item_hazardous_limited_qty_flg varchar NULL,
	item_hazardous_package_grp_cd varchar NULL,
	manufacturer_part_nbr_id varchar NULL,
	primary_vendor_upc_id varchar NULL,
	primary_vendor_item_id varchar NULL,
	host_status_cd varchar NULL,
	item_miscellaneous_attr_1_cd varchar NULL,
	item_miscellaneous_attr_1_desc varchar NULL,
	item_miscellaneous_attr_2_cd varchar NULL,
	item_miscellaneous_attr_2_desc varchar NULL,
	item_miscellaneous_attr_3_cd varchar NULL,
	item_miscellaneous_attr_3_desc varchar NULL,
	item_miscellaneous_attr_4_cd varchar NULL,
	item_miscellaneous_attr_4_desc varchar NULL,
	item_miscellaneous_attr_5_cd varchar NULL,
	item_miscellaneous_attr_5_desc varchar NULL,
	item_set_typ_cd varchar NULL,
	item_set_typ_nm varchar NULL,
	selling_uom_cd varchar NULL,
	chain_prc_cd varchar NULL,
	zone_prc_cd varchar NULL,
	store_prc_cd varchar NULL,
	item_discontinue_dt_skey date NULL,
	csc_stocked_ind float8 NULL,
	scrap_reporting_exclude_ind float8 NULL,
	private_label_cd varchar NULL,
	private_label_nm varchar NULL,
	rplc_item_key varchar NULL,
	dept_cls_hier_nm varchar NULL,
	dept_cls_hier_short_nm varchar NULL,
	primary_vendor_key varchar NULL,
	vendor_1_addr varchar NULL,
	vendor_2_addr varchar NULL,
	vendor_3_addr varchar NULL,
	city_nm varchar NULL,
	zip_cd varchar NULL,
	state_key varchar NULL,
	cntry_key varchar NULL,
	vendor_typ_cd varchar NULL,
	state_cd varchar NULL,
	state_nm varchar NULL,
	cntry_cd varchar NULL,
	cntry_nm varchar NULL,
	cntry_short_nm varchar NULL,
	buyer_key varchar NULL,
	buyer_phone_ext_cd varchar NULL,
	buyer_strt_dt_skey int4 NULL,
	merchandiser_key varchar NULL,
	merchandiser_id varchar NULL,
	merchandiser_nm varchar NULL,
	merchandiser_phone_ext_cd varchar NULL,
	merchandiser_strt_dt_skey int4 NULL,
	dept_cls_hier_key varchar NULL,
	sku_type_desc varchar NULL,
	active_flag varchar NULL,
	merch_flag int4 NOT NULL,
	"map" float8 NULL,
	manufacturer_id varchar NULL,
	CONSTRAINT product_attributes_filter_pk PRIMARY KEY (product_code, l0_name),
	CONSTRAINT product_attributes_filter_fk FOREIGN KEY (product_code) REFERENCES "global".product_master(product_code) ON DELETE CASCADE
)
PARTITION BY LIST (l0_name);
CREATE INDEX product_attributes_filter_l0_name_idx ON global.product_attributes_filter USING btree (l0_name);
CREATE INDEX product_attributes_filter_product_code_idx ON global.product_attributes_filter USING btree (product_code);


--changeset kumaran.k@impactanalytics.co:product_attributes_filter_v3 stripComments:false splitStatements:false context:Release_1_0 ignore:false labels:tb_product_hierarchy_combination_version
--comment: adding columns
ALTER TABLE "global".product_attributes_filter
add column product_bucket_code text NULL;


--changeset kumaran.k@impactanalytics.co:product_attributes_filter_v4 stripComments:false splitStatements:false context:Release_1_0 ignore:false labels:tb_product_hierarchy_combination_version
--comment: dropping and recreating the table


DROP TABLE IF EXISTS "global".product_attributes_filter CASCADE;
CREATE TABLE "global".product_attributes_filter (
	product_code varchar NOT NULL,
	product_name varchar NOT NULL,
	product_description text NULL,
	price float8 NULL,
	"cost" float8 NULL,
	original_price float8 NULL,
	active bool NOT NULL,
	clearance bool NOT NULL,
	receipt_date date NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	replacement_product_codes _varchar NULL,
	reference_product_codes _varchar NULL,
	is_deleted bool NULL,
	buyer_id varchar NULL,
	buyer_description varchar NULL,
	l0_code varchar NOT NULL,
	l0_description varchar NOT NULL,
	l1_code varchar NOT NULL,
	l1_description varchar NOT NULL,
	l2_code varchar NOT NULL,
	l2_description varchar NOT NULL,
	l3_code varchar NOT NULL,
	l3_description varchar NOT NULL,
	vendor_id varchar NULL,
	vendor_description varchar NULL,
	rebranded_item_id varchar NULL,
	pack_size int4 NULL,
	product_status varchar NULL,
	item_clearance_dt varchar NULL,
	launch_date date NULL,
	item_key varchar NULL,
	l0_name varchar NOT NULL,
	l1_name varchar NOT NULL,
	l2_name varchar NOT NULL,
	l3_name varchar NOT NULL,
	item_short_desc varchar NULL,
	item_typ_cd varchar NULL,
	item_typ_nm varchar NULL,
	item_hazardous_cd varchar NULL,
	item_hazardous_cls_cd varchar NULL,
	item_hazardous_sub_cls_cd varchar NULL,
	item_hazardous_property_1_nm varchar NULL,
	item_hazardous_property_2_nm varchar NULL,
	item_hazardous_property_3_nm varchar NULL,
	item_hazardous_un_id_cd varchar NULL,
	item_hazardous_limited_qty_flg varchar NULL,
	item_hazardous_package_grp_cd varchar NULL,
	manufacturer_part_nbr_id varchar NULL,
	primary_vendor_upc_id varchar NULL,
	primary_vendor_item_id varchar NULL,
	host_status_cd varchar NULL,
	item_miscellaneous_attr_1_cd varchar NULL,
	item_miscellaneous_attr_1_desc varchar NULL,
	item_miscellaneous_attr_2_cd varchar NULL,
	item_miscellaneous_attr_2_desc varchar NULL,
	item_miscellaneous_attr_3_cd varchar NULL,
	item_miscellaneous_attr_3_desc varchar NULL,
	item_miscellaneous_attr_4_cd varchar NULL,
	item_miscellaneous_attr_4_desc varchar NULL,
	item_miscellaneous_attr_5_cd varchar NULL,
	item_miscellaneous_attr_5_desc varchar NULL,
	item_set_typ_cd varchar NULL,
	item_set_typ_nm varchar NULL,
	selling_uom_cd varchar NULL,
	chain_prc_cd varchar NULL,
	zone_prc_cd varchar NULL,
	store_prc_cd varchar NULL,
	item_discontinue_dt_skey date NULL,
	csc_stocked_ind float8 NULL,
	scrap_reporting_exclude_ind float8 NULL,
	private_label_cd varchar NULL,
	private_label_nm varchar NULL,
	rplc_item_key varchar NULL,
	dept_cls_hier_nm varchar NULL,
	dept_cls_hier_short_nm varchar NULL,
	primary_vendor_key varchar NULL,
	vendor_1_addr varchar NULL,
	vendor_2_addr varchar NULL,
	vendor_3_addr varchar NULL,
	city_nm varchar NULL,
	zip_cd varchar NULL,
	state_key varchar NULL,
	cntry_key varchar NULL,
	vendor_typ_cd varchar NULL,
	state_cd varchar NULL,
	state_nm varchar NULL,
	cntry_cd varchar NULL,
	cntry_nm varchar NULL,
	cntry_short_nm varchar NULL,
	buyer_key varchar NULL,
	buyer_phone_ext_cd varchar NULL,
	buyer_strt_dt_skey int4 NULL,
	merchandiser_key varchar NULL,
	merchandiser_id varchar NULL,
	merchandiser_nm varchar NULL,
	merchandiser_phone_ext_cd varchar NULL,
	merchandiser_strt_dt_skey int4 NULL,
	dept_cls_hier_key varchar NULL,
	sku_type_desc varchar NULL,
	active_flag varchar NULL,
	merch_flag int4 NOT NULL,
	"map" float8 NULL,
	manufacturer_id varchar NULL,
	product_bucket_code text NULL,
	resi_logic_id varchar NULL,
	resi_promo_active_flag varchar NULL,
	resi_bp_opt_flag varchar NULL,
	comm_logic_id varchar NULL,
	comm_promo_active_flag varchar NULL,
	comm_bp_opt_flag varchar NULL,
	CONSTRAINT product_attributes_filter_pk PRIMARY KEY (product_code, l0_name),
	CONSTRAINT product_attributes_filter_fk FOREIGN KEY (product_code) REFERENCES "global".product_master(product_code) ON DELETE CASCADE
)
PARTITION BY LIST (l0_name);
CREATE INDEX product_attributes_filter_l0_name_idx ON global.product_attributes_filter USING btree (l0_name);
CREATE INDEX product_attributes_filter_product_code_idx ON global.product_attributes_filter USING btree (product_code);