--liquibase formatted sql
--changeset liquibase:store_attributes_filter_v2 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for store_attributes_filter_v2

DROP TABLE IF EXISTS "global".store_attributes_filter CASCADE;
CREATE TABLE "global".store_attributes_filter (
	store_code varchar NOT NULL,
	store_name varchar NOT NULL,
	store_description text NULL,
	active bool NOT NULL,
	special_classification varchar NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	dc_code int4 NULL,
	fc_code int4 NULL,
	is_deleted bool NULL,
	region varchar NOT NULL,
	district_id varchar NOT NULL,
	acquisition_cd varchar NULL,
	acquisition_key varchar NULL,
	active_flag int8 NULL,
	amex_id varchar NULL,
	aquablue_fiscal_qtr_cd varchar NULL,
	aquablue_strt_dt_skey int4 NULL,
	cass_standardized_cd varchar NULL,
	catalog_zone_cd varchar NULL,
	channel varchar NULL,
	city varchar NULL,
	close_date date NULL,
	cmp_cd varchar NULL,
	cmp_nm varchar NULL,
	comm_territory_cd varchar NULL,
	comm_territory_nm varchar NULL,
	costing_method_cd varchar NULL,
	country varchar NULL,
	discover_id varchar NULL,
	district varchar NULL,
	district_key varchar NULL,
	district_short_nm varchar NULL,
	geography_cd varchar NULL,
	latitude float8 NULL,
	leslies_cc_id varchar NULL,
	line_1_addr varchar NULL,
	line_2_addr varchar NULL,
	line_3_addr varchar NULL,
	longitude float8 NULL,
	merchant_id varchar NULL,
	model_store_cd varchar NULL,
	open_date date NULL,
	prior_district_key varchar NULL,
	prior_rgn_key varchar NULL,
	region_id varchar NULL,
	rgn_key varchar NULL,
	rgn_manager_nm varchar NULL,
	rgn_phone_txt varchar NULL,
	rgn_short_nm varchar NULL,
	shk_store_maturity_cd varchar NULL,
	state varchar NULL,
	store_actv_on_ap_flg varchar NULL,
	store_actv_on_ar_flg varchar NULL,
	store_actv_on_gl_flg varchar NULL,
	store_comp_end_dt_skey int4 NULL,
	store_comp_refr_dt_skey int4 NULL,
	store_comp_start_dt_skey int4 NULL,
	store_fax_txt varchar NULL,
	store_gl_cmp_nbr int4 NULL,
	store_intf_flg varchar NULL,
	store_key varchar NULL,
	store_last_merchant_cnt int4 NULL,
	store_manager_nm varchar NULL,
	store_office_cd varchar NULL,
	store_open_sunday_flg varchar NULL,
	store_oper_cd varchar NULL,
	store_phone_txt varchar NULL,
	store_preferred_cust_1_key varchar NULL,
	store_preferred_cust_2_key varchar NULL,
	store_preferred_cust_3_key varchar NULL,
	store_repl_flg varchar NULL,
	store_short_nm varchar NULL,
	store_size float8 NULL,
	store_typ_cd varchar NULL,
	store_type varchar NULL,
	store_warehouse_cd varchar NULL,
	svc_trade_territory_cd varchar NULL,
	svc_trade_territory_nm varchar NULL,
	township_nm varchar NULL,
	wfb_id varchar NULL,
	zipcode varchar NULL,
	zone_cat_cd varchar NULL,
	zone_id varchar NULL,
	zone_key varchar NULL,
	zone_nm varchar NULL,
	zone_short_nm varchar NULL,
	market_name varchar NULL,
	CONSTRAINT store_attributes_filter_pk PRIMARY KEY (store_code),
	CONSTRAINT store_attributes_filter_fk FOREIGN KEY (store_code) REFERENCES "global".store_master(store_code) ON DELETE CASCADE
);


--changeset kumaran.k@impactanalytics.co:store_attributes_filter_v2 stripComments:false splitStatements:false context:Release_1_0 ignore:false labels:tb_product_hierarchy_combination_version
--comment: renaming columns
ALTER TABLE "global".store_attributes_filter
RENAME COLUMN active_flag TO active_flag_store;