--liquibase formatted sql
--changeset mayank.bhardwaj@impactanalytics.co :assort_smart.plan_hierarchy_budget_opt_master_wp stripComments:false splitStatements:false context:MTP-70241 labels:create_table
--comment: initial changeset for plan_hierarchy_budget_opt_master_wp

CREATE TABLE assort_smart.plan_hierarchy_budget_opt_master_wp (
	plan_hierarchy_budget_opt_master_id serial4 NOT NULL,
	plan_code int4 NULL,
	is_active text NULL,
	optimization_level text NULL,
	carryover_flag text NULL,
	compare_type int4 NULL,
	new_l3_flag bool NULL,
	penetration_ly numeric NULL,
	margin_percentage numeric NULL,
	sell_through numeric NULL,
	txn_aur_ly numeric NULL,
	txn_aur_ty numeric NULL,
	aur_ly numeric NULL,
	aur_ty numeric NULL,
	air_ly numeric NULL,
	air_ty numeric NULL,
	imu_ly float4 NULL,
	imu_ty float4 NULL,
	cogs_ly numeric NULL,
	margin_ly numeric NULL,
	msrp_ly numeric NULL,
	receipts_quantity_ly numeric NULL,
	total_receipts_cost_ly numeric NULL,
	existing text NULL,
	revenue_ly numeric NULL,
	budget_ly numeric NULL,
	total_available_cost_ly numeric NULL,
	total_available_quantity_ly numeric NULL,
	receipts_price_per_unit numeric NULL,
	penetration_ty numeric NULL,
	cogs_ty numeric NULL,
	l2_launch_budget_ly numeric NULL,
	l2_launch_budget_ty numeric NULL,
	budget_ty numeric NULL,
	receipts_quantity_ty numeric NULL,
	total_receipts_price_ty numeric NULL,
	total_receipts_cost_ty numeric NULL,
	budget_diff numeric NULL,
	cost_budget_diff numeric NULL,
	penetration_diff numeric NULL,
	sales_ty numeric NULL,
	sales_ly numeric NULL,
	gross_margin_ty numeric NULL,
	gross_margin_ly numeric NULL,
	sales_units_ty numeric NULL,
	sales_units_ly numeric NULL,
	revenue_ty numeric NULL,
	store_eligibility_groups text NULL,
	default_budget_ty numeric NULL,
	default_receipts_quantity_ty numeric NULL,
	default_sales_ty numeric NULL,
	default_sales_units_ty numeric NULL,
	default_gross_margin_ty numeric NULL,
	default_cogs_ty numeric NULL,
	l3_name text NULL,
	hierarchy_code text NULL,
	channel int4 NULL,
	sub_channel int4 NULL,
	season_code int4 NULL,
	receipts_price_per_unit_ly numeric NULL,
	target float8 NULL,
	msrp_ty numeric NULL,
	margin_percentage_ty numeric NULL,
	sell_through_ly numeric NULL,
	bop_units_ly numeric DEFAULT 0 NULL,
	bop_units_ty numeric DEFAULT 0 NULL,
	CONSTRAINT plan_hierarchy_budget_master_wp_pkey1 PRIMARY KEY (plan_hierarchy_budget_opt_master_id)
);

--changeset ezhil.kannan@impactanalytics.co:assort_smart.plan_hierarchy_budget_opt_master_wp_sync_idx_starboard stripComments:false splitStatements:false context:aps_st_v3_perf_indexes labels:performance_index
--comment: Align with briscoes performance indexes for aps-st-v3
CREATE INDEX IF NOT EXISTS idx_plan_hierarchy_budget_opt_master_wp_plan_compare_hier_1
ON assort_smart.plan_hierarchy_budget_opt_master_wp (plan_code, compare_type, hierarchy_code);

CREATE INDEX IF NOT EXISTS idx_phbom_wp_plan_compare_opt ON assort_smart.plan_hierarchy_budget_opt_master_wp (plan_code, compare_type, optimization_level) WHERE is_active = 'YES';