--liquibase formatted sql
--changeset liquibase:update_defaults_in_ph_config runOnChange:true stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for update_defaults_in_ph_config
--rollback: SELECT 1
DROP PROCEDURE IF EXISTS inventory_smart.update_defaults_in_ph_config(IN mapping_codes integer[]);
CREATE OR REPLACE PROCEDURE inventory_smart.update_defaults_in_ph_config(IN mapping_codes integer[])
 LANGUAGE plpgsql
AS $procedure$
-- as per team request and client concern should not delete any config data generated by client + one observation i.e. only running this update for incoming codes while it should be global 
	
	/*
	 * Procedure name: global.update_defaults_in_ph_config
	 * Created by: Subhash Pophale
	 * Created at: 13-May-2022
	 * No of input parameter: 1
	 * Parameter Description : $1 = product to store mapping codes
	 * Purpose: This function been created update default store groups in 
	 *          inventory smart ph configuration maping
	 */

declare
	_log_code varchar := gen_random_uuid();
	_sp_name varchar := 'inventory_smart.update_defaults_in_ph_config';
	_log_step varchar;
	_st TIMESTAMP := clock_timestamp();
begin
	call global.data_ingestion_logs(_log_code, _sp_name, 'start', null, (clock_timestamp() - _st)::text, null);
	perform set_config('local.log_code', _log_code, true);
	perform set_config('local.sp_name', _sp_name, true);
	begin
--   update inventory_smart.ph_configuration_mapping pcm 
--   set default_store_groups  = (select array_agg(aa)
--                                from unnest(default_store_groups) aa left join unnest(available_store_grups.sg_codes) ab on aa = ab
--                                where ab is not null
--                               )
--   from (with product_store_mapping as (
-- 			  select 
-- 			    mapping_code,
-- 			    pmps.product_code ,
-- 			    pmps.store_code, 
-- 			    ph_code 
-- 			  from 
-- 			    inventory_smart.ph_master ph 
-- 			    join global.product_mapping_product_store pmps on pmps.product_code = ANY (ph.product_codes) 
-- 			    join (SELECT store_code, channel FROM "global".store_attributes_filter  ) saf 
-- 				on ph.channel = saf.channel 
-- 				and pmps.store_code = saf.store_code 
-- 			  where 
-- 			    is_active = true 
-- 			  and 
-- 			     pmps.mapping_code = ANY(mapping_codes)
-- 			)
-- 			--select * from product_store_mapping 
-- 				  select ph_code,
-- 				  		 array_agg(distinct sg.sg_code)  as sg_codes,
-- 				  		 count(distinct sgm2.store_code) as store_available_count
-- 				  from 
-- 				        "global".store_groups_mapping sgm2
-- 				  join product_store_mapping psm on psm.store_code = sgm2.store_code
-- 				  join (
-- 				  	select 
-- 				        sg.sg_code
-- 				      from 
-- 				        global.store_groups sg 
-- 				        join global.store_groups_mapping sgm on sg.sg_code = sgm.sg_code 
-- 				      where 
-- 				        is_deleted = false
-- 						and application_code =1
-- 				        --and channel = channel
-- 				      group by 
-- 				        1
-- 				  ) sg on sg.sg_code = sgm2.sg_code group by ph_code 				
-- 			) available_store_grups
--    where pcm.ph_code  = available_store_grups.ph_code;
 
		call global.data_ingestion_logs(_log_code, _sp_name, 'end', null, (clock_timestamp() - _st)::text, null);
	exception
		when others then
	        -- Log the error if an exception occurs during any part of the procedure
	        call global.data_ingestion_logs(_log_code, _sp_name, _log_step, SQLERRM, (clock_timestamp() - _st)::text, null);
            raise exception 'Error occurred in the procedure: %', SQLERRM;
	end;
end;
$procedure$
;
