import makeStyles from "@mui/styles/makeStyles";

export const useProductExpansionStyles = makeStyles(() => ({
  // Figma 18260:70232 — separate card under Product Details
  panel: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    padding: "0 16px 12px 16px",
    borderRadius: 8,
    backgroundColor: "#fff",
    boxShadow: "0 0 4px 0 rgba(0, 0, 0, 0.12)",
    overflow: "visible",
    minHeight: 500,
    boxSizing: "border-box",
  },
  expansionRoot: {
    overflow: "visible",
    display: "flex",
    flexDirection: "column",
  },
  // Figma 18994:104372 — header + DC KPI as one block
  breakdownSummary: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "12px 0 0",
    overflow: "visible",
  },
  nestedDetail: {
    padding: "16px 24px",
    boxSizing: "border-box",
  },
  /* ── Header bar ── */
  headerBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 12px",
  },
  headerTitle: {
    fontFamily: "Manrope",
    fontWeight: 700,
    fontSize: 14,
    lineHeight: "21px",
    color: "#0d152c",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  verticalDivider: {
    width: 0,
    height: 12,
    borderLeft: "1px solid #c3c8d4",
    flexShrink: 0,
  },
  headerArticleWrap: {
    display: "flex",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  headerArticleLabel: {
    fontFamily: "Manrope",
    fontWeight: 700,
    fontSize: 14,
    lineHeight: "21px",
    color: "#60697d",
    whiteSpace: "nowrap",
    "& span": {
      color: "#31416e",
    },
  },
  headerBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minWidth: 56,
    maxHeight: 32,
    padding: "6px 12px",
    border: "1px solid #c3c8d4",
    borderRadius: 8,
    backgroundColor: "#fff",
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "20px",
    color: "#1f2b4d",
    cursor: "pointer",
    flexShrink: 0,
    textTransform: "capitalize",
    "&:hover": { backgroundColor: "#f5f6fa" },
  },
  closeBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minWidth: 56,
    maxHeight: 32,
    padding: "6px 12px",
    border: "none",
    borderRadius: 8,
    backgroundColor: "#f5f6fa",
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "20px",
    color: "#60697d",
    cursor: "pointer",
    flexShrink: 0,
    "&:hover": { backgroundColor: "#ebedf5" },
  },
  iconSm: {
    width: 16,
    height: 16,
    flexShrink: 0,
    display: "block",
  },
  /* ── DC strip ── */
  dcStrip: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
    overflow: "visible",
  },
  dcStripRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
  },
  dcCard: {
    flex: "1 1 0%",
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "nowrap",
    gap: 8,
    backgroundColor: "#f8f9fb",
    borderRadius: 12.851,
    padding: "4.284px 16px",
    boxShadow: "0px 0px 4px 0px rgba(0,0,0,0.12)",
    overflow: "visible",
    boxSizing: "border-box",
  },
  dcCardHalf: {
    flex: "0 1 calc(50% - 6px)",
    maxWidth: "calc(50% - 6px)",
  },
  dcCardName: {
    fontFamily: "Manrope",
    fontWeight: 600,
    fontSize: 17.134,
    lineHeight: "25.702px",
    color: "#31416e",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  dcCardMetrics: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flex: "1 1 0%",
    minWidth: 0,
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: 8.567,
    backgroundColor: "#fff",
    borderRadius: 4.284,
    padding: "4.284px 8.567px",
    flex: "1 1 185px",
    width: 185,
    minWidth: 0,
    boxSizing: "border-box",
    borderLeft: "1.606px solid",
  },
  legendLabel: {
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 12.851,
    lineHeight: 1.25,
    color: "#60697d",
    flex: "1 1 0%",
    minWidth: 0,
    whiteSpace: "nowrap",
  },
  legendValue: {
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 14.993,
    lineHeight: "21.418px",
    color: "#1f2b4d",
    textAlign: "right",
    flexShrink: 0,
    width: 42.836,
    whiteSpace: "nowrap",
  },
  dcExpandBtn: {
    appearance: "none",
    WebkitAppearance: "none",
    margin: 0,
    width: 32,
    height: 32,
    minWidth: 32,
    minHeight: 32,
    maxWidth: 32,
    maxHeight: 32,
    padding: 8,
    boxSizing: "border-box",
    backgroundColor: "#fff",
    border: "1px solid #c3c8d4",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    lineHeight: 0,
    "&:hover, &:active, &:focus": {
      backgroundColor: "#eceefd",
      border: "1px solid #3649c6",
      outline: "none",
    },
    "&:hover $dcExpandIcon path, &:active $dcExpandIcon path, &:focus $dcExpandIcon path": {
      fill: "#3649c6",
    },
  },
  dcExpandIcon: {
    width: 16,
    height: 16,
    display: "block",
    flexShrink: 0,
  },
  breakdownBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    background: "none",
    border: "none",
    padding: 0,
    margin: 0,
    cursor: "pointer",
    flexShrink: 0,
    lineHeight: 0,
  },
  breakdownTextWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 16,
    flexShrink: 0,
  },
  breakdownText: {
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "20px",
    color: "#4259ee",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  breakdownIcon: {
    width: 16,
    height: 16,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& svg": {
      width: 12,
      height: 12,
      display: "block",
    },
  },
  /* ── Table section — 16px under DC KPI (Figma 18260:70232) ── */
  tableSection: {
    marginTop: 16,
  },
  breakdownContent: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    overflow: "visible",
  },
}));
