--liquibase formatted sql
--changeset sreevathsa.sp:product_master_price_promo_view_20251224 runAlways:true stripComments:false splitStatements:false context:product_master labels:product_master
--comment: color columns added
--rollback: SELECT 1

DROP VIEW IF EXISTS price_promo.product_master;
CREATE OR REPLACE VIEW price_promo.product_master
AS SELECT 
    active,
    age_month_bucket,
    clearance_indicator,
    cost,
    cost_usd,
    currency_id,
    current_price,
    current_price_with_vat,
    ecom_age,
    eol_flag,
    hierarchy_id,
    is_active,
    it,
    kvi_indicator,
    l0_cid,
    l0_cuq,
    l0_id,
    l0_name,
    l1_cid,
    l1_cuq,
    l1_id,
    l1_name,
    l2_cid,
    l2_cuq,
    l2_id,
    l2_name,
    l3_cid,
    l3_cuq,
    l3_id,
    l3_name,
    l4_cid,
    l4_cuq,
    l4_id,
    l4_name,
    l5_cid,
    l5_cuq,
    l5_id,
    l5_name,
    l6_cid,
    l6_cuq,
    l6_id,
    l6_name,
    last_sold,
    launch_date,
    launch_price,
    lifecycle,
    lifecycle_indicator,
    max_age,
    merchant_mail_id,
    msrp,
    msrp_with_vat,
    oh,
    oo,
    price_bucket,
    price_bucket_cid,
    primary_upc,
    product_cuq,
    product_description,
    product_id,
    product_name,
    promo_base_price,
    promo_base_price_valid_from,
    promo_base_price_valid_to,
    size,
    size_bucket,
    size_bucket_cid,
    size_id,
    status,
    status_id,
    store_age,
    total_inventory,
    uam_hierarchy_id,
    launch_price_with_vat,
    l7_id,
    l7_name,
    l7_cid,
    l7_cuq,
    customer_choice_id,
    customer_choice_description,
    last_reg_price_bnm,
    last_reg_price_bnm_with_vat,
    last_reg_price_ecom,
    last_reg_price_ecom_with_vat,
    new_product_flag,
    program_id,
    program_name,
    color_cid,
    color_cuq
FROM price_promo.product_master_promo_version t1
WHERE version_code = global.get_table_version('price_promo.product_master_promo_version'::text);