--liquibase formatted sql
--changeset liquibase:store_attributes_filter stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for store_attributes_filter

CREATE TABLE "global".store_attributes_filter (
	store_code varchar NOT NULL,
	store_name varchar NOT NULL,
	store_description text NULL,
	active bool NOT NULL,
	special_classification varchar NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	dc_code int4 NULL,
	fc_code int4 NULL,
	is_deleted bool NULL,
	s0_id varchar NOT NULL,
	s1_name varchar NOT NULL,
	s2_name varchar NOT NULL,
	s3_name varchar NULL,
	s4_name varchar NULL,
	s5_name varchar NOT NULL,
	channel_desc varchar NULL,
	channel_id varchar NULL,
	climate varchar NULL,
	close_date date NULL,
	comp_date date NULL,
	comp_status varchar NULL,
	latitude varchar NULL,
	like_store_id varchar NULL,
	location_type varchar NULL,
	longitude varchar NULL,
	open_date date NULL,
	store_selling_area int4 NULL,
	store_status varchar NULL,
	store_tier_grade varchar NULL,
	store_type varchar NULL,
	total_store_area int4 NULL,
	traffic int4 NOT NULL,
	zipcode varchar NULL,
	perimeter varchar NULL,
	perimeter_cy varchar NULL,
	perimeter_ly varchar NULL,
	perimeter_lly varchar NULL,
	CONSTRAINT store_attributes_filter_pk PRIMARY KEY (store_code),
	CONSTRAINT store_attributes_filter_fk FOREIGN KEY (store_code) REFERENCES "global".store_master(store_code) ON DELETE CASCADE
);