--liquibase formatted sql
--changeset kalyan.chandu@impactanalytics.co:new_skus stripComments:false splitStatements:false context:Release_1_0 labels:new_skus_itemsmart_initial_commit
--comment: initial changeset for new_skus

CREATE TABLE item_smart.new_skus (
	hierarchy_code int4 NULL,
	l0_name varchar NULL,
	l1_name varchar NULL,
	l2_name varchar NULL,
	l3_name varchar NULL,
	product_code varchar NULL,
	product_name varchar NULL,
	"level" int2 NULL,
	active bool NULL,
	product_description text NULL,
	l1_id varchar NULL,
	l2_desc varchar NULL,
	l2_id varchar NULL,
	l3_desc varchar NULL,
	l3_id varchar NULL,
	"cost" float8 NULL,
	"size" varchar NULL,
	paf_active bool NULL,
	allow_direct_ship_code float8 NULL,
	allow_direct_ship_desc varchar NULL,
	class_name varchar NULL,
	clearance bool NULL,
	collection_desc varchar NULL,
	collection_id varchar NULL,
	collection_name varchar NULL,
	created_at timestamptz NULL,
	created_by int4 NULL,
	cubic_meter varchar NULL,
	depth_dimension float8 NULL,
	division_name varchar NULL,
	dpt_name varchar NULL,
	first_case_sell_price float8 NULL,
	first_sugg_retail_price float8 NULL,
	height_dimension float8 NULL,
	is_deleted bool NULL,
	is_special_order bool NULL,
	kit_status varchar NULL,
	kit_status_desc varchar NULL,
	lifestyle varchar NULL,
	multi_division_mapping_flag int8 NULL,
	original_price float8 NULL,
	price float8 NULL,
	price_bucket varchar NULL,
	promo_end_date varchar NULL,
	promo_price float8 NULL,
	promo_start_date varchar NULL,
	purchase_status varchar NULL,
	purchase_status_code varchar NULL,
	purchase_status_type varchar NULL,
	purchase_status_type_code varchar NULL,
	rec_status varchar NULL,
	receipt_date date NULL,
	reference_product_codes _varchar NULL,
	replacement_product_codes _varchar NULL,
	retail_price float8 NULL,
	sell_price float8 NULL,
	storage_depth float8 NULL,
	storage_height float8 NULL,
	storage_weight float8 NULL,
	storage_width float8 NULL,
	super_collection_desc varchar NULL,
	super_collection_id varchar NULL,
	updated_at timestamptz NULL,
	updated_by int4 NULL,
	vendor_id varchar NULL,
	vendor_model_number varchar NULL,
	vendor_name varchar NULL,
	width_dimension float8 NULL,
	worry_free_eligible float8 NULL,
	worry_free_outdoor_eligible float8 NULL,
	product_bucket_code int8 NULL,
	active_flag varchar NULL,
	comfort varchar NULL,
	second_description varchar NULL,
	finish varchar NULL,
	special_order_lead_time varchar NULL,
	"type" varchar NULL,
	markdown_date date NULL,
	shape varchar NULL,
	form varchar NULL,
	moq varchar NULL,
	launch_date date NULL,
	custom_special_order_lead_time varchar NULL,
	description varchar NULL,
	exit_date date NULL,
	"function" varchar NULL,
	aesthetic varchar NULL,
	no_of_reg_weeks int8 NULL,
	covering varchar NULL,
	color varchar NULL,
	product_type varchar NULL,
	first_replacement_cost float8 NULL,
	replacement_cost float8 NULL,
	plannable_hierarchy int8 NULL,
	master_hierarchy_code varchar NULL,
	lead_time int8 NULL,
	is_cadence_generated bool DEFAULT false NULL,
	is_mapped bool DEFAULT false NULL,
	mapped_product_code varchar NULL
);

--changeset kalyan.chandu@impactanalytics.co:added_mapped_product_code_description_for_new_skus stripComments:false splitStatements:false context:Release_1_1 labels:added_mapped_product_code_description_for_new_skus
--comment: added_mapped_product_code_description_for_new_skus

ALTER TABLE item_smart.new_skus ADD COLUMN mapped_product_code_description VARCHAR NULL;