--liquibase formatted sql
--changeset sreevathsa.sp:product_master_pricesmart_view_20251224 runAlways:true stripComments:false splitStatements:false context:Release_1_0 labels:product_master_pricesmart
--comment: Updated product_master view to use price_markdown.product_master_price_markdown_version
--rollback: SELECT 1

DROP VIEW IF EXISTS pricesmart.product_master CASCADE;
CREATE OR REPLACE VIEW pricesmart.product_master
AS SELECT 
    t1.article,
    t1.active,
    t1.age_month_bucket,
    t1.clearance_indicator,
    t1.cost,
    t1.cost_usd,
    t1.currency_id,
    t1.current_price,
    t1.current_price_with_vat,
    t1.ecom_age,
    t1.eol_flag,
    t1.hierarchy_id,
    t1.is_active,
    t1.it,
    t1.kvi_indicator,
    t1.l0_cid,
    t1.l0_cuq,
    t1.l0_id,
    t1.l0_name,
    t1.l1_cid,
    t1.l1_cuq,
    t1.l1_id,
    t1.l1_name,
    t1.l2_cid,
    t1.l2_cuq,
    t1.l2_id,
    t1.l2_name,
    t1.l3_cid,
    t1.l3_cuq,
    t1.l3_id,
    t1.l3_name,
    t1.l4_cid,
    t1.l4_cuq,
    t1.l4_id,
    t1.l4_name,
    t1.l5_cid,
    t1.l5_cuq,
    t1.l5_id,
    t1.l5_name,
    t1.l6_cid,
    t1.l6_cuq,
    t1.l6_id,
    t1.l6_name,
    t1.last_sold,
    t1.launch_date,
    t1.launch_price,
    t1.lifecycle,
    t1.lifecycle_indicator,
    t1.max_age,
    t1.merchant_mail_id,
    t1.msrp,
    t1.msrp_with_vat,
    t1.oh,
    t1.oo,
    t1.price_bucket,
    t1.price_bucket_cid,
    t1.primary_upc,
    t1.product_cuq,
    t1.product_description,
    t1.product_id,
    t1.product_name,
    t1.promo_base_price,
    t1.promo_base_price_valid_from,
    t1.promo_base_price_valid_to,
    t1.size,
    t1.size_bucket,
    t1.size_bucket_cid,
    t1.size_id,
    t1.status,
    t1.status_id,
    t1.store_age,
    t1.total_inventory,
    t1.uam_hierarchy_id,
    t1.launch_price_with_vat,
    t1.l7_id,
    t1.l7_name,
    t1.l7_cid,
    t1.l7_cuq,
    t1.customer_choice_id,
    t1.customer_choice_description,
    t1.last_reg_price_bnm,
    t1.last_reg_price_bnm_with_vat,
    t1.last_reg_price_ecom,
    t1.last_reg_price_ecom_with_vat,
    t1.new_product_flag,
    t1.program_id,
    t1.program_name,
    t1.color_cid,
    t1.color_cuq
FROM pricesmart.product_master_pricesmart_version t1
WHERE t1.version_code = global.get_table_version('pricesmart.product_master_pricesmart_version'::text);