--liquibase formatted sql
--changeset liquibase:tb_calendar_date_mapping stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for tb_calendar_date_mapping
DROP TABLE IF EXISTS "global".calendar_date_mapping;
CREATE TABLE "global".calendar_date_mapping (
	"day" int2 NULL,
	week_in_month int2 NULL,
	week_in_quarter int2 NULL,
	day_name varchar NULL,
	week_begin_date date NULL,
	week_end_date date NULL,
	year_month int4 NULL,
	day_name_abb varchar NULL,
	month_in_quarter int2 NULL,
	month_in_year int2 NULL,
	month_begin_date date NULL,
	week_in_season int2 NULL,
	month_end_date date NULL,
	quarter_in_year int2 NULL,
	year_week_prior int4 NULL,
	year_week_2wa int4 NULL,
	quarter_begin_date date NULL,
	quarter_end_date date NULL,
	year_begin_date date NULL,
	month_in_season int2 NULL,
	year_end_date date NULL,
	day_in_week int2 NULL,
	prior_year_comp_week int4 NULL,
	season_begin_date date NULL,
	week int2 NULL,
	quarter_name varchar NULL,
	quarter_name_abb varchar NULL,
	year_quarter_prior int4 NULL,
	week_in_year int2 NULL,
	season_in_year int2 NULL,
	season_end_date date NULL,
	year_season_prior int4 NULL,
	calendar_date date NULL,
	date_id int4 NULL,
	weekday_indicator varchar NULL,
	quarter_in_season int2 NULL,
	month_name varchar NULL,
	month_name_abb varchar NULL,
	year_month_prior int4 NULL,
	year_period int4 NULL,
	day_in_season int2 NULL,
	day_in_quarter int2 NULL,
	year_week int4 NULL,
	bi_week int2 NULL,
	day_in_year int2 NULL,
	day_of_week int2 NULL,
	"date" date NOT NULL,
	day_in_month int2 NULL,
	year_quarter int4 NULL,
	season varchar NULL,
	season_name_abb varchar NULL,
	"month" int2 NULL,
	quarter int2 NULL,
	"year" int2 NULL,
	year_week_3wa int4 NULL,
	year_season int4 NULL,
	trend int4 NULL,
	year_month_id int4 NULL,
	CONSTRAINT calendar_date_mapping_pk PRIMARY KEY (date)
);
CREATE INDEX calendar_date_mapping_date_idx ON global.calendar_date_mapping USING btree (date);