--liquibase formatted sql
--changeset siddharth.bajpai@impactanalytics.co:tb_transaction_latest_mkd_version_20251216 stripComments:false splitStatements:false context:Release_1_0 labels:tb_transaction_latest_mkd
--comment: Create tb_transaction_latest_mkd_version table

CREATE TABLE IF NOT EXISTS price_markdown_opt.tb_transaction_latest_mkd_version (
	date_id date NOT NULL,
	s0_id int4 NULL,
	s1_id int4 NULL,
	product_id int4 NOT NULL,
	store_id int4 NOT NULL,
	clearance_indicator int4 NOT NULL,
	"cost" float4 NULL,
	retail_price float4 NULL,
	aur float4 NULL,
	aum float4 NULL,
	selling_price float4 NULL,
	selling_price_with_vat float4 NULL,
	final_discount_percent float4 NULL,
	total_inv int4 NULL,
	sync_date_time date NULL,
	currency_id int8 NULL,
	retail_price_with_vat float8 NULL,
	revenue_with_vat float8 NULL,
	margin_with_vat float8 NULL,
	aur_with_vat float8 NULL,
	aum_with_vat float8 NULL,
	final_price_with_vat float8 NULL,
	currency text NULL,
	no_of_txn int4 NULL,
	gross_quantity int4 NULL,
	gross_revenue float4 NULL,
	gross_revenue_with_vat float4 NULL,
	gross_margin float4 NULL,
	gross_margin_with_vat float4 NULL,
	gross_sp_with_vat float4 NULL,
	gross_sp float4 NULL,
	gross_dis_amount_with_vat float4 NULL,
	gross_dis_amount float4 NULL,
	gross_dis_perc_with_vat float4 NULL,
	gross_dis_perc float4 NULL,
	final_discount_percent_with_vat float4 NULL,
	final_amount float4 NULL,
	final_amount_with_vat float4 NULL,
	promo_spend float8 NULL,
	promo_discount float8 NULL,
	promo_amount float4 NULL,
	promo_amount_with_vat float4 NULL,
	promo_discount_with_vat float4 NULL,
	coupon_amount float4 NULL,
	coupon_amount_with_vat float4 NULL,
	coupon_discount float4 NULL,
	coupon_discount_with_vat float4 NULL,
	vat_rate_per float4 NULL,
	version_code int4 NOT NULL,
	dis_amount float4 NULL,
	dis_perc float4 NULL,
	store_reco_level text NULL,
	CONSTRAINT tb_transaction_latest_mkd_version_pk PRIMARY KEY (product_id, store_id, date_id, clearance_indicator)
)
PARTITION BY RANGE (date_id);
CREATE INDEX mkd_txn_version_store_id_product_id_date_idx ON price_markdown_opt.tb_transaction_latest_mkd_version USING btree (product_id, store_id, date_id);

