let chatbotFilterConfig = {
  total: null,
  page: null,
  count: null,
  status: true,
  data: [
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l0_name",
      label: "Brand",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l1_name",
      label: "Channel",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l2_name",
      label: "Department",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l3_name",
      label: "Class",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l4_name",
      label: "Sub Class",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l5_name",
      label: "Silhouette",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l6_name",
      label: "Collection",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l7_name",
      label: "Sub Collect",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l8_name",
      label: "Style Group",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "article",
      label: "Style Color ID",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "product_code",
      label: "Product Code",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "active",
      label: "Active",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "article_orig",
      label: "Article Orig",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "assortment_indicator",
      label: "Assortment Indicator",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "channel",
      label: "Channel",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "classcode",
      label: "Classcode",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "clearance_start_date",
      label: "Clearance Start Date",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "collection_code",
      label: "Collection Code",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "color",
      label: "Color",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "color_code",
      label: "Color Code",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "color_family_description",
      label: "Color Family Description",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "color_name",
      label: "Color Name",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "cost",
      label: "Cost",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "dept_grouping",
      label: "Dept Grouping",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "deptid",
      label: "Deptid",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "factory_type",
      label: "Factory Type",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "flag",
      label: "Flag",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "ia_sku_type",
      label: "Ia Sku Type",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "intro_date",
      label: "Intro Date",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l0_id",
      label: "Brand",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l1_id",
      label: "L1 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l2_id",
      label: "L2 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l3_id",
      label: "L3 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l4_id",
      label: "L4 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l5_id",
      label: "L5 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l6_id",
      label: "L6 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l7_id",
      label: "L7 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "l8_id",
      label: "L8 Id",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "launch_date",
      label: "Launch Date",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "mapped_color",
      label: "Mapped Color",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "nrf_code",
      label: "Nrf Code",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "price",
      label: "Price",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "product_bucket_code",
      label: "Product Bucket Code",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "product_channel",
      label: "Product Channel",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "product_description",
      label: "Product Description",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "product_name",
      label: "Product Name",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "product_segmentation",
      label: "Product Segmentation",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "seasoncode",
      label: "Seasoncode",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "seasoncode_descr",
      label: "Seasoncode Descr",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "silhouette_code",
      label: "Silhouette Code",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "size",
      label: "Size",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "size_mapping_classification",
      label: "Size Mapping Classification",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "size_name",
      label: "Size Name",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "sku",
      label: "Sku",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "style",
      label: "Style",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "styledesc",
      label: "Styledesc",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "style_long_description",
      label: "Style Long Description",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "style_name",
      label: "Style Name",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "subclasscode",
      label: "Subclasscode",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "subcollect_code",
      label: "Subcollect Code",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "subdeptcode",
      label: "Subdeptcode",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "subdeptname",
      label: "Subdeptname",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "supersede_flag",
      label: "Supersede Flag",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "upc",
      label: "Upc",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "upc_orig",
      label: "Upc Orig",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "vendor_description",
      label: "Vendor Description",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "product",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "vendor_id",
      label: "Vendor Id",
    },
  ],
  message: "Data fetched successfully",
  previous: null,
  next: null,
  offset: null,
  sub_offset: null,
  download_rows: null,
};

let getFilterOptionsPayload = {
  attributes: [
    {
      attribute_name: "l1_name",
      dimension: "product",
      filter_type: "cascaded",
    },
  ],
  filter_type: "cascaded",
  filters: [],
  is_urm_filter: true,
  screen_name: "Chatbot",
  application_code: 1,
};

let getFilterOptionsResponse = {
  total: null,
  page: null,
  count: 1,
  status: true,
  data: {
    l1_name: ["Outlet-Store", "Retail-Store"],
  },
  message: "Successful",
  previous: null,
  next: null,
  offset: null,
  sub_offset: null,
  download_rows: null,
};

let getFilterOptionsWhenSomeFiltersSelectedPayload = {
  attributes: [
    {
      attribute_name: "l3_name",
      dimension: "product",
      filter_type: "cascaded",
    },
  ],
  filter_type: "cascaded",
  filters: [
    {
      filter_name: "Channel",
      filter_id: "l1_name",
      filter_type: "cascaded",
      dimension: "product",
      display_type: "dropdown",
      check_configuration: [],
      is_mandatory: true,
      extra: {},
      values: ["Outlet-Store"],
      attribute_name: "l1_name",
      operator: "in",
      display_order: 2,
    },
    {
      filter_name: "Department",
      filter_id: "l2_name",
      filter_type: "cascaded",
      dimension: "product",
      display_type: "dropdown",
      check_configuration: [],
      is_mandatory: false,
      extra: {},
      values: ["D01-Womens Bags", "D02-Womens Wallets"],
      attribute_name: "l2_name",
      operator: "in",
      display_order: 3,
    },
  ],
  is_urm_filter: true,
  screen_name: "Chatbot",
  application_code: 1,
};

let getFilterOptionsWhenSomeFiltersSelectedResponse = {
  total: null,
  page: null,
  count: 1,
  status: true,
  data: {
    l3_name: ["LGO-Logo", "LTH-Leather", "MIX-Mixed Material", "OTH-Other"],
  },
  message: "Successful",
  previous: null,
  next: null,
  offset: null,
  sub_offset: null,
  download_rows: null,
};

export let chatbotFilterCustomConfig = {
  total: null,
  page: null,
  count: null,
  status: true,
  data: [
    {
      fc_code: null,
      type: "cascaded",
      display_type: "DateTimeField",
      level: null,
      dimension: "custom",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: {
      },
      is_deleted: false,
      column_name: "custom_brand",
      label: "Custom Brand",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "dropdown",
      level: null,
      dimension: "vendor",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "vendor_name",
      label: "Vendor Name",
    },
    {
      fc_code: null,
      type: "cascaded",
      display_type: "sliderRange",
      level: null,
      dimension: "group",
      is_mandatory: false,
      is_multiple_selection: true,
      range_min: null,
      range_max: null,
      default_value: null,
      is_disabled: false,
      is_clearable: true,
      display_order: null,
      is_required: false,
      extra: null,
      is_deleted: false,
      column_name: "group_name",
      label: "Group Name",
    },
  ],
  message: "Data fetched successfully",
  previous: null,
  next: null,
  offset: null,
  sub_offset: null,
  download_rows: null,
};

export let singleConversationNewData = [
  {
    userType: "user",
    chatType: "text",
    data: "List the products which are about to change status in next 10 days",
  },
  {
    userType: "bot",
    chatType: "thinking",
    data: "I will fetch all product status records with effective date ranges that begin or end within the next 10 days. This will provide the raw data needed to identify which products are about to change their active/inactive status soon. Downstream nodes will filter and compute which products have a status transition in the specified window, ensuring the user receives a list of products with upcoming status changes.I will fetch all product status records with effective date ranges that begin or end within the next 10 days. This will provide the raw data needed to identify which products are about to change their active/inactive status soon. Downstream nodes will filter and compute which products have a status transition in the specified window, ensuring the user receives a list of products with upcoming status changes.",
  },
  {
    userType: "bot",
    chatType: "steps",
    data: [
        {
          header: "Assessing user query",
          step_status: "completed",
          sub_header: "Query is within scope and determined as New query",
          current_intent: "List the products which are about to change status in next 10 days"
        },
        {
          header: "Creating Plan of Action",
          step_status: "completed",
          sub_header: "Alan is working to determine the best approach to answer user query",
          current_intent: "List the products which are about to change status in next 10 days"
        },
        {
          header: "Executing Step",
          step_status: "completed",
          sub_header: "Executing Step 1/1",
          current_intent: "List the products which are about to change status in next 10 days"
        },
      ]
  },
  {
    userType: "bot",
    chatType: "agent",
    data: [
      { "type": "select", "data": { "header": "Select", "inputPosition": "inline", "labelOrientation": "top", "label": "L0 Name", "param_name": "l0_name", "options": [{ "label": "Coach", "value": "Coach" }, { "label": "KateSpade", "value": "KateSpade" }], "isRequired": true, "isDisabled": false, "isMulti": true } }, { "type": "select", "data": { "header": "Select", "inputPosition": "inline", "labelOrientation": "top", "label": "L1 Name", "param_name": "l1_name", "options": [{ "label": "Outlet-Store", "value": "Outlet-Store" }, { "label": "Retail-Store", "value": "Retail-Store" }], "isRequired": true, "isDisabled": false, "isMulti": true } }, {"type": "table", "data": {"display_name": "Results", "unique_id": "", "row_data": [{"Style Color ID": "CDM80 B4__ia_char_03M2-Retail-Store", "Style Description": "DSNY GLOV SWINGER", "stockout_store_count": 346, "max_dc_oh_it_oo": 284.0, "lw_sales_units": 6}, {"Style Color ID": "CDN03 B4PF7-Retail-Store", "Style Description": "DSNY GLOV SWINGER", "stockout_store_count": 346, "max_dc_oh_it_oo": 274.0, "lw_sales_units": 5}, {"Style Color ID": "CT255 IMWQJ-Retail-Store", "Style Description": "LTH STP JAMIE CMR", "stockout_store_count": 346, "max_dc_oh_it_oo": 13.0, "lw_sales_units": 2}, {"Style Color ID": "CZ186 IMY4C-Retail-Store", "Style Description": "SIG JAMIE CMR", "stockout_store_count": 346, "max_dc_oh_it_oo": 6.0, "lw_sales_units": 1}, {"Style Color ID": "CCZ17 IMA47-Retail-Store", "Style Description": "CHRRY PT RWN BKT", "stockout_store_count": 346, "max_dc_oh_it_oo": 4.0, "lw_sales_units": 1}], "table_config": [{"column_header": "Style Color Id", "field": "Style Color ID", "is_searchable": true, type: "str"}, {"column_header": "Style Description", "field": "Style Description", "is_searchable": true}, {"column_header": "Stockout Store Count", "field": "stockout_store_count", "is_searchable": true}, {"column_header": "Max Dc Oh It Oo", "field": "max_dc_oh_it_oo", "is_searchable": true}, {"column_header": "Lw Sales Units", "field": "lw_sales_units", "is_searchable": true}]}}]
  }
]

export let dummyStepFormData = { "widget_data": [{ "type": "select", "data": { "header": "Select", "inputPosition": "inline", "labelOrientation": "top", "label": "L0 Name", "param_name": "l0_name", "options": [{ "label": "Coach", "value": "Coach" }, { "label": "KateSpadeeeeeeeeeee", "value": "KateSpade" }], "isRequired": true, "isDisabled": false, "isMulti": true } }, { "type": "select", "data": { "header": "Select", "inputPosition": "inline", "labelOrientation": "top", "label": "L1 Name", "param_name": "l1_name", "options": [{ "label": "Outlet-Store", "value": "Outlet-Store" }, { "label": "Retail-Store", "value": "Retail-Store" }], "isRequired": true, "isDisabled": false, "isMulti": true } }] }
// export let dummyStepFormData = { "widget_data":  [{"type": "datePicker", "data": {"displayFormat": "YYYY-MM-DD", "label": "Start Date", "param_name": "start_date", "isRequired": true, "labelOrientation": "top", "placeholder": "Select Date", "minDate": null, "maxDate": null, "isDisabled": false}}, {"type": "datePicker", "data": {"displayFormat": "YYYY-MM-DD", "label": "End Date", "param_name": "end_date", "isRequired": true, "labelOrientation": "top", "placeholder": "Select Date", "minDate": null, "maxDate": null, "isDisabled": false}}] }
let initApiResponse = `data: {"response_type": "text", "message": "", "response_heading": "Create constraints for the style-colors 101520197 300, 102813APR 600 at the stores KS1802 and KS1803 with min=5, max =100, wos =4 valid for coming 20 days ?", "is_error": false, "status": "started"}

: keepalive

data: {"response_type": "text", "message": "", "response_heading": "Create constraints for the style-colors 101520197 300, 102813APR 600 at the stores KS1802 and KS1803 with min=5, max =100, wos =4 valid for coming 20 days ?", "status": "step", "widget_data": [{"header": "The style-color and store inputs were classified as a new task, so the next pass will shape the 20-day min, max, and weeks-of-supply rules for KS1802 and KS1803.", "sub_header": "", "step_status": "completed", "current_intent": "New constraint request is now queued"}], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

: keepalive

: keepalive

data: {"response_type": "text", "message": "", "response_heading": "Create constraints for the style-colors 101520197 300, 102813APR 600 at the stores KS1802 and KS1803 with min=5, max =100, wos =4 valid for coming 20 days ?", "status": "step", "widget_data": [{"header": "Create constraints for the style-colors 101520197 300, 102813APR 600 at the stores KS1802 and KS1803 with min=5, max =100, wos =4 valid for coming 20 days ?", "sub_header": "", "step_status": "completed", "current_intent": "Identified 1 actionable sub-task to get this done"}], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

: keepalive

: keepalive

: keepalive

data: {"response_type": "text", "message": "", "response_heading": "Create constraints for the style-colors 101520197 300, 102813APR 600 at the stores KS1802 and KS1803 with min=5, max =100, wos =4 valid for coming 20 days ?", "status": "step", "widget_data": [{"header": "The rewrite split the style-color and store inputs into a specific 20-day constraint set for KS1802 and KS1803, locking min 5, max 100, and wos 4.", "sub_header": "", "step_status": "completed", "current_intent": "The request was reshaped into a new working pass"}], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

: keepalive

data: {"response_type": "text", "message": "\n", "response_heading": null, "status": "streaming", "widget_data": [], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

data: {"response_type": "text", "message": "\n", "response_heading": null, "status": "streaming", "widget_data": [], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

data: {"response_type": "text", "message": "Do you want me to proceed with creation of the Constraints Rule?", "response_heading": null, "status": "streaming", "widget_data": [], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

data: {"response_type": "text", "message": "", "response_heading": "Create constraints for the style-colors 101520197 300, 102813APR 600 at the stores KS1802 and KS1803 with min=5, max =100, wos =4 valid for coming 20 days ?", "status": "step", "widget_data": [{"header": "The chosen path matches article-based hierarchy limits, and the store-style-color grain is already locked to KS1802 and KS1803 with min 5, max 100, and WOS 4.", "sub_header": "", "step_status": "completed", "current_intent": "Constraint setup fits article-level inventory rules"}], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

: keepalive

data: {"response_type": "text", "message": "", "response_heading": "Create constraints for the style-colors 101520197 300, 102813APR 600 at the stores KS1802 and KS1803 with min=5, max =100, wos =4 valid for coming 20 days ?", "status": "step", "widget_data": [{"header": "Need the missing article-based hierarchy permission and final field confirmation before the 20-day KS1802 and KS1803 constraints can be created.", "sub_header": "", "step_status": "completed", "current_intent": "Two approvals still block the constraint write"}], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

data: {"response_type": "text", "message": "", "response_heading": null, "status": "step", "widget_data": [{"header": "Awaiting User response", "sub_header": "Waiting for User response", "step_status": "not-completed", "current_intent": "Executing Step 1/1"}], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false}

data: {"response_type": "text", "message": "[DONE]", "response_heading": null, "status": "step_form", "widget_data": [{"type": "radio", "data": {"label": "Consent", "param_name": "consent", "isDisabled": false, "orientation": "row", "options": [{"label": "Yes", "value": "Yes"}, {"label": "No", "value": "No"}]}, "current_intent": "Executing Step 1/1"}], "session_id": "1_cbb54d61-1006-4d5d-8142-735cf15922bb", "chat_id": "1_f08f01fd-b004-48b5-af33-81cfc7dabea6", "is_error": false, "show_saved_filters": false}

`
export default chatbotFilterConfig;
