import React from "react";
import "./AISummaryCard.css";
import AI from "assets/AI.png";
import VolumeUpIcon from "@mui/icons-material/VolumeUp";

/**
 * Reusable AI summary card
 * - content: { headerBadge, title, items: [{category, summary, recommendations?, confidence?}, ...] }
 * - onClose: optional close handler (x button hidden if not provided)
 */
export default function AISummaryCard({ content, onClose }) {
  const data = content || {};
  return (
    <div className="ais-card">
      {onClose && (
        <button
          className="ais-closeAbs"
          onClick={onClose}
          aria-label="Close AI summary"
        >
          ×
        </button>
      )}
      <br />

      {/* Header */}
      <div className="ais-header">
        <div className="ais-headerRow">
          <div className="ais-lineLeft"></div>

          <div className="ais-pill">
            <img src={AI} alt="AI Icon" className="ais-aiIcon" />
            <span className="ais-pillText">Generated by Iris</span>
          </div>

          <div className="ais-lineRight"></div>
        </div>
      </div>

      {/* Body */}
      <div className="ais-body">
        <ul className="ais-list">
          {(data.items || []).map((it, idx) => (
            <li key={idx} className="ais-item">
              {it.category && (
                <div className="ais-categorySection">
                  <div className="ais-categoryLine"></div>
                  <div className="ais-categoryPill">
                    <span className="ais-label ais-bold">
                      Insight Category:
                    </span>
                    <span className="ais-value ais-highlight">
                      {it.category}
                    </span>
                  </div>
                </div>
              )}

              {it.summary && (
                <div className="ais-summaryWrapper">
                  {/* this code might be used in next deployment
                   <span className="ais-label ais-bold">Summary:</span> */}
                  <div className="ais-value">{it.summary}</div>
                  <button className="ais-voiceBtn">
                    <VolumeUpIcon className="ais-voiceIcon" />
                  </button>
                </div>
              )}

              {Array.isArray(it.recommendations) &&
                it.recommendations.length > 0 && (
                  <div className="ais-recoContainer">
                    <div className="ais-recoTitle">Recommended Actions:</div>
                    <ul className="ais-recoList">
                      {it.recommendations.map((rec, i) => (
                        <li key={i}>{rec}</li>
                      ))}
                    </ul>
                  </div>
                )}

              {/* this could be required in next deployment so keeping this snippet of code
              {it.confidence && (
                <div className="ais-line">
                  <span className="ais-label ais-bold">Confidence:</span>
                  <span className="ais-value ais-confidence">
                    {it.confidence}
                  </span>
                </div>
              )} */}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

