import { useCallback, useState } from "react";
import { Panel } from "impact-ui-v3";
import AI from "assets/AI.png";
import Loader from "core/Utils/Loader/loader";
import KpiSummarySection from "./KpiSummarySection";
import OverviewSection from "./OverviewSection";
import InsightsSmartActionsSection from "./InsightsSmartActionsSection";
import "./AISummaryCard.css";

const AlanSummaryDemoPanel = ({ open, onClose, filters }) => {
  const [sectionLoading, setSectionLoading] = useState({
    kpi: true,
    overview: true,
    insights: true,
  });

  const handleKpiLoadingChange = useCallback((loading) => {
    setSectionLoading((prev) => (prev.kpi === loading ? prev : { ...prev, kpi: loading }));
  }, []);
  const handleOverviewLoadingChange = useCallback((loading) => {
    setSectionLoading((prev) => (prev.overview === loading ? prev : { ...prev, overview: loading }));
  }, []);
  const handleInsightsLoadingChange = useCallback((loading) => {
    setSectionLoading((prev) => (prev.insights === loading ? prev : { ...prev, insights: loading }));
  }, []);

  const isLoading = sectionLoading.kpi || sectionLoading.overview || sectionLoading.insights;

  return (
    <Panel
      title="Auto Allocation Summary"
      size="large"
      anchor="right"
      open={open}
      onClose={onClose}
      className="alan-summary-panel"
    >
      <div className="ais-card">
        <div className="ais-header">
          <div className="ais-headerRow">
            <div className="ais-lineLeft"></div>

            <div className="ais-pill">
              <img src={AI} alt="AI Icon" className="ais-aiIcon" />
              <span className="ais-pillText">Generated by Iris</span>
            </div>

            <div className="ais-lineRight"></div>
          </div>
        </div>

        {isLoading && (
          <div className="ai-insights-loader-wrapper">
            <Loader
              loader={true}
              size="medium"
              text="Fetching auto allocation insights..."
              minHeight="200px"
              showSkeleton={true}
            />
          </div>
        )}

        <div
          className="ais-body"
          style={{
            display: isLoading ? "none" : "flex",
            flexDirection: "column",
            gap: 16,
          }}
        >
          <KpiSummarySection filters={filters} onLoadingChange={handleKpiLoadingChange} />
          <OverviewSection filters={filters} onLoadingChange={handleOverviewLoadingChange} />
          <InsightsSmartActionsSection filters={filters} onLoadingChange={handleInsightsLoadingChange} />
        </div>
      </div>
    </Panel>
  );
};

export default AlanSummaryDemoPanel;
