import { INVENTORY_SUBMODULES_NAMES } from "modules/inventorysmart/constants-inventorysmart/stringConstants";

const {
  INVENTORY_DASHBOARD_FORECAST_ALERTS,
  INVENTORY_DASHBOARD_FORECAST_KPI,
  INVENTORY_DASHBOARD_STORE_INVENTORY_KPI,
  INVENTORY_DASHBOARD_STORE_INVENTORY_ALERTS,
  INVENTORY_DASHBOARD_VIEW_PLANS,
  INVENTORY_DASHBOARD_ARTICLE_DETAILS,
  INVENTORY_DASHBOARD_ORDER_INVENTORY_KPI,
  INVENTORY_DASHBOARD_ORDER_INVENTORY_ALERTS,
} = INVENTORY_SUBMODULES_NAMES;

export const tabModulePermissionMap = {
  forecast: [
    INVENTORY_DASHBOARD_FORECAST_ALERTS,
    INVENTORY_DASHBOARD_FORECAST_KPI,
  ],
  store_inventory: [
    INVENTORY_DASHBOARD_STORE_INVENTORY_KPI,
    INVENTORY_DASHBOARD_STORE_INVENTORY_ALERTS,
    INVENTORY_DASHBOARD_VIEW_PLANS,
    INVENTORY_DASHBOARD_ARTICLE_DETAILS,
  ],
  oms: [
    INVENTORY_DASHBOARD_ORDER_INVENTORY_KPI,
    INVENTORY_DASHBOARD_ORDER_INVENTORY_ALERTS,
  ],
};
