--liquibase formatted sql
--changeset aman.lakkoju:paf_schema_changes stripComments:false splitStatements:false context:Release_1_0 labels:paf_schema_changes
--comment: paf_schema_changes

CREATE TABLE IF NOT EXISTS "global".product_attributes_filter (
	l0_name varchar(50) NOT NULL,
	l1_name varchar(50) NULL,
	l2_name varchar(50) NULL,
	l3_name varchar(50) NULL,
	style_id varchar(50) NULL,
	style_desc varchar(50) NULL,
	clearance bool NULL,
	color_id varchar NULL,
	product_code varchar NOT NULL,
	product_description varchar(256) NULL,
	price float4 NULL,
	"cost" float4 NULL,
	active bool NULL,
	item_status varchar(50) NULL,
	"size" varchar(50) NULL,
	product_type varchar(50) NULL,
	launch_date date NULL,
	rcl_hash jsonb DEFAULT '{}'::jsonb NOT NULL,
	psa_codes _varchar DEFAULT '{}'::character varying[] NOT NULL,
	"ordering" varchar(50) NULL,
	replenishment_status varchar(50) NULL,
	product_image_link varchar(50) NULL,
	is_deleted bool NULL,
	clearance_start_date date NULL,
	primary_vendor_id varchar(50) NULL,
	primary_vendor_name varchar NULL,
	vendor varchar(50) NULL,
	vendor_case_pack int4 NULL,
	drop_ship_flag bool NULL,
	product_channel varchar(50) NULL,
	product_attribute_1 varchar(50) NULL,
	product_attribute_2 varchar(50) NULL,
	product_attribute_3 varchar(50) NULL,
	product_attribute_4 varchar(50) NULL,
	product_attribute_5 varchar(50) NULL,
	created_at date NULL,
	updated_at date NULL,
	product_name varchar(128) NULL,
	replacement_product_codes _varchar DEFAULT '{}'::character varying[] NULL,
	reference_product_codes _varchar DEFAULT '{}'::character varying[] NULL,
	ia_sku_type varchar NULL,
	receipt_date date NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	color varchar NULL,
	original_price float8 NULL,
	product_bucket_code int8 NULL,
	article varchar NULL,
	CONSTRAINT product_attributes_filter_pk PRIMARY KEY (product_code, l0_name),
	CONSTRAINT product_attributes_filter_fk FOREIGN KEY (product_code) REFERENCES "global".product_master(product_code) ON DELETE CASCADE
)
PARTITION BY LIST (l0_name);
CREATE INDEX if not EXISTS product_attributes_filter_l0_name_idx ON  global.product_attributes_filter USING btree (l0_name);
CREATE INDEX if not EXISTS product_attributes_filter_product_code_idx ON  global.product_attributes_filter USING btree (product_code);