const response1 = {
  data: {
    "total": 1,
    "page": null,
    "count": null,
    "status": true,
    "data": [
      // A to B finalized
      {
        key: '111530375NFW-A-B-true',
        "article": "111530375NFW",
        "dc_transfer_code": "0a16913e-95e7-432f-8dc8-ab5ff1bccfaa",
        "source_dc": "A",
        "destination_dc": "B",
        is_visible: true,
        "data": [
          {
            key: '111530375NFW-LARGE-A-B',
            "size": "LARGE",
            "source_dc": "A",
            "product_code": "26685856",
            "destination_dc": "B",
            "source_dc_code": 99,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 1734,
            "total_excess_units": 1,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 1784,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 77,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 27,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: true,
          },
          {
            key: '111530375NFW-MED-A-B',
            "size": "MED",
            "source_dc": "A",
            "product_code": "26685873",
            "destination_dc": "B",
            "source_dc_code": 99,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 2068,
            "total_excess_units": 100,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 2118,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 102,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 52,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: true,
          }
        ]
      },
      {
        // B to A finalised
        key: '111530375NFW-B-A-true',
        "article": "111530375NFW",
        "dc_transfer_code": "0a16913e-95e7-432f-8dc8-ab5ff1bccfaa",
        "source_dc": "B",
        "destination_dc": "A",
        is_visible: true,
        "data": [
          {
            key: '111530375NFW-LARGE-B-A',
            "size": "LARGE",
            "source_dc": "B",
            "product_code": "26685856",
            "destination_dc": "A",
            "source_dc_code": 99,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 1734,
            "total_excess_units": 100,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 1784,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 77,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 27,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: true,
          },
          {
            key: '111530375NFW-MED-B-A',
            "size": "MED",
            "source_dc": "B",
            "product_code": "26685873",
            "destination_dc": "A",
            "source_dc_code": 99,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 2068,
            "total_excess_units": 100,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 2118,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 102,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 52,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: true,
          },
          {
            key: '111530375NFW-SMALL-B-A',
            "size": "SMALL",
            "source_dc": "B",
            "product_code": "26681390",
            "destination_dc": "S073",
            "source_dc_code": 99,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 1634,
            "total_excess_units": 100,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 4,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 1684,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 5,
            "destination_dc_oh_after": 75,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 2,
            "destination_dc_oh_initial": 25,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: true,
          }
        ]
      },
      {
        // Both A to B and B to A unfinalized
        key: '111530375NFW-false',
        "article": "111530375NFW",
        "dc_transfer_code": "0a16913e-95e7-432f-8dc8-ab5ff1bccfaa",
        "source_dc": null,
        "destination_dc": null,
        is_visible: false,
        "data": [
          {
            key: '111530375NFW-XS-A-B',
            sourceoptions: [
              { label: "A", value: "A", id: "A" },
              { label: "B", value: "B", id: "B" },
            ],
            destinationoptions: [
              { label: "A", value: "A", id: "A" },
              { label: "B", value: "B", id: "B" },
            ],
            "size": "XS",
            "source_dc": "A",
            "product_code": "26685813",
            "destination_dc": "B",
            "source_dc_code": 99,
            "transfer_units": 111,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 1681,
            "total_excess_units": 1,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 1731,
            "min_transfer_quantity": 200, // This for transfer unit min value 
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 70,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 20,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: false,
          },
          {
            key: '111530375NFW-XS-B-A',
            sourceoptions: [
              { label: "A", value: "A", id: "A" },
              { label: "B", value: "B", id: "B" },
            ],
            destinationoptions: [
              { label: "A", value: "A", id: "A" },
              { label: "B", value: "B", id: "B" },
            ],
            "size": "XS",
            "source_dc": "B",
            "product_code": "26685813",
            "destination_dc": "A",
            "source_dc_code": 99,
            "transfer_units": 200,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 1681,
            "total_excess_units": 2,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 1731,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 70,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 20,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: false,
          },
          {
            key: '111530375NFW-XXS-A-B',
            sourceoptions: [
              { label: "A", value: "A", id: "1" },
              { label: "B", value: "B", id: "2" },
            ],
            destinationoptions: [
              { label: "A", value: "A", id: "1" },
              { label: "B", value: "B", id: "2" },
            ],
            "size": "XXS",
            "source_dc": "A",
            "product_code": "26685813",
            "destination_dc": "B",
            "source_dc_code": 99,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 1681,
            "total_excess_units": 3,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 1731,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 70,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 20,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: false,
          },
          {
            key: '111530375NFW-XXS-B-A',
            sourceoptions: [
              { label: "A", value: "A", id: "1" },
              { label: "B", value: "B", id: "2" },
            ],
            destinationoptions: [
              { label: "A", value: "A", id: "1" },
              { label: "B", value: "B", id: "2" },
            ],
            "size": "XXS",
            "source_dc": "B",
            "product_code": "26685813",
            "destination_dc": "A",
            "source_dc_code": 99,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 50,
            "source_dc_oh_after": 1681,
            "total_excess_units": 4,
            "destination_dc_code": 108,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 1,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 1731,
            "min_transfer_quantity": 200,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 70,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 20,
            "destination_dc_wos_initial": 1,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 100,
            "destination_dc_demand_projection": 50,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50,
            is_visible: false,
          }
        ]
      }
    ],
    "message": "Successful",
    "previous": null,
    "next": null,
    "offset": null,
    "sub_offset": null,
    "download_rows": null,
    "page_size": null
  }
}

const response = {
  data: {
    "total": null,
    "page": null,
    "count": null,
    "status": true,
    "data": [
      {
        "article": "111530375NFW",
        "dc_transfer_code": "53528412-7823-407b-8601-5c0e87f4fcc0",
        "source_dc": "S015",
        "destination_dc": "S073",
        "destination_dc_code": 38,
        "source_dc_code": 17,
        "total_excess_units": "150",
        "total_deficit_units": "150",
        "ia_recommended_transfer": "150",
        "transfer_units": "150",
        "is_visible": true,
        "key": "111530375NFW-S015-S073-true",
        "data": [
          {
            "key": "111530375NFW-SMALL-S015-S073",
            "size": "SMALL",
            "source_dc": "S015",
            "is_visible": true,
            "product_code": "26599377",
            "sourceoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "destination_dc": "S073",
            "source_dc_code": 17,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 0,
            "destinationoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "source_dc_oh_after": -29,
            "total_excess_units": 50,
            "destination_dc_code": 38,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 0,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 21,
            "min_transfer_quantity": 10,
            "source_dc_wos_initial": 1,
            "destination_dc_oh_after": 54,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 4,
            "destination_dc_wos_initial": 0,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 50,
            "destination_dc_demand_projection": 100,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50
          },
          {
            "key": "111530375NFW-XL-S015-S073",
            "size": "XL",
            "source_dc": "S015",
            "is_visible": true,
            "product_code": "26599536",
            "sourceoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "destination_dc": "S073",
            "source_dc_code": 17,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 0,
            "destinationoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "source_dc_oh_after": -50,
            "total_excess_units": 50,
            "destination_dc_code": 38,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 0,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 0,
            "min_transfer_quantity": 10,
            "source_dc_wos_initial": 0,
            "destination_dc_oh_after": 50,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 0,
            "destination_dc_wos_initial": 0,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 50,
            "destination_dc_demand_projection": 100,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50
          },
          {
            "key": "111530375NFW-XXL-S015-S073",
            "size": "XXL",
            "source_dc": "S015",
            "is_visible": true,
            "product_code": "26599622",
            "sourceoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "destination_dc": "S073",
            "source_dc_code": 17,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 0,
            "destinationoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "source_dc_oh_after": -50,
            "total_excess_units": 50,
            "destination_dc_code": 38,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 0,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 0,
            "min_transfer_quantity": 10,
            "source_dc_wos_initial": 0,
            "destination_dc_oh_after": 50,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 0,
            "destination_dc_wos_initial": 0,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 50,
            "destination_dc_demand_projection": 100,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50
          }
        ]
      },
      {
        "article": "111530375NFW",
        "dc_transfer_code": "53528412-7823-407b-8601-5c0e87f4fcc0",
        "source_dc": null,
        "destination_dc": null,
        "destination_dc_code": null,
        "source_dc_code": null,
        "total_excess_units": "100",
        "total_deficit_units": "100",
        "ia_recommended_transfer": "100",
        "transfer_units": "100",
        "is_visible": false,
        "key": "111530375NFW-false",
        "data": [
          {
            "key": "111530375NFW-LARGE-S015-S073",
            "size": "LARGE",
            "source_dc": "S015",
            "is_visible": false,
            "product_code": "26599454",
            "sourceoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "destination_dc": "S073",
            "source_dc_code": 17,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 0,
            "destinationoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "source_dc_oh_after": -50,
            "total_excess_units": 50,
            "destination_dc_code": 38,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 0,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 0,
            "min_transfer_quantity": 100,
            "source_dc_wos_initial": 0,
            "destination_dc_oh_after": 50,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 0,
            "destination_dc_wos_initial": 0,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 50,
            "destination_dc_demand_projection": 100,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50
          },
          {
            "key": "111530375NFW-XS-S015-S073",
            "size": "XS",
            "source_dc": "S015",
            "is_visible": false,
            "product_code": "26599509",
            "sourceoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "destination_dc": "S073",
            "source_dc_code": 17,
            "transfer_units": 50,
            "pending_deficit": 0,
            "ia_reco_transfer": 50,
            "remaining_excess": 0,
            "destinationoptions": [
              {
                "id": 17,
                "label": "S015",
                "value": "S015"
              },
              {
                "id": 38,
                "label": "S073",
                "value": "S073"
              }
            ],
            "source_dc_oh_after": -50,
            "total_excess_units": 50,
            "destination_dc_code": 38,
            "source_dc_min_stock": 1,
            "source_dc_wos_after": 0,
            "total_deficit_units": 50,
            "source_dc_oh_initial": 0,
            "min_transfer_quantity": 100,
            "source_dc_wos_initial": 0,
            "destination_dc_oh_after": 50,
            "destination_dc_min_stock": 1,
            "destination_dc_wos_after": 1,
            "destination_dc_oh_initial": 0,
            "destination_dc_wos_initial": 0,
            "source_dc_demand_projection": 100,
            "source_dc_safety_stock_units": 1000,
            "total_source_dc_excess_units": 50,
            "destination_dc_demand_projection": 100,
            "destination_dc_safety_stock_units": 1000,
            "total_destination_dc_deficit_units": 50
          }
        ]
      }
    ],
    "message": "Successful",
    "previous": null,
    "next": null,
    "offset": null,
    "sub_offset": null,
    "download_rows": null,
    "page_size": null
  }
}

let newRowTemplate = {
  "size": null,
  "source_dc": null,
  "product_code": null,
  "destination_dc": null,
  "source_dc_code": null,
  "transfer_units": null,
  "pending_deficit": null,
  "ia_reco_transfer": null,
  "remaining_excess": null,
  "source_dc_oh_after": null,
  "total_excess_units": null,
  "destination_dc_code": null,
  "source_dc_min_stock": null,
  "source_dc_wos_after": null,
  "total_deficit_units": null,
  "source_dc_oh_initial": null,
  "min_transfer_quantity": null,
  "source_dc_wos_initial": null,
  "destination_dc_oh_after": null,
  "destination_dc_min_stock": null,
  "destination_dc_wos_after": null,
  "destination_dc_oh_initial": null,
  "destination_dc_wos_initial": null,
  "source_dc_demand_projection": null,
  "source_dc_safety_stock_units": null,
  "total_source_dc_excess_units": null,
  "destination_dc_demand_projection": null,
  "destination_dc_safety_stock_units": null,
  "total_destination_dc_deficit_units": null,
  is_added: true,
  is_visible: false,
}

let meta = {
  "search": [],
  "range": [],
  "sort": [],
  "limit": {
    "limit": 10,
    "page": 1
  }
}

export { response, newRowTemplate, meta }