      let DC_Table_Response = {data:{
        total: null,
        page: null,
        count: 4,
        status: true,
        data: [
          {
            c_rule_code: 174,
            c_rcl_code: 8,
            rule_name: "new name",
            rcl_dimension: {
              gender: "GIRL",
              l0_name: "CAN",
              l1_name: "Brick __ia_char_13 Mortar",
            },
            _default_auto_allocation_rule_code: null,
            _default_auto_allocation_rule_name: "No Rule",
            _default_dc_store_rule_rule_code: null,
            _default_dc_store_rule_rule_name: "Default Rule",
            _default_auto_allocation_scheduler_code: null,
            _default_auto_allocation_scheduler_name: "No Rule",
            _store_group_ids: [504],
            _default_store_groups_mapped: "186/1",
            _default_product_profile_code: null,
            _default_product_profile_name: "ia-recommended",
            _store_groups_names: "existing_CAN",
            store_details: [
              {
                user: "qa@impactanalytics.co",
                end_date: "2024-07-24",
                user_code: 251,
                created_at: "2024-07-02T05:56:35.776058+00:00",
                created_by: 251,
                start_date: "2024-07-02",
                updated_at: "2024-07-24T09:10:12.309519+00:00",
                updated_by: 251,
                dc_store_rule: null,
                product_profile: "LFP PP  1",
                dc_store_rule_name: "Default Rule",
                auto_allocation_rule: null,
                default_store_groups: [501, 197],
                default_product_profile: 5000074,
                auto_allocation_rule_name: "No Rule",
                auto_allocation_schedular: null,
                store_store_groups_mapped: "789/2",
                store_groups_names: "Name1",
                auto_allocation_schedular_name: "No Rule",
              },
            ],
            is_default: false,
          },
          {
            c_rule_code: 168,
            c_rcl_code: 6,
            rule_name: "were new",
            rcl_dimension: {
              l0_name: "CAN",
              l1_name: "Brick __ia_char_13 Mortar",
              clearance_flag: 0,
            },
            _default_auto_allocation_rule_code: null,
            _default_auto_allocation_rule_name: "No Rule",
            _default_dc_store_rule_rule_code: null,
            _default_dc_store_rule_rule_name: "Default Rule",
            _default_auto_allocation_scheduler_code: null,
            _default_auto_allocation_scheduler_name: "No Rule",
            _store_group_ids: [504],
            _default_store_groups_mapped: "186/1",
            _default_product_profile_code: null,
            _default_product_profile_name: "ia-recommended",
            _store_groups_names: "existing_CAN",
            store_details: [
              {
                user: "qa@impactanalytics.co",
                end_date: "2024-06-22",
                user_code: 251,
                created_at: "2024-06-28T03:44:19.501698+00:00",
                created_by: 251,
                start_date: "2024-06-04",
                updated_at: "2024-07-24T09:10:12.307109+00:00",
                updated_by: 251,
                dc_store_rule: null,
                product_profile: "LFP PP  1",
                dc_store_rule_name: "Default Rule",
                auto_allocation_rule: null,
                default_store_groups: null,
                default_product_profile: 5000074,
                auto_allocation_rule_name: "No Rule",
                auto_allocation_schedular: null,
                store_store_groups_mapped: "0/0",
                store_groups_names: "Name2",
                auto_allocation_schedular_name: "No Rule",
              },
            ],
            is_default: false,
          },
          {
            c_rule_code: 167,
            c_rcl_code: 6,
            rule_name: "qw",
            rcl_dimension: {
              l0_name: "CAN",
              l1_name: "Brick __ia_char_13 Mortar",
              clearance_flag: 1,
            },
            _default_auto_allocation_rule_code: null,
            _default_auto_allocation_rule_name: "No Rule",
            _default_dc_store_rule_rule_code: null,
            _default_dc_store_rule_rule_name: "Default Rule",
            _default_auto_allocation_scheduler_code: null,
            _default_auto_allocation_scheduler_name: "No Rule",
            _store_group_ids: [504],
            _default_store_groups_mapped: "186/1",
            _default_product_profile_code: null,
            _default_product_profile_name: "ia-recommended",
            _store_groups_names: "existing_CAN",
            store_details: [
              {
                user: "qa@impactanalytics.co",
                end_date: "2024-07-13",
                user_code: 251,
                created_at: "2024-06-28T03:44:19.502239+00:00",
                created_by: 251,
                start_date: "2024-06-05",
                updated_at: "2024-07-23T10:28:50.175529+00:00",
                updated_by: 251,
                dc_store_rule: 74,
                product_profile: "product test",
                dc_store_rule_name: "HA_check",
                auto_allocation_rule: 61,
                default_store_groups: [
                  501,
                  505,
                  506,
                  502,
                  504,
                  14,
                  197,
                  217,
                  218,
                ],
                default_product_profile: 5000044,
                auto_allocation_rule_name: "RuleTest",
                auto_allocation_schedular: 21,
                store_store_groups_mapped: "975/9",
                store_groups_names: "Name3",
                auto_allocation_schedular_name: "RuleTest",
              },
            ],
            is_default: false,
          },
          {
            c_rule_code: 28833,
            c_rcl_code: 131091,
            rule_name: "Default Rule",
            rcl_dimension: {
              l0_name: "CAN",
              l1_name: "Brick __ia_char_13 Mortar",
            },
            _default_auto_allocation_rule_code: null,
            _default_auto_allocation_rule_name: "No Rule",
            _default_dc_store_rule_rule_code: null,
            _default_dc_store_rule_rule_name: "Default Rule",
            _default_auto_allocation_scheduler_code: null,
            _default_auto_allocation_scheduler_name: "No Rule",
            _store_group_ids: [504],
            _default_store_groups_mapped: "186/1",
            _default_product_profile_code: null,
            _default_product_profile_name: "ia-recommended",
            _store_groups_names: "existing_CAN",
            store_details: [
              {
                user: "qa@impactanalytics.co",
                end_date: "2050-12-31",
                user_code: 251,
                created_at: "2024-07-18T08:51:07.19+00:00",
                created_by: 251,
                start_date: "2024-01-01",
                updated_at: null,
                updated_by: null,
                dc_store_rule: null,
                product_profile: "ia-recommended",
                dc_store_rule_name: "Default Rule",
                auto_allocation_rule: null,
                default_store_groups: [504],
                default_product_profile: null,
                auto_allocation_rule_name: "No Rule",
                auto_allocation_schedular: null,
                store_store_groups_mapped: "186/1",
                store_groups_names: "Name4",
                auto_allocation_schedular_name: "No Rule",
              },
            ],
            is_default: true,
          },
        ],
        message: "Successful",
        previous: null,
        next: null,
        offset: null,
        sub_offset: null,
        download_rows: null,
        page_size: null,
      }};

export { DC_Table_Response };
