--liquibase formatted sql
--changeset liquibase:oms_deep_dive_base stripComments:false splitStatements:false context:Release_1_0 labels:oms_deep_dive_base
--comment: initial changeset for oms_deep_dive_base

CREATE TABLE IF NOT EXISTS inventory_smart.oms_deep_dive_base (
	product_code text NOT NULL,
	loc_code text NOT NULL,
	fiscal_year_week int8 NOT NULL,
	week text NULL,
	"month" text NULL,
	predicted_qty float8 NULL,
	rolling_std_dev float8 NULL,
	rolling_forecast float8 NULL,
	variance float8 NULL,
	safety_stock float8 NULL,
	receipt1 int8 NULL,
	receipt1_qc int8 NULL,
	total_dc_forecast float8 NULL,
	dc_inv float8 NULL,
	lost_sales float8 NULL,
	"style" text NOT NULL,
	article text NOT NULL,
	"size" text NOT NULL,
	channel text NOT NULL,
	vendor_code text NOT NULL,
	vendor_name text NULL,
	week_starting text NULL,
	week_ending text NULL,
	total_mins int8 NULL,
	additional_forecast int8 NULL,
	additional_inventory int8 NULL,
	inventory_deficit int8 NULL,
	ecom_forecast float8 NULL,
	ecom_reserve float8 NULL,
	created_by int8 NULL,
	created_at timestamptz NULL,
	updated_by int8 NULL,
	updated_at timestamptz NULL,
	eff_lead_time int4 NULL,
	approved_receipt float4 NULL,
	ly_sales float8 NULL,
	ly_oh float8 NULL,
	total_dc_forecast_final_roq float8 NULL,
	total_stores_count int4 NULL,
	CONSTRAINT uk_oms_deep_dive_base PRIMARY KEY (product_code, style, article, size, channel, vendor_code, loc_code, fiscal_year_week),
	CONSTRAINT unique_product_loc_week UNIQUE (product_code, loc_code, fiscal_year_week)
);