--liquibase formatted sql
--changeset pradeep.kumar@impactanalytics.co:alerts_product_channel stripComments:false splitStatements:false context:VS_inv_smart labels:alerts_product_channel
--comment: initial changeset for alerts_product_channel_level intl

DROP TABLE IF EXISTS inventory_smart.alerts_product_channel_level;

CREATE TABLE IF NOT EXISTS inventory_smart.alerts_product_channel_level (
	article varchar(256) NULL,
	l7_name varchar(256) NULL,
	channel varchar(50) NULL,
	color varchar(256) NULL,
	l0_name varchar(256) NULL,
	l3_name varchar(256) NULL,
	l4_name varchar(256) NULL,
	l5_name varchar(256) NULL,
	l6_name varchar(256) NULL,
	flex_style varchar(256) NULL,
	generic varchar(256) NULL,
	sizes_mat varchar(256) NULL,
	form varchar(256) NULL,
	user_defined_1 varchar(50) NULL,
	user_defined_2 varchar(50) NULL,
	user_defined_3 varchar(50) NULL,
	user_defined_4 varchar(50) NULL,
	user_defined_5 varchar(50) NULL,
	product_lifecycle varchar(50) NULL,
	subbrand_code_desc text NULL,
	masterstyle_descr text NULL,
	total_inv int4 NULL,
	dc_oh int4 NULL,
	forecast_21_28_weeks float4 NULL,
	ly_21_28_weeks int4 NULL,
	lr_ly_deviation float4 NULL,
	ly_store_count float4 NULL,
	forecasted_store_count float4 NULL,
	lr_store_count_deviation float4 NULL,
	ly_week_promo float4 NULL,
	forecasted_promo float4 NULL,
	lr_promo_deviation float4 NULL,
	past_4_weeks_actual float4 NULL,
	next_4_weeks_mfp_forecast float4 NULL,
	next_4_weeks_forecast float4 NULL,
	ly_deviation float4 NULL,
	store_count_deviation float4 NULL,
	promo_deviation float4 NULL,
	mfp_deviation float4 NULL,
	ly_past_4_weeks_actual float4 NULL,
	ly_next_4_weeks_actual float4 NULL,
	recent_deviation float4 NULL,
	past_4_weeks_store_count float4 NULL,
	next_4_weeks_store_count float4 NULL,
	past_4_weeks_actual_promo float4 NULL,
	next_4_weeks_planned_promo float4 NULL,
	past_4_weeks_planned_promo float4 NULL,
	past_4_weeks_forecast float4 NULL,
	absolute_error float4 NULL,
	accuracy float4 NULL,
	allocate_and_replen_choices_flag int4 NULL,
	recently_launched_flag int4 NULL,
	recent_deviation_flag int4 NULL,
	ia_vs_mfp_flag int4 NULL,
	long_range_flag int4 NULL,
	allocate_replen_tag varchar(50) NULL,
	ar_is_resolved int4 NULL,
	rl_is_resolved int4 NULL,
	rd_is_resolved int4 NULL,
	mfpd_is_resolved int4 NULL,
	lr_is_resolved int4 NULL,
	floorset_name varchar NULL,
	floorset_start_date date NULL,
	floorset_end_date date NULL,
	CONSTRAINT alerts_product_channel_level_un UNIQUE (article, channel)
);