--liquibase formatted sql
--changeset pradeep.kumar@impactanalytics.co:alerts_product_level stripComments:false splitStatements:false context:VS_inv_smart labels:alerts_product_level
--comment: initial changeset for alerts_product_level intl

CREATE TABLE IF NOT EXISTS inventory_smart.alerts_product_level (
	article varchar NOT NULL,
	l0_name varchar NOT NULL,
	generic varchar NOT NULL,
	l3_name varchar NOT NULL,
	l4_name varchar NOT NULL,
	l5_name varchar NOT NULL,
	form varchar NULL,
	l7_name varchar NULL,
	flex_style varchar NULL,
	l6_name varchar NULL,
	color varchar NULL,
	launch_floorset varchar NULL,
	sizes_mat varchar NOT NULL,
	new_choice_flag int4 NULL,
	upcoming_po int4 NULL,
	oh float4 NULL,
	it float4 NULL,
	oo float4 NULL,
	oh_dc float4 NULL,
	forecast_over_target_wos float4 NULL,
	wip int4 NULL,
	user_defined_1 varchar NULL,
	user_defined_2 varchar NULL,
	user_defined_3 varchar NULL,
	user_defined_4 varchar NULL,
	user_defined_5 varchar NULL,
	floorset_end_date date NULL,
	floorset_start_date date NULL,
	launch_date date NULL,
	next_po_upcoming_date date NULL,
	collection varchar NULL,
	masterstyle_descr varchar NULL,
	subbrand_code_desc varchar NULL,
	product_lifecycle varchar NULL,
	nc_is_resolved int4 DEFAULT 0 NULL,
	store_count int4 NULL,
	product_group _varchar NULL,
	"choice	launch_date	launch_floorset	floorset_start_date	floorset" varchar(512) NULL,
	current_assortment_group varchar NULL,
	current_floorset varchar NULL,
	CONSTRAINT alerts_product_level_pk PRIMARY KEY (article)
);