--liquibase formatted sql
--changeset kanishka.parashar@impactanalytics.co:article_inventory_dashboard_v_1 stripComments:false splitStatements:false context:VS_inv_smart labels:alerts_product_channel_v1
--comment: initial changeset for article_inventory_dashboard_v_1
-- inventory_smart.article_inventory_dashboard definition

CREATE TABLE IF NOT EXISTS inventory_smart.article_inventory_dashboard (
	article varchar NULL,
	l7_name varchar NULL,
	color varchar NULL,
	l0_name varchar NULL,
	l3_name varchar NULL,
	l4_name varchar NULL,
	l5_name varchar NULL,
	l6_name varchar NULL,
	collection varchar NULL,
	masterstyle_descr varchar NULL,
	subbrand_code_desc varchar NULL,
	product_lifecycle varchar NULL,
	current_floorset varchar NULL,
	current_assortment_group varchar NULL,
	flex_style varchar NULL,
	generic varchar NULL,
	sizes_mat varchar NULL,
	form varchar NULL,
	user_defined_1 varchar NULL,
	user_defined_2 varchar NULL,
	user_defined_3 varchar NULL,
	user_defined_4 varchar NULL,
	user_defined_5 varchar NULL,
	store_code varchar NULL,
	store_name varchar NULL,
	channel varchar NULL,
	planning_division varchar NULL,
	partner_group_name varchar NULL,
	regional_master_name varchar NULL,
	store_format_description varchar NULL,
	vsba_regional_dc_descr varchar NULL,
	region_name varchar NULL,
	s1_name varchar NULL,
	s3_name varchar NULL,
	s4_name varchar NULL,
	store_tier varchar NULL,
	choice_status varchar(50) NULL,
	oh int4 NULL,
	it int4 NULL,
	oo int4 NULL,
	wip int4 NULL,
	initial_oh int4 NULL,
	rfid_delta int4 NULL,
	epc_units int4 NULL,
	tot_inv float4 NULL,
	r_site_oh int4 NULL,
	r_site_oo int4 NULL,
	r_site_it int4 NULL,
	r_site_wip int4 NULL,
	r_site_total_inv int4 NULL,
	l_site_oh int4 NULL,
	l_site_oo int4 NULL,
	l_site_it int4 NULL,
	l_site_wip int4 NULL,
	l_site_total_inv int4 NULL,
	last_week_sales float4 NULL,
	l4w_avg_sales float4 NULL,
	l12w_avg_sales float4 NULL,
	week_to_date_sales float4 NULL,
	last_week_revenue float4 NULL,
	store_forward_wos float4 NULL,
	r_site_forward_wos float4 NULL,
	size_integrity_oh float4 NULL,
	size_integrity_oh_oo_it float4 NULL,
	aur float4 NULL,
	excess int4 NULL,
	normal int4 NULL,
	shortfall int4 NULL,
	stockout float4 NULL,
	oh_dc int4 NULL,
	oo_it_dc float4 NULL,
	current_week_forecast float4 NULL,
	next_4_week_forecast float4 NULL,
	next_8_week_forecast float4 NULL,
	next_20_week_forecast float4 NULL,
	l8w_avg_sales float4 NULL
);

--changeset kanishka.parashar@impactanalytics.co:pp_master_v_2 stripComments:false splitStatements:false context:VS_inv_smart labels:alerts_product_channel_v1
--comment: initial changeset for product_profile_master_v_2
alter table inventory_smart.article_inventory_dashboard 
DROP COLUMN l8w_avg_sales;