import { makeStyles } from "@mui/styles";

export const SKU_CATEGORISATION_CHART_SIZE = 72;

export const useSkuCategorisationStyles = makeStyles(() => ({
  headerTitle: {
    fontSize: 14,
    fontWeight: 800,
    lineHeight: "20px",
    color: "#0D152C",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    whiteSpace: "nowrap",
  },
  headerSubtitle: {
    fontSize: 13,
    fontWeight: 500,
    lineHeight: "20px",
    color: "#60697D",
    "&::before": {
      content: '"•"',
      marginRight: 6,
      color: "#60697D",
    },
  },
  cardsRow: {
    display: "flex",
    alignItems: "stretch",
    gap: 12,
    width: "100%",
    marginTop: 12,
    marginBottom: 16,
    flexWrap: "nowrap",
  },
  card: {
    position: "relative",
    flex: "1 1 0",
    minWidth: 0,
    height: 126,
    minHeight: 126,
    maxHeight: 126,
    background: "#FFFFFF",
    border: "1px solid #ECEEFD",
    borderRadius: 12,
    padding: "12px 14px",
    boxSizing: "border-box",
    cursor: "pointer",
    transition: "border-color 0.15s ease, box-shadow 0.15s ease",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    overflow: "visible",
  },
  cardSelected: {
    border: "1.5px solid #687AF1",
    boxShadow: "0 0 0 1px rgba(104, 122, 241, 0.12)",
  },
  cardDisabled: {
    opacity: 0.55,
    cursor: "not-allowed",
  },
  cardEmptyCount: {
    opacity: 0.55,
    cursor: "pointer",
  },
  cardPointer: {
    position: "absolute",
    bottom: -7,
    left: "50%",
    transform: "translateX(-50%)",
    width: 0,
    height: 0,
    borderLeft: "7px solid transparent",
    borderRight: "7px solid transparent",
    borderTop: "7px solid #687AF1",
  },
  cardHeader: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    flexShrink: 1,
    overflow: "visible",
  },
  cardTitleGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
    height: 16,
    overflow: "visible",
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    margin: 0,
    padding: 0,
  },
  simpleCardContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    flex: 1,
    minWidth: 0,
  },
  cardValueRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    width: "100%",
    minWidth: 0,
  },
  cardCount: {
    fontSize: 20,
    fontWeight: 800,
    lineHeight: "30px",
    color: "#0D152C",
    flexShrink: 0,
  },
  cardSubtitle: {
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flexShrink: 1,
    minWidth: 0,
  },
  infoIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 16,
    height: 16,
    minWidth: 16,
    minHeight: 16,
    flexShrink: 0,
    overflow: "visible",
    cursor: "pointer",
    "& svg": {
      width: 16,
      height: 16,
      minWidth: 16,
      minHeight: 16,
      display: "block",
      overflow: "visible",
    },
  },
  comingSoonBadge: {
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
    marginLeft: 4,
    padding: "2px 8px",
    borderRadius: 999,
    border: "1px solid #8C6F06",
    background: "transparent",
    color: "#8C6F06",
    fontSize: 11,
    fontWeight: 500,
    lineHeight: "16px",
    whiteSpace: "nowrap",
  },
  chartCardContent: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    gap: 6,
    overflow: "hidden",
  },
  chartCardTopRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    width: "100%",
    minHeight: 16,
    flexShrink: 0,
  },
  chartCardBody: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    minWidth: 0,
    height: SKU_CATEGORISATION_CHART_SIZE,
    minHeight: SKU_CATEGORISATION_CHART_SIZE,
    maxHeight: SKU_CATEGORISATION_CHART_SIZE,
    flexShrink: 0,
  },
  chartWrapper: {
    width: SKU_CATEGORISATION_CHART_SIZE,
    height: SKU_CATEGORISATION_CHART_SIZE,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  chartLegend: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
    height: "100%",
  },
  legendRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    width: "100%",
    minWidth: 0,
    minHeight: 16,
  },
  legendBar: {
    width: 3,
    height: 12,
    borderRadius: 1,
    flexShrink: 0,
  },
  legendValue: {
    fontSize: 12,
    fontWeight: 800,
    lineHeight: "16px",
    color: "#0D152C",
    flexShrink: 0,
    textAlign: "right",
  },
  legendLabel: {
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  chartCardCount: {
    fontSize: 16,
    fontWeight: 800,
    lineHeight: "24px",
    color: "#0D152C",
    flexShrink: 0,
    whiteSpace: "nowrap",
    marginTop: -2,
  },
}));
