--liquibase formatted sql
--changeset jaya.khandelwal@impactanalytics.co:lf_wholesale_report stripComments:false splitStatements:false context:Release_1_0 labels:MTP-38204
--comment: initial changeset for lf_wholesale_report
CREATE UNLOGGED TABLE plan_smart.lf_wholesale_report (
    "Timestamp" timestamp NULL,
    "BU" text NULL,
    "Group" varchar NULL,
    "Customer" varchar(50) NULL,
    "Division" varchar NULL,
    "Department" varchar NULL,
    "Class" varchar NULL,
    "Line" varchar NULL,
    fiscal_month_in_year text NULL,
    fiscal_year int2 NULL,
    "Comp Sls U" float8 NULL,
    "NComp Sls U" float8 NULL,
    "Ttl Sls U" float8 NULL,
    "Comp Sls $" float8 NULL,
    "NComp Sls $" float8 NULL,
    "Ttl Sls $" float8 NULL,
    "Comp AUR" float8 NULL,
    "NComp AUR" float8 NULL,
    "Ttl AUR" float8 NULL,
    "Comp AUP" float8 NULL,
    "Ttl AUP" float8 NULL,
    "Comp COGS" float8 NULL,
    "NComp COGS" float8 NULL,
    "Ttl COGS" float8 NULL,
    "Comp Adj Cst" float8 NULL,
    "NComp Adj Cst" float8 NULL,
    "Ttl Adj Cst" float8 NULL,
    "Comp COGS." float8 NULL,
    "Ttl COGS." float8 NULL,
    "Comp AUC" float8 NULL,
    "NComp AUC" float8 NULL,
    "Ttl AUC" float8 NULL,
    "Comp Adj AUC" float8 NULL,
    "NComp Adj AUC" float8 NULL,
    "Ttl Adj AUC" float8 NULL,
    "Comp AULC" float8 NULL,
    "Ttl AULC" float8 NULL,
    "Comp Sls U Build" float8 NULL,
    "NComp Sls U Build" float8 NULL,
    "Ttl Sls U Build" float8 NULL,
    "Comp Sls $ Build" float8 NULL,
    "NComp Sls $ Build" float8 NULL,
    "Ttl Sls $ Build" float8 NULL,
    "Comp GM $" float8 NULL,
    "NComp GM $" float8 NULL,
    "Ttl GM $" float8 NULL,
    "Comp GM %" float8 NULL,
    "NComp GM %" float8 NULL,
    "Ttl GM %" float8 NULL,
    "Comp Adj GM $" float8 NULL,
    "NComp Adj GM $" float8 NULL,
    "Ttl Adj GM $" float8 NULL,
    "Comp Adj GM %" float8 NULL,
    "NComp Adj GM %" float8 NULL,
    "Ttl Adj GM %" float8 NULL,
    "Comp GMROI" float8 NULL,
    "NComp GMROI" float8 NULL,
    "Ttl GMROI" float8 NULL,
    "Comp Svc Lvl" float8 NULL,
    "Ttl Svc Lvl" float8 NULL,
    "Comp Qty Shp" float8 NULL,
    "Ttl Qty Shp" float8 NULL,
    "Comp Qty Ord" float8 NULL,
    "Ttl Qty Ord" float8 NULL,
    "Comp BOH U" float8 NULL,
    "NComp BOH U" float8 NULL,
    "Ttl BOH U" float8 NULL,
    "Comp BOH Cst" float8 NULL,
    "NComp BOH Cst" float8 NULL,
    "Ttl BOH Cst" float8 NULL,
    "Comp BOH LCst" float8 NULL,
    "Ttl BOH LCst" float8 NULL,
    "Comp BOH AUC" float8 NULL,
    "NComp BOH AUC" float8 NULL,
    "Ttl BOH AUC" float8 NULL,
    "Comp BOH AULC" float8 NULL,
    "Ttl BOH AULC" float8 NULL,
    "Comp EOH U" float8 NULL,
    "NComp EOH U" float8 NULL,
    "Ttl EOH U" float8 NULL,
    "Comp EOH Cst" float8 NULL,
    "NComp EOH Cst" float8 NULL,
    "Ttl EOH Cst" float8 NULL,
    "Comp EOH AUC" float8 NULL,
    "NComp EOH AUC" float8 NULL,
    "Ttl EOH AUC" float8 NULL,
    "Comp EOH AULC" float8 NULL,
    "Ttl EOH AULC" float8 NULL,
    "Comp Avg Inv" float8 NULL,
    "NComp Avg Inv" float8 NULL,
    "Ttl Avg Inv" float8 NULL,
    "Comp ST%" float8 NULL,
    "NComp ST%" float8 NULL,
    "Ttl ST%" float8 NULL,
    "Comp WOS" float8 NULL,
    "NComp WOS" float8 NULL,
    "Ttl WOS" float8 NULL,
    "Comp In Stock %" float8 NULL,
    "NComp In Stock %" float8 NULL,
    "Ttl In Stock %" float8 NULL,
    "Comp Rct U" float8 NULL,
    "NComp Rct U" float8 NULL,
    "Ttl Rct U" float8 NULL,
    "Comp Rct Cst" float8 NULL,
    "NComp Rct Cst" float8 NULL,
    "Ttl Rct Cst" float8 NULL,
    "Comp Rct LCst" float8 NULL,
    "Ttl Rct LCst" float8 NULL,
    "Comp Rct AUC" float8 NULL,
    "NComp Rct AUC" float8 NULL,
    "Ttl Rct AUC" float8 NULL,
    "Comp Rct AULC" float8 NULL,
    "Ttl Rct AULC" float8 NULL,
    "Comp CH Est Res U" float8 NULL,
    "Ttl CH Est Res U" float8 NULL,
    "Comp CH Est Res LCst" float8 NULL,
    "Ttl CH Est Res LCst" float8 NULL,
    "Comp CH Est Res AULC" float8 NULL,
    "Ttl CH Est Res AULC" float8 NULL,
    "Comp CH FULL U" float8 NULL,
    "Ttl CH FULL U" float8 NULL,
    "Comp CH FULL LCst" float8 NULL,
    "Ttl CH FULL LCst" float8 NULL,
    "Comp CH FULL AULC" float8 NULL,
    "Ttl CH FULL AULC" float8 NULL,
    "Comp Var Res FULL U" float8 NULL,
    "Ttl Var Res FULL U" float8 NULL,
    "Comp Var Res FULL LCst" float8 NULL,
    "Ttl Var Res FULL LCst" float8 NULL,
    "Comp Turn U" float8 NULL,
    "NComp Turn U" float8 NULL,
    "Ttl Turn U" float8 NULL,
    "Comp Turn Cst" float8 NULL,
    "NComp Turn Cst" float8 NULL,
    "Ttl Turn Cst" float8 NULL,
    "Comp OO U (Com)" float8 NULL,
    "NComp OO U (Com)" float8 NULL,
    "Ttl OO U (Com)" float8 NULL,
    "Comp OO Cst (Com)" float8 NULL,
    "NComp OO Cst (Com)" float8 NULL,
    "Ttl OO Cst (Com)" float8 NULL,
    "Comp OO LCst (Com)" float8 NULL,
    "Ttl OO LCst (Com)" float8 NULL,
    "Comp OO AUC (Com)" float8 NULL,
    "NComp OO AUC (Com)" float8 NULL,
    "Ttl OO AUC (Com)" float8 NULL,
    "Comp OO AULC (Com)" float8 NULL,
    "Ttl OO AULC (Com)" float8 NULL,
    "Comp OO U (NCom)" float8 NULL,
    "NComp OO U (NCom)" float8 NULL,
    "Ttl OO U (NCom)" float8 NULL,
    "Comp OO Cst (NCom)" float8 NULL,
    "NComp OO Cst (NCom)" float8 NULL,
    "Ttl OO Cst (NCom)" float8 NULL,
    "Comp OO LCst (NCom)" float8 NULL,
    "Ttl OO LCst (NCom)" float8 NULL,
    "Comp OO AUC (NCom)" float8 NULL,
    "NComp OO AUC (NCom)" float8 NULL,
    "Ttl OO AUC (NCom)" float8 NULL,
    "Comp OO AULC (NCom)" float8 NULL,
    "Ttl OO AULC (NCom)" float8 NULL,
    "Comp Inv Adj U" float8 NULL,
    "NComp Inv Adj U" float8 NULL,
    "Ttl Inv Adj U" float8 NULL,
    "Comp Inv Adj Cst" float8 NULL,
    "NComp Inv Adj Cst" float8 NULL,
    "Ttl Inv Adj Cst" float8 NULL,
    "Comp Inv Adj LCst" float8 NULL,
    "Ttl Inv Adj LCst" float8 NULL,
    "Comp Inv Adj AUC" float8 NULL,
    "NComp Inv Adj AUC" float8 NULL,
    "Ttl Inv Adj AUC" float8 NULL,
    "Comp Inv Adj AULC" float8 NULL,
    "Ttl Inv Adj AULC" float8 NULL,
    "Comp EOH U OP" float8 NULL,
    "Ttl EOH U OP" float8 NULL,
    "Comp EOH U LF" float8 NULL,
    "Ttl EOH U LF" float8 NULL,
    "Comp EOH Cst OP" float8 NULL,
    "NComp EOH Cst OP" float8 NULL,
    "Ttl EOH Cst OP" float8 NULL,
    "Comp EOH LCst OP" float8 NULL,
    "Ttl EOH LCst OP" float8 NULL,
    "Comp EOH Cst LF" float8 NULL,
    "NComp EOH Cst LF" float8 NULL,
    "Ttl EOH Cst LF" float8 NULL,
    "Comp EOH LCst LF" float8 NULL,
    "Ttl EOH LCst LF" float8 NULL,
    "Comp OTB $ (WF vs OP)" float8 NULL,
    "NComp OTB $ (WF vs OP)" float8 NULL,
    "Ttl OTB $ (WF vs OP)" float8 NULL,
    "Comp OTB $ (WF vs LF)" float8 NULL,
    "NComp OTB $ (WF vs LF)" float8 NULL,
    "Ttl OTB $ (WF vs LF)" float8 NULL,
    "Comp OTB LCst WF to OP" float8 NULL,
    "Ttl OTB LCst WF to OP" float8 NULL,
    "Comp OTB LCst WF to LF" float8 NULL,
    "Ttl OTB LCst WF to LF" float8 NULL,
    "Comp Store Instock Facings" float8 NULL,
    "NComp Store Instock Facings" float8 NULL,
    "Ttl Store Instock Facings" float8 NULL,
    "Comp Store Total Facings" float8 NULL,
    "NComp Store Total Facings" float8 NULL,
    "Ttl Store Total Facings" float8 NULL,
    "Comp CH BOH U IMP" float8 NULL,
    "Ttl CH BOH U IMP" float8 NULL,
    "Comp CH BOH LCst IMP" float8 NULL,
    "Ttl CH BOH LCst IMP" float8 NULL,
    "Comp CH BOH Cst IMP" float8 NULL,
    "Ttl CH BOH Cst IMP" float8 NULL,
    "Comp CH BOH U" float8 NULL,
    "Ttl CH BOH U" float8 NULL,
    "Comp CH BOH Cst" float8 NULL,
    "Ttl CH BOH Cst" float8 NULL,
    "Comp CH BOH AULC" float8 NULL,
    "Ttl CH EOH Cst" float8 NULL,
    "Ttl CH BOH AULC" float8 NULL,
    "Comp CH EOH U IMP" float8 NULL,
    "Ttl CH EOH U IMP" float8 NULL,
    "Comp CH EOH LCst IMP" float8 NULL,
    "Ttl CH EOH LCst IMP" float8 NULL,
    "Comp CH EOH Cst IMP" float8 NULL,
    "Ttl CH EOH Cst IMP" float8 NULL,
    "Comp CH EOH U" float8 NULL,
    "Ttl CH EOH U" float8 NULL,
    "Comp CH EOH Cst" float8 NULL,
    "Comp CH EOH AULC" float8 NULL,
    "Ttl CH EOH AULC" float8 NULL,
    "Comp CH Est Res Rec %" float8 NULL,
    "Ttl CH Est Res Rec %" float8 NULL,
    "Comp CH Est Res Rec U" float8 NULL,
    "Ttl CH Est Res Rec U" float8 NULL,
    "Comp CH Est Res Rec Cst" float8 NULL,
    "Ttl CH Est Res Rec Cst" float8 NULL,
    "Comp Est 3rd Pty Rec %" float8 NULL,
    "Ttl Est 3rd Pty Rec %" float8 NULL,
    "Comp Est 3rd Pty Rec U" float8 NULL,
    "Ttl Est 3rd Pty Rec U" float8 NULL,
    "Comp Est 3rd Pty Rec Cst" float8 NULL,
    "Ttl Est 3rd Pty Rec Cst" float8 NULL,
    "Comp Est Bypass Rec %" float8 NULL,
    "Ttl Est Bypass Rec %" float8 NULL,
    "Comp Est Bypass Rec U" float8 NULL,
    "Ttl Est Bypass Rec U" float8 NULL,
    "Comp Est Bypass Rec Cst" float8 NULL,
    "Ttl Est Bypass Rec Cst" float8 NULL,
    "Comp CH Ttl Rct U" float8 NULL,
    "Ttl CH Ttl Rct U" float8 NULL,
    "Comp CH Ttl Rct Cst" float8 NULL,
    "Ttl CH Ttl Rct Cst" float8 NULL,
    "Ttl EOH LCst" float8 NULL,
    "Comp EOH LCst" float8 NULL
);
