import { makeStyles } from "@mui/styles";

export const useCreateRuleFlowStyles = makeStyles(() => ({
  contentWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    paddingBottom: "80px",
    marginTop: 0,
  },
  stepSectionsWrapper: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    width: "100%",
  },
  sectionCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "16px",
    backgroundColor: "#FFFFFF",
    borderRadius: "8px",
    padding: "16px",
    width: "100%",
    boxSizing: "border-box",
  },
  sectionTitle: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 800,
    lineHeight: "21px",
    color: "#0D152C",
    textTransform: "capitalize",
    margin: 0,
    width: "100%",
  },
  formFields: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    alignItems: "flex-start",
    width: "100%",
  },
  ruleNameField: {
    width: "282px",
    maxWidth: "282px",
    flexShrink: 0,
    "& .impact_inputbox_container": {
      width: "282px",
      maxWidth: "282px",
    },
  },
  /** Clamp impact-ui TextArea — TextareaAutosize ignores height and grows past 100px. */
  descriptionField: {
    width: "585px",
    maxWidth: "100%",
    "& .impact_textarea textarea": {
      height: "100px !important",
      minHeight: "100px !important",
      maxHeight: "100px !important",
      overflowY: "auto !important",
      boxSizing: "border-box",
    },
  },
  chipsDisabled: {
    opacity: 0.6,
    pointerEvents: "none",
  },
  placeholderText: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "21px",
    color: "#60697D",
  },
  storeSelectionTabsRow: {
    width: "100%",
  },
  storeSelectionTabContent: {
    width: "100%",
  },
  generalInfoRow: {
    display: "flex",
    gap: "24px",
    alignItems: "center",
    flexWrap: "wrap",
    width: "100%",
  },
  generalInfoContent: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    width: "100%",
  },
  storeGroupField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "289px",
    maxWidth: "100%",
    flexShrink: 0,
  },
  geoRestrictionField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    flexShrink: 0,
  },
  geoRestrictionFieldGrow: {
    flex: 1,
    minWidth: 0,
  },
  transferRestrictionField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    flexShrink: 0,
  },
  chipsLoader: {
    display: "flex",
    alignItems: "center",
    minHeight: "32px",
  },
  fieldLabel: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    margin: 0,
    textTransform: "capitalize",
  },
  requiredMark: {
    color: "#D32F2F",
    marginLeft: "2px",
  },
  geoRestrictionChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    alignItems: "flex-start",
  },
  hierarchyFiltersRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "24px",
    alignItems: "flex-start",
    width: "100%",
  },
  hierarchyFilterField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "289px",
    maxWidth: "100%",
    flexShrink: 0,
  },
  restrictionsAccordionWrapper: {
    width: "100%",
    /**
     * Beat impact-ui Accordion selectors
     * (`.impact_accordion_main_container .accordion_main_container …`) on specificity.
     * Outer shell must stay transparent — a white wrapper hides the 8px card radius
     * against the page background.
     */
    "& .impact_accordion_main_container": {
      backgroundColor: "transparent",
      gap: 0,
    },
    "& .impact_accordion_main_container .accordion_main_container": {
      backgroundColor: "#FFFFFF !important",
      border: "1px solid #EFF2FA !important",
      borderRadius: "8px !important",
      boxShadow: "none !important",
      padding: "8px 16px !important",
      overflow: "hidden",
      margin: "0 !important",
      "&::before": {
        display: "none",
      },
      "&.Mui-expanded": {
        margin: "0 !important",
        borderRadius: "8px !important",
      },
    },
    "& .impact_accordion_main_container .accordion_main_container .accordion_header": {
      display: "flex !important",
      flexDirection: "row-reverse",
      justifyContent: "flex-start !important",
      alignItems: "center",
      gap: "12px",
      height: "32px !important",
      minHeight: "32px !important",
      margin: "0 !important",
      padding: "0 !important",
      "&.Mui-expanded": {
        height: "32px !important",
        minHeight: "32px !important",
        margin: "0 !important",
      },
    },
    "& .impact_accordion_main_container .accordion_main_container .accordion_header .MuiAccordionSummary-content": {
      flexGrow: "1 !important",
      margin: "0 !important",
      width: "100%",
      justifyContent: "flex-start",
      "&.Mui-expanded": {
        margin: "0 !important",
      },
    },
    "& .impact_accordion_main_container .accordion_main_container .accordion_body": {
      padding: "12px 0 0 !important",
    },
  },
  restrictionsAccordionHeaderSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: "12px",
    width: "100%",
    minWidth: 0,
  },
  restrictionsAccordionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexShrink: 0,
  },
  restrictionsAccordionTitle: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#0D152C",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  fixedPushWarningBanner: {
    display: "flex",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
    maxWidth: "1100px",
    justifyContent: "space-between",
    gap: "12px",
    boxSizing: "border-box",
    padding: "8px 16px",
    backgroundColor: "#FFF8D5",
    borderRadius: "8px",
  },
  fixedPushWarningContent: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: 0,
    flex: 1,
  },
  fixedPushWarningIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    "& svg": {
      width: "18px",
      height: "17px",
      display: "block",
    },
  },
  fixedPushWarningText: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#0D152C",
    margin: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  fixedPushWarningCloseIcon: {
    cursor: "pointer",
    color: "#60697D",
    height: "20px",
    width: "20px",
    flexShrink: 0,
  },
  restrictionsPoolsRow: {
    display: "flex",
    gap: "24px",
    alignItems: "stretch",
    width: "100%",
  },
  restrictionsLockedContent: {
    position: "relative",
    width: "100%",
  },
  restrictionsPoolsRowLocked: {
    opacity: 0.4,
    pointerEvents: "none",
    userSelect: "none",
  },
  restrictionsLockOverlay: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    padding: "16px 29px",
    backgroundColor: "#FFFFFF",
    border: "1.5px solid #4259EE",
    borderRadius: "9999px",
    boxShadow: "0px 0px 26px rgba(66, 89, 238, 0.2)",
    zIndex: 1,
    pointerEvents: "none",
  },
  restrictionsLockText: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#1F2B4D",
    whiteSpace: "nowrap",
    margin: 0,
  },
  restrictionsLockIcon: {
    width: "16px",
    height: "16px",
    color: "#1F2B4D",
    flexShrink: 0,
  },
  restrictionsPoolsArrow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    color: "#60697D",
    alignSelf: "center",
    "& svg": {
      width: "24px",
      height: "24px",
      display: "block",
    },
  },
  restrictionPoolPanel: {
    position: "relative",
    flex: 1,
    minWidth: 0,
    border: "1px solid #D9DDE7",
    borderRadius: "12px",
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    paddingBottom: "16px",
    boxSizing: "border-box",
  },
  restrictionPoolHeader: {
    backgroundColor: "#ECEEFD",
    padding: "12px 16px",
    height: "40px",
    minHeight: "40px",
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    width: "100%",
    borderTopLeftRadius: "12px",
    borderTopRightRadius: "12px",
  },
  restrictionPoolTitle: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#0D152C",
    margin: 0,
  },
  restrictionPoolBody: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: "0 16px",
    width: "100%",
    boxSizing: "border-box",
  },
  poolGroupsContent: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    width: "100%",
  },
  poolSubSection: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
  },
  poolSubSectionTitle: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#1F2B4D",
    margin: 0,
    textTransform: "capitalize",
  },
  poolFilterByAttributesRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "16px",
    alignItems: "center",
  },
  poolHierarchyFiltersRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "16px",
    alignItems: "flex-start",
    width: "100%",
  },
  poolSelectField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    width: "332px",
    maxWidth: "100%",
    flexShrink: 0,
  },
  stepperToolbar: {
    position: "relative",
    width: "100%",
    marginBottom: "12px",
    padding: "12px 0",
    minHeight: "48px",
  },
  stepperToolbarMain: {
    width: "70%",
    margin: "0 auto",
    display: "flex",
    justifyContent: "center",
  },
  stepperToolbarActions: {
    position: "absolute",
    right: 0,
    top: "50%",
    transform: "translateY(-50%)",
    display: "flex",
    alignItems: "center",
  },
  viewEditIcon: {
    width: "16px",
    height: "16px",
    flexShrink: 0,
    display: "block",
    color: "inherit",
    "& path": {
      fill: "currentColor !important",
    },
  },
  /** Figma Bottom navigation: white bar with soft elevation shadow. */
  bottomButtonsContainer: {
    position: "fixed",
    zIndex: 10,
    bottom: 0,
    left: "60px",
    width: "calc(100% - 60px)",
    backgroundColor: "#FFFFFF",
    padding: "16px 24px",
    boxSizing: "border-box",
    boxShadow: "0px 0px 18px 5px rgba(0, 0, 0, 0.06)",
  },
  button: {
    margin: "0 5px",
    "&:nth-of-type(1)": {
      marginLeft: 0,
    },
    "&:last-child": {
      marginRight: 0,
    },
  },
}));
