--liquibase formatted sql
--changeset anoop.madamsetty@impactanalytics.co:product_attributes_filter stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for product_attributes_filter

CREATE TABLE "global".product_attributes_filter (
	product_code varchar NOT NULL,
	product_name varchar NOT NULL,
	product_description text NULL,
	price float8 NULL,
	"cost" float8 NULL,
	original_price float8 NULL,
	active bool NOT NULL,
	clearance bool NOT NULL,
	receipt_date date NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	replacement_product_codes _varchar NULL,
	reference_product_codes _varchar NULL,
	is_deleted bool NULL,
	l0_name varchar NOT NULL,
	l2_id varchar NOT NULL,
	l1_name varchar NOT NULL,
	l3_id varchar NOT NULL,
	l2_name varchar NOT NULL,
	managed_by_code varchar NULL,
	status varchar NOT NULL,
	l0_id varchar NOT NULL,
	phase_id int4 NULL,
	mfg_name varchar NULL,
	buyer_id varchar NULL,
	l5_id varchar NOT NULL,
	color varchar NULL,
	"size" varchar NULL,
	current_price float8 NULL,
	color_id varchar NULL,
	launch_week int4 NULL,
	l4_id varchar NOT NULL,
	l3_name varchar NOT NULL,
	vendor_style varchar NULL,
	buyer_name varchar NULL,
	phase_desc varchar NULL,
	launch_date date NULL,
	mfg_no varchar NULL,
	lifecycle_indicator varchar NULL,
	l6_name varchar NULL,
	l4_name varchar NOT NULL,
	msrp float8 NULL,
	l1_id varchar NOT NULL,
	dropship_indicator varchar NULL,
	eol_flag varchar NULL,
	gender varchar NULL,
	banner varchar NULL,
	l6_id varchar NOT NULL,
	"catalog" varchar NULL,
	season_desc varchar NULL,
	product_bucket_code varchar NOT NULL,
	vendor_name varchar NULL,
	launch_price float8 NULL,
	article varchar NOT NULL,
	bopis varchar NULL,
	alt_hier varchar NULL,
	brand varchar NULL,
	vendor_id varchar NULL,
	launch_year int4 NULL,
	brand_modelling varchar NOT NULL,
	brand_modelling_name varchar NOT NULL,
	CONSTRAINT product_attributes_filter_pk PRIMARY KEY (product_code, l0_name)
)
PARTITION BY LIST (l0_name);
CREATE INDEX product_attributes_filter_l0_name_idx ON global.product_attributes_filter USING btree (l0_name);
CREATE INDEX product_attributes_filter_product_code_idx ON global.product_attributes_filter USING btree (product_code);
