--liquibase formatted sql
--changeset liquibase:oms_deep_dive_base stripComments:false splitStatements:false context:initial_release labels:liquibase_project_start
--comment: initial changeset for oms_deep_dive_base

CREATE TABLE IF NOT EXISTS inventory_smart.oms_deep_dive_base (
	product_code varchar(50) NULL,
	"style" varchar(50) NULL,
	article varchar(50) NULL,
	"size" varchar(50) NULL,
	channel varchar(50) NULL,
	vendor_code varchar NULL,
	vendor_name varchar NULL,
	loc_code varchar(50) NULL,
	fiscal_year_week int8 NULL,
	week date NULL,
	"month" varchar(50) NULL,
	predicted_qty int4 NULL,
	eff_lead_time int4 NULL,
	rolling_std_dev float4 NULL,
	rolling_forecast float4 NULL,
	variance int4 NULL,
	safety_stock int4 NULL,
	receipt1 int4 NULL,
	receipt1_qc int4 NULL,
	total_dc_forecast int4 NULL,
	dc_inv int4 NULL,
	total_mins int4 NULL,
	additional_forecast int4 NULL,
	additional_inventory int4 NULL,
	approved_receipt int4 NULL,
	lost_sales int4 NULL,
	inventory_deficit int4 NULL,
	ecom_forecast int4 NULL,
	ecom_reserve int4 NULL,
	id serial4 NOT NULL,
	created_by int4 NULL,
	created_at timestamptz NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	week_starting date NULL,
	week_ending date NULL,
	approved_receipt_1 int4 NULL,
	total_dc_forecast_final_roq float4 NULL,
	ly_sales int4 NULL,
	ly_oh int4 NULL,
	total_stores_count int4 NULL,
	CONSTRAINT uk_oms_deep_dive_base UNIQUE (product_code, loc_code, fiscal_year_week)
);