--liquibase formatted sql
--changeset liquibase:oms_orders_recommended stripComments:false splitStatements:false context:initial_release labels:liquibase_project_start
--comment: initial changeset for oms_orders_recommended

CREATE SEQUENCE IF NOT EXISTS inventory_smart.oms_orders_recommended_new_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE IF NOT EXISTS inventory_smart.oms_orders_recommended (
	fiscal_year_week int4 NULL,
	fiscal_year_month int4 NULL,
	fiscal_year varchar NULL,
	fiscal_year_quarter varchar NULL,
	week_start_date date NULL,
	"month" varchar NULL,
	id int4 DEFAULT nextval('inventory_smart.oms_orders_recommended_new_id_seq'::regclass) NULL,
	order_gen_type varchar NULL,
	product_code varchar NULL,
	loc_code varchar NULL,
	channel varchar NULL,
	"size" varchar NULL,
	"style" varchar NULL,
	article varchar NULL,
	order_type varchar NULL,
	flow_id varchar NULL,
	vendor_code varchar NULL,
	vendor_name varchar NULL,
	grade varchar(50) NULL,
	order_quantity int4 NULL,
	order_cost float8 NULL,
	unit_cost float8 NULL,
	raw_roq float4 NULL,
	roq_unconstrained int4 NULL,
	roq_constrained int4 NULL,
	immd_roq int4 NULL,
	min_order_quantity_shipment int4 NULL,
	max_order_quantity_shipment int4 NULL,
	min_order_quantity_sku int4 NULL,
	max_order_quantity_sku int4 NULL,
	min_order_quantity_style int4 NULL,
	max_order_quantity_style int4 NULL,
	order_to_po_processing_time int4 NULL,
	lead_time int4 NULL,
	order_placement_date date NULL,
	order_placement_recom_date date NULL,
	order_multiple int4 NULL,
	editable_expected_receipt_date date NULL,
	expected_receipt_date date NULL,
	order_status_id int4 NULL,
	rop date NULL,
	rop_ideal date NULL,
	effective_lead_time int4 NULL,
	inventory_hold int4 NULL,
	created_by int4 NULL,
	created_at timestamptz NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	approve_by_date date NULL,
	is_deleted bool NULL,
	is_resolved bool NULL,
	recom_receipt_date date NULL,
	create_by_date date NULL,
	lost_sales_agg float4 NULL,
	inventory_deficit_agg float4 NULL,
	orders_upto_qty int4 NULL,
	elt_projected_bop int4 NULL,
	elt_projected_safety_stock int4 NULL,
	target_qty int4 NULL,
	lost_sales_agg_1 float4 NULL,
	forecasted_sales int4 NULL,
	target_wos int4 NULL,
	lost_sales_agg_2 float4 NULL,
	excess_inv float4 NULL,
	unmapped_store_inventory float4 NULL,
	store_counts int4 NULL,
	store_groups int4 NULL,
	ia_shipment_order_quantity int4 NULL,
	mode_shipment varchar NULL,
	order_reason varchar NULL,
	order_batch_name varchar(100) NULL,
	order_group_id varchar(250) NULL,
	order_placement_date_original date NULL,
	elt_projected_store_inv int4 DEFAULT 0 NULL,
	CONSTRAINT uk_oms_orders_recommended UNIQUE (product_code, loc_code, channel, vendor_code, rop, expected_receipt_date, order_status_id, order_gen_type)
);
