--liquibase formatted sql
--changeset liquibase:oms_kpi stripComments:false splitStatements:false context:initial_release labels:liquibase_project_start
--comment: initial changeset for oms_kpi
CREATE TABLE IF NOT EXISTS inventory_smart.oms_kpi (
	product_code varchar(50) NOT NULL,
	loc_code varchar(50) NOT NULL,
	dc_inv int4 NULL,
	safety_stock int4 NULL,
	created_by int4 NULL,
	created_at timestamptz NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	effective_lead_time varchar(50) NULL,
	adjusted_forecast_qty_4w varchar(50) NULL,
	adjusted_forecast_qty_4w_lc varchar(50) NULL,
	adjusted_forecast_qty_8w varchar(50) NULL,
	adjusted_forecast_qty_8w_lc varchar(50) NULL,
	adjusted_forecast_qty_12w varchar(50) NULL,
	adjusted_forecast_qty_12w_lc varchar(50) NULL,
	wos int4 NULL,
	target_service_level float8 NULL,
	ss_base float4 NULL,
	system_inv int4 NULL,
	open_receipt_units int4 NULL,
	channel varchar NULL,
	store_inv int4 NULL,
	mrpc int4 NULL,
	id serial4 NOT NULL,
	min_order_quantity_style int4 NULL,
	max_order_quantity_style int4 NULL,
	min_order_quantity_sku int4 NULL,
	max_order_quantity_sku int4 NULL,
	min_order_quantity_shipment int4 NULL,
	max_order_quantity_shipment int4 NULL,
	order_multiple int4 NULL,
	year_week varchar NULL,
	column_updated varchar NULL,
	vendor_code varchar NULL,
	vendor_name varchar NULL,
	CONSTRAINT pk_oms_kpi PRIMARY KEY (loc_code, product_code)
);