--liquibase formatted sql
--changeset liquibase:speed_tracing_simulate stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for speed_tracing_simulate

CREATE TABLE price_promo_opt.speed_tracing_simulate (
	id serial4 NOT NULL,
	fetch_promo_details_start timestamptz NULL,
	fetch_promo_details_end timestamptz NULL,
	create_promo_product_filter_start timestamptz NULL,
	create_promo_product_filter_end timestamptz NULL,
	create_discount_filter_start timestamptz NULL,
	create_discount_filter_end timestamptz NULL,
	delete_existing_recommended_scenarios_start timestamptz NULL,
	delete_existing_recommended_scenarios_end timestamptz NULL,
	create_date_partitions_start timestamptz NULL,
	create_date_partitions_end timestamptz NULL,
	fetch_store_data_start timestamptz NULL,
	fetch_store_data_end timestamptz NULL,
	offer_attractiveness_start timestamptz NULL,
	offer_attractiveness_end timestamptz NULL,
	cannibalization_coeff_start timestamptz NULL,
	cannibalization_coeff_end timestamptz NULL,
	pf_coeff_start timestamptz NULL,
	pf_coeff_end timestamptz NULL,
	insert_data_start timestamptz NULL,
	insert_data_end timestamptz NULL,
	refresh_aggregated_scenarios_start timestamptz NULL,
	refresh_aggregated_scenarios_end timestamptz NULL,
	drop_unlogged_tables_start timestamptz NULL,
	drop_unlogged_tables_end timestamptz NULL,
	promo_id int4 NULL,
	scenario_id _int4 NULL,
	total_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM drop_unlogged_tables_end - fetch_promo_details_start)::integer) STORED NULL,
	insert_data_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM insert_data_end - insert_data_start)::integer) STORED NULL,
	create_promo_product_filter_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM create_promo_product_filter_end - create_promo_product_filter_start)::integer) STORED NULL,
	create_discount_filter_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM create_discount_filter_end - create_discount_filter_start)::integer) STORED NULL,
	fetch_store_data_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM fetch_store_data_end - fetch_store_data_start)::integer) STORED NULL,
	offer_attractiveness_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM offer_attractiveness_end - offer_attractiveness_start)::integer) STORED NULL,
	cannibalization_coeff_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM cannibalization_coeff_end - cannibalization_coeff_start)::integer) STORED NULL,
	pf_coeff_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM pf_coeff_end - pf_coeff_start)::integer) STORED NULL,
	refresh_aggregated_scenarios_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM refresh_aggregated_scenarios_end - refresh_aggregated_scenarios_start)::integer) STORED NULL,
	fetch_promo_details_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM fetch_promo_details_end - fetch_promo_details_start)::integer) STORED NULL,
	drop_unlogged_tables_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM drop_unlogged_tables_end - drop_unlogged_tables_start)::integer) STORED NULL,
	delete_existing_recommended_scenarios_dur int4 GENERATED ALWAYS AS (EXTRACT(epoch FROM delete_existing_recommended_scenarios_end - delete_existing_recommended_scenarios_start)::integer) STORED NULL
);