--liquibase formatted sql
--changeset harshith.mandli@impactanalytics.co:tb_backsync_finalized_table stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for tb_backsync_finalized_table

DROP TABLE IF EXISTS price_promo_opt.tb_backsync_finalized_table;

CREATE TABLE price_promo_opt.tb_backsync_finalized_table (
	event_id int4 NULL,
	promo_id int4 NOT NULL,
	product_id int8 NOT NULL,
	recommendation_date date NOT NULL,
	discount_level_value int8 NULL,
	offer_type_id int4 NULL,
	effective_discount int4 NULL,
	original_cost float8 NULL,
	discounted_price float8 NULL,
	promo_spend float8 NULL,
	sales_units float8 NULL,
	baseline_sales_units float8 NULL,
	incremental_sales_units float8 NULL,
	revenue float8 NULL,
	baseline_revenue float8 NULL,
	incremental_revenue float8 NULL,
	margin float8 NULL,
	baseline_margin float8 NULL,
	incremental_margin float8 NULL,
	affinity_revenue float8 NULL,
	cannibalization_revenue float8 NULL,
	pull_forward_revenue float8 NULL,
	affinity_margin float8 NULL,
	cannibalization_margin float8 NULL,
	pull_forward_margin float8 NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	contribution_revenue float8 NULL,
	contribution_margin float4 NULL,
	offer_type_combined_display_name varchar NULL,
	store_reco_level varchar NOT NULL,
	currency_id int4 NOT NULL,
	vat_percentage float4 NULL,
	price_spend float8 NULL,
	customer_reco_level varchar NOT NULL,
	gross_revenue float8 NULL,
	gross_margin float8 NULL,
	gross_sales_units float8 NULL,
	coupon_spend float8 NULL,
	margin_wo_vf float8 NULL,
	scan_back float8 NULL,
	off_invoice float8 NULL,
	tot_vendor_fund float8 NULL,
	cannibalization_units numeric NULL,
	pull_forward_units numeric NULL,
	affinity_units numeric NULL,
	last_backsync_at timestamptz NOT NULL
);