--liquibase formatted sql
--changeset krithika.s@impactanalytics.co:bp_product_attributes_v2 stripComments:false splitStatements:false context:Release_1_0 labels: liquibase_project_start
--comment: changeset for base_pricing.bp_product_attributes_v2

CREATE TABLE base_pricing.bp_product_attributes (
	product_id int4 NOT NULL,
	product_description text NULL,
	pre_price bool NULL,
	price_lock bool NULL,
	brand_family text NULL,
	brand_class text NULL,
	size_family text NULL,
	size_class text NULL,
	line_group text NULL,
	other_family_1 text NULL,
	other_class_1 text NULL,
	material text NULL,
	fitting_size_in text NULL,
	pack_size text NULL,
	package_quantity int4 NULL,
	sell_pack_options text NULL,
	sellable_intent text NULL,
	colour text NULL,
	finish text NULL,
	features text NULL,
	application text NULL,
	core_type text NULL,
	connection_method text NULL,
	fitting_or_connector_type text NULL,
	merv_rating text NULL,
	works_with_smart_home text NULL,
	bore_type text NULL,
	moulding_type text NULL,
	cut_type text NULL,
	wood_species text NULL,
	base_cost float8 NULL,
	residential_price float8 NULL,
	"size" int4 NULL,
	uom text NULL,
	derived_size int4 NULL,
	derived_uom text NULL,
	product_status bool NULL,
	total_inventory varchar(50) NULL,
	rules_applied varchar(50) NULL,
	exceptions varchar(50) NULL,
	"style" text NULL,
	rebate float8 NULL,
	marketplace_fee float8 NULL,
	shipping_cost float8 NULL
);CREATE INDEX bs_product_attributes_idx ON base_pricing.bp_product_attributes USING btree (product_id);