import { makeStyles } from "@mui/styles";

// not adding colors from colour.js and changing pxToRem as this design is not given from design team, once given by them there will changes in this file
export const useStyles = makeStyles((theme) => ({
  outerWrapper: {
    position: "relative",
  },
  actionLoadingOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(255,255,255,0.6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  actionLoadingOverlayText: {
    background: "#FFFFFF",
    border: "1px solid #E5E7EB",
    borderRadius: 8,
    padding: "8px 12px",
    color: "#374151",
    fontSize: 13,
  },
  memoryLoadingOverlay: {
    padding: 16,
    color: "#6B7280",
    fontSize: 14,
  },
  memorySection: {
    background: "#FFFFFF",
    border: "1px solid #E2E8F0",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  memoryTextSection: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
  },
  memoryTextInputSection: {
    flex: 1,
    fontSize: 14,
    lineHeight: "20px",
    padding: "8px 10px",
    border: "1px solid #CBD5E1",
    borderRadius: 6,
  },
  editConfirmButtonDiv: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#10B981",
    border: "1px solid #10B981",
    borderRadius: 6,
    padding: 8,
    cursor: "pointer",
  },
  editConfirmButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#10B981",
    border: "1px solid #10B981",
    borderRadius: 6,
    padding: 8,
    cursor: "pointer",
  },
  confirmButton: { display: "inline-flex", width: 16, height: 16 },
  memoryText: {
    color: "#111827",
    fontSize: 14,
    lineHeight: "20px",
  },
  separator: {
    height: 1,
    background: "#E5E7EB",
    margin: "12px 0",
  },
  actionsRow: {
    display: "flex",
    gap: 8,
    justifyContent: "flex-end",
  },
  actionButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    border: "1px solid #E5E7EB",
    borderRadius: 6,
    padding: "6px 10px",
    cursor: "pointer",
  },
  iconWrapSmall: { display: "inline-flex", width: 14, height: 14 },
  iconSvgSmall: { width: 14, height: 14 },
  confirmIconSvg: { width: 16, height: 16, color: "#FFFFFF" },
  editText: { fontSize: 12, color: "#374151" },
  deleteText: { fontSize: 12, color: "#B91C1C" },
}));
