import { makeStyles } from "@mui/styles";

/**
 * Figma 20746:24454 / Component 1760 (20746:24450).
 * Overlay is 120×150 at 1920, pinned to the container padding-box edge
 * (x=0 / x=1688), not the inset card row. Progressive blur 7.6 → 0,
 * fill #FFFFFF 10%, hover appear 300ms ease-out (opacity).
 * Width scale: 1920→120, 1440→90, 1366→85, 1280→80, 1024→64.
 */
export const KPI_EDGE_BLUR = {
  baseWidth: 120,
  startBlurPx: 7.6,
  midBlurPx: 3.8,
  softBlurPx: 1.9,
  duration: "0.3s",
  easing: "ease-out",
  // 16 top padding + 32 header + 12 gap — Figma overlay y=61
  topOffset: 60,
  stripHeight: 116,
};

const BLUR_TRANSITION = `opacity ${KPI_EDGE_BLUR.duration} ${KPI_EDGE_BLUR.easing}`;

const maskLeft = (end) =>
  `linear-gradient(to right, #000 0%, transparent ${end}%)`;
const maskRight = (end) =>
  `linear-gradient(to left, #000 0%, transparent ${end}%)`;

const useStyles = makeStyles(() => ({
  section: {
    boxSizing: "border-box",
    width: "100%",
    backgroundColor: "#fff",
    borderBottom: "1px solid #d9dde7",
    borderRadius: 8,
    padding: "16px 16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    position: "relative",
    isolation: "isolate",
    "--kpi-edge-blur": `${KPI_EDGE_BLUR.baseWidth}px`,
    "@media (max-width: 1440px)": { "--kpi-edge-blur": "90px" },
    "@media (max-width: 1366px)": { "--kpi-edge-blur": "85px" },
    "@media (max-width: 1280px)": { "--kpi-edge-blur": "80px" },
    "@media (max-width: 1024px)": { "--kpi-edge-blur": "64px" },
  },
  sectionCollapsed: {
    height: 196,
    overflow: "hidden",
  },
  sectionExpanded: {
    minHeight: 452,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    height: 32,
    gap: 12,
    flexShrink: 0,
    zIndex: 2,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontFamily: "Manrope",
    fontWeight: 700,
    fontSize: 14,
    lineHeight: "21px",
    color: "#0d152c",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  chromeIcon: {
    width: 16,
    height: 16,
    display: "block",
    flexShrink: 0,
  },
  expandButton: {
    appearance: "none",
    WebkitAppearance: "none",
    margin: 0,
    width: 32,
    height: 32,
    minWidth: 32,
    minHeight: 32,
    maxWidth: 32,
    maxHeight: 32,
    padding: 8,
    boxSizing: "border-box",
    backgroundColor: "#fff",
    border: "1px solid #c3c8d4",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    lineHeight: 0,
    "&:hover, &:active, &:focus": {
      backgroundColor: "#eceefd",
      border: "1px solid #3649c6",
      outline: "none",
    },
    "&:hover $chromeIcon path, &:active $chromeIcon path, &:focus $chromeIcon path": {
      fill: "#3649c6",
    },
  },
  stripWrap: {
    position: "relative",
    width: "100%",
    flexShrink: 0,
    zIndex: 1,
    overflow: "hidden",
  },
  // Pinned to the section padding-box (left:0 / right:0) so the 16px card
  // inset stays in flow but the overlay paints over it — Figma x=0 / x=1688.
  // Height matches the card strip only (116); do not extend below the cards.
  edgeBlur: {
    position: "absolute",
    top: KPI_EDGE_BLUR.topOffset,
    height: KPI_EDGE_BLUR.stripHeight,
    width: "var(--kpi-edge-blur)",
    pointerEvents: "none",
    zIndex: 3,
    opacity: 0,
    transition: BLUR_TRANSITION,
    "& $edgeBlurTint, & $edgeBlurStop": {
      position: "absolute",
      inset: 0,
    },
    "@media (prefers-reduced-motion: reduce)": {
      transition: "none",
    },
  },
  edgeBlurVisible: {
    opacity: 1,
  },
  edgeBlurTint: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  edgeBlurStop: {
    display: "block",
  },
  edgeBlurStopSoft: {
    backdropFilter: `blur(${KPI_EDGE_BLUR.softBlurPx}px)`,
    WebkitBackdropFilter: `blur(${KPI_EDGE_BLUR.softBlurPx}px)`,
  },
  edgeBlurStopMid: {
    backdropFilter: `blur(${KPI_EDGE_BLUR.midBlurPx}px)`,
    WebkitBackdropFilter: `blur(${KPI_EDGE_BLUR.midBlurPx}px)`,
  },
  edgeBlurStopHard: {
    backdropFilter: `blur(${KPI_EDGE_BLUR.startBlurPx}px)`,
    WebkitBackdropFilter: `blur(${KPI_EDGE_BLUR.startBlurPx}px)`,
  },
  edgeBlurLeft: {
    left: 0,
    "& $edgeBlurTint, & $edgeBlurStopSoft": {
      WebkitMaskImage: maskLeft(100),
      maskImage: maskLeft(100),
    },
    "& $edgeBlurStopMid": {
      WebkitMaskImage: maskLeft(70),
      maskImage: maskLeft(70),
    },
    "& $edgeBlurStopHard": {
      WebkitMaskImage: maskLeft(40),
      maskImage: maskLeft(40),
    },
  },
  edgeBlurRight: {
    right: 0,
    "& $edgeBlurTint, & $edgeBlurStopSoft": {
      WebkitMaskImage: maskRight(100),
      maskImage: maskRight(100),
    },
    "& $edgeBlurStopMid": {
      WebkitMaskImage: maskRight(70),
      maskImage: maskRight(70),
    },
    "& $edgeBlurStopHard": {
      WebkitMaskImage: maskRight(40),
      maskImage: maskRight(40),
    },
  },
  strip: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: 2,
    width: "100%",
    boxSizing: "border-box",
    overflowX: "auto",
    overflowY: "hidden",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
      width: 0,
      height: 0,
    },
  },
  stripCollapsed: {
    overflowX: "auto",
    overflowY: "hidden",
    height: 116,
  },
  stripHovered: {
    overflowX: "auto",
    overflowY: "hidden",
    height: 116,
  },
  customScrollTrack: {
    position: "absolute",
    bottom: 6,
    left: 0,
    right: 0,
    margin: "0 auto",
    width: 200,
    height: 8,
    borderRadius: 999,
    backgroundColor: "#f6f5fa",
    overflow: "hidden",
    zIndex: 6,
    pointerEvents: "auto",
  },
  customScrollThumb: {
    position: "absolute",
    top: 0,
    left: 0,
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#7a8294",
    cursor: "pointer",
  },
  stripExpanded: {
    display: "flex",
    flexWrap: "wrap",
    alignContent: "flex-start",
    alignItems: "flex-start",
    gap: 16,
    padding: 2,
    width: "100%",
    minHeight: 372,
    overflow: "visible",
    boxSizing: "border-box",
    // Figma 16524:55401 — type A min 333×112; grow with max-content if label/icon
    // needs more than 333 (52×47 SVG viewBoxes, not Figma 36×36 frames).
    "& [data-kpi-type='a']": {
      width: "max-content",
      minWidth: 333,
    },
    "& [data-kpi-type='a'] $typeAText": {
      minWidth: "max-content",
      flexShrink: 0,
    },
  },
  scrollArrow: {
    appearance: "none",
    WebkitAppearance: "none",
    margin: 0,
    position: "absolute",
    top: 102,
    width: 32,
    height: 32,
    minWidth: 32,
    minHeight: 32,
    maxWidth: 32,
    maxHeight: 32,
    padding: 8,
    boxSizing: "border-box",
    backgroundColor: "#fff",
    border: "1.5px solid #4259ee",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    lineHeight: 0,
    pointerEvents: "auto",
  },
  scrollArrowLeft: {
    left: 8,
    zIndex: 4,
  },
  scrollArrowRight: {
    right: 8,
    zIndex: 5,
  },
  scrollArrowVisible: {
    visibility: "visible",
    opacity: 1,
  },
  scrollArrowHidden: {
    visibility: "hidden",
    opacity: 0,
    pointerEvents: "none",
  },
  card: {
    boxSizing: "border-box",
    height: 112,
    padding: "16px 24px",
    display: "flex",
    alignItems: "center",
    gap: 16,
    backgroundColor: "#fff",
    borderRadius: 8,
    boxShadow: "0px 0px 2px rgba(0, 0, 0, 0.12)",
    flexShrink: 0,
  },
  iconSlot: {
    width: 52,
    height: 47,
    flexShrink: 0,
    overflow: "visible",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& svg, & img": {
      width: "100%",
      height: "100%",
      display: "block",
    },
  },
  typeAText: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    height: "100%",
    justifyContent: "center",
    alignItems: "flex-start",
    minWidth: 0,
  },
  typeAValueRow: {
    display: "flex",
    alignItems: "center",
    gap: 10.814,
    padding: "4px 0",
    borderRadius: 8,
    width: "100%",
  },
  typeBText: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    alignItems: "flex-start",
    flexShrink: 0,
  },
  divider: {
    width: 1,
    height: 20,
    backgroundColor: "#d9dde7",
    flexShrink: 0,
    border: 0,
    padding: 0,
    margin: 0,
  },
  chipsColumn: {
    display: "grid",
    gridTemplateRows: "auto auto",
    gridAutoFlow: "column",
    gridAutoColumns: "max-content",
    gap: 16,
    alignContent: "center",
    justifyContent: "start",
    width: "max-content",
    flexShrink: 0,
    overflow: "visible",
  },
  chip: {
    boxSizing: "border-box",
    minWidth: 192,
    width: "max-content",
    padding: "4px 8px",
    borderRadius: 8,
    backgroundColor: "#f5f6fa",
    display: "flex",
    alignItems: "center",
    gap: 10.814,
    flexShrink: 0,
  },
  chipLabel: {
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "20px",
    color: "#1f2b4d",
    width: 108,
    flexShrink: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    textAlign: "left",
  },
  chipValue: {
    fontFamily: "Manrope",
    fontWeight: 800,
    fontSize: 16,
    lineHeight: "24px",
    color: "#1f2b4d",
    flexGrow: 1,
    flexShrink: 0,
    minWidth: "min-content",
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  chipArrow: {
    width: 24,
    height: 24,
    minWidth: 24,
    minHeight: 24,
    maxWidth: 24,
    maxHeight: 24,
    padding: 0,
    boxSizing: "border-box",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
    "& svg, & img": {
      width: 6,
      height: 10,
      display: "block",
      flexShrink: 0,
    },
  },
  chipArrowButton: {
    appearance: "none",
    WebkitAppearance: "none",
    margin: 0,
    border: 0,
    backgroundColor: "transparent",
    cursor: "pointer",
    font: "inherit",
    color: "inherit",
    lineHeight: 0,
    "&:hover, &:active, &:focus": {
      outline: "none",
    },
  },
  sizePopover: {
    position: "fixed",
    zIndex: 1500,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 8,
    padding: 12,
    width: "max-content",
    backgroundColor: "#fff",
    borderRadius: 12,
    boxShadow: "0px 0px 2px rgba(0, 0, 0, 0.12)",
    minWidth: 130,
  },
  popoverInner: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    gap: 12,
    width: "max-content",
  },
  popoverHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minWidth: 130,
    width: "100%",
  },
  popoverTitle: {
    flex: 1,
    fontFamily: "Manrope",
    fontWeight: 800,
    fontSize: 14,
    lineHeight: "21px",
    height: 22,
    color: "#0d152c",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  popoverCloseButton: {
    appearance: "none",
    WebkitAppearance: "none",
    margin: 0,
    width: 24,
    height: 24,
    minWidth: 24,
    minHeight: 24,
    maxWidth: 24,
    maxHeight: 24,
    padding: 8,
    boxSizing: "border-box",
    backgroundColor: "transparent",
    border: 0,
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    lineHeight: 0,
    flexShrink: 0,
    "&:hover, &:active, &:focus": {
      outline: "none",
    },
  },
  popoverCloseIcon: {
    width: 16,
    height: 16,
    display: "block",
    flexShrink: 0,
  },
  popoverChipWrap: {
    display: "grid",
    gridTemplateColumns: "repeat(3, max-content)",
    gap: 8,
    width: "max-content",
  },
  popoverChip: {
    boxSizing: "border-box",
    minWidth: 67,
    width: "auto",
    padding: "4px 8px",
    borderRadius: 8,
    backgroundColor: "#f5f6fa",
    border: "0.216px solid #d9dde7",
    display: "flex",
    alignItems: "center",
    overflow: "visible",
    flexShrink: 0,
  },
  popoverChipInner: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  popoverChipLabel: {
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 14,
    lineHeight: "20px",
    color: "#1f2b4d",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  popoverChipValue: {
    fontFamily: "Manrope",
    fontWeight: 800,
    fontSize: 16,
    lineHeight: "24px",
    color: "#1f2b4d",
    textAlign: "right",
    whiteSpace: "nowrap",
  },
  label: {
    fontFamily: "Manrope",
    fontWeight: 600,
    fontSize: 16,
    lineHeight: "24px",
    color: "#1f2b4d",
    whiteSpace: "nowrap",
  },
  value: {
    fontFamily: "Manrope",
    fontWeight: 800,
    fontSize: 16,
    lineHeight: "24px",
    color: "#1f2b4d",
    whiteSpace: "nowrap",
  },
}));

export default useStyles;
