--liquibase formatted sql
--changeset bhavya.visaria@impactanalytics.co:budget_product_hierarchy stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial version of budget_product_hierarchy 

CREATE TABLE IF NOT EXISTS oms.budget_product_hierarchy (
	hierarchy_id serial4 NOT NULL,
	hierarchy_level varchar NOT NULL,
	l0_id varchar NOT NULL,
	l0_name varchar NOT NULL,
	l1_id varchar NULL,
	l1_name varchar NULL,
	l2_id varchar NULL,
	l2_name varchar NULL,
	l3_id varchar NULL,
	l3_name varchar NULL,
	l4_id varchar NULL,
	l4_name varchar NULL,
	l5_id varchar NULL,
	l5_name varchar NULL,
	l6_id varchar NULL,
	l6_name varchar NULL,
	l7_id varchar NULL,
	l7_name varchar NULL,
	l8_id varchar NULL,
	l8_name varchar NULL,
	l9_id varchar NULL,
	l9_name varchar NULL,
	l10_id varchar NULL,
	l10_name varchar NULL,
	loc_code varchar NULL,
	channel varchar NULL,
	is_active bool DEFAULT true NOT NULL,
	created_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	product_code varchar NULL,
	product_name varchar NULL,
	product_description text NULL,
	price float8 NULL,
	original_price float8 NULL,
	"cost" float8 NULL,
	active bool DEFAULT true NOT NULL,
	item_status varchar NULL,
	primary_trait_desc varchar NULL,
	primary_vendor_name varchar NULL,
	style_desc varchar NULL,
	color varchar NULL,
	"size" varchar NULL,
	sbt_flag varchar NULL,
	drop_ship_flag varchar NULL,
	ia_custom_style_id varchar NULL,
	ia_sku_type varchar NULL,
	product_type varchar NULL,
	product_category varchar NULL,
	product_attribute_4 varchar NULL,
	product_attribute_5 varchar NULL,
	product_attribute_6 varchar NULL,
	product_attribute_7 varchar NULL,
	product_attribute_8 varchar NULL,
	product_attribute_9 varchar NULL,
	product_attribute_10 varchar NULL,
	product_attribute_11 varchar NULL,
	product_attribute_12 varchar NULL,
	product_attribute_13 varchar NULL,
	product_attribute_14 varchar NULL,
	product_attribute_15 varchar NULL,
	launch_date date NULL,
	clearance bool DEFAULT false NOT NULL,
	receipt_date date NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	replacement_product_codes _varchar NULL,
	reference_product_codes _varchar NULL,
	is_deleted bool NULL,
	"style" varchar NULL,
	article varchar NULL,
	primary_trait_id varchar NULL,
	color_desc varchar NULL,
	uda_value_desc _varchar NULL,
	brand varchar NULL,
	clearance_start_date date NULL,
	color_id varchar NULL,
	color_name varchar NULL,
	l3_name_brand varchar NULL,
	primary_vendor_id varchar NULL,
	product_bucket_code int8 NULL,
	product_channel varchar NULL,
	size_name varchar NULL,
	sku varchar NULL,
	style_color_id varchar NULL,
	style_id varchar NULL,
	supersede_flag varchar NULL,
	upc varchar NULL,
	vendor varchar NULL,
	vendor_case_pack varchar NULL,
	inner_pack_units varchar NULL,
	"ordering" varchar NULL,
	replenishment_status varchar NULL,
	product_image_link varchar NULL,
	vendor_location varchar NULL,
	CONSTRAINT budget_product_hierarchy_pkey PRIMARY KEY (hierarchy_id)
);

CREATE INDEX idx_ph_level ON oms.budget_product_hierarchy(hierarchy_level);
CREATE INDEX idx_ph_l4_id ON oms.budget_product_hierarchy(l4_id);
CREATE INDEX idx_ph_l1_id ON oms.budget_product_hierarchy(l1_id) WHERE l1_id IS NOT NULL;
CREATE INDEX idx_ph_l5_id ON oms.budget_product_hierarchy(l5_id) WHERE l5_id IS NOT NULL;
CREATE INDEX idx_ph_l3_id ON oms.budget_product_hierarchy(l3_id) WHERE l3_id IS NOT NULL;
CREATE INDEX idx_ph_parent ON oms.budget_product_hierarchy(hierarchy_id);
CREATE INDEX idx_ph_active ON oms.budget_product_hierarchy(is_active) WHERE is_active = TRUE;
