--liquibase formatted sql
--changeset kailash.kangne@impactanalytics.co:GA_Instance_schema_creation_update1 stripComments:false splitStatements:false context:Release_1_0 labels:moving_tables_to_oms
--comment: starboard

CREATE TABLE IF NOT EXISTS oms.oms_orders_approved (
	id int8 NOT NULL,
	order_gen_type varchar NOT NULL,
	product_code varchar NOT NULL,
	vendor_code varchar NOT NULL,
	rop date NOT NULL,
	grade varchar NULL,
	order_quantity int4 NOT NULL,
	pack_id varchar NULL,
	unit_cost float8 NOT NULL,
	order_cost float8 NULL,
	roq_constrained int4 NULL,
	roq_unconstrained int4 NULL,
	order_placement_date date NOT NULL,
	order_placement_recom_date date NOT NULL,
	expected_receipt_date date NULL,
	rop_ideal date NULL,
	lead_time int4 NULL,
	effective_lead_time int4 NULL,
	store_inv int4 NULL,
	dc_inv int4 NULL,
	system_inv int4 NULL,
	mrpc float4 NULL,
	min_order_quantity_sku int4 NULL,
	max_order_quantity int4 NULL,
	order_multiple int4 NULL,
	inventory_hold int4 NULL,
	order_status_id int8 DEFAULT 3 NOT NULL,
	created_by int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	edit_by_date date NULL,
	is_deleted bool NULL,
	"comment" text NULL,
	article varchar(100) NULL,
	"size" varchar(100) NULL,
	"style" varchar(100) NULL,
	channel varchar(100) NULL,
	min_order_quantity_style int4 NULL,
	editable_expected_receipt_date date NULL,
	min_order_quantity_shipment int4 NULL,
	max_order_quantity_sku int4 NULL,
	max_order_quantity_style int4 NULL,
	max_order_quantity_shipment int4 NULL,
	loc_code varchar DEFAULT '-'::character varying NOT NULL,
	order_type varchar(100) NULL,
	reconciliation_id varchar NULL,
	order_batch_name varchar NULL,
	approved_orders_pending_reconciliation int4 NULL,
    fiscal_year_week int4 NULL,
    fiscal_year_month int4 NULL,
    mode_shipment varchar(256) NULL,
    order_id int4 NULL,
    order_reason varchar(256) NULL,
    raw_roq int4 NULL,
	CONSTRAINT uk_oms_orders_approved UNIQUE (product_code, vendor_code, channel, loc_code, rop, expected_receipt_date, order_gen_type)
);


