-- liquibase formatted sql
-- changeset kumaran.k@impactanalytics.co:sync_product_master_promo_v5 runOnChange:true stripComments:false splitStatements:false context:Release_1_0 labels:sync_product_master_promo
-- comment: derived table for product master promo_v5

DROP  PROCEDURE if exists public.sync_product_master_promo();

CREATE OR REPLACE PROCEDURE public.sync_product_master_promo()
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $procedure$
declare
	_log_code varchar := gen_random_uuid();
	_sp_name varchar := 'public.sync_product_master_promo';
	_log_step varchar;
	_st TIMESTAMP := clock_timestamp();
begin
	call global.data_ingestion_logs(_log_code, _sp_name, 'start', null, (clock_timestamp() - _st)::text, null);
	perform set_config('local.log_code', _log_code, true);
	perform set_config('local.sp_name', _sp_name, true);
	begin
	        TRUNCATE TABLE price_promo.product_master;

	         DROP INDEX IF EXISTS price_promo.product_master_promo_product_id_idx;
           
	        INSERT INTO price_promo.product_master
	        (
            l0_id,
            l0_name,
            l0_cuq,
            l0_cid,
            l1_id,
            l1_name,
            l1_cuq,
            l1_cid,
            l2_id,
            l2_name,
            l2_cuq,
            l2_cid,
            l3_id,
            l3_name,
            l3_cuq,
            l3_cid,
            l4_id,
            l4_name,
            l4_cuq,
            l4_cid,
            product_id,
            product_name,
            product_cuq,
            item_key,
            dept_cls_hier_key,
            sku_type_desc,
            manufacturer_id,
            active,
            is_active,
            merch_flag,
            clearance_indicator,
            clearance,
            status,
            product_status,
            item_clearance_dt,
            launch_date,
            item_short_desc,
            item_set_typ_cd,
            item_set_typ_nm,
            selling_uom_cd,
            chain_prc_cd,
            zone_prc_cd,
            store_prc_cd,
            item_discontinue_dt_skey,
            buyer_id,
            buyer_description,
            vendor_id,
            vendor_description,
	    launch_price,
	    current_price,
      current_bnm_price,
      current_ecom_lesl_price,
      current_ecom_its_price,
      current_comm_price, 
      current_pro_bnm_price,
      current_c8_price,
      current_c9_price,
            "cost",
            "map",
              kvi_store_res,
              kvi_les_res,
              kvi_its_res,
              kvi_mkt_res,
              kvi_com_com,
              kvc_store_res,
              kvc_les_res,
              kvc_its_res,
              kvc_mkt_res,
              kvc_com_com,
              kvi_store_res_id,
              kvi_les_res_id,
              kvi_its_res_id,
              kvi_mkt_res_id,
              kvi_com_com_id,
              kvc_store_res_id,
              kvc_les_res_id,
              kvc_its_res_id,
              kvc_mkt_res_id,
              kvc_com_com_id,
              kvi_indicator,
              currency_id,
              map_flag,
              bnm_inv,
              ecom_lesliespool_inv,
              ecom_its_inv,
              commercial_inv,
              product_status_cid,
			  manufacturer_name,
			  total_inv,
  			  clearance_cid,
  			  shipping_cost,
  			  rebate,
  			  marketplace_fee
	        )

			select
            l0_id,
            l0_name,
            l0_cuq,
            l0_cid,
            l1_id,
            l1_name,
            l1_cuq,
            l1_cid,
            l2_id,
            l2_name,
            l2_cuq,
            l2_cid,
            l3_id,
            l3_name,
            l3_cuq,
            l3_cid,
            l4_id,
            l4_name,
            l4_cuq,
            l4_cid,
            product_id,
            product_name,
            product_cuq,
            item_key,
            dept_cls_hier_key,
            sku_type_desc,
            manufacturer_id,
            active,
            is_active,
            merch_flag,
            clearance_indicator,
            clearance,
            status,
            product_status,
            item_clearance_dt,
            launch_date,
            item_short_desc,
            item_set_typ_cd,
            item_set_typ_nm,
            selling_uom_cd,
            chain_prc_cd,
            zone_prc_cd,
            store_prc_cd,
            item_discontinue_dt_skey,
            buyer_id,
            buyer_description,
            vendor_id,
            vendor_description,
            launch_price,
	    current_price,
      current_bnm_price,
      current_ecom_lesl_price,
      current_ecom_its_price,
      current_comm_price, 
      current_pro_bnm_price,
      current_c9_price,
      current_c9_price,
            "cost",
            "map",
              kvi_store_res,
              kvi_les_res,
              kvi_its_res,
              kvi_mkt_res,
              kvi_com_com,
              kvc_store_res,
              kvc_les_res,
              kvc_its_res,
              kvc_mkt_res,
              kvc_com_com,
              kvi_store_res_id,
              kvi_les_res_id,
              kvi_its_res_id,
              kvi_mkt_res_id,
              kvi_com_com_id,
              kvc_store_res_id,
              kvc_les_res_id,
              kvc_its_res_id,
              kvc_mkt_res_id,
              kvc_com_com_id,
              kvi_indicator,
              currency_id,
              map_flag,
              bnm_inv,
              ecom_lesliespool_inv,
              ecom_its_inv,
              "Commercial_inv",
              product_status_cid,
			  manufacturer_name,
			  total_inv,
  			  clearance_cid,
  			  shipping_cost,
  			  rebate,
  			  marketplace_fee
			from public.product_master_promo
		group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93;
	CREATE INDEX product_master_promo_product_id_idx ON price_promo.product_master (product_id);
		call global.data_ingestion_logs(_log_code, _sp_name, 'end', null, (clock_timestamp() - _st)::text, null);
	exception
		when others then
	        -- Log the error if an exception occurs during any part of the procedure
	        call global.data_ingestion_logs(_log_code, _sp_name, _log_step, SQLERRM, (clock_timestamp() - _st)::text, null);
            raise exception 'Error occurred in the procedure: %', SQLERRM;
	end;
	    end
$procedure$
;