/**
 * GENERAL_CONFIGURATION is the json which will be used to
 * render the general configuration page through module
 * configurator
 */
export const TABLE_CONFIGURATION = {
  components: {
    id: "table-configuration-container",
    type: "div",
    pathSrc: "core",
    componentPath: "commonComponents/ui/wrapper-div/wrapper-div.jsx",
    staticProps: {
      style: {
        padding: "24px 23px",
        width: "100%",
      },
    },
    children: [
      {
        id: "table-configuration",
        type: "table",
        pathSrc: "core",
        componentPath: "commonComponents/ui/table-wrapper/table-wrapper.jsx",
        staticProps: {
          reducerKey: "table-configuration-form",
          columnKey: "tableWrapperColumns",
          rowKey: "tableWrapperRowData",
          isColumnDataFromApi: true,
          isRowDataFromApi: true,
        },
        children: null,
        functionProps: [
          {
            functionName: "onLoad",
            actions: [
              {
                type: "api_function",
                apiUrl: "/core/table-fields",
                apiMethod: "GET",
                apiResponseAlerts: {
                  success: "Api successfully called",
                  error: "Error in api call",
                  successResponseFromApi: true,
                },
                params: [
                  {
                    dataType: "string",
                    source: "reducer",
                    reducerName: "configuratorReducer",
                    reducerKey: "currentTableName",
                    paramName: "table_name",
                    shouldFormat: true,
                    functionPath: "utils.js",
                    functionName: "testHelperFunction",
                  },
                ],
                responseFormatter: [
                  {
                    reducerName: "jsonParserReducer",
                    reducerKey: "tableWrapperColumns",
                  },
                ],
              },
            ],
          },
          {
            functionName: "onLoad",
            actions: [
              {
                type: "api_function",
                apiUrl: "/core/release-notes",
                apiMethod: "GET",
                apiResponseAlerts: {
                  success: "Api successfully called",
                  error: "Error in api call",
                },
                params: [],
                responseFormatter: [
                  {
                    reducerName: "jsonParserReducer",
                    reducerKey: "tableWrapperRowData",
                  },
                ],
              },
            ],
          },
          {
            functionName: "onLoad",
            actions: [
              {
                type: "api_function",
                apiUrl: "/inventory-smart/dashboard/refresh-date",
                apiMethod: "GET",
                apiResponseAlerts: {
                  success: "Api successfully called",
                  error: "Error in api call",
                },
                params: [],
                responseFormatter: [
                  {
                    reducerName: "jsonParserReducer",
                    reducerKey: "mfpDate",
                    apiKey: "mfp_date",
                    shouldFormat: true,
                    functionPath: "utils.js",
                    functionName: "testHelperFunction",
                  },
                  {
                    reducerName: "jsonParserReducer",
                    reducerKey: "refreshDate",
                    apiKey: "refresh_date",
                  },
                  {
                    reducerName: "jsonParserReducer",
                    reducerKey: "refreshDateString",
                    value: "refresh_date",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "table-configuration",
        type: "table",
        pathSrc: "core",
        componentPath: "commonComponents/ui/table-wrapper/table-wrapper.jsx",
        staticProps: {
          reducerKey: "table-configuration-form",
          columnKey: "tableWrapperColumns1",
          rowKey: "tableWrapperRowData1",
          isColumnDataFromApi: true,
          isRowDataFromApi: true,
        },
        children: null,
        functionProps: [
          {
            functionName: "onLoad",
            actions: [
              {
                type: "api_function",
                apiUrl: "/core/table-fields",
                apiMethod: "GET",
                apiResponseAlerts: {
                  success: "Api successfully called",
                  error: "Error in api call",
                },
                params: [
                  {
                    dataType: "value",
                    source: "self",
                    value: "dc_status",
                    paramName: "table_name",
                  },
                ],
                responseFormatter: [
                  {
                    reducerName: "jsonParserReducer",
                    reducerKey: "tableWrapperColumns1",
                  },
                ],
              },
            ],
          },
          {
            functionName: "onLoad",
            actions: [
              {
                type: "api_function",
                apiUrl: "/master/dc_status/dc",
                apiMethod: "POST",
                apiResponseAlerts: {
                  success: "Api successfully called",
                  error: "Error in api call",
                },
                params: [
                  {
                    dataType: "value",
                    source: "self",
                    value: [],
                    paramName: "filters",
                  },
                  {
                    dataType: "value",
                    source: "self",
                    value: [],
                    paramName: "headers",
                  },
                  {
                    dataType: "value",
                    source: "self",
                    value: {
                      search: [],
                      range: [],
                      sort: [],
                      limit: { limit: 10, page: 1 },
                    },
                    paramName: "meta",
                  },
                ],
                responseFormatter: [
                  {
                    reducerName: "jsonParserReducer",
                    reducerKey: "tableWrapperRowData1",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: "table-configuration",
        type: "table",
        pathSrc: "core",
        componentPath: "commonComponents/ui/table-wrapper/table-wrapper.jsx",
        staticProps: {
          reducerKey: "table-configuration-form",
          isColumnDataFromApi: false,
          isRowDataFromApi: false,
          staticColumnData: [
            {
              sub_headers: [],
              tc_code: 501,
              label: "User id",
              column_name: "user_id",
              dimension: "Product",
              type: "link",
              is_frozen: false,
              is_editable: true,
              is_aggregated: false,
              order_of_display: 1.0,
              is_hidden: false,
              is_required: false,
              tc_mapping_code: 200005,
              aggregate_type: "",
              formatter: "",
              is_row_span: false,
              footer: "",
              is_searchable: true,
              extra: {},
              is_sortable: true,
              width: 200,
              is_deleted: false,
            },
            {
              sub_headers: [],
              tc_code: 501,
              label: "Requester name",
              column_name: "user_name",
              dimension: "Product",
              type: "str",
              is_frozen: false,
              is_editable: false,
              is_aggregated: false,
              order_of_display: 2.0,
              is_hidden: false,
              is_required: false,
              tc_mapping_code: 200006,
              aggregate_type: "",
              formatter: "",
              is_row_span: false,
              footer: "",
              is_searchable: true,
              extra: {},
              is_sortable: true,
              width: 200,
              is_deleted: false,
            },
            {
              sub_headers: [],
              tc_code: 501,
              label: "Total tickets",
              column_name: "total",
              dimension: "Product",
              type: "link",
              is_frozen: false,
              is_editable: true,
              is_aggregated: false,
              order_of_display: 3.0,
              is_hidden: false,
              is_required: false,
              tc_mapping_code: 200007,
              aggregate_type: "",
              formatter: "",
              is_row_span: false,
              footer: "",
              is_searchable: true,
              extra: {},
              is_sortable: true,
              width: 200,
              is_deleted: false,
            },
            {
              sub_headers: [],
              tc_code: 501,
              label: "Open tickets",
              column_name: "open",
              dimension: "Product",
              type: "link",
              is_frozen: false,
              is_editable: true,
              is_aggregated: false,
              order_of_display: 4.0,
              is_hidden: false,
              is_required: false,
              tc_mapping_code: 200008,
              aggregate_type: "",
              formatter: "",
              is_row_span: false,
              footer: "",
              is_searchable: true,
              extra: {},
              is_sortable: true,
              width: 200,
              is_deleted: false,
            },
            {
              sub_headers: [],
              tc_code: 501,
              label: "Closed tickets",
              column_name: "closed",
              dimension: "Product",
              type: "link",
              is_frozen: false,
              is_editable: true,
              is_aggregated: false,
              order_of_display: 5.0,
              is_hidden: false,
              is_required: false,
              tc_mapping_code: 200009,
              aggregate_type: "",
              formatter: "",
              is_row_span: false,
              footer: "",
              is_searchable: true,
              extra: {},
              is_sortable: true,
              width: 200,
              is_deleted: false,
            },
          ],
          staticRowData: [
            {
              closed: 10,
              open: 17,
              total: 27,
              user_id: 251,
              user_name: "Demo",
            },
          ],
        },
        children: null,
      },
    ],
  },
};
