--liquibase formatted sql
--changeset abhishek.singh@impactanalytics.co:bp_product_store_attributes_mapping_v4 stripComments:false splitStatements:false context:Release_1_0 labels: liquibase_project_start
--comment: changeset for base_pricing.bp_product_store_attributes_mapping_v4

CREATE TABLE base_pricing.bp_product_store_attributes_mapping_v4 (
	product_id int8 NOT NULL,
	store_id int4 NOT NULL,
	segment_id int4 NOT NULL,
	channel_id int2 NULL,
	zone_structure varchar(50) NULL,
	price_zone varchar(50) NULL,
	effective_price_zone varchar(50) NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	attribute_1 float8 NULL,
	attribute_2 float8 NULL,
	attribute_3 float8 NULL,
	attribute_4 float8 NULL,
	attribute_5 float8 NULL,
	attribute_6 bool DEFAULT false NULL,
	attribute_7 bool DEFAULT false NULL,
	attribute_8 bool DEFAULT false NULL,
	attribute_9 bool DEFAULT false NULL,
	attribute_10 text NULL,
	attribute_11 int4 NULL,
	attribute_12 float8 NULL,
	attribute_13 float8 NULL,
	attribute_14 text NULL,
	attribute_15 text NULL,
	attribute_16 bool DEFAULT false NULL,
	attribute_17 int4 NULL,
	attribute_18 float8 NULL,
	attribute_19 float8 NULL,
	attribute_20 text NULL,
	attribute_2000 float8 NULL,
	attribute_2001 float8 NULL,
	attribute_2002 float8 NULL,
	attribute_2003 float8 NULL,
	attribute_2004 float8 NULL,
	attribute_2005 float8 NULL,
	attribute_2006 float8 NULL,
	attribute_2007 float8 NULL,
	attribute_2008 float8 NULL,
	attribute_2009 float8 NULL,
	attribute_2010 float8 NULL,
	attribute_2011 float8 NULL,
	attribute_2012 float8 NULL,
	attribute_2013 float8 NULL,
	attribute_2014 float8 NULL,
	primary_bucket _varchar DEFAULT '{}'::character varying[] NULL,
	primary_mode varchar(50) NULL,
	secondary_bucket _varchar DEFAULT '{}'::character varying[] NULL,
	secondary_mode varchar(50) NULL,
	tertiary_bucket _varchar DEFAULT '{}'::character varying[] NULL,
	tertiary_mode varchar(50) NULL,
	quaternary_bucket _varchar DEFAULT '{}'::character varying[] NULL,
	quaternary_mode varchar(50) NULL,
	CONSTRAINT bp_product_store_attributes_mapping_v4_pkey PRIMARY KEY (product_id, store_id, segment_id)
)
WITH (
	autovacuum_enabled=false
);