--liquibase formatted sql
--changeset abhishek.singh@impactanalytics.co:bp_price_reco_current_last_approved_snapshot stripComments:false splitStatements:false context:Release_1_0 labels: liquibase_project_start
--comment: changeset for base_pricing.bp_price_reco_current_last_approved_snapshot

CREATE TABLE base_pricing.bp_price_reco_current_last_approved_snapshot (
	id bigserial NOT NULL,
	strategy_id int4 NOT NULL,
	product_id int4 NOT NULL,
	store_id varchar(255) NOT NULL,
	segment_id int4 NULL,
	channel_id int4 NULL,
	product_name varchar(255) NOT NULL,
	store_name varchar(255) NOT NULL,
	segment_name varchar(255) NOT NULL,
	strategy_name varchar NULL,
	opt_level_bins varchar(255) NULL,
	start_date date NOT NULL,
	end_date date NOT NULL,
	line_group varchar(100) NULL,
	size_family varchar(100) NULL,
	size_class varchar(100) NULL,
	brand_family varchar(100) NULL,
	brand_class varchar(100) NULL,
	channel varchar(100) NULL,
	zone_structure_id int4 NULL,
	zone_structure_name varchar(255) NULL,
	effective_price_zone text NULL,
	price_zone_id int4 NULL,
	price_zone_name varchar(255) NULL,
	uom varchar(50) NULL,
	"size" float8 NULL,
	"cost" float8 NULL,
	custom_family_1 varchar NULL,
	custom_family_2 varchar NULL,
	custom_class_1 varchar NULL,
	custom_class_2 varchar NULL,
	pre_price int2 DEFAULT 0 NULL,
	price_lock int2 DEFAULT 0 NULL,
	zone_exception int2 DEFAULT 0 NULL,
	derived_uom varchar(50) NULL,
	derived_size float8 NULL,
	price float8 NULL,
	base_price float8 NULL,
	price_difference float8 NULL,
	sales_units float8 NULL,
	revenue float8 NULL,
	gross_margin_dollar float8 NULL,
	gross_margin_percentage float8 NULL,
	asp float8 NULL,
	aum float8 NULL,
	promotion_applied float8 NULL,
	competitor_price json NULL,
	competitor_price_difference_dollar json NULL,
	competitor_price_difference_percentage json NULL,
	base_price_per_unit float8 NULL,
	price_change_reason text NULL,
	rules_exception jsonb NULL,
	rules_followed int4 NULL,
	old_cost float8 NULL,
	cost_changes float8 NULL,
	new_margin float8 NULL,
	"source" varchar(50) NULL,
	connection_id int4 NULL,
	product_attributes jsonb NULL,
	competitor_mode json NULL,
	competitor_comparison json NULL,
	competitor_name json NULL,
	baseline_sales float8 NULL,
	baseline_revenue float8 NULL,
	baseline_margin_dollar float8 NULL,
	baseline_margin_percentage float8 NULL,
	forecast_confidence varchar(50) NULL,
	contribution_margin_dollar float8 NULL,
	contribution_margin_percentage float8 NULL,
	baseline_contribution_margin_dollar float8 NULL,
	baseline_contribution_margin_percentage float8 NULL,
	store_ids _int4 NULL,
	product_ids _int4 NULL,
	distinct_prices _float8 NULL,
	price_points _text NULL,
	actuals_sales_units float8 NULL,
	actuals_revenue float8 NULL,
	actuals_gross_margin_dollar float8 NULL,
	actuals_gross_margin_percentage float8 NULL,
	actuals_asp float8 NULL,
	actuals_aum float8 NULL,
	snapshot_timestamp timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	approval_status varchar(50) DEFAULT 'approved'::character varying NULL,
	approved_by varchar(255) NULL,
	approval_date timestamptz NULL,
	snapshot_version int4 DEFAULT 1 NULL,
	CONSTRAINT bp_price_reco_current_last_approved_snapshot_pkey PRIMARY KEY (id, strategy_id),
	CONSTRAINT uq_bp_price_reco_current_last_approved_snapshot_unique UNIQUE (strategy_id, product_id, store_id, segment_id, channel_id, snapshot_version)
)
PARTITION BY LIST (strategy_id);

CREATE INDEX idx_bp_price_reco_current_last_approved_snapshot_approval_statu ON  base_pricing.bp_price_reco_current_last_approved_snapshot USING btree (approval_status);
CREATE INDEX idx_bp_price_reco_current_last_approved_snapshot_product_store ON  base_pricing.bp_price_reco_current_last_approved_snapshot USING btree (product_id, store_id, segment_id);
CREATE INDEX idx_bp_price_reco_current_last_approved_snapshot_product_store_ ON  base_pricing.bp_price_reco_current_last_approved_snapshot USING btree (strategy_id, product_id, store_id, segment_id);
CREATE INDEX idx_bp_price_reco_current_last_approved_snapshot_strategy ON  base_pricing.bp_price_reco_current_last_approved_snapshot USING btree (strategy_id);
CREATE INDEX idx_bp_price_reco_current_last_approved_snapshot_strategy_chann ON  base_pricing.bp_price_reco_current_last_approved_snapshot USING btree (strategy_id, channel_id);
CREATE INDEX idx_bp_price_reco_current_last_approved_snapshot_timestamp ON  base_pricing.bp_price_reco_current_last_approved_snapshot USING btree (snapshot_timestamp);