import { makeStyles } from "@mui/styles";

export const vpaStoreCardStyles = makeStyles(() => ({
  mainGridCardContainer: {
    display: "flex",
    flexDirection: "column",
    background: "#FFFFFF",
    padding: "12px 15px 11px 15px",
    borderRadius: "8px",
    "& .inv-card-view-header": {
      marginBottom: "26px", // basically 16 only ubt have the absolute position component
      display: "flex",
      "& .inv-card-view-header-title": {
        color: "#0D152C",
        fontFamily: "Manrope",
        fontSize: "14px",
        fontWeight: 700,
        lineHeight: "21px",
      },
      "& .inv-card-button-render": {
        width: "calc(100% - 32px)",
        display: "flex",
        justifyContent: "center",
        position: "absolute",
      },
    },
  },
  cardGridStoreTransfer: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "24px",
    padding: "1px",
    "&::-webkit-scrollbar": {
      display: "none"
    }
  },
  cardStoreTransfer: {
    background: "#ffffff",
    borderRadius: "8px",
    padding: "16px 24px",
    boxShadow: "0 0 4px rgba(0, 0, 0, 0.12)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    height: "241px",
    minWidth: 0,
    overflow: "hidden",
  },
  cardHeaderStoreTransfer: {
    display: "flex",
    gap: "24px",
    padding: "8px 8px 16px 8px",
    borderBottom: "1px solid #D9DDE7",
    alignSelf: "stretch",
    minWidth: 0,
  },
  headerRowStoreTransfer: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    flexShrink: 0,
    height: "37px",
    "&:first-child": {
      flexGrow: 1,
      flexShrink: 1,
      minWidth: 0,
    },
  },
  headerLabelStoreTransfer: {
    color: "#7A8294",
    fontFamily: "Manrope",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "16px",
  },
  headerValueStoreTransfer: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "21px",
  },
  headerValuePlanNameStoreTransfer: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "21px",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    width: "100%",
  },
  headerValueCreatedByStoreTransfer: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "21px",
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  },
  cardBodyStoreTransfer: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    padding: "0 8px",
  },
  bodyRowStoreTransfer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  bodyLabelStoreTransfer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#60697D",
    fontFamily: "Manrope",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 600,
    lineHeight: "24px",
    "&::before": {
      content: "''",
      width: 0,
      height: "12px",
      borderLeft: "1px solid #D9DDE7",
      display: "block",
    },
  },
  bodyValueStoreTransfer: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "24px",
  },
  tagsContainerStoreTransfer: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 800,
    lineHeight: "24px",
  },
  cardFooterStoreTransfer: {
    display: "flex",
    justifyContent: "flex-start",
    paddingTop: 0,
  },
  releaseDateStoreTransfer: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "14px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "24px",
    marginRight: 0,
  },
  releaseTimeStoreTransfer: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "12px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "16px",
  },
  transparentStickyFooterStoreTransfer: {
    position: "fixed",
    bottom: 0,
    left: "60px",
    width: "calc(100% - 60px)",
    height: "24px",
    backgroundColor: "#EFF2FA",
    zIndex: 10,
  },
}));
