export const getStyles = (messagesLength) => ({
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  modal: {
    width: "600px",
    height: messagesLength > 0 ? "70vh" : "auto",
    background: "#fff",
    borderRadius: "12px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    padding: "16px",
    borderBottom: "1px solid #eee",
  },
  title: {
    fontSize: "18px",
    fontWeight: "600",
  },
  subtitle: {
    fontSize: "13px",
    color: "#777",
  },
  close: {
    cursor: "pointer",
    fontSize: "18px",
  },
  section: {
    padding: "16px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  sectionTitle: {
    marginBottom: "10px",
    fontWeight: "500",
  },
  question: {
    background: "#f5f7fb",
    padding: "10px",
    borderRadius: "8px",
    marginBottom: "8px",
    cursor: "pointer",
  },
  footer: {
    display: "flex",
    gap: "10px",
    padding: "16px",
    borderTop: "1px solid #eee",
  },
  input: {
    flex: 1,
    padding: "10px",
    borderRadius: "8px",
    border: "1px solid #ccc",
  },
  messagesContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  messageBlock: {
    marginBottom: "20px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  questionHeader: {
    fontSize: "16px",
    fontWeight: "500",
    marginBottom: "10px",
  },
  tabs: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "10px",
  },
  tab: {
    padding: "6px 12px",
    borderRadius: "6px",
    background: "#f0f0f0",
    cursor: "pointer",
  },
  activeTab: {
    padding: "6px 12px",
    borderRadius: "6px",
    background: "#e0e7ff",
    fontWeight: "600",
    cursor: "pointer",
  },
  action: {
    cursor: "pointer",
    color: "#666",
  },
  tableWrapper: {
    border: "1px solid #ddd",
    borderRadius: "8px",
    flex: 1,
    overflow: "auto",
    minHeight: "300px",
  },
  table: {
    width: "100%",
    minWidth: "700px",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "10px",
    background: "#f5f5f5",
    borderBottom: "1px solid #ccc",
    borderRight: "1px solid #e0e0e0",
    fontWeight: "600",
  },
  td: {
    padding: "10px",
    borderBottom: "1px solid #eee",
    borderRight: "1px solid #f0f0f0",
    fontSize: "14px",
  },
  textContainer: {
    border: "1px solid #ddd",
    borderRadius: "8px",
    padding: "12px",
    fontSize: "13px",
    lineHeight: "1.6",
    background: "#fafafa",
    overflow: "auto",
    maxHeight: "300px",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  textHeaderRow: {
  display: "flex",
  justifyContent: "flex-end",
  alignItems: "center",
  marginBottom: "10px",
  gap: "8px",
},

extractLabel: {
  fontSize: "12px",
  color: "#666",
  fontWeight: 500,
},

dropdown: {
  padding: "6px 10px",
  borderRadius: "6px",
  border: "1px solid #ccc",
  cursor: "pointer",
},
});