--liquibase formatted sql
--changeset abhimanyu.sheoran@impactanalytics.co:oor_store_rnd_add stripComments:false splitStatements:false context:Release_1_0 ignore:false labels:oor_store_rnd_add
--comment: schema for oms_orders_recommended_store_rnd_add

CREATE SEQUENCE inventory_smart.oms_orders_recommended_store_rnd_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

CREATE TABLE IF NOT EXISTS inventory_smart.oms_orders_recommended_store_rnd (
	fiscal_year_week int4 NULL,
	fiscal_year_month int4 NULL,
	fiscal_year int4 NULL,
	fiscal_year_quarter int4 NULL,
	week_start_date date NULL,
	"month" text NULL,
	id int4 DEFAULT nextval('inventory_smart.oms_orders_recommended_store_rnd_id_seq'::regclass) NOT NULL,
	order_gen_type text NULL,
	store_code text NULL,
	channel text NULL,
	"size" text NULL,
	"style" text NULL,
	article text NULL,
	order_type text NULL,
	flow_id text NULL,
	vendor_code text NULL,
	vendor_name text NULL,
	grade text NULL,
	order_quantity int4 NULL,
	order_cost float4 NULL,
	unit_cost float4 NULL,
	raw_roq int4 NULL,
	roq_unconstrained_eaches int4 NULL,
	roq_constrained int4 NULL,
	immd_roq text NULL,
	min_order_quantity_shipment int4 NULL,
	max_order_quantity_shipment int4 NULL,
	min_order_quantity_sku int4 NULL,
	max_order_quantity_sku int4 NULL,
	min_order_quantity_style int4 NULL,
	max_order_quantity_style int4 NULL,
	order_to_po_processing_time int4 NULL,
	lead_time int4 NULL,
	order_placement_date date NULL,
	order_placement_recom_date date NULL,
	order_multiple int4 NULL,
	editable_expected_receipt_date date NULL,
	expected_receipt_date date NULL,
	order_status_id int4 NULL,
	rop date NULL,
	rop_ideal date NULL,
	effective_lead_time int4 NULL,
	inventory_hold int4 NULL,
	created_by int4 NULL,
	created_at timestamptz NULL,
	updated_by int4 NULL,
	updated_at timestamptz NULL,
	approve_by_date date NULL,
	is_deleted bool NULL,
	is_resolved text NULL,
	recom_receipt_date date NULL,
	create_by_date date NULL,
	lost_sales_agg int4 NULL,
	inventory_deficit_agg int4 NULL,
	elt_projected_bop int4 NULL,
	elt_projected_safety_stock int4 NULL,
	lost_sales_agg_1 int4 NULL,
	forecasted_sales float4 NULL,
	target_wos int4 NULL,
	lost_sales_agg_2 int4 NULL,
	excess_inv int4 NULL,
	store_counts int4 NULL,
	store_tier text NULL,
	ia_shipment_order_quantity int4 NULL,
	mode_shipment text NULL,
	order_reason text NULL,
	order_batch_name text NULL,
	order_group_id text NULL,
	vendor_moq_adjusted_roq int4 NULL,
	shipment_optimized_roq int4 NULL,
	size_ratio_store float4 NULL,
	size_ratio_size float4 NULL,
	pack_config float4 NULL,
	pack_id int4 NULL,
	order_quantity_eaches float4 NULL,
	raw_roq_eaches int4 NULL,
	roq_constrained_eaches int4 NULL,
	elt_projected_store_inv int4 NULL,
	editable_effective_lead_time int4 NULL,
	edited_mode_shipment text NULL,
	on_order_quantity int4 NULL,
	elt_sales_forecast_twos int4 NULL,
	landing_cost int4 NULL,
	product_code text NULL,
	store_min int4 NULL,
	store_max int4 NULL,
	store_wos int4 NULL,
	"comment" varchar NULL,
	roq_unconstrained float4 NULL,
	projected_delivery_date date NULL,
	l0_name varchar NULL,
	l1_name varchar NULL,
	l2_name varchar NULL,
	l3_name varchar NULL,
	l5_name varchar NULL,
	l6_name varchar NULL,
	style_name varchar NULL,
	store_name varchar NULL,
	region_name varchar NULL,
	sales_org_name varchar NULL,
	"cost" float8 NULL,
	"ordering" varchar NULL,
	ordering_flag varchar NULL
);