export const CUSTOMFILTERS = [
  {
    column_name: "default_store_groups_available",
    default_value: null,
    dimension: "custom",
    display_type: "dropdown",
    fc_code: 100,
    filter_keyword: "default_store_groups_available",
    is_mandatory: false,
    is_multiple_selection: false,
    label: "Default Store Group",
    level: 2,
    type: "non-cascaded",
    initialData: [
      { label: "True", id: true, value: true },
      { label: "False", id: false, value: false },
    ],
  },
  {
    column_name: "default_dcs_available",
    default_value: null,
    dimension: "custom",
    display_type: "dropdown",
    fc_code: 100,
    filter_keyword: "default_dcs_available",
    is_mandatory: false,
    is_multiple_selection: false,
    label: "Default DC",
    level: 2,
    type: "non-cascaded",
    initialData: [
      { label: "True", id: true, value: true },
      { label: "False", id: false, value: false },
    ],
  },
  {
    column_name: "product_profile_mapped_available",
    default_value: null,
    dimension: "custom",
    display_type: "dropdown",
    fc_code: 100,
    filter_keyword: "product_profile_mapped_available",
    is_mandatory: false,
    is_multiple_selection: false,
    label: "Product Profile Mapped",
    level: 2,
    type: "non-cascaded",
    initialData: [
      { label: "True", id: true, value: true },
      { label: "False", id: false, value: false },
    ],
  },
];
