--liquibase formatted sql
--changeset liquibase:product_master_new stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for product_master_new
CREATE TABLE visual_line_planning.product_master_new (
	product_code varchar(255) NOT NULL,
	product_description text NULL,
	article_season_name varchar(255) NULL,
	article_season_year int4 NULL,
	a0_name text NULL,
	l0_name varchar(255) NULL,
	brand_id int4 NULL,
	l4_name varchar(255) NULL,
	buyer_name varchar(255) NULL,
	category_id int4 NULL,
	category_name varchar(255) NULL,
	a1_name text NULL,
	colour_char_name varchar(255) NULL,
	colour_internal_char int4 NULL,
	"cost" numeric(10, 2) NULL,
	cross_site_status_id varchar(50) NULL,
	cross_site_status_name varchar(255) NULL,
	generic_article_id int8 NOT NULL,
	generic_article_name varchar(255) NULL,
	info_capacity text NULL,
	order_unit varchar(50) NULL,
	unit_of_issue varchar(50) NULL,
	info_capsule text NULL,
	info_capsule_description text NULL,
	info_design text NULL,
	info_design_description text NULL,
	a2_name text NULL,
	info_lifecycle_description text NULL,
	info_material_description text NULL,
	info_pattern_description text NULL,
	info_range_description text NULL,
	info_set_description text NULL,
	info_watts_description text NULL,
	merchandise_category_id int8 NULL,
	merchandise_category_name varchar(255) NULL,
	purchasing_group_id varchar(50) NULL,
	price numeric(10, 2) NULL,
	size_char_name varchar(255) NULL,
	sub_category_id int4 NULL,
	sub_category_name varchar(255) NULL,
	vendor_article_numb varchar(255) NULL,
	vendor_id int4 NULL,
	vendor_name varchar(255) NULL,
	client_active_flag bool NULL,
	replen_flag bool NULL,
	local_flag bool NULL,
	dropship_flag bool NULL,
	l1_name varchar(255) NULL,
	l2_name varchar(255) NULL,
	l3_name varchar(255) NULL,
	l5_name varchar(255) NULL,
	l6_name varchar(255) NULL,
	style_name varchar(255) NULL,
	article varchar(255) NULL,
	order_counter int4 NULL,
	replen_counter int4 NULL,
	parent_id int8 NULL,
	product_name text NULL,
	original_price numeric(10, 2) NULL,
	clearance bool NULL,
	receipt_date date NULL,
	product_bucket_code numeric NULL,
	sales_org_name varchar(255) NULL,
	active bool NULL,
	l5_display_name varchar(255) NULL,
	air int4 NULL,
	auc int4 NULL,
	"size" varchar(50) NULL,
	color varchar(50) NULL,
	info_lifecycle varchar(50) NULL,
	image_url text NULL,
	launch_date date NULL,
	exit_date date NULL,
	column74 varchar(50) NULL,
	column75 varchar(50) NULL,
	CONSTRAINT product_master_new_pkey PRIMARY KEY (product_code)
);