--liquibase formatted sql
--     
--      #######  ##    ## ##       ##    ##          ###    ########  ########  ######## ##    ## ########   ######  
--     ##     ## ###   ## ##        ##  ##          ## ##   ##     ## ##     ## ##       ###   ## ##     ## ##    ## 
--     ##     ## ####  ## ##         ####          ##   ##  ##     ## ##     ## ##       ####  ## ##     ## ##       
--     ##     ## ## ## ## ##          ##          ##     ## ########  ########  ######   ## ## ## ##     ##  ######  
--     ##     ## ##  #### ##          ##          ######### ##        ##        ##       ##  #### ##     ##       ## 
--     ##     ## ##   ### ##          ##          ##     ## ##        ##        ##       ##   ### ##     ## ##    ## 
--      #######  ##    ## ########    ##          ##     ## ##        ##        ######## ##    ## ########   ######  
--                                                                                     
--     ##    ##  #######        ########  ########  ##        ######                                                 
--     ###   ## ##     ##       ##     ## ##     ## ##       ##    ##                                                
--     ####  ## ##     ##       ##     ## ##     ## ##       ##                                                      
--     ## ## ## ##     ##       ##     ## ##     ## ##        ######                                                 
--     ##  #### ##     ##       ##     ## ##     ## ##             ##                                                
--     ##   ### ##     ##       ##     ## ##     ## ##       ##    ##                                                
--     ##    ##  #######        ########  ########  ########  ######                                                 
--  

--changeset ashish@impactanalytics.co:reset_custom_migration stripComments:false splitStatements:false context:Release_1 labels:Custom_Migration_Technique
--comment: initial changeset for custom_migration
DELETE FROM liquibase.databasechangelog where filename like '%custom_migration.sql%';

--changeset raj.mohan@impactanalytics.co:rem_user_preference_table_config Comments:false splitStatements:false context:Release_1 labels:remove_uahmstripComments
--comment: rem_user_preference_table_config
DELETE FROM global.user_preference_table_config where true;

--changeset kaustubh.gupta@impactanalytics.co:inactive_default_removal stripComments:false splitStatements:false context:Release_1 labels:inactive_default_removal
--comment: changeset for inactive_default_removal MTP-135939
create table if not exists inventory_smart.rcl_constraint_master_bkp_20260401 as
select * from inventory_smart.rcl_constraint_master;

create table if not exists inventory_smart.rcl_constraint_master_rule_bkp_20260401 as
select * from inventory_smart.rcl_constraint_master_rule;

delete from inventory_smart.rcl_constraint_master r
using inventory_smart.rcl_constraint_master_rule b 
where 1=1
and r.rule_code = b.rule_code
and r.rcl_code = 5
and rcl_dimension->>'primary_trait_desc' in (
'2010 Bike Week',
'2018 KY Derby',
'43 Store Test - Cars',
'Access Apr FY14',
'Access Mar FY14',
'Access May FY14',
'Accessories Military',
'Beach Story FY18',
'Brompton__ia_char_13Langley Bin',
'Buckeyes',
'Butterflies',
'CB 50TH ANNIVERSARY',
'CB Glitter Globe',
'COMMONWEALTH BIN',
'Car Stickers',
'Christmas Food FY07',
'Christmas Vinyl',
'Classic Collections',
'Cline Dropship',
'Collegiate Rockers',
'Dec Jwlry Test FY09',
'Demdaco Ornaments',
'Dilly Dally',
'Disney Vinyl',
'Do Not Use 701505',
'Dress Up',
'EC only item-Theme',
'ECOMM Avanti',
'EVDY Animal Candles',
'EVDY Bath Bombs',
'EVDY Blind Bags',
'EVDY CBOCS',
'EVDY Candle Access',
'EVDY Chesapke Herit',
'EVDY Coloring Books',
'EVDY CreateaBracelet',
'EVDY Deco Fragrance',
'EVDY Decorware',
'EVDY Frag nonYK__ia_char_03WW',
'EVDY FunZone Car',
'EVDY INSP Jewelry',
'EVDY JFL Puzzles',
'EVDY LED Candles',
'EVDY Leggings',
'EVDY Necklace Charms',
'EVDY Paddywax',
'EVDY Sentiments Cndl',
'EVDY Swan Creek',
'EVDY Tapers',
'EVDY Woodwk Car Frag',
'Everyday Watch Prog',
'Exclusive CD__ia_char_01s',
'FY 15 Watermelon Bin',
'FY08 EG',
'FY09 Cmas GCard Hdr',
'FY09 Elegant Rooster',
'FY09 Gingermint',
'FY09 MD Jwld Gftbls',
'FY09 Masqrade Party',
'FY09 Peace on Earth',
'FY09 Road Trip',
'FY10 AMERICAN HERITG',
'FY10 Christmas Food',
'FY10 Cmas CLG',
'FY10 Fall CLG',
'FY10 HOLIDAY GARDEN',
'FY10 Harvest Food',
'FY10 Inspiration',
'FY10 Regional Spring',
'FY10 Road Trip',
'FY11 Amer Heritage',
'FY11 Best Friends',
'FY11 Celebrate',
'FY11 Christmas Food',
'FY11 Fall Great Gfts',
'FY11 Halloween Food',
'FY11 In Bloom',
'FY11 Jwld Gifts Mar',
'FY11 Life isa Garden',
'FY11 Spring RGL',
'FY12 2 CUTE 2 SPOOK',
'FY12 American Pride',
'FY12 Colleg Opp Buy',
'FY12 Fall Grt Gifts',
'FY12 Inspiration',
'FY12 Jwld Gft Aug',
'FY12 Mful Messages',
'FY12 Mltry Mdl Test',
'FY12 Nature__ia_char_01s Garden',
'FY12 Roadtrip',
'FY12 Simply White',
'FY12 Sprg Regional',
'FY12 Summer Fun',
'FY13 American Pride',
'FY13 Backyard BBQ',
'FY13 Bacon',
'FY13 Blush',
'FY13 BlushTransition',
'FY13 CMA',
'FY13 Christmas Food',
'FY13 Cmas CDs',
'FY13 Coastal',
'FY13 Duck Cmndr May',
'FY13 Easter Treasure',
'FY13 Eye Want Candy',
'FY13 Fall Adult GG',
'FY13 Fall Collegiate',
'FY13 Fall Kids GG',
'FY13 Family Night',
'FY13 Gift Card',
'FY13 Grn Apple Food',
'FY13 Halloween Hoot',
'FY13 Harvest Food',
'FY13 Inspiration',
'FY13 Kids Road Trip',
'FY13 Mens',
'FY13 Milt ornment',
'FY13 Peacock',
'FY13 Regional',
'FY13 Rooster',
'FY13 Snow Friends',
'FY13 Spring Food',
'FY13 Summer Fun',
'FY13 Sundrenched',
'FY13 Sweets __ia_char_13 Treats',
'FY13 Tr Tops Glisten',
'FY13 Woodland Gardn',
'FY14 Access Hutch',
'FY14 Back2Preschool',
'FY14 Bee Bright',
'FY14 Bowl Games',
'FY14 Calendars',
'FY14 Christmas Food',
'FY14 Cmas CDs',
'FY14 Cmas2Remember',
'FY14 Coke Oct',
'FY14 Coral Reef',
'FY14 Duck Commader',
'FY14 Easter Food',
'FY14 FIFA',
'FY14 FINAL 4',
'FY14 Floral Stchwork',
'FY14 Frog Trouble',
'FY14 Grandmas Pantry',
'FY14 Great Gifts',
'FY14 Green Aple Food',
'FY14 HW Avanti Cards',
'FY14 Halloween',
'FY14 Halloween Food',
'FY14 In Full Bloom',
'FY14 Inspiration',
'FY14 Jingle __ia_char_13 Mingle',
'FY14 Knotical',
'FY14 Mad for Plaid',
'FY14 Mens',
'FY14 Military',
'FY14 Nesting Garden',
'FY14 Peacock',
'FY14 Polka Dots',
'FY14 Porch Living',
'FY14 Sanctuary Grdn',
'FY14 Sock Monkey',
'FY14 Spring Mens',
'FY14 Summer Cards',
'FY14 Under the Stars',
'FY14 Valentines',
'FY14 Winter White',
'FY14S Hat Rack',
'FY15 Apple',
'FY15 Beverages',
'FY15 Blush __ia_char_13 Grey',
'FY15 Cars__ia_char_13Trucks',
'FY15 Choc__ia_char_03Coffee__ia_char_03Tea',
'FY15 Cmas Collegiate',
'FY15 Cmas Food',
'FY15 Coastal',
'FY15 Coral',
'FY15 Country Style',
'FY15 Creatures Cmfrt',
'FY15 Garden 1',
'FY15 Grandma Pantry',
'FY15 Green with Envy',
'FY15 Grn Apple Food',
'FY15 HGR Store',
'FY15 HVST__ia_char_03Ap Vest',
'FY15 Hanukkah',
'FY15 Holiday Larry',
'FY15 Hween Food',
'FY15 Inspiration',
'FY15 Knotical',
'FY15 MLB',
'FY15 Metal Toys',
'FY15 Oct Gloves',
'FY15 Red',
'FY15 Riding Country',
'FY15 Rooster',
'FY15 Safari',
'FY15 SeasonalTidings',
'FY15 Shades of Blue',
'FY15 Sprng Insp',
'FY15 Winter White',
'FY15 Womens Scarf',
'FY15 __ia_char_1010 and Under',
'FY16 Apple',
'FY16 Calendars',
'FY16 Camo',
'FY16 Coastal',
'FY16 Easter Endcap',
'FY16 Fall Boutique',
'FY16 Fall Peacock',
'FY16 Final 4',
'FY16 Floral Sttchwrk',
'FY16 Fur __ia_char_13 Fringe',
'FY16 Garage',
'FY16 Grandmas Pantry',
'FY16 Great Gifts',
'FY16 Green Apple Bin',
'FY16 HANNUKAH',
'FY16 Halloween',
'FY16 Halloween Food',
'FY16 Harvest',
'FY16 In Full Bloom',
'FY16 Lake',
'FY16 Lemon Bin',
'FY16 Metallic',
'FY16 NHL',
'FY16 Nesting Garden',
'FY16 Nov Opp Jewelry',
'FY16 Spring Boutique',
'FY16 Sprng Insp',
'FY17  Winter Insp',
'FY17 Biketoberfest',
'FY17 Bowl Games',
'FY17 Breakfst Endcap',
'FY17 CMA Fest',
'FY17 CWS',
'FY17 Calendars',
'FY17 Christmas Ty',
'FY17 Cmas Endcap',
'FY17 Daytona 500',
'FY17 Easter',
'FY17 Easter Endcap',
'FY17 Easter Ty',
'FY17 Elegant',
'FY17 Final 4',
'FY17 Gift Card Hldr',
'FY17 Halloween Food',
'FY17 Halloween Ty',
'FY17 Hanukkah',
'FY17 Indy 500',
'FY17 KY Derby',
'FY17 Last Min Gifts',
'FY17 Stanley Cup',
'FY17 Summer Endcap',
'FY17 Traditional',
'FY17 Valentine Ty',
'FY17 Winter Lodge',
'FY17 World Series',
'FY17Spg GiftCrd Hldr',
'FY18 BIN ORNAMENTS',
'FY18 Bike Week',
'FY18 Bowl Games',
'FY18 CMA Fest',
'FY18 CWS',
'FY18 Christmas Ty',
'FY18 Cmas L',
'FY18 Coke Zero 400',
'FY18 Cup Playoffs',
'FY18 Daytona 500',
'FY18 Easter Ty',
'FY18 Fall Insp',
'FY18 Fball Champs',
'FY18 Final 4',
'FY18 Gift Card Hldr',
'FY18 Halloween Ty',
'FY18 Indy 500',
'FY18 KY Derby',
'FY18 MLB',
'FY18 Mardi Gras',
'FY18 Nshvl Sounds',
'FY18 Q3 Bow Sneaker',
'FY18 Slippers Opp',
'FY18 Sprg Insp',
'FY18 Stanley Cup',
'FY18 Super Bowl',
'FY18 Veterans Day',
'FY18 World Series',
'FY18 brkfast endcap',
'FY18 famfun endcap',
'FY18 summer endcap',
'FY18Sp NovltyBathBin',
'FY19 Aug Kids ACC',
'FY19 Balloonfest',
'FY19 Bball Champs',
'FY19 Bball Conf Chmp',
'FY19 Bike Week',
'FY19 Biketoberfest',
'FY19 Bracelet Buy',
'FY19 Burts Holiday',
'FY19 Christmas Ty',
'FY19 Cmas L',
'FY19 Daytona 500',
'FY19 Easter Ty',
'FY19 Final 4',
'FY19 GftCard Hldr',
'FY19 GltrBoot KeyBuy',
'FY19 Halloween Ty',
'FY19 Hween Endcap',
'FY19 Indy 500',
'FY19 KY Derby',
'FY19 Natl Champs',
'FY19 Nville Sounds',
'FY19 SB Champs',
'FY19 Super Bowl 53',
'FY19 TY Opp Buy',
'FY19 Valentine Ty',
'FY19 WS Champs',
'FY1920 Jul Kids Acc',
'FY1920 Jun Wmns Acc',
'FY20 Badger Bug__ia_char_03Sun',
'FY20 Burts Holiday',
'FY20 CMAS STOCKINGS',
'FY20 Cmas Plush Bin',
'FY20 Easter TY',
'FY20 Feb Wmns Acc',
'FY20 Frozen Watch',
'FY20 GiftCard Boxes',
'FY20 Gloves',
'FY20 GltrBoot KeyBuy',
'FY20 Knotical',
'FY20 Lindt Contest',
'FY20 Novelty Bath',
'FY20 Oct Wmns Acc',
'FY20 Opp Fall Toys',
'FY20 Sprg Cndl Hutch',
'FY20 Spring Toys',
'FY20 TY Halloween',
'FY20 Ty Slipper Buy',
'FY20 Val endcap',
'FY20 Valentines TY',
'FY20 Wraps',
'FY20 cmas L',
'FY20 fun wfood endcp',
'FY20 hween endcap',
'FY2021 Jul Wmns Acc',
'FY21 Burts Holiday',
'FY21 Christmas Plush',
'FY21 Cmas Food L',
'FY21 Cmas Stockings',
'FY21 Dec Wmns Acc',
'FY21 Easter Food L',
'FY21 Easter Plush',
'FY21 FunwFood Endcap',
'FY21 Hearth Decor',
'FY21 Jan Wmns Acc',
'FY21 Lindt Contest',
'FY21 Mr Christmas',
'FY21 Nov Fash Fixt',
'FY21 S__ia_char_03S STORE DECOR',
'FY21 Sep Wmns Acc',
'FY21 Summer Endcap',
'FY21 Ty Halloween',
'FY2122 Jul Wmns Acc',
'FY22 Al Fresco',
'FY22 CMAS STOCKINGS',
'FY22 Chimes__ia_char_03Leaners',
'FY22 Christmas Plush',
'FY22 Fall Toys',
'FY22 Halloween Plush',
'FY22 M-AT App Buy',
'FY22 Mr Cmas Opp Buy',
'FY22 Nov Wmns Acc',
'FY22 Q4 WW Contest',
'FY22 Sep Kids Acc',
'FY22 Sep Wmns Acc',
'FY22 Summer Toys',
'FY22 cmas food L',
'FY22 easter food L',
'FY22 hween endcap',
'FY23 CMAS ECOM',
'FY23 Christmas Plush',
'FY23 Easter L',
'FY23 SPRING TOWELS',
'FY23 Spring Toys',
'FY24 Jewelry Opp Buy',
'Fash Fix Aug FY14',
'Fash Fixt Aug FY15',
'Fash Fixt Aug FY16',
'Fash Fixt Aug FY17',
'Fash Fixt Feb FY15',
'Fash Fixt Feb FY16',
'Fash Fixt May FY15',
'Fash Fixt May FY16',
'Fash Fixt May FY17',
'Fash Fixt Nov FY15',
'Fash Fixt Nov FY16',
'Fash Fixt Nov FY17',
'Fash Fixt Nov FY19',
'Fashion Fix Feb FY14',
'Fashion Fix May FY14',
'Fashion Fix Nov FY13',
'Hershey Bath',
'JOHN DEERE',
'Jelly Belly',
'Kid Acc April FY18',
'Kid Acc June FY18__ia_char_0319',
'Kids Ac Jul FY13FY14',
'Kids Ac Jul FY14FY15',
'Kids Ac Jul FY15FY16',
'Kids Ac Jun FY14FY15',
'Kids Ac Jun FY15FY16',
'Kids Acc Apr FY15',
'Kids Acc Apr FY16',
'Kids Acc April FY17',
'Kids Acc Aug FY16',
'Kids Acc Aug FY18',
'Kids Acc Dec FY15',
'Kids Acc Dec FY16',
'Kids Acc Dec FY17',
'Kids Acc Dec FY18',
'Kids Acc Dec FY19',
'Kids Acc Feb FY15',
'Kids Acc Feb FY16',
'Kids Acc Feb FY17',
'Kids Acc Jan FY15',
'Kids Acc Jan FY16',
'Kids Acc Jan FY17',
'Kids Acc Jan FY18',
'Kids Acc Jul FY18__ia_char_0319',
'Kids Acc Mar FY15',
'Kids Acc Mar FY16',
'Kids Acc Mar FY17',
'Kids Acc Mar FY18',
'Kids Acc May FY16',
'Kids Acc May FY17',
'Kids Acc May FY18',
'Kids Acc Nov FY15',
'Kids Acc Nov FY16',
'Kids Acc Nov FY17',
'Kids Acc Oct FY15',
'Kids Acc Oct FY16',
'Kids Acc Oct FY17',
'Kids Acc Sep FY15',
'Kids Acc Sep FY16',
'Kids Acc Sept FY17',
'Kids Acc Sept FY18',
'Kids Acc Sept FY19',
'Kids Acces Sept FY14',
'Kids Access Apr FY14',
'Kids Access Aug FY14',
'Kids Access Dec FY14',
'Kids Access Feb FY14',
'Kids Access Jan FY14',
'Kids Access Mar FY13',
'Kids Access Mar FY14',
'Kids Access May FY13',
'Kids Access May FY14',
'Kids Access Oct FY14',
'Kids Ap Jun FY15FY16',
'Kids Ap Jun FY16FY17',
'Kids App Apr FY15',
'Kids App Aug FY15',
'Kids App Aug FY16',
'Kids App Dec FY16',
'Kids App Feb FY16',
'Kids App Jan FY15',
'Kids App Jan FY16',
'Kids App Jan FY17',
'Kids App Mar FY15',
'Kids App Mar FY16',
'Kids App Mar FY17',
'Kids App May FY15',
'Kids App May FY16',
'Kids App Nov FY16',
'Kids App Nov FY17',
'Kids App Oct FY15',
'Kids App Oct FY17',
'Kids App Sep FY16',
'Kids App Sept FY17',
'Kids Mar FY12',
'Kids March FY11',
'Kids Nov Access FY13',
'Kids Sept FY12',
'Little Golden Books',
'Made in USA Tee FY12',
'Media Boxed Set',
'Mens Hat Fxtr FY10',
'Military Rockers',
'Motion Plush',
'Mr. Cmas VendorNet',
'Opry CD__ia_char_01s',
'Q1 Woodwick promo',
'Q2 Woodwick promo',
'Q2.18 Food Frsh Toy',
'Q2.18 India Bags',
'Q2.18 Italy Access',
'Q2.18 Str Wrs Tshirt',
'Q2.18 Swarovski',
'Q2.18 mini sayings',
'Q2.18 tervis tumbler',
'Q3.18 Lip Keychain',
'Q3.18 Woodwick Cameo',
'Q4.18 Food TicTac',
'Q4.18 Woodwick Cndl',
'Remodel Test 50',
'Seas Chspk Herit Fal',
'Seas Chspk Herit Spr',
'Seas Yankee Car Fall',
'Sep Jwl Fixture FY10',
'Special Buy Rockers',
'Thin Sticks',
'Various Accessories',
'WW FY20 Q2 Promo',
'Wmn Acc Oct FY12',
'Wmn Oct FY12',
'Wmns Ac Jun FY15FY16',
'Wmns Ac Jun FY16FY17',
'Wmns Ap Jun FY15FY16',
'Wmns Ap Jun FY16FY17',
'Wmns Tees FY16 Trans',
'Women Acc April FY17',
'Womens Acc Apr FY16',
'Womens Acc Aug FY15',
'Womens Acc Aug FY16',
'Womens Acc Feb FY15',
'Womens Acc Feb FY17',
'Womens Acc June FY17',
'Womens Acc Mar FY15',
'Womens Acc Mar FY16',
'Womens Acc May FY19',
'Womens Acc Nov FY16',
'Womens Acc Nov FY17',
'Womens Acc Nov FY18',
'Womens Acc Nov FY19',
'Womens Acc Oct FY16',
'Womens Acc Oct FY17',
'Womens Acc Oct FY19',
'Womens Acc Sep FY15',
'Womens Acc Sep FY16',
'Womens Acc Sept FY17',
'Womens Acc Sept FY18',
'Womens App Apr FY16',
'Womens App Aug FY16',
'Womens App Dec FY16',
'Womens App Dec FY17',
'Womens App Feb FY16',
'Womens App Feb FY17',
'Womens App Mar FY16',
'Womens App Mar FY17',
'Womens App May FY15',
'Womens App May FY16',
'Womens App Nov FY16',
'Womens App Nov FY17',
'Womens App Oct FY16',
'Womens App Oct FY17',
'Womens Apr FY14',
'Womens Mar FY14',
'Womens Wraps FY17',
'Wreaths Acrs America',
'Yankee Q3 Promo',
'__ia_char_1405 Cmas Season Eleg',
'__ia_char_1405 Cmas in  Woods',
'__ia_char_14American Legends',
'__ia_char_14CHILD NOSTALGIA',
'__ia_char_14Easter Apparel Pet',
'__ia_char_14FY06 Christmas Food',
'__ia_char_14Fall__ia_char_03Winter AppFY05',
'__ia_char_14Harvest FY06',
'__ia_char_14MENS GIFT  NOVELTY',
'__ia_char_14Pet',
'__ia_char_14REGIONAL COOKBOOKS',
'__ia_char_14SCHYLLING TINS',
'__ia_char_14Trad Easter 05');


delete from inventory_smart.rcl_constraint_master_rule b 
where 1=1
and rcl_code=5
and rcl_dimension->>'primary_trait_desc' in (
'2010 Bike Week',
'2018 KY Derby',
'43 Store Test - Cars',
'Access Apr FY14',
'Access Mar FY14',
'Access May FY14',
'Accessories Military',
'Beach Story FY18',
'Brompton__ia_char_13Langley Bin',
'Buckeyes',
'Butterflies',
'CB 50TH ANNIVERSARY',
'CB Glitter Globe',
'COMMONWEALTH BIN',
'Car Stickers',
'Christmas Food FY07',
'Christmas Vinyl',
'Classic Collections',
'Cline Dropship',
'Collegiate Rockers',
'Dec Jwlry Test FY09',
'Demdaco Ornaments',
'Dilly Dally',
'Disney Vinyl',
'Do Not Use 701505',
'Dress Up',
'EC only item-Theme',
'ECOMM Avanti',
'EVDY Animal Candles',
'EVDY Bath Bombs',
'EVDY Blind Bags',
'EVDY CBOCS',
'EVDY Candle Access',
'EVDY Chesapke Herit',
'EVDY Coloring Books',
'EVDY CreateaBracelet',
'EVDY Deco Fragrance',
'EVDY Decorware',
'EVDY Frag nonYK__ia_char_03WW',
'EVDY FunZone Car',
'EVDY INSP Jewelry',
'EVDY JFL Puzzles',
'EVDY LED Candles',
'EVDY Leggings',
'EVDY Necklace Charms',
'EVDY Paddywax',
'EVDY Sentiments Cndl',
'EVDY Swan Creek',
'EVDY Tapers',
'EVDY Woodwk Car Frag',
'Everyday Watch Prog',
'Exclusive CD__ia_char_01s',
'FY 15 Watermelon Bin',
'FY08 EG',
'FY09 Cmas GCard Hdr',
'FY09 Elegant Rooster',
'FY09 Gingermint',
'FY09 MD Jwld Gftbls',
'FY09 Masqrade Party',
'FY09 Peace on Earth',
'FY09 Road Trip',
'FY10 AMERICAN HERITG',
'FY10 Christmas Food',
'FY10 Cmas CLG',
'FY10 Fall CLG',
'FY10 HOLIDAY GARDEN',
'FY10 Harvest Food',
'FY10 Inspiration',
'FY10 Regional Spring',
'FY10 Road Trip',
'FY11 Amer Heritage',
'FY11 Best Friends',
'FY11 Celebrate',
'FY11 Christmas Food',
'FY11 Fall Great Gfts',
'FY11 Halloween Food',
'FY11 In Bloom',
'FY11 Jwld Gifts Mar',
'FY11 Life isa Garden',
'FY11 Spring RGL',
'FY12 2 CUTE 2 SPOOK',
'FY12 American Pride',
'FY12 Colleg Opp Buy',
'FY12 Fall Grt Gifts',
'FY12 Inspiration',
'FY12 Jwld Gft Aug',
'FY12 Mful Messages',
'FY12 Mltry Mdl Test',
'FY12 Nature__ia_char_01s Garden',
'FY12 Roadtrip',
'FY12 Simply White',
'FY12 Sprg Regional',
'FY12 Summer Fun',
'FY13 American Pride',
'FY13 Backyard BBQ',
'FY13 Bacon',
'FY13 Blush',
'FY13 BlushTransition',
'FY13 CMA',
'FY13 Christmas Food',
'FY13 Cmas CDs',
'FY13 Coastal',
'FY13 Duck Cmndr May',
'FY13 Easter Treasure',
'FY13 Eye Want Candy',
'FY13 Fall Adult GG',
'FY13 Fall Collegiate',
'FY13 Fall Kids GG',
'FY13 Family Night',
'FY13 Gift Card',
'FY13 Grn Apple Food',
'FY13 Halloween Hoot',
'FY13 Harvest Food',
'FY13 Inspiration',
'FY13 Kids Road Trip',
'FY13 Mens',
'FY13 Milt ornment',
'FY13 Peacock',
'FY13 Regional',
'FY13 Rooster',
'FY13 Snow Friends',
'FY13 Spring Food',
'FY13 Summer Fun',
'FY13 Sundrenched',
'FY13 Sweets __ia_char_13 Treats',
'FY13 Tr Tops Glisten',
'FY13 Woodland Gardn',
'FY14 Access Hutch',
'FY14 Back2Preschool',
'FY14 Bee Bright',
'FY14 Bowl Games',
'FY14 Calendars',
'FY14 Christmas Food',
'FY14 Cmas CDs',
'FY14 Cmas2Remember',
'FY14 Coke Oct',
'FY14 Coral Reef',
'FY14 Duck Commader',
'FY14 Easter Food',
'FY14 FIFA',
'FY14 FINAL 4',
'FY14 Floral Stchwork',
'FY14 Frog Trouble',
'FY14 Grandmas Pantry',
'FY14 Great Gifts',
'FY14 Green Aple Food',
'FY14 HW Avanti Cards',
'FY14 Halloween',
'FY14 Halloween Food',
'FY14 In Full Bloom',
'FY14 Inspiration',
'FY14 Jingle __ia_char_13 Mingle',
'FY14 Knotical',
'FY14 Mad for Plaid',
'FY14 Mens',
'FY14 Military',
'FY14 Nesting Garden',
'FY14 Peacock',
'FY14 Polka Dots',
'FY14 Porch Living',
'FY14 Sanctuary Grdn',
'FY14 Sock Monkey',
'FY14 Spring Mens',
'FY14 Summer Cards',
'FY14 Under the Stars',
'FY14 Valentines',
'FY14 Winter White',
'FY14S Hat Rack',
'FY15 Apple',
'FY15 Beverages',
'FY15 Blush __ia_char_13 Grey',
'FY15 Cars__ia_char_13Trucks',
'FY15 Choc__ia_char_03Coffee__ia_char_03Tea',
'FY15 Cmas Collegiate',
'FY15 Cmas Food',
'FY15 Coastal',
'FY15 Coral',
'FY15 Country Style',
'FY15 Creatures Cmfrt',
'FY15 Garden 1',
'FY15 Grandma Pantry',
'FY15 Green with Envy',
'FY15 Grn Apple Food',
'FY15 HGR Store',
'FY15 HVST__ia_char_03Ap Vest',
'FY15 Hanukkah',
'FY15 Holiday Larry',
'FY15 Hween Food',
'FY15 Inspiration',
'FY15 Knotical',
'FY15 MLB',
'FY15 Metal Toys',
'FY15 Oct Gloves',
'FY15 Red',
'FY15 Riding Country',
'FY15 Rooster',
'FY15 Safari',
'FY15 SeasonalTidings',
'FY15 Shades of Blue',
'FY15 Sprng Insp',
'FY15 Winter White',
'FY15 Womens Scarf',
'FY15 __ia_char_1010 and Under',
'FY16 Apple',
'FY16 Calendars',
'FY16 Camo',
'FY16 Coastal',
'FY16 Easter Endcap',
'FY16 Fall Boutique',
'FY16 Fall Peacock',
'FY16 Final 4',
'FY16 Floral Sttchwrk',
'FY16 Fur __ia_char_13 Fringe',
'FY16 Garage',
'FY16 Grandmas Pantry',
'FY16 Great Gifts',
'FY16 Green Apple Bin',
'FY16 HANNUKAH',
'FY16 Halloween',
'FY16 Halloween Food',
'FY16 Harvest',
'FY16 In Full Bloom',
'FY16 Lake',
'FY16 Lemon Bin',
'FY16 Metallic',
'FY16 NHL',
'FY16 Nesting Garden',
'FY16 Nov Opp Jewelry',
'FY16 Spring Boutique',
'FY16 Sprng Insp',
'FY17  Winter Insp',
'FY17 Biketoberfest',
'FY17 Bowl Games',
'FY17 Breakfst Endcap',
'FY17 CMA Fest',
'FY17 CWS',
'FY17 Calendars',
'FY17 Christmas Ty',
'FY17 Cmas Endcap',
'FY17 Daytona 500',
'FY17 Easter',
'FY17 Easter Endcap',
'FY17 Easter Ty',
'FY17 Elegant',
'FY17 Final 4',
'FY17 Gift Card Hldr',
'FY17 Halloween Food',
'FY17 Halloween Ty',
'FY17 Hanukkah',
'FY17 Indy 500',
'FY17 KY Derby',
'FY17 Last Min Gifts',
'FY17 Stanley Cup',
'FY17 Summer Endcap',
'FY17 Traditional',
'FY17 Valentine Ty',
'FY17 Winter Lodge',
'FY17 World Series',
'FY17Spg GiftCrd Hldr',
'FY18 BIN ORNAMENTS',
'FY18 Bike Week',
'FY18 Bowl Games',
'FY18 CMA Fest',
'FY18 CWS',
'FY18 Christmas Ty',
'FY18 Cmas L',
'FY18 Coke Zero 400',
'FY18 Cup Playoffs',
'FY18 Daytona 500',
'FY18 Easter Ty',
'FY18 Fall Insp',
'FY18 Fball Champs',
'FY18 Final 4',
'FY18 Gift Card Hldr',
'FY18 Halloween Ty',
'FY18 Indy 500',
'FY18 KY Derby',
'FY18 MLB',
'FY18 Mardi Gras',
'FY18 Nshvl Sounds',
'FY18 Q3 Bow Sneaker',
'FY18 Slippers Opp',
'FY18 Sprg Insp',
'FY18 Stanley Cup',
'FY18 Super Bowl',
'FY18 Veterans Day',
'FY18 World Series',
'FY18 brkfast endcap',
'FY18 famfun endcap',
'FY18 summer endcap',
'FY18Sp NovltyBathBin',
'FY19 Aug Kids ACC',
'FY19 Balloonfest',
'FY19 Bball Champs',
'FY19 Bball Conf Chmp',
'FY19 Bike Week',
'FY19 Biketoberfest',
'FY19 Bracelet Buy',
'FY19 Burts Holiday',
'FY19 Christmas Ty',
'FY19 Cmas L',
'FY19 Daytona 500',
'FY19 Easter Ty',
'FY19 Final 4',
'FY19 GftCard Hldr',
'FY19 GltrBoot KeyBuy',
'FY19 Halloween Ty',
'FY19 Hween Endcap',
'FY19 Indy 500',
'FY19 KY Derby',
'FY19 Natl Champs',
'FY19 Nville Sounds',
'FY19 SB Champs',
'FY19 Super Bowl 53',
'FY19 TY Opp Buy',
'FY19 Valentine Ty',
'FY19 WS Champs',
'FY1920 Jul Kids Acc',
'FY1920 Jun Wmns Acc',
'FY20 Badger Bug__ia_char_03Sun',
'FY20 Burts Holiday',
'FY20 CMAS STOCKINGS',
'FY20 Cmas Plush Bin',
'FY20 Easter TY',
'FY20 Feb Wmns Acc',
'FY20 Frozen Watch',
'FY20 GiftCard Boxes',
'FY20 Gloves',
'FY20 GltrBoot KeyBuy',
'FY20 Knotical',
'FY20 Lindt Contest',
'FY20 Novelty Bath',
'FY20 Oct Wmns Acc',
'FY20 Opp Fall Toys',
'FY20 Sprg Cndl Hutch',
'FY20 Spring Toys',
'FY20 TY Halloween',
'FY20 Ty Slipper Buy',
'FY20 Val endcap',
'FY20 Valentines TY',
'FY20 Wraps',
'FY20 cmas L',
'FY20 fun wfood endcp',
'FY20 hween endcap',
'FY2021 Jul Wmns Acc',
'FY21 Burts Holiday',
'FY21 Christmas Plush',
'FY21 Cmas Food L',
'FY21 Cmas Stockings',
'FY21 Dec Wmns Acc',
'FY21 Easter Food L',
'FY21 Easter Plush',
'FY21 FunwFood Endcap',
'FY21 Hearth Decor',
'FY21 Jan Wmns Acc',
'FY21 Lindt Contest',
'FY21 Mr Christmas',
'FY21 Nov Fash Fixt',
'FY21 S__ia_char_03S STORE DECOR',
'FY21 Sep Wmns Acc',
'FY21 Summer Endcap',
'FY21 Ty Halloween',
'FY2122 Jul Wmns Acc',
'FY22 Al Fresco',
'FY22 CMAS STOCKINGS',
'FY22 Chimes__ia_char_03Leaners',
'FY22 Christmas Plush',
'FY22 Fall Toys',
'FY22 Halloween Plush',
'FY22 M-AT App Buy',
'FY22 Mr Cmas Opp Buy',
'FY22 Nov Wmns Acc',
'FY22 Q4 WW Contest',
'FY22 Sep Kids Acc',
'FY22 Sep Wmns Acc',
'FY22 Summer Toys',
'FY22 cmas food L',
'FY22 easter food L',
'FY22 hween endcap',
'FY23 CMAS ECOM',
'FY23 Christmas Plush',
'FY23 Easter L',
'FY23 SPRING TOWELS',
'FY23 Spring Toys',
'FY24 Jewelry Opp Buy',
'Fash Fix Aug FY14',
'Fash Fixt Aug FY15',
'Fash Fixt Aug FY16',
'Fash Fixt Aug FY17',
'Fash Fixt Feb FY15',
'Fash Fixt Feb FY16',
'Fash Fixt May FY15',
'Fash Fixt May FY16',
'Fash Fixt May FY17',
'Fash Fixt Nov FY15',
'Fash Fixt Nov FY16',
'Fash Fixt Nov FY17',
'Fash Fixt Nov FY19',
'Fashion Fix Feb FY14',
'Fashion Fix May FY14',
'Fashion Fix Nov FY13',
'Hershey Bath',
'JOHN DEERE',
'Jelly Belly',
'Kid Acc April FY18',
'Kid Acc June FY18__ia_char_0319',
'Kids Ac Jul FY13FY14',
'Kids Ac Jul FY14FY15',
'Kids Ac Jul FY15FY16',
'Kids Ac Jun FY14FY15',
'Kids Ac Jun FY15FY16',
'Kids Acc Apr FY15',
'Kids Acc Apr FY16',
'Kids Acc April FY17',
'Kids Acc Aug FY16',
'Kids Acc Aug FY18',
'Kids Acc Dec FY15',
'Kids Acc Dec FY16',
'Kids Acc Dec FY17',
'Kids Acc Dec FY18',
'Kids Acc Dec FY19',
'Kids Acc Feb FY15',
'Kids Acc Feb FY16',
'Kids Acc Feb FY17',
'Kids Acc Jan FY15',
'Kids Acc Jan FY16',
'Kids Acc Jan FY17',
'Kids Acc Jan FY18',
'Kids Acc Jul FY18__ia_char_0319',
'Kids Acc Mar FY15',
'Kids Acc Mar FY16',
'Kids Acc Mar FY17',
'Kids Acc Mar FY18',
'Kids Acc May FY16',
'Kids Acc May FY17',
'Kids Acc May FY18',
'Kids Acc Nov FY15',
'Kids Acc Nov FY16',
'Kids Acc Nov FY17',
'Kids Acc Oct FY15',
'Kids Acc Oct FY16',
'Kids Acc Oct FY17',
'Kids Acc Sep FY15',
'Kids Acc Sep FY16',
'Kids Acc Sept FY17',
'Kids Acc Sept FY18',
'Kids Acc Sept FY19',
'Kids Acces Sept FY14',
'Kids Access Apr FY14',
'Kids Access Aug FY14',
'Kids Access Dec FY14',
'Kids Access Feb FY14',
'Kids Access Jan FY14',
'Kids Access Mar FY13',
'Kids Access Mar FY14',
'Kids Access May FY13',
'Kids Access May FY14',
'Kids Access Oct FY14',
'Kids Ap Jun FY15FY16',
'Kids Ap Jun FY16FY17',
'Kids App Apr FY15',
'Kids App Aug FY15',
'Kids App Aug FY16',
'Kids App Dec FY16',
'Kids App Feb FY16',
'Kids App Jan FY15',
'Kids App Jan FY16',
'Kids App Jan FY17',
'Kids App Mar FY15',
'Kids App Mar FY16',
'Kids App Mar FY17',
'Kids App May FY15',
'Kids App May FY16',
'Kids App Nov FY16',
'Kids App Nov FY17',
'Kids App Oct FY15',
'Kids App Oct FY17',
'Kids App Sep FY16',
'Kids App Sept FY17',
'Kids Mar FY12',
'Kids March FY11',
'Kids Nov Access FY13',
'Kids Sept FY12',
'Little Golden Books',
'Made in USA Tee FY12',
'Media Boxed Set',
'Mens Hat Fxtr FY10',
'Military Rockers',
'Motion Plush',
'Mr. Cmas VendorNet',
'Opry CD__ia_char_01s',
'Q1 Woodwick promo',
'Q2 Woodwick promo',
'Q2.18 Food Frsh Toy',
'Q2.18 India Bags',
'Q2.18 Italy Access',
'Q2.18 Str Wrs Tshirt',
'Q2.18 Swarovski',
'Q2.18 mini sayings',
'Q2.18 tervis tumbler',
'Q3.18 Lip Keychain',
'Q3.18 Woodwick Cameo',
'Q4.18 Food TicTac',
'Q4.18 Woodwick Cndl',
'Remodel Test 50',
'Seas Chspk Herit Fal',
'Seas Chspk Herit Spr',
'Seas Yankee Car Fall',
'Sep Jwl Fixture FY10',
'Special Buy Rockers',
'Thin Sticks',
'Various Accessories',
'WW FY20 Q2 Promo',
'Wmn Acc Oct FY12',
'Wmn Oct FY12',
'Wmns Ac Jun FY15FY16',
'Wmns Ac Jun FY16FY17',
'Wmns Ap Jun FY15FY16',
'Wmns Ap Jun FY16FY17',
'Wmns Tees FY16 Trans',
'Women Acc April FY17',
'Womens Acc Apr FY16',
'Womens Acc Aug FY15',
'Womens Acc Aug FY16',
'Womens Acc Feb FY15',
'Womens Acc Feb FY17',
'Womens Acc June FY17',
'Womens Acc Mar FY15',
'Womens Acc Mar FY16',
'Womens Acc May FY19',
'Womens Acc Nov FY16',
'Womens Acc Nov FY17',
'Womens Acc Nov FY18',
'Womens Acc Nov FY19',
'Womens Acc Oct FY16',
'Womens Acc Oct FY17',
'Womens Acc Oct FY19',
'Womens Acc Sep FY15',
'Womens Acc Sep FY16',
'Womens Acc Sept FY17',
'Womens Acc Sept FY18',
'Womens App Apr FY16',
'Womens App Aug FY16',
'Womens App Dec FY16',
'Womens App Dec FY17',
'Womens App Feb FY16',
'Womens App Feb FY17',
'Womens App Mar FY16',
'Womens App Mar FY17',
'Womens App May FY15',
'Womens App May FY16',
'Womens App Nov FY16',
'Womens App Nov FY17',
'Womens App Oct FY16',
'Womens App Oct FY17',
'Womens Apr FY14',
'Womens Mar FY14',
'Womens Wraps FY17',
'Wreaths Acrs America',
'Yankee Q3 Promo',
'__ia_char_1405 Cmas Season Eleg',
'__ia_char_1405 Cmas in  Woods',
'__ia_char_14American Legends',
'__ia_char_14CHILD NOSTALGIA',
'__ia_char_14Easter Apparel Pet',
'__ia_char_14FY06 Christmas Food',
'__ia_char_14Fall__ia_char_03Winter AppFY05',
'__ia_char_14Harvest FY06',
'__ia_char_14MENS GIFT  NOVELTY',
'__ia_char_14Pet',
'__ia_char_14REGIONAL COOKBOOKS',
'__ia_char_14SCHYLLING TINS',
'__ia_char_14Trad Easter 05');


--changeset shreyansh.jain@impactanalytics.co:ecom_default_store_group_remove stripComments:false splitStatements:false context:Release_1 labels:inactive_default_removal
--comment: changeset for ecom_default_store_group_remove MTP-136296
DELETE FROM "global".store_groups_mapping
WHERE sg_code=8 and store_code='800'