import { INVENTORY_SUBMODULES_NAMES } from "modules/inventorysmart/constants-inventorysmart/stringConstants";

const {
  INVENTORY_ALLOCATION_REPORTING_MODEL_STOCK_DEEP_DIVE,
  INVENTORY_ALLOCATION_REPORTING_STORE_STOCK,
  INVENTORY_ALLOCATION_REPORTING_LOST_SALES,
  INVENTORY_ALLOCATION_REPORTING_LOST_SALES_WITH_FISCAL_CALENDAR,
  INVENTORY_ALLOCATION_REPORTING_EXCESS_INV,
  INVENTORY_ALLOCATION_REPORTING_EXCESS_REPORT,
  INVENTORY_ALLOCATION_REPORTING_DEEP_DIVE,
  INVENTORY_ALLOCATION_REPORTING_DAILY_ALLOCATION,
  INVENTORY_ALLOCATION_REPORTING_FORECASTED_UNITS,
  INVENTORY_ALLOCATION_REPORTING_ADDITIONAL_REPORTS,
  INVENTORY_ALLOCATION_REPORTING_FUTURE_RECEIPTS,
  INVENTORY_ALLOCATION_REPORTING_FORECAST_REPORTS,
  INVENTORY_ALLOCATION_REPORTING_IN_STOCK,
  INVENTORY_ALLOCATION_REPORTING_INTENTIONAL_MIN_REPORTS,
  INVENTORY_ALLOCATION_REPORTING_DC_AVAILABILITY_REPORT,
  INVENTORY_ALLOCATION_REPORTING_FORECAST_VARIANCE_REPORT,
  INVENTORY_ALLOCATION_REPORTING_FORWARD_LOOKING_REPORT,
  INVENTORY_ORDER_VENDOR_PROJECTIONS,
  INVENTORY_ORDER_DROP_SHIP,
  INVENTORY_ORDER_EXPEDITE_ORDERS,
  INVENTORY_ORDER_LATE_ORDERS,
  INVENTORY_ORDER_FUTURE_RECEIPTS,
  INVENTORY_ORDER_FORECAST_ACCURACY,
} = INVENTORY_SUBMODULES_NAMES;

export const tabModulePermissionMap = {
  allocation_reporting: [
    INVENTORY_ALLOCATION_REPORTING_MODEL_STOCK_DEEP_DIVE,
    INVENTORY_ALLOCATION_REPORTING_STORE_STOCK,
    INVENTORY_ALLOCATION_REPORTING_LOST_SALES,
    INVENTORY_ALLOCATION_REPORTING_LOST_SALES_WITH_FISCAL_CALENDAR,
    INVENTORY_ALLOCATION_REPORTING_EXCESS_INV,
    INVENTORY_ALLOCATION_REPORTING_EXCESS_REPORT,
    INVENTORY_ALLOCATION_REPORTING_DEEP_DIVE,
    INVENTORY_ALLOCATION_REPORTING_DAILY_ALLOCATION,
    INVENTORY_ALLOCATION_REPORTING_FORECASTED_UNITS,
    INVENTORY_ALLOCATION_REPORTING_ADDITIONAL_REPORTS,
    INVENTORY_ALLOCATION_REPORTING_FUTURE_RECEIPTS,
    INVENTORY_ALLOCATION_REPORTING_FORECAST_REPORTS,
    INVENTORY_ALLOCATION_REPORTING_IN_STOCK,
    INVENTORY_ALLOCATION_REPORTING_INTENTIONAL_MIN_REPORTS,
    INVENTORY_ALLOCATION_REPORTING_DC_AVAILABILITY_REPORT,
    INVENTORY_ALLOCATION_REPORTING_FORECAST_VARIANCE_REPORT,
    INVENTORY_ALLOCATION_REPORTING_FORWARD_LOOKING_REPORT,
  ],
  reports_oms: [
    INVENTORY_ORDER_VENDOR_PROJECTIONS,
    INVENTORY_ORDER_DROP_SHIP,
    INVENTORY_ORDER_EXPEDITE_ORDERS,
    INVENTORY_ORDER_LATE_ORDERS,
    INVENTORY_ORDER_FUTURE_RECEIPTS,
    INVENTORY_ORDER_FORECAST_ACCURACY,
  ],
};

export const allocationReportingTabModulePermissionMap = {
  model_stock_deep_dive: [INVENTORY_ALLOCATION_REPORTING_MODEL_STOCK_DEEP_DIVE],
  store_stock: [INVENTORY_ALLOCATION_REPORTING_STORE_STOCK],
  store_stock_rl: [INVENTORY_ALLOCATION_REPORTING_STORE_STOCK],
  lost_sales: [INVENTORY_ALLOCATION_REPORTING_LOST_SALES],
  lost_sales_with_fiscal_calendar: [
    INVENTORY_ALLOCATION_REPORTING_LOST_SALES_WITH_FISCAL_CALENDAR,
  ],
  excess_inv: [INVENTORY_ALLOCATION_REPORTING_EXCESS_INV],
  excess_report: [INVENTORY_ALLOCATION_REPORTING_EXCESS_REPORT],
  deep_dive: [INVENTORY_ALLOCATION_REPORTING_DEEP_DIVE],
  daily_allocation: [INVENTORY_ALLOCATION_REPORTING_DAILY_ALLOCATION],
  forecasted_units: [INVENTORY_ALLOCATION_REPORTING_FORECASTED_UNITS],
  additional_reports: [INVENTORY_ALLOCATION_REPORTING_ADDITIONAL_REPORTS],
  future_receipts: [INVENTORY_ALLOCATION_REPORTING_FUTURE_RECEIPTS],
  forecast_reports: [INVENTORY_ALLOCATION_REPORTING_FORECAST_REPORTS],
  in_stock: [INVENTORY_ALLOCATION_REPORTING_IN_STOCK],
  intentional_min_reports: [
    INVENTORY_ALLOCATION_REPORTING_INTENTIONAL_MIN_REPORTS,
  ],
  dc_availability_report: [
    INVENTORY_ALLOCATION_REPORTING_DC_AVAILABILITY_REPORT,
  ],
  forecast_variance_report: [
    INVENTORY_ALLOCATION_REPORTING_FORECAST_VARIANCE_REPORT,
  ],
  forward_looking_report: [
    INVENTORY_ALLOCATION_REPORTING_FORWARD_LOOKING_REPORT,
  ],
};

export const omsTabModulePermissionMap = {
  vendor_projections: [INVENTORY_ORDER_VENDOR_PROJECTIONS],
  drop_ship: [INVENTORY_ORDER_DROP_SHIP],
  expedite_orders: [INVENTORY_ORDER_EXPEDITE_ORDERS],
  late_orders: [INVENTORY_ORDER_LATE_ORDERS],
  future_receipts_reports: [INVENTORY_ORDER_FUTURE_RECEIPTS],
  forecast_accuracy: [INVENTORY_ORDER_FORECAST_ACCURACY],
};
