import { makeStyles } from "@mui/styles";

export const useFulfilmentTypeCardStyles = makeStyles(() => ({
  fulfilmentCardsRow: {
    display: "flex",
    gap: "16px",
    flexWrap: "wrap",
    alignItems: "flex-start",
    width: "100%",
  },
  fulfilmentCard: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "24px",
    borderRadius: "12px",
    backgroundColor: "#FFFFFF",
    boxShadow: "0px 0px 4px 0px rgba(0, 0, 0, 0.12)",
    width: "500px",
    maxWidth: "100%",
    cursor: "pointer",
    border: "1.5px solid transparent",
    position: "relative",
    overflow: "hidden",
    textAlign: "left",
    boxSizing: "border-box",
  },
  fulfilmentCardSelected: {
    borderColor: "#4259EE",
  },
  fulfilmentCardGlow: {
    position: "absolute",
    left: "290px",
    top: "-297px",
    width: "374px",
    height: "374px",
    borderRadius: "50%",
    backgroundColor: "#A1B4FF",
    opacity: 0.35,
    filter: "blur(90px)",
    pointerEvents: "none",
    zIndex: 0,
  },
  fulfilmentCardReadOnly: {
    cursor: "default",
  },
  fulfilmentCardBlocked: {
    cursor: "default",
    pointerEvents: "none",
    opacity: 0.85,
  },
  fulfilmentIconWrap: {
    position: "relative",
    width: "36px",
    height: "36px",
    flexShrink: 0,
    overflow: "visible",
    zIndex: 1,
  },
  fulfilmentIcon: {
    position: "absolute",
    left: "-8px",
    top: "0",
    width: "52px",
    height: "47px",
    display: "block",
  },
  fulfilmentCardContent: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    flex: 1,
    minWidth: 0,
    zIndex: 1,
  },
  fulfilmentCardTitle: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "16px",
    fontWeight: 800,
    lineHeight: "24px",
    color: "#1F2B4D",
  },
  fulfilmentCardDescription: {
    fontFamily: "Manrope, sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "21px",
    color: "#8C95A7",
  },
}));
