//TODO: To be removed later
export const metricsColumnsData = [
    {
        "sub_headers": [],
        "tc_code": 37,
        "label": "Metrics",
        "column_name": "metric",
        "dimension": "Other",
        "type": "str",
        "is_frozen": false,
        "is_editable": false,
        "is_aggregated": false,
        "order_of_display": 1,
        "is_hidden": false,
        "is_required": true,
        "tc_mapping_code": 135,
        "aggregate_type": "",
        "formatter": "",
        "is_row_span": false,
        "footer": "",
        "is_searchable": true,
        "extra": {},
        "is_sortable": true,
        "width": 200
    },
    {
        "sub_headers": [],
        "tc_code": 37,
        "label": "Weightage",
        "column_name": "weightage",
        "dimension": "Other",
        "type": "rangeSlider",
        "is_frozen": false,
        "is_editable": true,
        "is_aggregated": false,
        "order_of_display": 2,
        "is_hidden": false,
        "is_required": false,
        "tc_mapping_code": 134,
        "aggregate_type": "",
        "formatter": "",
        "is_row_span": false,
        "footer": "",
        "is_searchable": false,
        "extra": {},
        "is_sortable": true,
        "width": 200
    },
    {
        "sub_headers": [],
        "tc_code": 37,
        "label": "",
        "column_name": "value",
        "dimension": "Other",
        "type": "str",
        "is_frozen": false,
        "is_editable": false,
        "is_aggregated": false,
        "order_of_display": 1,
        "is_hidden": false,
        "is_required": true,
        "tc_mapping_code": 135,
        "aggregate_type": "",
        "formatter": "",
        "is_row_span": false,
        "footer": "",
        "is_searchable": false,
        "extra": {},
        "is_sortable": true,
        "width": 100
    }
];