--liquibase formatted sql
--changeset abhimanyu.j@impactanalytics.co:mv_product_hierarchies_filter_2 runOnChange:true stripComments:false splitStatements:false context:Release_1_0 labels:MTP-58202
--comment:  intial changest mv_product_hierarchies_filter_changes
--rollback: SELECT 1
DROP MATERIALIZED VIEW IF EXISTS item_smart.mv_product_hierarchies_filter;

CREATE MATERIALIZED VIEW item_smart.mv_product_hierarchies_filter
   
AS SELECT phf.hierarchy_code,
    phf.l1_name,
    phf.l2_name,
    phf.l3_name,
    phf.l4_name,
    phf.color_description,
    phf.article AS product_code,
    phf.article,
    '-'::text AS product_name,
    phf.level,
    paf.receipt_date,
    paf.super_style_color_code,
    0 AS product_id,
    'Regular'::text AS product_type,
    paf.l0_name,
    paf.l1_id,
    paf.l2_id,
    paf.l3_id,
    paf.l4_id,
    paf.color,
    paf.replenishment_flag,
    paf.inseam,
    paf.inseam_name,
    paf.back_type,
    paf.back_type_name,
    paf.coverage_bra,
    paf.coverage_bra_name,
    paf.lining_bra,
    paf.lining_bra_name,
    paf.bust_type,
    paf.bust_type_name,
    paf.pocket_quantity,
    paf.fit,
    paf.fit_name,
    paf.height,
    paf.height_name,
    paf.impact_level,
    paf.impact_level_name,
    paf.longline_bra,
    paf.neckline,
    paf.neckline_name,
    paf.sheerness,
    paf.sheerness_name,
    paf.silhouette,
    paf.silhouette_name,
    paf.sleeve_length,
    paf.sleeve_length_name,
    paf.strap_type,
    paf.strap_type_name,
    paf.fabric_feel,
    paf.fabric_weight,
    paf.fabric_stretch,
    paf.sweat_wicking,
    paf.added_construction,
    paf.breathability,
    paf.end_use,
    paf.special_features,
    paf.target_area,
    paf.shapewear_wear_with,
    paf.department,
    paf.wash,
    paf.wash_name,
    paf.length_description,
    paf.length_description_name,
    paf.product_bucket_code,
    paf.product_lifecycle,
    paf.product_description,
    paf.item_description,
    paf.product_details_en_us,
    paf.closure_type,
    paf.closure_type_name,
    paf.price,
    paf.original_price,
    paf.cost,
    paf.launch_date,
    lt.lead_time,
    ( SELECT max(fiscal_date_mapping.calendar_date) AS max
           FROM global.fiscal_date_mapping) AS exit_date,
    paf.collection,
    paf.collection_desc,
    paf.superstyle_name,
    paf.superstyle,
    'A'::text AS purchase_status_code,
    'Active'::text AS purchase_status_type,
    'Active'::text AS purchase_status,
    'A'::text AS purchase_status_type_code
   FROM item_smart.product_hierarchies_filter phf
     JOIN ( SELECT paf_1.article,
            paf_1.receipt_date,
            paf_1.super_style_color_code,
            0 AS product_id,
            0 AS product_type,
            paf_1.l0_name,
            paf_1.l1_id,
            paf_1.l2_id,
            paf_1.l3_id,
            paf_1.l4_id,
            paf_1.color,
            paf_1.replenishment_flag,
            paf_1.inseam,
            paf_1.inseam_name,
            paf_1.back_type,
            paf_1.back_type_name,
            paf_1.coverage_bra,
            paf_1.coverage_bra_name,
            paf_1.lining_bra,
            paf_1.lining_bra_name,
            paf_1.bust_type,
            paf_1.bust_type_name,
            paf_1.pocket_quantity,
            paf_1.fit,
            paf_1.fit_name,
            paf_1.height,
            paf_1.height_name,
            paf_1.impact_level,
            paf_1.impact_level_name,
            paf_1.longline_bra,
            paf_1.neckline,
            paf_1.neckline_name,
            paf_1.sheerness,
            paf_1.sheerness_name,
            max(paf_1.silhouette) as silhouette,
            max(paf_1.silhouette_name) as silhouette_name,
            paf_1.sleeve_length,
            paf_1.sleeve_length_name,
            paf_1.strap_type,
            paf_1.strap_type_name,
            paf_1.fabric_feel,
            paf_1.fabric_weight,
            paf_1.fabric_stretch,
            paf_1.sweat_wicking,
            paf_1.added_construction,
            paf_1.breathability,
            paf_1.end_use,
            paf_1.special_features,
            paf_1.target_area,
            paf_1.shapewear_wear_with,
            paf_1.department,
            paf_1.wash,
            paf_1.wash_name,
            paf_1.length_description,
            paf_1.length_description_name,
            paf_1.product_bucket_code,
            max(paf_1.product_lifecycle) as product_lifecycle,
            paf_1.collection,
            paf_1.collection_desc,
            paf_1.superstyle_name,
            paf_1.superstyle,
            max(paf_1.product_description) AS product_description,
            max(paf_1.product_details_en_us::text) AS product_details_en_us,
            max(paf_1.article_description::text) AS item_description,
            max(paf_1.closure_type::text) AS closure_type,
            max(paf_1.closure_type_name::text) AS closure_type_name,
            avg(paf_1.price) AS price,
            avg(paf_1.original_price) AS original_price,
            avg(paf_1.cost) AS cost,
            min(launch_date) AS launch_date
           FROM global.product_attributes_filter paf_1
          GROUP BY paf_1.article, paf_1.receipt_date, paf_1.super_style_color_code, 0::integer, paf_1.l0_name, paf_1.l1_id, paf_1.l2_id, paf_1.l3_id, paf_1.l4_id, paf_1.color, paf_1.replenishment_flag, paf_1.inseam, paf_1.inseam_name, paf_1.back_type, paf_1.back_type_name, paf_1.coverage_bra, paf_1.coverage_bra_name, paf_1.lining_bra, paf_1.lining_bra_name, paf_1.bust_type, paf_1.bust_type_name, paf_1.pocket_quantity, paf_1.fit, paf_1.fit_name, paf_1.height, paf_1.height_name, paf_1.impact_level, paf_1.impact_level_name, paf_1.longline_bra, paf_1.neckline, paf_1.neckline_name, paf_1.sheerness, paf_1.sheerness_name, paf_1.sleeve_length, paf_1.sleeve_length_name, paf_1.strap_type, paf_1.strap_type_name, paf_1.fabric_feel, paf_1.fabric_weight, paf_1.fabric_stretch, paf_1.sweat_wicking, paf_1.added_construction, paf_1.breathability, paf_1.end_use, paf_1.special_features, paf_1.target_area, paf_1.shapewear_wear_with, paf_1.department, paf_1.wash, paf_1.wash_name, paf_1.length_description, paf_1.length_description_name, paf_1.product_bucket_code, paf_1.collection, paf_1.collection_desc, paf_1.superstyle_name, paf_1.superstyle) paf ON paf.article::text = phf.article::text
     LEFT JOIN ( SELECT hierarchy_code,
            lead_time
           FROM item_smart.itemfact_sku) lt ON paf.article::text = lt.hierarchy_code::text
WITH DATA;

-- View indexes:
CREATE INDEX idx_hcode_mv_phf ON item_smart.mv_product_hierarchies_filter USING btree (hierarchy_code);



