--liquibase formatted sql
--changeset ujjawal.singh@impactanalytics.co:alert_product_store_level stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for alert_product_store_level


CREATE TABLE IF NOT EXISTS inventory_smart.alerts_product_store_level (
	l0_name varchar NULL,
	l1_name varchar NULL,
	l2_name varchar NULL,
	l3_name varchar NULL,
	l4_name varchar NULL,
	l5_name varchar NULL,
	article varchar NULL,
	season varchar NULL,
	style_description varchar NULL,
	collection varchar NULL,
	store_code varchar NULL,
	s0_name varchar NULL,
	country varchar NULL,
	region varchar NULL,
	lw_units float8 NULL,
	lw_margin float8 NULL,
	lw_revenue float8 NULL,
	l4w_units float8 NULL,
	l4w_revenue float8 NULL,
	l8w_units float8 NULL,
	discount float8 NULL,
	stockout float8 NULL,
	shortfall float8 NULL,
	excess float8 NULL,
	normal float8 NULL,
	sell_through_perc float8 NULL,
	ata_eaches float8 NULL,
	ata_packs float8 NULL,
	ata float8 NULL,
	dc_instock float8 NULL,
	dc_oo float8 NULL,
	in_stock int4 NULL,
	in_stock_ata float8 NULL,
	allocated_units int4 NULL,
	wos_oh_oo_it float8 NULL,
	wos_oh_oo float8 NULL,
	wos_oh float8 NULL,
	launch_date date NULL,
	clearance bool NULL,
	price float8 NULL,
	msrp float8 NULL,
	oh float8 NULL,
	it float8 NULL,
	oo float8 NULL,
	total_inv float8 NULL,
	overstock_most_stores_alert int4 NULL,
	shortfall_most_stores_alert int4 NULL,
	stockout_most_stores_alert int4 NULL,
	cfc_age_weeks int4 NULL,
	cfc_age_gt_5_alert int4 NULL,
	cfc_age_gt_10_alert int4 NULL,
	cfc_age_gt_20_alert int4 NULL
);