--liquibase formatted sql
--changeset ujjawal.singh@impactanalytics.co:asn_master stripComments:false splitStatements:false context:Release_1_0 labels:VPP-262
--comment: initial changeset for cancelled_po


CREATE TABLE IF NOT EXISTS inventory_smart.cancelled_po (
	po_id varchar NOT NULL,
	receipt_id varchar NOT NULL,
	ref_id varchar NOT NULL,
	po_type varchar NOT NULL,
	order_date timestamptz NOT NULL,
	in_dc_date timestamptz NOT NULL,
	product_code varchar NOT NULL,
	product_description varchar NOT NULL,
	ordered_quantity int4 NOT NULL,
	allocation_multiple int4 NOT NULL,
	hold_or_reserve_quantity int4 NOT NULL,
	cancellation_flag bool NOT NULL,
	product_group varchar NOT NULL,
	product_group_ratio_flag bool NULL,
	pack_id varchar NOT NULL,
	pack_size int4 NOT NULL,
	destination_dc varchar NOT NULL,
	store_groups varchar NULL,
	header_min int4 NOT NULL,
	header_max int4 NOT NULL,
	line_item_level_min int4 NOT NULL,
	line_item_level_max int4 NOT NULL,
	method_of_allocation varchar NOT NULL,
	line_item_mandatory_flag bool NOT NULL,
	auto_allocation_flag bool NOT NULL,
	merch_base_level varchar NULL,
	"attribute" varchar NULL,
	time_period_history_calculation varchar NULL,
	eligibility_override_indicator bool NOT NULL,
	indicator_of_pack_type varchar NULL,
	master_pack_size int4 NOT NULL,
	ats_date timestamptz NULL,
	ly_ats_date timestamptz NULL,
	direction varchar NULL,
	num_weeks int4 NULL,
	start_date timestamptz NULL,
	end_date timestamptz NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	is_deleted bool NULL,
	processed_status int4 NOT NULL,
	processed_at timestamptz NULL,
	batch_id int8 NOT NULL,
	error_code int4 NULL,
	cancelled_created_at timestamptz DEFAULT now() NOT NULL,
	cancelled_updated_at timestamptz DEFAULT now() NOT NULL
);
