--liquibase formatted sql
--changeset jyothika.chowdary@impactanalytics.co:multichannel_view stripComments:false splitStatements:false context:Release_1_0 labels:itemsmart_initial_commit
--comment: initial changeset for multichannel_view
CREATE TABLE IF NOT EXISTS item_smart.multichannel_view (
	id serial4 NOT NULL,
	kpi_group varchar(100) NULL,
	kpi varchar(100) NULL,
	application_label varchar(100) NULL,
	view_omni bpchar(1) NULL,
	view_ecom bpchar(1) NULL,
	view_ecom_percent bpchar(1) NULL,
	view_wholesale bpchar(1) NULL,
	view_wholesale_percent bpchar(1) NULL,
	view_channel_3 bpchar(1) NULL,
	view_channel_3_percent bpchar(1) NULL,
	edit_omni bpchar(1) NULL,
	edit_ecom bpchar(1) NULL,
	edit_ecom_percent bpchar(1) NULL,
	edit_wholesale bpchar(1) NULL,
	edit_wholesale_percent bpchar(1) NULL,
	edit_channel_3 bpchar(1) NULL,
	edit_channel_3_percent bpchar(1) NULL,
	view_single_1 bpchar(1) NULL,
	view_subchannel_1 bpchar(1) NULL,
	view_subchannel_percent_1 bpchar(1) NULL,
	edit_single_1 bpchar(1) NULL,
	edit_subchannel_1 bpchar(1) NULL,
	edit_subchannel_percent_1 bpchar(1) NULL,
	view_single_2 bpchar(1) NULL,
	view_subchannel_2 bpchar(1) NULL,
	view_subchannel_percent_2 bpchar(1) NULL,
	edit_single_2 bpchar(1) NULL,
	edit_subchannel_2 bpchar(1) NULL,
	edit_subchannel_percent_2 bpchar(1) NULL,
	view_single_3 bpchar(1) NULL,
	view_subchannel_3 bpchar(1) NULL,
	view_subchannel_percent_3 bpchar(1) NULL,
	edit_single_3 bpchar(1) NULL,
	edit_subchannel_3 bpchar(1) NULL,
	edit_subchannel_percent_3 bpchar(1) NULL,
	CONSTRAINT multichannel_view_pkey PRIMARY KEY (id)
);
