--liquibase formatted sql
--changeset dodda.gowtham@impactanalytics.co:new_skus creation stripComments:false splitStatements:false context:Release_1_0 labels:itemsmart_initial_commit
--comment: initial creation of new_skus table

CREATE TABLE item_smart.new_skus (
    -- Core Identifiers
    id INTEGER,
    hierarchy_code INTEGER,
    style TEXT,
    level SMALLINT,
    product_code VARCHAR,
    sku TEXT,
    article INTEGER,
    product_name TEXT,
    product_name_orig TEXT,
    product_description TEXT,
    obs_bh_product_name TEXT,
    item VARCHAR,
    item_name TEXT,
    external_key TEXT,

    -- Hierarchy
    l0_name VARCHAR,
    l1_name VARCHAR,
    l2_name VARCHAR,
    l3_name VARCHAR,
    l4_name VARCHAR,
    l5_name VARCHAR,
    l0_id INTEGER,
    l1_id INTEGER,
    l2_id INTEGER,
    l3_id INTEGER,
    l4_id INTEGER,
    l5_id INTEGER,
    l6_id TEXT,

    -- Dates
    launch_date DATE,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    exit_date DATE,
    inserted_date TEXT,
    modified_date TEXT,
    live_on_sitedate DATE,

    -- Ownership / Source
    created_by INTEGER,
    updated_by INTEGER,
    fk_skuproductid DOUBLE PRECISION,
    fk_productid INTEGER,
    pk_skuproductid INTEGER,
    product_id INTEGER,
    product_bucket_code INTEGER,
    filesourceid INTEGER,
    pipeline_runid TEXT,

    -- Pricing
    price NUMERIC,
    cost NUMERIC,
    original_price NUMERIC,
    cost_first_product_value DOUBLE PRECISION,
    cost_first_product_unit TEXT,
    cost_fully_loaded_ship_value DOUBLE PRECISION,
    cost_fully_loaded_ship_unit TEXT,
    std_ship_cost_value DOUBLE PRECISION,
    std_ship_cost_unit TEXT,

    -- Status
    active BOOLEAN,
    clearance BOOLEAN,
    is_deleted BOOLEAN,
    product_status VARCHAR,

    -- Product Meta
    brand TEXT,
    product_type TEXT,
    item_type TEXT,
    entity_type TEXT,
    lifecycle TEXT,
    pillar_category TEXT,
    sku_code TEXT,

    -- Physical Attributes
    color TEXT,
    size_sml TEXT,
    shape_of_decor TEXT,
    shape_of_topiary TEXT,
    light_type TEXT,
    light_color TEXT,
    material TEXT,
    season TEXT,
    holiday TEXT,
    year DOUBLE PRECISION,
    raw_materials TEXT,
    raw_materials_type TEXT,
    species_treegreenery TEXT,
    type_lightcontrol TEXT,
    timer TEXT,
    outdoor_safe TEXT,
    level_realism TEXT,
    foliage_type TEXT,
    number_sectionsintree DOUBLE PRECISION,
    number_branchtips DOUBLE PRECISION,
    pottedtree TEXT,
    frosted TEXT,
    display_sizerange TEXT,
    level_of_decoration TEXT,
    tree_shape TEXT,
    tree_setup_type TEXT,
    needle_type TEXT,

    -- Dimensions and Measurements
    heights TEXT,
    lengths TEXT,
    widths TEXT,
    weights TEXT,
    heights_distinct TEXT,
    lengths_distinct TEXT,
    widths_distinct TEXT,
    weights_distinct TEXT,
    carton_total_count INTEGER,
    distinct_upc_count INTEGER,

    -- Detailed Measurements
    height_providedbyvendor TEXT,
    height_value_converted_value DOUBLE PRECISION,
    height_value_converted_unit TEXT,
    height_display_siteconverted DOUBLE PRECISION,
    height_override_display_site_convrt_val DOUBLE PRECISION,
    height_override_display_site_convrt_unit TEXT,
    
    length_providedbyvendor TEXT,
    length_value_converted_value DOUBLE PRECISION,
    length_value_converted_unit TEXT,
    length_display_site_converted DOUBLE PRECISION,
    length_override_display_site_convrt_val DOUBLE PRECISION,
    length_override_display_site_convrt_unit TEXT,
    
    width_providedbyvendor TEXT,
    width_value_converted_value DOUBLE PRECISION,
    width_value_converted_unit TEXT,
    width_display_siteconverted DOUBLE PRECISION,
    width_override_display_site_convrt_val DOUBLE PRECISION,
    width_override_display_site_convrt_unit TEXT,
    
    diameter_providedbyvendor TEXT,
    diameter_value_converted_value DOUBLE PRECISION,
    diameter_value_converted_unit TEXT,
    diameter_display_site_converted DOUBLE PRECISION,
    diameter_override_display_site_convrt_val DOUBLE PRECISION,
    diameter_override_display_site_convrt_unit TEXT,
    
    weight_providedbyvendor TEXT,
    weight_value_converted_value DOUBLE PRECISION,
    weight_value_converted_unit TEXT,
    weight_display_site_converted DOUBLE PRECISION,
    weight_override_display_site_convrt_value DOUBLE PRECISION,
    weight_override_display_site_convrt_unit TEXT,

    -- Attached Vessel Details
    attached_vessel_color TEXT,
    attached_vessel_height_value DOUBLE PRECISION,
    attached_vessel_height_unit TEXT,
    attached_vessel_length_value DOUBLE PRECISION,
    attached_vessel_length_unit TEXT,
    attached_vessel_width_value DOUBLE PRECISION,
    attached_vessel_width_unit TEXT,
    attache_vessel_material TEXT,

    -- Product Features
    size_set_pack DOUBLE PRECISION,
    shatter_resistant TEXT,
    tree_skirts_collars_shape TEXT,
    personalization_monogram TEXT,
    type_personalization TEXT,
    scent TEXT,
    scent_type TEXT,
    wick_wax_type TEXT,
    candle_burntime DOUBLE PRECISION,
    plays_music TEXT,
    handcrafted TEXT,
    handpainted TEXT,
    candle_type TEXT,

    -- Electrical/Power
    length_cord_inches_value DOUBLE PRECISION,
    length_cord_inches_unit TEXT,
    length_lit_length_value DOUBLE PRECISION,
    length_lit_length_unit TEXT,
    light_count DOUBLE PRECISION,
    assembly_required TEXT,
    batteries_included TEXT,
    batteries_required TEXT,
    batteries_number_required DOUBLE PRECISION,
    batteries_type_required TEXT,
    number_pairsofgloves DOUBLE PRECISION,
    tools_included TEXT,
    femaletree_toppercord TEXT,

    -- Tree Bags
    tree_bag_sku TEXT,
    number_tree_bags DOUBLE PRECISION,
    dimensions_tree_bag TEXT,

    -- Compliance / Certifications
    california_prop65_included TEXT,
    productcontains_lead TEXT,
    tax_weee_eligible TEXT,
    energy_star_certified TEXT,
    ul_certification TEXT,
    canadian_standards_association TEXT,
    government_compliance TEXT,
    warranty_periodoftime TEXT,
    return_standard TEXT,
    return_shipping_method TEXT,

    -- Vendor / Manufacturer
    vendor_productname TEXT,
    vendor_partnumber_sku TEXT,
    vendor_lightcolor TEXT,
    vendor_lighttype TEXT,
    vendor_color TEXT,
    vendor_contact_name TEXT,
    vendor_externalkey TEXT,
    vendor_label TEXT,
    vendor_street_address TEXT,
    vendor_city TEXT,
    vendor_state TEXT,
    vendor_zip_code TEXT,
    vendor_country TEXT,
    minimum_order_quantity DOUBLE PRECISION,
    third_party_liaisonagent TEXT,

    -- Marketing / PDP
    category_path TEXT,
    categorypage_pdp_badge TEXT,
    grid_layout TEXT,
    grid_rank DOUBLE PRECISION,
    display_product_out_of_stock TEXT,
    date_out_of_stock DATE,
    product_name_channel TEXT,
    onlinecatalog_prod_description TEXT,
    product_description_headline TEXT,
    product_description_shortened TEXT,
    pdpcontent_branch_details TEXT,
    pdpcontent_realism TEXT,
    pdpcontent_shape TEXT,
    pdpcontent_shapingtree TEXT,
    pdpcontent_storingtree TEXT,
    pdpcontent_typeofshapingtree TEXT,
    pdpcontent_typeofstoringtree TEXT,
    pdpcontent_lightguide TEXT,
    pdpcontent_assemblingtree TEXT,
    pdpcontent_whatsinbox TEXT,
    pdpcontent_whatsinboximage TEXT,
    pdpcontent_whatsinboxtext TEXT,
    pdpcontent_hyperlink_viewcount_weight TEXT,
    decorating_theme TEXT,
    gifting TEXT,
    light_design TEXT,
    needs_lifesize_largefigureverbiage TEXT,
    use_care_cleaning_recomdtn TEXT,
    cart_page_items_tree TEXT,
    addtnl_categories_item_appearin TEXT,
    balsam_hill_exclusive TEXT,
    print_catalog TEXT,
    foliagemodule_branchsamplekit TEXT,

    -- Logistics / Shipping
    approved_locations_cross_border_ship TEXT,
    port_of_origin TEXT,
    country_of_origin TEXT,
    shipping_method TEXT,
    oversized_shipping TEXT,
    extended_leadtimetoship TEXT,
    freight_classification TEXT,
    drop_ship TEXT,
    drop_ship_handling_fee_value DOUBLE PRECISION,
    drop_ship_handling_fee_unit TEXT,
    retailpackaging_available TEXT,
    standard_ship_cost DOUBLE PRECISION,
    ship_cost_2_day_value DOUBLE PRECISION,
    ship_cost_2_day_unit TEXT,
    express_ship_cost_value DOUBLE PRECISION,
    express_ship_cost_unit TEXT,
    alhi_ship_cost_value DOUBLE PRECISION,
    alhi_ship_cost_unit TEXT,
    canada_ship_cost_value DOUBLE PRECISION,
    canada_ship_cost_unit TEXT,
    puerto_rico_ship_cost_value DOUBLE PRECISION,
    puerto_rico_ship_cost_unit TEXT,
    masterpack_height_inches_value DOUBLE PRECISION,
    masterpack_height_inches_unit TEXT,
    masterpack_length_inches_value DOUBLE PRECISION,
    masterpack_length_lnches_unit TEXT,
    masterpack_width_inches_value DOUBLE PRECISION,
    masterpack_width_inches_unit TEXT,
    masterpack_weight_lbs_value DOUBLE PRECISION,
    masterpack_weight_lbs_unit TEXT,
    customs_info TEXT,
    duty TEXT,
    duty_charge_htc TEXT,
    item_restricted_contiguous_us TEXT,
    warehouse_return DOUBLE PRECISION,

    -- SEO and Content
    label TEXT,
    channel_status TEXT,
    language TEXT,
    seofollow_robotsmetatag TEXT,
    seoindex_robotsmetatag TEXT,
    seo_metadescription TEXT,
    seo_slug TEXT,
    seo_titletag TEXT,
    f_seo_followrobotsmetatag TEXT,
    f_seo_indexrobotsmetatag TEXT,
    f_seo_metadescription TEXT,
    f_seo_slug TEXT,
    f_seo_titletag TEXT,
    f_seo_hreflangdomain TEXT,
    f_seo_hreflangurl TEXT,
    f_seo_canonicaltag TEXT,
    f_externalkey TEXT,
    f_familycode TEXT,
    f_familydescription TEXT,
    compatibilitycode TEXT,
    adapterplug TEXT,
    transformer TEXT,
    voltagetype TEXT,
    warranty_eligibil_code_light DOUBLE PRECISION,
    warranty_eligibil_code_product DOUBLE PRECISION,
    warranty_eligibil_code_foliage DOUBLE PRECISION,
    type_of_serveware TEXT,
    type_of_storage TEXT,
    flavor TEXT,

    -- Product Metadata
    sap_number TEXT,
    pim_id TEXT,
    prodname_detailed_reporting TEXT,

    -- Materials
    percent_material TEXT,
    pe_percent_value DOUBLE PRECISION,
    pe_percent_unit TEXT,
    pvcpercent_value DOUBLE PRECISION,
    pvcpercent_unit TEXT,
    pineneedle_percent_value DOUBLE PRECISION,
    pineneedle_percent_unit TEXT,

    -- References and Mappings
    replacement_product_codes VARCHAR[],
    reference_product_codes VARCHAR[],
    mapped_product_code VARCHAR,
    mapped_product_code_description VARCHAR,
    is_mapped BOOLEAN DEFAULT FALSE,
    is_cadence_generated BOOLEAN DEFAULT FALSE,
    channel_approval TEXT
);