--liquibase formatted sql
--changeset Shaik.Azmathulla:product_attributes_filter_footlocker_v2 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for product_attributes_filter

CREATE TABLE IF NOT EXISTS "global".product_attributes_filter (
  --"product_code" varchar NOT NULL,
  	"cost" float8 NULL,
	created_at timestamptz NULL,
	updated_at timestamptz NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	replacement_product_codes _varchar NULL,
	reference_product_codes _varchar NULL,
	is_deleted bool NULL,
	product_code varchar NOT NULL,
	product_name varchar NOT NULL,
	product_description varchar NULL,
    original_price FLOAT8 NULL,
    sku_number VARCHAR NULL,
    l0_name VARCHAR NOT NULL,
    l1_name VARCHAR NOT NULL,
    l2_name VARCHAR NOT NULL,
    division_desc VARCHAR NULL,
    division_id VARCHAR NULL,
    l3_name VARCHAR NOT NULL,
    l2_id VARCHAR NULL,
    l4_name VARCHAR NOT NULL,
    l3_id VARCHAR NULL,
    article VARCHAR NOT NULL,
    l4_id VARCHAR NULL,
    color_way VARCHAR NOT NULL,
    colors VARCHAR NULL,
    global_brand_desc VARCHAR NULL,
    global_brand_id VARCHAR NULL,
    legacy_brand_desc VARCHAR NULL,
    legacy_brand_id VARCHAR NULL,
    ses_brand_desc VARCHAR NULL,
    ses_brand_id VARCHAR NULL,
    buying_unit_desc VARCHAR NULL,
    buying_unit_id VARCHAR NULL,
    los_desc VARCHAR NULL,
    season_code VARCHAR NULL,
    size_desc VARCHAR NULL,
    product_weight FLOAT8 NULL,
    us_vendor_name VARCHAR NULL,
    ca_vendor_name VARCHAR NULL,
    us_ses_vendor_name VARCHAR NULL,
    ca_ses_vendor_name VARCHAR NULL,
    silo_desc VARCHAR NULL,
    silo_id VARCHAR NULL,
    material_desc VARCHAR NULL,
    material_id VARCHAR NULL,
    assortment_desc VARCHAR NULL,
    assortment_code VARCHAR NULL,
    manufacturer_desc VARCHAR NULL,
    manufacturer_id VARCHAR NULL,
    designator_desc VARCHAR NULL,
    designator_id VARCHAR NULL,
    country_origin_desc VARCHAR NULL,
    country_origin_id VARCHAR NULL,
    gender_age_desc VARCHAR NULL,
    gender_age_id VARCHAR NULL,
    online_us_sku VARCHAR NULL,
    online_ca_sku VARCHAR NULL,
    vendor_style_number VARCHAR NULL,
    us_internal_product_number VARCHAR NULL,
    ca_internal_product_number VARCHAR NULL,
    last_refresh_date DATE NULL,

CONSTRAINT product_attributes_filter_pk PRIMARY KEY (product_code,l0_name)
)
PARTITION BY LIST (l0_name);
CREATE INDEX IF NOT EXISTS product_attributes_filter_l0_name_idx ON global.product_attributes_filter USING btree (l0_name);

