--liquibase formatted sql
--changeset linu.nazil:alerts_product_store_level stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for alerts_product_store_level
CREATE TABLE inventory_smart.alerts_product_store_level (
	store_code varchar NULL,
	last_allocated int4 NULL,
	lw_units float4 NULL,
	lw_revenue float4 NULL,
	lw_margin float4 NULL,
	promo float4 NULL,
	lw_aur float4 NULL,
	store_on_hand float4 NULL,
	total_store_on_hand float4 NULL,
	on_order float4 NULL,
	in_transit float4 NULL,
	wos_oh float4 NULL,
	wos_oh_oo float4 NULL,
	wos float4 NULL,
	united_legwear_whs int4 NULL,
	retail_bulk int4 NULL,
	retail_bulk_wh20 int4 NULL,
	puma_retail_stores_wh10 int4 NULL,
	us_continental int4 NULL,
	infinity int4 NULL,
	size_integrity float4 NULL,
	size_integrity_dc float4 NULL,
	stockout int4 NULL,
	shortfall int4 NULL,
	normal int4 NULL,
	excess int4 NULL,
	total_stores int4 NULL,
	clearance_alert int4 NULL,
	launch_alert int4 NULL,
	current_season_alert int4 NULL,
	shortfall_alert int4 NULL,
	stockout_alert int4 NULL,
	excess_alert int4 NULL,
	auto_alloc_alert int4 NULL,
	style_description varchar NULL,
	color varchar NULL,
	l2_name varchar NULL,
	l4_name varchar NULL,
	l5_name varchar NULL,
	article varchar NULL,
	l3_name varchar NULL,
	l1_name varchar NULL,
	l0_name varchar NULL,
	clearance_article bool NULL,
	articlestatustag varchar NULL,
	store_id varchar NULL,
	store_name varchar NULL,
	CONSTRAINT alerts_product_store_level_un UNIQUE (article, store_code)
);
ALTER TABLE inventory_smart.alerts_product_store_level ADD CONSTRAINT alerts_product_store_level_fk FOREIGN KEY (store_code) REFERENCES "global".store_master(store_code) ON DELETE CASCADE;
