import { END_DATE } from "config/constants/index";

export const TIME_PERIOD_FORM_FIELDS = [
  {
    sub_headers: [],
    label: "Start Date",
    accessor: "start_date",
    column_name: "start_date",
    dimension: "Product Mapping",
    field_type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 1,
    is_hidden: false,
    is_required: true,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: { disableOnlyPast: true },
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
  {
    sub_headers: [],
    label: "End Date",
    accessor: "end_date",
    column_name: "end_date",
    dimension: "Product Mapping",
    field_type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 2,
    is_hidden: false,
    is_required: false,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: { disableOnlyPast: true },
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
];

export const SET_ALL_FORM = [
  {
    sub_headers: [],
    label: "Rule Code",
    column_name: "rulecode",
    accessor: "rulecode",
    dimension: "mapping",
    type: "list",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 1,
    is_hidden: false,
    is_required: true,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    label: "Start Date",
    column_name: "start_date",
    accessor: "start_date",
    dimension: "mapping",
    type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 2,
    is_hidden: false,
    is_required: true,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: { disableOnlyPast: true },
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
  {
    sub_headers: [],
    label: "End Date",
    column_name: "end_date",
    accessor: "end_date",
    dimension: "mapping",
    type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 3,
    is_hidden: false,
    is_required: false,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: { disableOnlyPast: true },
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
];

export const SET_ALL_VALIDITY_FORM = [
  {
    sub_headers: [],
    label: "Start Date",
    column_name: "start_date",
    accessor: "start_date",
    dimension: "mapping",
    type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 2,
    is_hidden: false,
    is_required: true,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
  {
    sub_headers: [],
    label: "End Date",
    column_name: "end_date",
    accessor: "end_date",
    dimension: "mapping",
    type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 3,
    is_hidden: false,
    is_required: false,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
];

export const CUSTOM_FILTER = [
  {
    column_name: "time-period",
    default_value: null,
    dimension: "custom",
    display_order: 1,
    display_type: "rangePicker",
    disableType: "disableOnlyPast",
    extra: {},
    filter_keyword: "time-period",
    initialData: [],
    is_clearable: false,
    is_deleted: false,
    is_disabled: false,
    is_mandatory: true,
    is_multiple_selection: false,
    is_required: false,
    label: "Select Timeline",
    level: 6,
    mappedKey: "",
    range_max: null,
    range_min: null,
    type: "non-cascaded",
  },
];

// Style config for Row And Cell Renders.
// const styleConfig = {
//   rowStyles: [
//     {
//       styleFunction: firstStyleCase,
//       style: {
//         backgroundColor: "blue",
//       },
//       applyStylesFromFunction: false,
//     },
//     {
//       styleFunction: secondStyleCase,
//       style: {
//         backgroundColor: "red",
//       },
//       applyStylesFromFunction: false,
//     },
//   ],
//   cellStyle: {
//     primary_sku: [
//       {
//         styleFunction: firstStyleCase,
//         style: {
//           backgroundColor: "blue",
//         },
//         applyStylesFromFunction: false,
//       },
//       {
//         styleFunction: secondStyleCase,
//         style: {
//           backgroundColor: "red",
//         },
//         applyStylesFromFunction: false,
//       },
//     ],
//   },
// };
