--liquibase formatted sql
--changeset keerthi.vardhani@impactanalytics.co:sync_alerts_product_store_level_change_v6 runOnChange:true stripComments:false splitStatements:false context:ASync_Procedures labels:figs_sync_alerts_product_store_level
--comment: initial changeset for sync_alerts_product_store_level 

DROP PROCEDURE if exists  public.sync_alerts_product_store_level();

CREATE OR REPLACE PROCEDURE public.sync_alerts_product_store_level(IN _is_historic boolean DEFAULT true)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $procedure$
declare
	_log_code varchar := gen_random_uuid();
	_sp_name varchar := 'public.sync_alerts_product_store_level';
	_log_step varchar;
	_st TIMESTAMP := clock_timestamp();
begin
	call global.data_ingestion_logs(_log_code, _sp_name, 'start', null, (clock_timestamp() - _st)::text, null);
	perform set_config('local.log_code', _log_code, true);
	perform set_config('local.sp_name', _sp_name, true);
	begin
		delete from 
		  inventory_smart.alerts_product_store_level 
		where 
		  true; 
		INSERT INTO inventory_smart.alerts_product_store_level (
			article,
	store_code,
	l0_name ,
	l1_name ,
	l2_name ,
	l3_name ,
	l4_name ,
	s0_name ,
	s1_name ,
	s2_name ,
    style,
	channel ,
    channel_name ,
    product_description ,
	dc_flag ,
	excs_flg ,
	shrtfl_flg ,
	stckout_flg ,
	overstock ,
	shortfall ,
	stockout ,
	normal ,
	oh ,
	it ,
	oo ,
	lw_units ,
	lw_revenue ,
	lw_margin ,
	promo_percentage ,
	fwos ,
	size_integrity ,
	week_to_date_sales ,
	last_day_sales ,
	oh_dc ,
	sales_1_ago ,
	sales_2_ago ,
	sales_3_ago ,
	sales_4_ago ,
	sales_5_ago ,
	sales_6_ago ,
	sales_7_ago ,
	sales_8_ago ,
	lw_aur ,
    lw_store_units ,
    lw_sfs_units ,
    wos_oh ,
    promo_deviation_pct ,
    past_4_weeks_actual_promo ,
    next_4_weeks_planned_promo ,
    ly_deviation_pct ,
    ly_past_4wks_actual_sales ,
    ly_next_4wks_actual_sales ,
    past_4wks_promo_pct ,
    store_count_deviation_pct ,
    next_4wks_store_count ,
    past_4wks_store_count ,
    past_4wks_actual_sales ,
    forecast_deviation_pct ,
    in_stock_percentage ,
     first_sale_date ,
     last_receipt_date ,
    color_name ,
    tot_inv, 
	clearance_alert_flag ,
	newly_launched_alert_flag ,
	"Retirement_alert_flag" ,
    lw_price ,
    lw_aps ,
    sell_through_rate ,
    wos_oh_it ,
    forecast_this_wk ,
    forecast_next_week,
    forecast_4_next_week ,
    forecast_8_next_week ,
    next_4wks_promo_pct ,
    mfp_forecast_4_next_wk ,
    no_of_stores_oh ,
    store_name ,
     excs_is_resolved ,
     shrtfl_is_resolved ,
     stckout_is_resolved ,
     oo_dc ,
     lw_discount_amount ,
    lw_discount_percentage ,
     dc_available ,
     dc_oo ,
     dc_oo_30_days ,
     hybrid_wos ,
     hybrid_wos_oh_it ,
     upas ,
     style_color_status ,
     dc_oo_po ,
     it_dc ,
     available_stores_percentage ,
     in_stock_count ,
     total_count ,
     store_level_prediction ,
        color_id,
      style_type,
      f_style_fabric,
      replenish_status,
      style_name
        ) 
        SELECT distinct
            apsl.article,
            apsl.store_code,
            paf.l0_name,
            paf.l1_name,
            paf.l2_name,
            apsl.l3_name,
            paf.l4_name,
            apsl.s0_name,
            apsl.s1_name,
            apsl.s2_name,
            paf.style_name as style,
            apsl.channel,
            apsl.channel_name,
            apsl.article as product_description,
            apsl.dc_flag,
            apsl.excs_flg,
            apsl.shrtfl_flg,
            apsl.stckout_flg,
            apsl.overstock,
            apsl.shortfall,
            apsl.stockout,
            apsl.normal,
            apsl.oh,
            apsl.it,
            apsl.oo,
            apsl.lw_units,
            apsl.lw_revenue,
            apsl.lw_margin,
            apsl.promo_percentage,
            apsl.fwos,
            apsl.size_integrity ,
	apsl.week_to_date_sales ,
	apsl.last_day_sales ,
	apsl.oh_dc ,
	apsl.sales_1_ago ,
	apsl.sales_2_ago ,
	apsl.sales_3_ago ,
	apsl.sales_4_ago ,
	apsl.sales_5_ago ,
	apsl.sales_6_ago ,
	apsl.sales_7_ago ,
	apsl.sales_8_ago ,
	apsl.lw_aur ,
    apsl.lw_store_units ,
    apsl.lw_sfs_units ,
    apsl.wos_oh ,
    apsl.promo_deviation_pct ,
    apsl.past_4_weeks_actual_promo ,
    apsl.next_4_weeks_planned_promo ,
    apsl.ly_deviation_pct ,
    apsl.ly_past_4wks_actual_sales ,
    apsl.ly_next_4wks_actual_sales ,
    apsl.past_4wks_promo_pct ,
    apsl.store_count_deviation_pct ,
    apsl.next_4wks_store_count ,
    apsl.past_4wks_store_count ,
    apsl.past_4wks_actual_sales ,
    apsl.forecast_deviation_pct ,
    apsl.in_stock_percentage ,
     apsl.first_sale_date ,
     apsl.last_receipt_date ,
    paf.color_id as color_name ,
    apsl.tot_inv, 
	apsl.clearance_alert_flag ,
	apsl.newly_launched_alert_flag ,
	apsl."Retirement_alert_flag" ,
    apsl.lw_price ,
    apsl.lw_aps ,
    apsl.sell_through_rate ,
    apsl.wos_oh_it ,
    apsl.forecast_this_wk  ,
    apsl.forecast_next_wk as forecast_next_week,
    apsl.forecast_4_next_wk as forecast_4_next_week ,
    apsl.forecast_8_next_wk as forecast_8_next_week,
    apsl.next_4wks_promo_pct ,
    apsl.mfp_forecast_4_next_wk ,
    apsl.no_of_stores_oh ,
    apsl.store_name ,
     apsl.excs_is_resolved ,
     apsl.shrtfl_is_resolved ,
     apsl.stckout_is_resolved ,
     apsl.oo_dc ,
     apsl.lw_discount_amount ,
    apsl.lw_discount_percentage ,
     apsl.dc_available ,
     apsl.dc_oo ,
     apsl.dc_oo_30_days ,
     apsl.hybrid_wos ,
     apsl.hybrid_wos_oh_it ,
     apsl.upas ,
     apsl.style_color_status ,
     apsl.dc_oo_po ,
     apsl.it_dc ,
     apsl.available_stores_percentage ,
     apsl.in_stock_count ,
     apsl.total_count ,
     apsl.store_level_prediction ,
    paf.color_id,
    paf.style_type,
    paf.f_style_fabric,
    paf.replenish_status,
    paf.style_name        
        FROM 
		  public.alerts_product_store_level apsl
          LEFT JOIN global.product_attributes_filter paf ON apsl.article = paf.article
          LEFT JOIN global.store_attributes_filter saf using(store_code)
          where not paf.is_deleted
		;
		call global.data_ingestion_logs(_log_code, _sp_name, 'end', null, (clock_timestamp() - _st)::text, null);
	exception
		when others then
	        -- Log the error if an exception occurs during any part of the procedure
	        call global.data_ingestion_logs(_log_code, _sp_name, _log_step, SQLERRM, (clock_timestamp() - _st)::text, null);
            raise exception 'Error occurred in the procedure: %', SQLERRM;
	end;
	end
$procedure$
;