--liquibase formatted sql
--changeset liquibase:product_master_sku stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for product_master
CREATE TABLE price_markdown.product_master_sku (
	l0_id int4 NULL,
	l0_name text NULL,
	l0_cuq text NULL,
	l0_cid int4 NULL,
	l1_id int4 NULL,
	l1_name text NULL,
	l1_cuq text NULL,
	l1_cid int4 NULL,
	l2_id int4 NULL,
	l2_name text NULL,
	l2_cuq text NULL,
	l2_cid int4 NULL,
	l3_id int4 NULL,
	l3_name text NULL,
	l3_cuq text NULL,
	l3_cid int4 NULL,
	l4_id int8 NULL,
	l4_name text NULL,
	l4_cuq text NULL,
	l4_cid int4 NULL,
	brand text NULL,
	brand_cid int4 NULL,
	org_brand text NULL,
	l5_id int8 NULL,
	l5_cuq text NULL,
	l5_cid int4 NULL,
	style_id int8 NULL,
	style_cuq text NULL,
	style_desc text NULL,
	mfg_no int8 NULL,
	mfg_name text NULL,
	product_id int8 NULL,
	sku_id int8 NOT NULL,
	sku_name text NULL,
	product_name text NULL,
	product_cuq text NULL,
	msrp float8 NULL,
	launch_price float8 NULL,
	current_price float8 NULL,
	"cost" float8 NULL,
	ecom_shipping_cost int4 NULL,
	phase_id text NULL,
	phase_desc text NULL,
	launch_date date NULL,
	eol_flag text NULL,
	lifecycle_indicator text NULL,
	clearance_indicator int4 NULL,
	dropship_indicator text NULL,
	bopis text NULL,
	status text NULL,
	active bool NULL,
	is_active int4 NULL,
	store_age int4 NULL,
	ecom_age int4 NULL,
	max_age int4 NULL,
	age_month_bucket text NULL,
	fob text NULL,
	original_style_desc text NULL,
	st_bnm float4 NULL,
	st_ecom float4 NULL,
	clearance_eligible_bnm int4 NULL,
	clearance_eligible_ecom int4 NULL,
	last_reg_price_bnm float4 NULL,
	last_reg_price_ecom float4 NULL,
	clearance_eligible int4 DEFAULT 1 NULL,
	CONSTRAINT product_master_sku_pk PRIMARY KEY (sku_id)
);
CREATE INDEX product_master_sku_mkd_is_active_idx ON price_markdown.product_master_sku USING btree (is_active);
CREATE INDEX product_master_sku_mkd_product_id_idx ON price_markdown.product_master_sku USING btree (product_id);