import { INVENTORY_SUBMODULES_NAMES } from "modules/inventorysmart/constants-inventorysmart/stringConstants";

const {
  INVENTORY_STORE_CONSTRAINTS,
  INVENTORY_STORE_GRADE_CONSTRAINTS,
  INVENTORY_STORE_GROUP_CONSTRAINTS,
  INVENTORY_ORDER_STATUS,
  INVENTORY_ORDER_DELIVERY,
  INVENTORY_ORDER_ORDERING,
  INVENTORY_ORDER_SAFETY_STOCK,
  INVENTORY_ORDER_POLICY,
  INVENTORY_PO_CONVERSION,
  INVENTORY_USER_RESERVE,
  INVENTORY_SMA,
} = INVENTORY_SUBMODULES_NAMES;

export const tabModulePermissionMap = {
  store_allocations: [
    INVENTORY_STORE_CONSTRAINTS,
    INVENTORY_STORE_GRADE_CONSTRAINTS,
    INVENTORY_STORE_GROUP_CONSTRAINTS,
  ],
  constraints_oms: [
    INVENTORY_ORDER_STATUS,
    INVENTORY_ORDER_DELIVERY,
    INVENTORY_ORDER_ORDERING,
    INVENTORY_ORDER_SAFETY_STOCK,
    INVENTORY_ORDER_POLICY,
    INVENTORY_PO_CONVERSION,
  ],
  user_reserve: [INVENTORY_USER_RESERVE],
  sma: [INVENTORY_SMA],
};

export const omsTabModulePermissionMap = {
  constraints_status: [INVENTORY_ORDER_STATUS],
  constraints_delivery: [INVENTORY_ORDER_DELIVERY],
  constraints_ordering: [INVENTORY_ORDER_ORDERING],
  constraints_safety_stock: [INVENTORY_ORDER_SAFETY_STOCK],
  constraints_order_policy: [INVENTORY_ORDER_POLICY],
  constraints_po_conversion: [INVENTORY_PO_CONVERSION],
};
