--liquibase formatted sql
--changeset srinivasgowda.sg@impactanalytics.co :assort_smart.line_plan_choice_launch stripComments:false splitStatements:false context:MTP-129397 labels:opt_to_line_plan_choice_launch
--comment: opt changeset for line_plan_choice_launch

CREATE TABLE assort_smart.line_plan_choice_launch (
    id bigserial NOT NULL,
	plan_code int4 NOT NULL,
	hierarchy_code varchar NOT NULL,
	final_level varchar NOT NULL,
	channel int4 NOT NULL,
	sub_channel int4 NOT NULL,
	gender varchar NULL,
	season_code varchar NULL,
	placeholder_choice_id varchar NOT NULL,
	placeholder_style_id varchar NOT NULL,
	image_name_url varchar NULL,
	style_id varchar NULL,
	color_id varchar NULL,
	style_name varchar NULL,
	color_name varchar NULL,
	style_tag varchar NULL,
	launch varchar NULL,
	launch_start_date date NULL,
	launch_end_date date NULL,
	split_by_delivery bool NULL,
	delivery_count int4 NULL,
	product_launch_date date NULL,
	product_exit_date date NULL,
	launch_season varchar NULL,
	"attributes" jsonb NULL,
	cluster_code varchar NULL,
	cluster_display_name varchar NULL,
	cluster_store_count int4 NULL,
	flow_cluster_perc float8 DEFAULT 0.0 NULL,
	total_inv_units jsonb NULL,
	sales_units jsonb NULL,
	receipt_units jsonb NULL,
	receipts_price_per_unit jsonb NULL,
	aps jsonb NULL,
	sales jsonb NULL,
	receipts jsonb NULL,
	st jsonb NULL,
	avg_wk_cnt jsonb NULL,
	gross_margin jsonb NULL,
	aur jsonb NULL,
	air jsonb NULL,
	aic jsonb NULL,
	last_season jsonb NULL,
	is_deleted bool DEFAULT false NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	global_choice_id varchar(255) NULL,
	below_moq_flag int4 DEFAULT 0 NOT NULL,
	nrf_color_bucket varchar NULL,
	carryover_style varchar NULL,
	min_per_order varchar NULL,
	marketing varchar NULL,
	exit_floorset varchar NULL,
	sample_request varchar NULL,
	vendor_name varchar NULL,
	merchant_comments varchar NULL,
	planner_comments varchar NULL,
	attr_comment_1 varchar NULL,
	attr_comment_2 varchar NULL,
	attr_comment_3 varchar NULL,
	attr_comment_4 varchar NULL,
	size_range_type varchar NULL,
	relevant_size text NULL,
	initial_sales_date date NULL,
	style_color varchar NULL,
	flex_subclass_code varchar NULL,
	flex_subclass varchar NULL,
	flex_size_range varchar NULL,
	global_style_id varchar(255) DEFAULT NULL::character varying NULL,
	target_imu_per float8 DEFAULT 0 NULL,
	imu_per float8 DEFAULT 0 NULL,
	placeholder_choice_id_order int4 DEFAULT 0 NULL,
	vendor_product_id varchar(255) DEFAULT NULL::character varying NULL,
	product_description varchar(255) DEFAULT NULL::character varying NULL,
	"range" varchar(255) DEFAULT NULL::character varying NULL,
	color_family varchar(255) DEFAULT NULL::character varying NULL,
	value_stream varchar(255) DEFAULT NULL::character varying NULL,
	season varchar(255) DEFAULT NULL::character varying NULL,
	season_year varchar(255) DEFAULT NULL::character varying NULL,
	price_architecture varchar(255) DEFAULT NULL::character varying NULL,
	sustainability varchar(255) DEFAULT NULL::character varying NULL,
	commitment_type varchar(255) DEFAULT NULL::character varying NULL,
	choice_status varchar(255) DEFAULT NULL::character varying NULL,
	country_of_origin varchar(255) DEFAULT NULL::character varying NULL,
	material varchar(255) DEFAULT NULL::character varying NULL,
	pattern varchar(255) DEFAULT NULL::character varying NULL,
	fit varchar(255) DEFAULT NULL::character varying NULL,
	width varchar(255) DEFAULT NULL::character varying NULL,
	license varchar(255) DEFAULT NULL::character varying NULL,
	down_ratio varchar(255) DEFAULT NULL::character varying NULL,
	thread_count varchar(255) DEFAULT NULL::character varying NULL,
	global_choice_id_order int4 DEFAULT 0 NOT NULL,
	global_style_id_order int4 DEFAULT 0 NOT NULL,
	placeholder_style_id_order int4 DEFAULT 0 NOT NULL,
	sales_units_season numeric GENERATED ALWAYS AS ((sales_units ->> 'season'::text)::numeric) STORED NULL,
	sales_units_lifecycle numeric GENERATED ALWAYS AS ((sales_units ->> 'lifecycle'::text)::numeric) STORED NULL,
	sales_units_season_reco numeric GENERATED ALWAYS AS ((sales_units ->> 'season_reco'::text)::numeric) STORED NULL,
	sales_units_lifecycle_reco numeric GENERATED ALWAYS AS ((sales_units ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	receipt_units_season numeric GENERATED ALWAYS AS ((receipt_units ->> 'season'::text)::numeric) STORED NULL,
	receipt_units_lifecycle numeric GENERATED ALWAYS AS ((receipt_units ->> 'lifecycle'::text)::numeric) STORED NULL,
	receipt_units_season_reco numeric GENERATED ALWAYS AS ((receipt_units ->> 'season_reco'::text)::numeric) STORED NULL,
	receipt_units_lifecycle_reco numeric GENERATED ALWAYS AS ((receipt_units ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	sales_season numeric GENERATED ALWAYS AS ((sales ->> 'season'::text)::numeric) STORED NULL,
	sales_lifecycle numeric GENERATED ALWAYS AS ((sales ->> 'lifecycle'::text)::numeric) STORED NULL,
	gross_margin_season numeric GENERATED ALWAYS AS ((gross_margin ->> 'season'::text)::numeric) STORED NULL,
	gross_margin_lifecycle numeric GENERATED ALWAYS AS ((gross_margin ->> 'lifecycle'::text)::numeric) STORED NULL,
	aps_season numeric GENERATED ALWAYS AS ((aps ->> 'season'::text)::numeric) STORED NULL,
	aps_lifecycle numeric GENERATED ALWAYS AS ((aps ->> 'lifecycle'::text)::numeric) STORED NULL,
	st_season numeric GENERATED ALWAYS AS (((st ->> 'season'::text)::numeric) / 100.0) STORED NULL,
	st_lifecycle numeric GENERATED ALWAYS AS (((st ->> 'lifecycle'::text)::numeric) / 100.0) STORED NULL,
	st_season_reco numeric GENERATED ALWAYS AS (((st ->> 'season_reco'::text)::numeric) / 100.0) STORED NULL,
	st_lifecycle_reco numeric GENERATED ALWAYS AS (((st ->> 'lifecycle_reco'::text)::numeric) / 100.0) STORED NULL,
	aur_season numeric GENERATED ALWAYS AS ((aur ->> 'season'::text)::numeric) STORED NULL,
	aur_lifecycle numeric GENERATED ALWAYS AS ((aur ->> 'lifecycle'::text)::numeric) STORED NULL,
	air_season numeric GENERATED ALWAYS AS ((air ->> 'season'::text)::numeric) STORED NULL,
	air_lifecycle numeric GENERATED ALWAYS AS ((air ->> 'lifecycle'::text)::numeric) STORED NULL,
	total_inv_units_bop_qty numeric GENERATED ALWAYS AS ((total_inv_units ->> 'bop_qty'::text)::numeric) STORED NULL,
	total_inv_units_season numeric GENERATED ALWAYS AS ((total_inv_units ->> 'season'::text)::numeric) STORED NULL,
	total_inv_units_lifecycle numeric GENERATED ALWAYS AS ((total_inv_units ->> 'lifecycle'::text)::numeric) STORED NULL,
	avg_wk_cnt_season numeric GENERATED ALWAYS AS ((avg_wk_cnt ->> 'season'::text)::numeric) STORED NULL,
	avg_wk_cnt_lifecycle numeric GENERATED ALWAYS AS ((avg_wk_cnt ->> 'lifecycle'::text)::numeric) STORED NULL,
	avg_wk_cnt_season_reco numeric GENERATED ALWAYS AS ((avg_wk_cnt ->> 'season_reco'::text)::numeric) STORED NULL,
	avg_wk_cnt_lifecycle_reco numeric GENERATED ALWAYS AS ((avg_wk_cnt ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	aic_season numeric GENERATED ALWAYS AS ((aic ->> 'season'::text)::numeric) STORED NULL,
	aic_lifecycle numeric GENERATED ALWAYS AS ((aic ->> 'lifecycle'::text)::numeric) STORED NULL,
	aic_season_reco numeric GENERATED ALWAYS AS ((aic ->> 'season_reco'::text)::numeric) STORED NULL,
	aic_lifecycle_reco numeric GENERATED ALWAYS AS ((aic ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	receipts_season numeric GENERATED ALWAYS AS ((receipts ->> 'season'::text)::numeric) STORED NULL,
	receipts_lifecycle numeric GENERATED ALWAYS AS ((receipts ->> 'lifecycle'::text)::numeric) STORED NULL,
	receipts_season_reco numeric GENERATED ALWAYS AS ((receipts ->> 'season_reco'::text)::numeric) STORED NULL,
	receipts_lifecycle_reco numeric GENERATED ALWAYS AS ((receipts ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	sales_season_reco numeric GENERATED ALWAYS AS ((sales ->> 'season_reco'::text)::numeric) STORED NULL,
	sales_lifecycle_reco numeric GENERATED ALWAYS AS ((sales ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	gross_margin_season_reco numeric GENERATED ALWAYS AS ((gross_margin ->> 'season_reco'::text)::numeric) STORED NULL,
	gross_margin_lifecycle_reco numeric GENERATED ALWAYS AS ((gross_margin ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	aps_season_reco numeric GENERATED ALWAYS AS ((aps ->> 'season_reco'::text)::numeric) STORED NULL,
	aps_lifecycle_reco numeric GENERATED ALWAYS AS ((aps ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	aur_season_reco numeric GENERATED ALWAYS AS ((aur ->> 'season_reco'::text)::numeric) STORED NULL,
	aur_lifecycle_reco numeric GENERATED ALWAYS AS ((aur ->> 'lifecycle_reco'::text)::numeric) STORED NULL,
	air_season_reco numeric GENERATED ALWAYS AS ((air ->> 'season_reco'::text)::numeric) STORED NULL,
	air_lifecycle_reco numeric GENERATED ALWAYS AS ((air ->> 'lifecycle_reco'::text)::numeric) STORED NULL
)
PARTITION BY LIST (plan_code);
CREATE INDEX idx_lpcl_attrs ON  assort_smart.line_plan_choice_launch USING gin (attributes jsonb_path_ops);
CREATE INDEX idx_lpcl_choice ON  assort_smart.line_plan_choice_launch USING btree (plan_code, placeholder_choice_id);
CREATE INDEX idx_lpcl_join ON  assort_smart.line_plan_choice_launch USING btree (hierarchy_code, cluster_code);
CREATE INDEX idx_lpcl_kpi_season ON  assort_smart.line_plan_choice_launch USING btree (plan_code, sales_units_season, total_inv_units_season);
CREATE INDEX idx_lpcl_primary ON  assort_smart.line_plan_choice_launch USING btree (plan_code, final_level, channel, season_code);
CREATE INDEX idx_lpcl_style ON  assort_smart.line_plan_choice_launch USING btree (plan_code, placeholder_style_id, global_style_id);
CREATE INDEX idx_lpcl_style_tag ON  assort_smart.line_plan_choice_launch USING btree (plan_code, style_tag);

--changeset ezhil.kannan@impactanalytics.co:add_index_lpcl_id_briscoes stripComments:false splitStatements:false context:perf_optimization labels:add_index
--comment: Add index on id for apply_constraint stored procedure UPDATE performance
CREATE INDEX IF NOT EXISTS idx_lpcl_id ON assort_smart.line_plan_choice_launch (id);

--changeset ezhil.kannan@impactanalytics.co:add_index_lpcl_merge_join_briscoes stripComments:false splitStatements:false context:perf_optimization labels:add_index
--comment: Avoid Nested Loop 361M rows removed by join filter; Merge Join sort Disk spill. EXPLAIN: Join Filter (plan_code,final_level)=ANY(CTE arrays), Sort Key (plan_code, final_level, placeholder_choice_id).
CREATE INDEX IF NOT EXISTS idx_lpcl_plan_code_final_level_placeholder_choice_id ON assort_smart.line_plan_choice_launch (plan_code, final_level, placeholder_choice_id);
CREATE INDEX IF NOT EXISTS idx_lpcl_plan_code_final_level ON assort_smart.line_plan_choice_launch (plan_code, final_level);

--changeset mehul.jain@impactanalytics.co:alter_vendor_product_id_to_integer stripComments:false splitStatements:false context:alter_vendor_product_id labels:alter_vendor_product_id_column
--comment: Alter vendor_product_id column from varchar to integer
ALTER TABLE assort_smart.line_plan_choice_launch ADD COLUMN vendor_product_id_int integer DEFAULT NULL;
UPDATE assort_smart.line_plan_choice_launch SET vendor_product_id_int = vendor_product_id::integer;
ALTER TABLE assort_smart.line_plan_choice_launch DROP COLUMN vendor_product_id;
ALTER TABLE assort_smart.line_plan_choice_launch RENAME COLUMN vendor_product_id_int TO vendor_product_id;