import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles(() => ({
  pannelContainer: {
    padding: "16px 12px 12px",
    background: "#fff",
    borderRadius: "8px",
    overflow: "hidden",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
  },
  flex_1: {
    flex: 1,
  },
  cardWrapper: {
    border: "1px solid #E5E8EB",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
    padding: "16px 24px",
    height: "100%",
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    transition: "all 0.2s ease-in-out",
    width: "fit-content",
    overflow: "visible",
    minWidth: 0,
    "&:hover": {
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    },
  },
  allocatedQtyCardWrapper: {
    border: "1px solid #E5E8EB",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
    padding: "16px 24px",
    height: "100%",
    display: "flex",
    alignItems: "center",
    whiteSpace: "nowrap",
    width: "fit-content",
    overflow: "visible",
    minWidth: 0,
  },
  cardStyles_WithNoSubMetrics: {
    width: "fit-content",
    borderRadius: "8px",
    minWidth: 0,
  },
  flexContainerStyles: {
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    alignItems: "center",
  },
  flexItemStyles: {
    display: "flex",
    alignItems: "center",
    height: "30px",
  },
  titleSubTitleFlex: {
    display: "flex",
    flexDirection: "column",
    marginTop: "5px",
  },
  marginTop_10: {
    marginTop: "10px",
  },
  marginRight_10: {
    marginRight: "10px",
  },
  flex_center: {
    display: "flex",
    alignItems: "center",
  },
  flex_column: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    margin: "0 8px",
    minWidth: 0,
    flex: "0 1 auto",
    width: "auto",
  },
  dividerLine: {
    width: "1px",
    height: "12px",
    margin: "0 8px",
    backgroundColor: "#d9dde7",
  },
  dividerLine12: {
    width: "1px",
    height: "12px",
    margin: "0 12px",
    backgroundColor: "#d9dde7",
  },
  icon_container: {
    borderRadius: "50%",
    width: "52px",
    height: "45px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "12px",
  },
  noSubMetricsFlexContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
  },
  noSubMetricsLabelStyles: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "16px",
    fontWeight: 600,
    whiteSpace: "nowrap",
    lineHeight: "24px",
    overflow: "visible",
  },
  labelContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "auto",
    minWidth: 0,
  },
  noSubMertricsValueStyles: {
    color: "#1F2B4D",
    fontFamily: "Manrope",
    fontSize: "16px",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  subHeaderValueStyles: {
    fontSize: "16px",
    fontWeight: 600,
  },
  flex_row: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
  },
  panelHeaderTestStyles: {
    fontSize: "14px",
    fontFamily: "Manrope",
    fontWeight: "bold",
  },
  panelHeaderContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  panelContentContainer: {
    display: "flex",
    flexDirection: "row",
    gap: "16px",
    overflowY: "auto",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  kpiBox: {
    borderRadius: "16px",
    boxShadow: "0 4px 12px 0 rgba(0, 0, 0, 0.02), 0 1px 3px 0 rgba(0, 0, 0, 0.04)",
    display: "flex",
    background: "#FFF",
    padding: "20px",
    border: "1px solid rgba(0, 0, 0, 0.06)",
    alignItems: "center",
  },
  kpiBoxMiddleDivider: {
    width: "1px",
    height: "20px",
    backgroundColor: "#D9DDE7",
    margin: "0 16px",
  },
  kpiBoxLeftSection: {
    display: "flex",
    flexDirection: "row",
    gap: "16px",
    alignItems: "center",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  kpiMetricChip: {
    display: "flex",
    flexDirection: "row",
    gap: "8px",
    backgroundColor: "#F5F6FA",
    border: "0.216px solid #D9DDE7",
    borderRadius: "8px",
    padding: "6px 8px",
    justifyContent: "space-between",
    alignItems: "center",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  kpiMetricTitle: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#1F2B4D",
    whiteSpace: "nowrap",
  },
  kpiMetricValue: {
    fontSize: "16px",
    fontWeight: 800,
    color: "#1F2B4D",
    whiteSpace: "nowrap",
  },
    kpiMetricChangePositive: {
      fontSize: "14px",
      fontWeight: 400,
      color: "#3BB273",
    },
    kpiMetricChangeNegative: {
      fontSize: "14px",
      fontWeight: 400,
      color: "#E15554",
    },
  kpiBoxRightRow: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: "8px",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  kpiBoxRightSection: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    alignItems: "stretch",
    flex: 1,
  },
  kpiBoxLeftTitleSection:{
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: "4px",
    position: "relative",
  },
  moreInfoPopover: {
    minWidth: "220px",
    maxWidth: "520px",
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "12px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15)",
    zIndex: 1500,
  },
  editPopoverBody: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    paddingTop: "16px",
  },
  editPopoverActions: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: "8px",
  },
  kpiMoreInfo:{
    fontSize: "14px",
    fontWeight: 500,
    color: "#4259EE",
    cursor: "pointer",
  },
  kpiMoreInfoText:{
    fontSize: "14px",
    fontWeight: 500,
    color: "#60697D",
    whiteSpace: "nowrap",
  },
  topRightSection: {
    display: "flex",
    height: "56px",
    flexDirection: "row",
    gap: "16px",
    alignItems: "center",
    padding: "12px 20px",
    alignSelf: "stretch",
    borderRadius: "8px",
    border: "1px solid #D9DDE7",
    marginBottom: "8px",
  },
  topRightSectionText:{
    fontSize: "16px",
    fontWeight: 600,
    lineHeight: "24px",
    color: "#1F2B4D",
  },
  topRightDivider: {
    width: 0,
    height: "16px",
    borderLeft: "1px solid #D9DDE7",
  },
  expandButton:{
    border: "1px solid #C3C8D4",
    borderRadius: "8px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "32px",
    height: "32px",
    "&:hover": {
        border: "1px solid #3649c6", 
    },
  },
  expandedPanelContainerStyles: {
    display: "flex",
    flexWrap: "wrap",
    gap: "24px",
    width: "100%",
    alignItems: "stretch",
  },
  nonExpandedContainerStyles: {
    display: "flex",
    alignItems: "stretch",
    gap: "24px",
    width: "100%",
    flex: 1,
    overflowX: "auto",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  cardItemContainer: {
    flex: "0 0 auto",
    height: "auto",
    minHeight: "96px",
    whiteSpace: "nowrap",
    width: "fit-content",
  },
  expandedCardItemContainer: {
    marginBottom: "16px",
    height: "auto",
    minHeight: "96px",
    whiteSpace: "nowrap",
    display: "flex",
    flex: "0 1 auto",
    width: "fit-content",
    minWidth: "220px",
    overflow: "visible",
  },
  dcDataContainer: {
    display: "flex",
    overflowX: "auto",
    whiteSpace: "nowrap",
    width: "100%",
    minWidth: 0,
    gap: "8px",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    "&::-webkit-scrollbar": {
      display: "none",
    },
  },
  dcDataItem: {
    alignItems: "center",
    padding: "4px 8px",
    display: "flex",
    backgroundColor: "#F5F6FA",
    borderRadius: "8px",
    flexShrink: 0,
  },
  dcDataLabel: {
    fontSize: "14px",
    color: "#1F2B4D",
    fontWeight: "500",
    marginRight: "8px",
  },
  arrowButton: {
    cursor: "pointer",
    marginLeft: "8px",
  },
  subHeaderLabel: {
    fontSize: "14px",
    color: "#1F2B4D",
    marginRight: "8px",
    fontWeight: "500",
  },
  popoverHeader: {
    height: "24px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  popoverTitle: {
    fontSize: "16px",
    fontWeight: "800",
    color: "#1F2B4D",
  },
  popoverCloseButton: {
    padding: "4px",
    cursor: "pointer",
  },
  popoverContent: {
    paddingTop: "16px",
  },
  moreInfoColumns: {
    display: "flex",
    flexDirection: "row",
    gap: "16px",
  },
  moreInfoColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  moreInfoColumnTitle: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#1F2B4D",
  },
  moreInfoChipColumn: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    alignItems: "stretch",
    "& $kpiMetricChip": {
      width: "100%",
    },
  },
  moreInfoText: {
    fontSize: "14px",
    fontWeight: 500,
    color: "#1F2B4D",
  },
  paddingBottom8: {
    paddingBottom: "8px",
  },
  paddingBottom4: {
    paddingBottom: "4px",
  },
  popoverSizeGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  popoverSizeRow: {
    display: "flex",
    gap: "8px",
  },
  popoverSizeColumn: {
    display: "flex", 
    width: "48%",
    gap: "4px",
  },
  singleItemSize:{
    display: "flex",
    width: "100%",
  },
  popoverDividerLine: {
    width: "1px",
    height: "12px",
    backgroundColor: "#d9dde7", 
  },
  popoverSizeItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  popoverSizeLabel: {
    fontSize: "14px",
    color: "#1F2B4D",
    fontWeight: "500",
    width: "65%", 
    whiteSpace: "nowrap", 
    overflow: "hidden", 
    textOverflow: "ellipsis", 
  },
  popoverSizeValue: {
    fontSize: "16px",
    fontWeight: "800",
    color: "#1F2B4D",
    width: "32%", 
    whiteSpace: "nowrap", 
    overflow: "hidden", 
    textOverflow: "ellipsis", 
  },
  popoverSizeItemContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "8px 4px",
    backgroundColor: "#F5F6FA",
    borderRadius: "4px",
  },
  verticalSeparator: {
    width: "1px",
    height: "24px",
    backgroundColor: "#D9DDE7",
  },
  kpiContainerWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  scrollButtonWrapperLeft: {
    position: "absolute",
    left: "4px",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10,
    "& .ia-btn-tertiary": {
      backgroundColor: "#eceefd !important",
      borderColor: "#3649c6 !important",
      color: "#3649c6 !important",
    },
    "& .ia-btn-tertiary svg": {
      color: "#3649c6 !important",
    },
    "& .ia-btn-tertiary svg path": {
      fill: "#3649c6 !important",
    },
  },
  scrollButtonWrapperRight: {
    position: "absolute",
    right: "4px",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 10,
    "& .ia-btn-tertiary": {
      backgroundColor: "#eceefd !important",
      borderColor: "#3649c6 !important",
      color: "#3649c6 !important",
    },
    "& .ia-btn-tertiary svg": {
      color: "#3649c6 !important",
    },
    "& .ia-btn-tertiary svg path": {
      fill: "#3649c6 !important",
    },
  },
  edgeFade: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "144px",
    pointerEvents: "none",
    zIndex: 5,
    backdropFilter: "blur(3.8px)",
    WebkitBackdropFilter: "blur(3.8px)",
    "@media (max-width: 1440px)": {
      width: "90px",
    },
    "@media (max-width: 1366px)": {
      width: "85px",
    },
    "@media (max-width: 1280px)": {
      width: "80px",
    },
    "@media (max-width: 1024px)": {
      width: "64px",
    },
  },
  edgeFadeLeft: {
    left: 0,
    maskImage: "linear-gradient(to right, black 0%, transparent 100%)",
    WebkitMaskImage:
      "linear-gradient(to right, black 0%, transparent 100%)",
  },
  edgeFadeRight: {
    right: 0,
    maskImage: "linear-gradient(to left, black 0%, transparent 100%)",
    WebkitMaskImage: "linear-gradient(to left, black 0%, transparent 100%)",
  },
  customScrollTrack: {
    bottom: "7px",
    left: 0,
    right: 0,
    margin: "0 auto",
    width: "120px",
    height: "8px",
    borderRadius: "999px",
    backgroundColor: "#F6F5FA",
    position: "absolute",
    overflow: "hidden",
    zIndex: 10,
  },
  customScrollThumb: {
    position: "absolute",
    top: 0,
    left: 0,
    height: "100%",
    width: "40px",
    strokeWidth: "8px",
    borderRadius: "999px",
    backgroundColor: "#7A8294",
  },
  kpiContainer: {
    position: "relative",
    padding: "16px 16px 20px 16px",
    background: "#fff",
    borderRadius: "8px",
    overflow: "hidden",
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    borderBottom: "1px solid var(--Colors-Neutrals-Border-Subtle, #D9DDE7)"
  },
}));