--liquibase formatted sql
    --changeset rohankumar.sinha:marksmart_product_master_pricesmart_version stripComments:false splitStatements:false context:marksmart_product_master_pricesmart_version
    --comment: initial changeset for marksmart_product_master_pricesmart_version



CREATE TABLE pricesmart.marksmart_product_master_pricesmart_version (
	version_code int4 NOT NULL,
	currency text NULL,
	l0_id int4 NULL,
	l0_name text NULL,
	l0_cuq text NULL,
	l0_cid int4 NULL,
	l1_name text NULL,
	l1_id int4 NULL,
	l1_cuq text NULL,
	l1_cid int4 NULL,
	l2_name text NULL,
	l2_id int4 NULL,
	l2_cuq text NULL,
	l2_cid int4 NULL,
	l3_name text NULL,
	l3_id int4 NULL,
	l3_cuq text NULL,
	l3_cid int4 NULL,
	l4_id int4 NULL,
	l4_name text NULL,
	l4_cuq text NULL,
	l4_cid int4 NULL,
	brand int4 NULL,
	brand_cid int4 NULL,
	org_brand int4 NULL,
	l5_id int4 NULL,
	l5_name text NULL,
	l5_cuq text NULL,
	l5_cid int4 NULL,
	l6_id int4 NULL,
	l6_name text NULL,
	l6_cuq text NULL,
	l6_cid int4 NULL,
	range_id int4 NULL,
	range_name text NULL,
	product_id int4 NOT NULL,
	product_name text NULL,
	product_cuq text NULL,
	msrp_with_vat float4 NULL,
	current_price_with_vat float4 NULL,
	cost_aud float4 NULL,
	product_lifecycle text NULL,
	drop_ship text NULL,
	status_id int4 NULL,
	status text NULL,
	ecom_age int4 NULL,
	max_age int4 NULL,
	store_age int4 NULL,
	age_month_bucket text NULL,
	vat_rate_per float4 NULL,
	sku text NULL,
	avg_sale_price float4 NULL,
	avg_sale_price_with_vat float4 NULL,
	msrp float4 NULL,
	current_price float4 NULL,
	current_price_aud float4 NULL,
	active bool NULL,
	is_active int4 NOT NULL,
	clearance_indicator int4 NOT NULL,
	"cost" float4 NULL,
	last_reg_price_bnm float4 NULL,
	last_reg_price_bnm_with_vat float4 NULL,
	last_reg_price_ecom float4 NULL,
	last_reg_price_ecom_with_vat float4 NULL,
	current_price_with_vat_aud float4 NULL,
	msrp_with_vat_aud float4 NULL,
	product_lifecycle_id int4 NULL,
	currency_id int4 NULL,
	group_number_id int4 NULL,
	group_number_name text NULL,
	CONSTRAINT marksmart_product_master_pk PRIMARY KEY (version_code, product_id)
)
PARTITION BY LIST (version_code);
CREATE INDEX marksmart_product_master_l0_id_idx_2 ON pricesmart.marksmart_product_master_pricesmart_version USING btree (version_code, l0_id);