import { END_DATE } from "config/constants/index";

export const TIME_PERIOD_FORM_FIELDS = [
  {
    sub_headers: [],
    label: "Start Date",
    accessor: "start_date",
    column_name: "start_date",
    dimension: "Product Mapping",
    field_type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 1,
    is_hidden: false,
    is_required: true,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
  {
    sub_headers: [],
    label: "End Date",
    accessor: "end_date",
    column_name: "end_date",
    dimension: "Product Mapping",
    field_type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 2,
    is_hidden: false,
    is_required: false,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
];

export const SET_ALL_FORM = [
  {
    sub_headers: [],
    label: "Rule Code",
    column_name: "rulecode",
    accessor: "rulecode",
    dimension: "mapping",
    type: "list",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 1,
    is_hidden: false,
    is_required: true,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
  },
  {
    sub_headers: [],
    label: "Start Date",
    column_name: "start_date",
    accessor: "start_date",
    dimension: "mapping",
    type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 2,
    is_hidden: false,
    is_required: true,
    required: true,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
  {
    sub_headers: [],
    label: "End Date",
    column_name: "end_date",
    accessor: "end_date",
    dimension: "mapping",
    type: "DateTimeField",
    is_frozen: false,
    is_editable: true,
    is_aggregated: false,
    order_of_display: 3,
    is_hidden: false,
    is_required: true,
    required: false,
    aggregate_type: null,
    formatter: null,
    is_row_span: false,
    footer: null,
    is_searchable: false,
    extra: {},
    is_sortable: true,
    width: 200,
    is_deleted: false,
    is_master_group: false,
    disablePast: true,
    maxDate: END_DATE,
  },
];
