import makeStyles from "@mui/styles/makeStyles";

export const useStyles = makeStyles((theme) => ({
  pageContainer: {
    background: "#EFF2FA",
    minHeight: "calc(100vh - 3.5rem)",
    display: "flex",
    flexDirection: "column",
  },
  contentWrapper: {
    flex: 1,
    padding: "0 24px 24px 24px",
    display: "flex",
    flexDirection: "column",
    gap: "0",
  },
  /* ── Step Tabs ── */
  stepsContainer: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    marginTop: "12px",
  },
  stepsRow: {
    display: "flex",
    gap: "24px",
    width: "78%",
  },
  stepTab: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    position: "relative",
    cursor: "pointer",
  },
  stepTabInner: {
    width: "100%",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    padding: "8px 12px",
    borderRadius: "12px",
    border: "1.5px solid #E8EAF0",
    background: "#FFFFFF",
    boxShadow: "0 0 12px 8px rgba(0, 0, 0, 0.04)",
    transition: "all 0.2s ease",
  },
  stepTabActive: {
    background: "linear-gradient(90deg, #FFFFFF 0%, #FFFFFF 40%, #F3EEFF 100%)",
    border: "1.5px solid #D6C8FF",
    boxShadow: "0 0 8px 4px rgba(180, 154, 255, 0.10)",
  },
  stepTabContent: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  stepIconWrapper: {
    width: "32px",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  stepIcon: {
    width: "28px",
    height: "28px",
    objectFit: "contain",
  },
  stepTextGroup: {
    display: "flex",
    flexDirection: "column",
  },
  stepTitle: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "16px",
    fontWeight: 800,
    lineHeight: "24px",
    color: "#1F2B4D",
    margin: 0,
  },
  stepSubtitle: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#7A8294",
    margin: 0,
  },
  stepTick: {
    width: "14px",
    height: "14px",
    flexShrink: 0,
  },
  stepArrow: {
    width: 0,
    height: 0,
    borderLeft: "7px solid transparent",
    borderRight: "7px solid transparent",
    borderTop: "8px solid #D6C8FF",
    marginLeft: "36px",
    marginTop: "0px",
  },
  /* ── Form Content Area ── */
  formCard: {
    background: "#FFFFFF",
    borderRadius: "12px",
    border: "1px solid #E8EAF0",
    padding: "24px",
    display: "flex",
    flexDirection: "column",
    flex: 1,
    marginTop: "12px",
  },
  sectionTitle: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "14px",
    fontWeight: 700,
    lineHeight: "21px",
    color: "#1F2B4D",
    margin: "0 0 24px 0",
  },
  formRow: {
    display: "flex",
    gap: "24px",
    marginBottom: "32px",
    alignItems: "flex-end",
    flexWrap: "wrap",
  },
  formField: {
    flex: "1 1 0",
    minWidth: "150px",
    "& > div": {
      width: "100% !important",
      maxWidth: "100% !important",
    },
  },
  fieldLabel: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    color: "#7A8294",
  },
  fieldInput: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#1F2B4D",
    padding: "6px 12px",
    border: "1px solid #D1D5DB",
    borderRadius: "8px",
    background: "#FFFFFF",
    outline: "none",
    height: "32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    cursor: "pointer",
    "&:hover": {
      borderColor: "#9CA3AF",
    },
  },
  fieldValueText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  fieldIcons: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginLeft: "8px",
    flexShrink: 0,
  },
  dropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    background: "#FFFFFF",
    border: "1px solid #D1D5DB",
    borderRadius: "8px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
    zIndex: 10,
    maxHeight: "200px",
    overflowY: "auto",
    marginTop: "4px",
  },
  dropdownItem: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#1F2B4D",
    padding: "8px 12px",
    cursor: "pointer",
    "&:hover": {
      background: "#F4F6FC",
    },
  },
  divider: {
    width: "100%",
    height: 0,
    borderTop: "1px solid #E8EAF0",
    margin: "0 0 32px 0",
  },
  uamRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  uamLabel: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "21px",
    color: "#1F2B4D",
    whiteSpace: "nowrap",
  },
  /* ── Footer ── */
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "12px 24px",
    background: "#FFFFFF",
    borderTop: "1px solid #E8EAF0",
    position: "sticky",
    bottom: 0,
  },
  backLink: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#1F2B4D",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    cursor: "pointer",
    background: "none",
    border: "1px solid #D1D5DB",
    borderRadius: "8px",
    padding: "6px 12px",
    "&:hover": {
      background: "#F4F6FC",
    },
  },
  saveButton: {
    fontFamily: "'Manrope', sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    color: "#FFFFFF",
    background: "#4259EE",
    border: "none",
    borderRadius: "8px",
    padding: "6px 16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "4px",
    "&:hover": {
      background: "#3449D1",
    },
  },
}));
