import makeStyles from "@mui/styles/makeStyles";

export const useExpediteOrdersCardsStyles = makeStyles((theme) => ({
  cardsContainer: {
    display: "flex",
    width: "100%",
    padding: "12px 12px",
    gap: 12,
    alignItems: "stretch",
    borderRadius: 12,
    background: theme.palette.common.white,
    boxShadow: "0px 0px 16px 0px rgba(0, 0, 0, 0.06)",
    minHeight: 141,
    boxSizing: "border-box",
  },
  /** Step-1 wrapper around the cards container + NOTE footnote. */
  kpiPanelStepOne: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    minWidth: 0,
  },
  rows: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
    overflow: "visible",
  },
  pageHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
    width: "100%",
    minWidth: 0,
  },
  pageTitle: {
    fontSize: 16,
    lineHeight: "24px",
    fontWeight: 700,
    color: "#0D152C",
    margin: 0,
    flexShrink: 0,
  },
  pageHeaderRight: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flex: "0 0 auto",
    marginLeft: "auto",
    minWidth: 0,
    overflow: "visible",
  },
  expeditePageRoot: {
    display: "flex",
    flexDirection: "column",
    height: "calc(100vh - 64px)",
    boxSizing: "border-box",
    overflow: "hidden",
    padding: "0 !important",
  },
  expeditePageColumn: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
  },
  expeditePageMain: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
  },
  expediteTopBar: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "16px 24px 12px",
  },
  expediteScrollBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    padding: "4px 24px 16px",
  },
  /* Left section: KPI metric cards + optional footnote (step 1) */
  kpiSectionColumn: {
    display: "flex",
    flex: "1 1 auto",
    flexDirection: "column",
    gap: 8,
    minWidth: 0,
    alignSelf: "stretch",
    justifyContent: "center",
  },
  kpiSection: {
    display: "flex",
    flex: "1 0 0",
    gap: 24,
    alignItems: "center",
    minWidth: 0,
  },
  cardsSeparator: {
    width: 1,
    height: 50,
    background: theme.palette.divider,
    alignSelf: "center",
    flexShrink: 0,
  },
  /* Right section: carousel / CTA */
  rightSection: {
    flex: "0 0 auto",
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    alignSelf: "stretch",
  },

  /* ── Metric KPI Card (node 3216:84184) ── */
  metricCard: {
    flex: "1 0 0",
    minWidth: 220,
    display: "flex",
    flexDirection: "column",
    padding: 16,
    gap: 18,
    borderRadius: 16,
    border: "2px solid #FFF",
    background: "linear-gradient(76.83deg, #FFF 46.051%, #ECEEFD 177.43%)",
    boxShadow: "0px 0px 4px 0px rgba(0, 0, 0, 0.12)",
    alignItems: "flex-end",
  },
  metricTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 8,
  },
  metricIconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: theme.palette.common.white,
    border: "0.5px solid #ECEEFD",
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  metricIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& svg": {
      width: 20,
      height: 20,
      display: "block",
      transform: "scale(0.75)",
      transformOrigin: "center",
    },
  },
  metricTitle: {
    fontSize: 14,
    lineHeight: "20px",
    color: "#60697D",
    fontWeight: 500,
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  metricProgressSection: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    width: "100%",
  },
  miniProgressBar: {
    width: "100%",
    position: "relative",
    "& .MuiLinearProgress-root": {
      height: 8,
      borderRadius: 70,
      background: "linear-gradient(90deg, #FEEAF7 0%, #FFB1B1 100%)",
      overflow: "hidden",
    },
    "& .MuiLinearProgress-bar": {
      borderRadius: 70,
      background: "#3BB273",
    },
  },
  metricValueRow: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    whiteSpace: "nowrap",
  },
  metricValue: {
    fontSize: 20,
    lineHeight: "30px",
    fontWeight: 800,
    color: "#0D152C",
  },
  metricTotal: {
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#31416E",
    textTransform: "capitalize",
  },
  /* ── Lost Sales / Recoverable KPI Card (donut + dual metrics) ── */
  lostSalesKpiCardsRow: {
    display: "flex",
    flex: "1 1 auto",
    width: "100%",
    gap: 12,
    minWidth: 0,
    alignItems: "stretch",
    flexWrap: "wrap",
  },
  lostSalesKpiCard: {
    flex: "1 1 0",
    minWidth: 280,
    alignSelf: "stretch",
    /* Override impact-ui-v3 Card defaults (sx maxWidth:500, minHeight:300). */
    maxWidth: "100% !important",
    width: "100% !important",
    minHeight: "auto !important",
    display: "flex !important",
    flexDirection: "column",
    justifyContent: "center",
    padding: "14px !important",
    borderRadius: "12px !important",
    border: "1px solid #ECEEFD !important",
    background:
      "linear-gradient(135deg, rgba(236, 238, 253, 0.35) 0%, #FFFFFF 65%) !important",
  },
  /* Card body: donut left, right column (header + metrics) right */
  lostSalesKpiBody: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    width: "100%",
    minWidth: 0,
  },
  lostSalesKpiRight: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  /* Header row: icon + title (top-right of card) */
  lostSalesKpiHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
  },
  lostSalesKpiTitle: {
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: 700,
    color: "#0D152C",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  lostSalesKpiIcon: {
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
    "& svg": {
      width: 22,
      height: 22,
      transform: "scale(0.85)",
      transformOrigin: "center",
    },
  },
  /* Two metric columns (each: dot + value/total inline, sub-label below) */
  lostSalesKpiMetricsRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    width: "100%",
    minWidth: 0,
    flexWrap: "nowrap",
  },
  lostSalesKpiMetricCol: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    flex: "1 1 0",
  },
  lostSalesKpiMetricValueRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    whiteSpace: "nowrap",
    minWidth: 0,
    overflow: "hidden",
  },
  lostSalesKpiMetricDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
    display: "inline-block",
  },
  lostSalesKpiMetricValue: {
    fontSize: 15,
    lineHeight: "20px",
    fontWeight: 800,
    color: "#0D152C",
  },
  lostSalesKpiMetricTotal: {
    fontSize: 11,
    lineHeight: "14px",
    fontWeight: 500,
    color: "#60697D",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  lostSalesKpiMetricLabel: {
    fontSize: 11,
    lineHeight: "14px",
    fontWeight: 500,
    color: "#60697D",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    paddingLeft: 14,
  },

  /* Animated wrapper for the compact KPI strip — slides + fades in/out so the
   * transition between the full panel and the sticky strip feels smooth.
   *
   * Implementation notes:
   * - `max-height` is animated from 0 to a generous upper bound; we can't
   *   transition to `auto`, so we pick a value comfortably larger than the
   *   strip's intrinsic height.
   * - `pointerEvents: none` while collapsed prevents the (invisible) strip
   *   from intercepting clicks above the page header. */
  kpiCompactStripContainer: {
    overflow: "hidden",
    maxHeight: 0,
    opacity: 0,
    transform: "translateY(-6px)",
    pointerEvents: "none",
    transition:
      "max-height 220ms ease, opacity 200ms ease, transform 220ms ease, margin-top 220ms ease",
    marginTop: 0,
    willChange: "max-height, opacity, transform",
  },
  kpiCompactStripContainerVisible: {
    maxHeight: 160,
    opacity: 1,
    transform: "translateY(0)",
    pointerEvents: "auto",
    marginTop: 4,
  },

  /* ── Sticky compact KPI strip (rendered in topBar on scroll) ── */
  kpiCompactStrip: {
    display: "flex",
    width: "100%",
    padding: "8px 12px",
    gap: 10,
    alignItems: "stretch",
    borderRadius: 12,
    background: theme.palette.common.white,
    boxShadow: "0px 0px 16px 0px rgba(0, 0, 0, 0.06)",
    boxSizing: "border-box",
    flexWrap: "nowrap",
    overflow: "hidden",
  },
  kpiCompactCard: {
    flex: "1 1 0",
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "8px 12px",
    border: "1px solid #ECEEFD",
    borderRadius: 10,
    background:
      "linear-gradient(135deg, rgba(236, 238, 253, 0.35) 0%, #FFFFFF 65%)",
    boxSizing: "border-box",
    minHeight: 48,
  },
  kpiCompactLeftCol: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
    flex: "0 1 auto",
  },
  kpiCompactTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  kpiCompactIcon: {
    width: 18,
    height: 18,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    "& svg": {
      width: 18,
      height: 18,
      transform: "scale(0.8)",
      transformOrigin: "center",
    },
  },
  kpiCompactTitle: {
    fontSize: 12,
    lineHeight: "16px",
    fontWeight: 700,
    color: "#0D152C",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  kpiCompactBar: {
    width: 90,
    height: 6,
    borderRadius: 70,
    overflow: "hidden",
    position: "relative",
  },
  kpiCompactBarFill: {
    display: "block",
    height: "100%",
    borderRadius: 70,
    transition: "width 0.2s ease",
  },
  kpiCompactMetrics: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    flex: "1 1 0",
    minWidth: 0,
    justifyContent: "flex-end",
  },
  kpiCompactMetricCol: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
    alignItems: "flex-start",
  },
  kpiCompactMetricLabel: {
    fontSize: 10,
    lineHeight: "12px",
    fontWeight: 500,
    color: "#60697D",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  kpiCompactMetricValueRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 3,
    whiteSpace: "nowrap",
  },
  kpiCompactMetricValue: {
    fontSize: 13,
    lineHeight: "16px",
    fontWeight: 800,
    color: "#0D152C",
  },
  kpiCompactMetricTotal: {
    fontSize: 10,
    lineHeight: "12px",
    fontWeight: 500,
    color: "#60697D",
  },
  /* Compact CTA inside the sticky strip */
  ctaCardCompact: {
    flex: "0 0 auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "6px 10px",
    border: "1px solid #ECEEFD",
    borderRadius: 10,
    background:
      "linear-gradient(135deg, rgba(236, 238, 253, 0.35) 0%, rgba(255, 255, 255, 1) 55%, rgba(255, 234, 247, 0.25) 100%)",
    boxSizing: "border-box",
    minHeight: 48,
  },
  kpiCompactCtaEmoji: {
    fontSize: 14,
    lineHeight: 1,
    flexShrink: 0,
  },
  kpiCompactCtaTitle: {
    fontSize: 12,
    lineHeight: "16px",
    fontWeight: 700,
    color: "#31416E",
    whiteSpace: "nowrap",
  },
  kpiCompactCtaButtons: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },

  /* Before/After button group slot, sits beside the title (notification mode). */
  pageHeaderBeforeAfter: {
    display: "flex",
    alignItems: "center",
    flex: "0 0 auto",
    marginLeft: "auto",
  },

  /* Page header: "• N Styles Selected" indicator beside the title. */
  pageTitleSubtitle: {
    fontSize: 13,
    lineHeight: "20px",
    fontWeight: 500,
    color: "#60697D",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    marginLeft: 8,
    "&::before": {
      content: '"•"',
      color: "#60697D",
    },
  },

  /* ── Generated Order Card (Figma 3184:95537 — actions 12px gap, hover-reveal) ── */
  generatedOrderCard: {
    background: theme.palette.common.white,
    border: "1px solid #ECEEFD",
    borderRadius: 12,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    flexShrink: 0,
    boxSizing: "border-box",
    maxWidth: "fit-content",
    width: "100%",
    position: "relative",
    "&:hover $generatedOrderCardActions": {
      opacity: 1,
      pointerEvents: "auto",
    },
  },
  generatedOrderCardTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    minWidth: 0,
  },
  generatedOrderCardTitleGroup: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
    flex: 1,
  },
  generatedOrderCardIconBox: {
    width: 36,
    height: 36,
    borderRadius: 11,
    background: "linear-gradient(143.6deg, #F0DFFB 5.57%, #F6EDFD 122.58%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
    position: "relative",
    "& img": {
      width: 24,
      height: 24,
      objectFit: "contain",
    },
    "& svg": {
      width: 22,
      height: 22,
      color: "#9C5FC1",
    },
  },
  generatedOrderCardOrderId: {
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "16px",
    color: "#60697D",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textTransform: "capitalize",
  },
  generatedOrderCardActions: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexShrink: 0,
    opacity: 0,
    pointerEvents: "none",
    transition: "opacity 0.15s ease",
  },
  generatedOrderCardIconAction: {
    minWidth: 28,
    maxHeight: 28,
    padding: "6px !important",
  },
  generatedOrderCardStatsRow: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 32,
    width: "100%",
  },
  generatedOrderCardStatCol: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-start",
    justifyContent: "center",
    minWidth: 0,
  },
  generatedOrderCardStatLabel: {
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    color: "#60697D",
    textTransform: "capitalize",
    whiteSpace: "nowrap",
  },
  generatedOrderCardStatValue: {
    fontSize: 14,
    fontWeight: 800,
    lineHeight: "21px",
    color: "#31416E",
    whiteSpace: "nowrap",
  },

  /* ── CTA Card (step 1) — sibling of the two donut cards inside cardsContainer.
     Fixed width is sized so the two action buttons fit on a single row. */
  ctaCard: {
    flex: "0 0 320px",
    minWidth: 280,
    alignSelf: "stretch",
    border: "1px solid #ECEEFD",
    borderRadius: 12,
    background:
      "linear-gradient(135deg, rgba(236, 238, 253, 0.35) 0%, rgba(255, 255, 255, 1) 55%, rgba(255, 234, 247, 0.25) 100%)",
    padding: 12,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 10,
    boxShadow: "0 0 4px 0 rgba(0, 0, 0, 0.12)",
    boxSizing: "border-box",
  },
  ctaCardContent: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    minWidth: 0,
  },
  ctaIconWrapper: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: theme.palette.common.white,
    border: "0.5px solid #ECEEFD",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  ctaEmoji: {
    fontSize: 16,
    lineHeight: 1,
  },
  ctaTextBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 0,
  },
  ctaTitle: {
    fontSize: 13,
    lineHeight: "18px",
    fontWeight: 700,
    color: "#31416E",
  },
  ctaDesc: {
    fontSize: 11,
    lineHeight: "14px",
    color: "#60697D",
    maxWidth: 360,
  },
  ctaButtonsRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "nowrap",
    width: "100%",
  },
  ctaButton: {
    fontSize: "12px !important",
    padding: "6px 10px !important",
    minHeight: "28px !important",
    height: "28px !important",
    minWidth: "0 !important",
    whiteSpace: "nowrap",
    flex: "0 0 auto",
  },

  /* ── Bottom navigation (Figma 3060:65850) ── */
  expediteBottomNav: {
    flexShrink: 0,
    zIndex: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
    padding: "12px 24px",
    marginTop: 0,
    width: "100%",
    boxSizing: "border-box",
    borderTop: `1px solid ${theme.palette.divider}`,
    background: theme.palette.common.white,
  },
  expediteBottomNavBack: {
    borderColor: "#C3C8D4",
    color: "#1F2B4D",
  },
  expediteBottomNavRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  expediteBottomNavCancel: {
    background: "#F5F6FA !important",
    color: "#60697D",
  },
  expediteBottomNavFinalize: {
    "&.Mui-disabled": {
      background: "#C3C8D4 !important",
      color: "#FFFFFF !important",
    },
  },

  /* ── Generated Orders Carousel ── */
  carouselRoot: {
    display: "flex",
    flex: 1,
    alignItems: "center",
    gap: 12,
    alignSelf: "stretch",
    minWidth: 0,
  },
  carouselNavBtn: {
    width: 32,
    height: 32,
    border: `1px solid ${theme.palette.divider}`,
    borderRadius: 8,
    background: theme.palette.common.white,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    cursor: "pointer",
    padding: 0,
    "&:hover": {
      background: "#F5F6FF",
    },
    "&:disabled": {
      opacity: 0.35,
      cursor: "not-allowed",
    },
  },
  carouselTrack: {
    flex: 1,
    display: "flex",
    gap: 12,
    overflowX: "hidden",
    minWidth: 0,
    alignSelf: "stretch",
    alignItems: "center",
  },

  responsiveWrap: {
    [theme.breakpoints.down("md")]: {
      flexWrap: "wrap",
    },
  },
  [theme.breakpoints.down("md")]: {
    cardsSeparator: {
      display: "none",
    },
    kpiSection: {
      flexWrap: "wrap",
    },
  },
}));
