--liquibase formatted sql
--changeset liquibase:promo_txn_basket_0206 stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for promo_txn_basket


CREATE TABLE price_promo_opt.promo_txn_basket (
	product_id int4 NULL,
	transaction_id text NULL,
	date_id date NULL,
	store_id int4 NULL,
	currency text NULL,
	currency_id int4 NULL,
	no_of_txn int4 NULL,
	"cost" float4 NULL,
	base_price_with_vat float4 NULL,
	base_price float4 NULL,
	base_price_secondary int4 NULL,
	retail_price_with_vat float4 NULL,
	retail_price float4 NULL,
	gross_quantity int4 NULL,
	gross_revenue float4 NULL,
	gross_revenue_with_vat float4 NULL,
	gross_margin float4 NULL,
	gross_margin_with_vat float4 NULL,
	gross_sp_with_vat float4 NULL,
	gross_sp float4 NULL,
	gross_dis_amount_with_vat float4 NULL,
	gross_dis_amount float4 NULL,
	gross_dis_perc float4 NULL,
	gross_dis_perc_with_vat float4 NULL,
	final_discount_percent_with_vat float4 NULL,
	final_discount_percent float4 NULL,
	final_amount float4 NULL,
	final_amount_with_vat float4 NULL,
	promo_amount float4 NULL,
	promo_amount_with_vat float4 NULL,
	promo_discount float4 NULL,
	promo_discount_with_vat float4 NULL,
	coupon_amount_with_vat float4 NULL,
	coupon_amount float4 NULL,
	coupon_discount float4 NULL,
	coupon_discount_with_vat float4 NULL,
	aur float4 NULL,
	aur_with_vat float4 NULL,
	aum float4 NULL,
	aum_with_vat float4 NULL,
	total_inv int4 NULL,
	vat_rate_per float4 NULL,
	clearance_indicator int4 NULL
);