--liquibase formatted sql
--changeset pavankumar.reddy@impactanalytics.co:fiscal_date_mapping  stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for fiscal_date_mapping

CREATE TABLE "global".fiscal_date_mapping (
	fiscal_day int2 NULL,
	fiscal_week_in_month int2 NULL,
	fiscal_week_in_quarter int2 NULL,
	fiscal_day_name varchar NULL,
	fiscal_week_begin_date date NULL,
	fiscal_week_end_date date NULL,
	fiscal_year_month int4 NULL,
	fiscal_day_name_abb varchar NULL,
	fiscal_month_in_quarter int2 NULL,
	fiscal_month_in_year int2 NULL,
	fiscal_month_begin_date date NULL,
	fiscal_week_in_season int2 NULL,
	fiscal_month_end_date date NULL,
	fiscal_quarter_in_year int2 NULL,
	fiscal_year_week_prior int4 NULL,
	fiscal_year_week_2wa int4 NULL,
	fiscal_quarter_begin_date date NULL,
	fiscal_quarter_end_date date NULL,
	fiscal_year_begin_date date NULL,
	fiscal_month_in_season int2 NULL,
	fiscal_year_end_date date NULL,
	fiscal_day_in_week int2 NULL,
	fiscal_prior_year_comp_week int4 NULL,
	fiscal_season_begin_date date NULL,
	fiscal_week int2 NULL,
	fiscal_quarter_name varchar NULL,
	fiscal_quarter_name_abb varchar NULL,
	fiscal_year_quarter_prior int4 NULL,
	fiscal_week_in_year int2 NULL,
	fiscal_season_in_year int2 NULL,
	fiscal_season_end_date date NULL,
	fiscal_year_season_prior int2 NULL,
	calendar_date date NULL,
	date_id int4 NULL,
	weekday_indicator varchar NULL,
	fiscal_quarter_in_season int2 NULL,
	fiscal_month_name varchar NULL,
	fiscal_month_name_abb varchar NULL,
	fiscal_year_month_prior int4 NULL,
	fiscal_year_period int4 NULL,
	fiscal_day_in_season int2 NULL,
	fiscal_day_in_quarter int2 NULL,
	fiscal_year_week int4 NULL,
	fiscal_bi_week int2 NULL,
	fiscal_day_in_year int2 NULL,
	day_of_week int2 NULL,
	"date" date NOT NULL,
	fiscal_day_in_month int2 NULL,
	fiscal_year_quarter int4 NULL,
	fiscal_season_name varchar NULL,
	fiscal_season_name_abb varchar NULL,
	fiscal_month int2 NULL,
	fiscal_quarter int2 NULL,
	fiscal_year int2 NULL,
	fiscal_year_week_3wa int4 NULL,
	fiscal_year_season int2 NULL,
	trend int4 NULL,
	holiday varchar NULL,
	cal_week_end_day date NULL,
	cal_week_start_day date NULL,
	fiscal_half_year int4 NULL,
	half_year_name varchar NULL,
	gregorian_year int4 NULL,
	gregorian_quarter int4 NULL,
	gregorian_month int4 NULL,
	gregorian_day_of_week varchar NULL,
	gregorian_day_of_month int4 NULL,
	gregorian_day_of_year int4 NULL,
	gregorian_is_weekend bool NULL,
	gregorian_month_name varchar NULL,
	gregorian_quarter_year varchar NULL,
	gregorian_year_month int4 NULL,
	gregorian_week int4 NULL,
	CONSTRAINT date_un PRIMARY KEY (date)
);
CREATE INDEX fiscal_date_mapping_date_idx ON global.fiscal_date_mapping USING btree (date);
CREATE INDEX idx_calendar_date ON global.fiscal_date_mapping USING btree (calendar_date);
CREATE INDEX idx_fiscal_year_month ON global.fiscal_date_mapping USING btree (fiscal_year_month);

--changeset pavankumar.reddy@impactanalytics.co:fiscal_date_mapping_vp_2  stripComments:false splitStatements:false context:v2 labels:liquibase_project_start_02_03
--comment: making datatype changes for fiscal_date_mapping
ALTER TABLE "global".fiscal_date_mapping
ALTER COLUMN fiscal_day TYPE int8,
ALTER COLUMN fiscal_week_in_month TYPE int8,
ALTER COLUMN fiscal_week_in_quarter TYPE int8,
ALTER COLUMN fiscal_year_month TYPE int8,
ALTER COLUMN fiscal_month_in_quarter TYPE int8,
ALTER COLUMN fiscal_month_in_year TYPE int8,
ALTER COLUMN fiscal_week_in_season TYPE int8,
ALTER COLUMN fiscal_quarter_in_year TYPE int8,
ALTER COLUMN fiscal_year_week_prior TYPE int8,
ALTER COLUMN fiscal_year_week_2wa TYPE int8,
ALTER COLUMN fiscal_month_in_season TYPE int8,
ALTER COLUMN fiscal_day_in_week TYPE int8,
ALTER COLUMN fiscal_prior_year_comp_week TYPE int8,
ALTER COLUMN fiscal_week TYPE int8,
ALTER COLUMN fiscal_year_quarter_prior TYPE int8,
ALTER COLUMN fiscal_week_in_year TYPE int8,
ALTER COLUMN fiscal_season_in_year TYPE int8,
ALTER COLUMN fiscal_year_season_prior TYPE int8,
ALTER COLUMN date_id TYPE int8,
ALTER COLUMN fiscal_quarter_in_season TYPE int8,
ALTER COLUMN fiscal_year_month_prior TYPE int8,
ALTER COLUMN fiscal_year_period TYPE int8,
ALTER COLUMN fiscal_day_in_season TYPE int8,
ALTER COLUMN fiscal_day_in_quarter TYPE int8,
ALTER COLUMN fiscal_year_week TYPE int8,
ALTER COLUMN fiscal_bi_week TYPE int8,
ALTER COLUMN fiscal_day_in_year TYPE int8,
ALTER COLUMN day_of_week TYPE int8,
ALTER COLUMN fiscal_day_in_month TYPE int8,
ALTER COLUMN fiscal_year_quarter TYPE int8,
ALTER COLUMN fiscal_month TYPE int8,
ALTER COLUMN fiscal_quarter TYPE int8,
ALTER COLUMN fiscal_year TYPE int8,
ALTER COLUMN fiscal_year_week_3wa TYPE int8,
ALTER COLUMN fiscal_year_season TYPE int8,
ALTER COLUMN trend TYPE int8,
ALTER COLUMN fiscal_half_year TYPE int8,
ALTER COLUMN gregorian_year TYPE int8,
ALTER COLUMN gregorian_quarter TYPE int8,
ALTER COLUMN gregorian_month TYPE int8,
ALTER COLUMN gregorian_day_of_month TYPE int8,
ALTER COLUMN gregorian_day_of_year TYPE int8,
ALTER COLUMN gregorian_year_month TYPE int8,
ALTER COLUMN gregorian_week TYPE int8;