--liquibase formatted sql
--changeset pavankumar.reddy@impactanalytics.co:product_attributes_filter  stripComments:false splitStatements:false context:Release_1_0 labels:liquibase_project_start
--comment: initial changeset for product_attributes_filter

CREATE TABLE "global".product_attributes_filter (
	merchandise_category_sap_id text NULL,
	article_merchandise_category_sap_id int4 NULL,
	article_merchandise_category_sap_desc text NULL,
	created_timestamp timestamp NULL,
	updated_timestamp timestamp NULL,
	product_code varchar NOT NULL,
	product_name varchar NOT NULL,
	price numeric NULL,
	"cost" numeric NULL,
	original_price numeric NULL,
	l0_id varchar NOT NULL,
	l0_name varchar NOT NULL,
	l1_id varchar NOT NULL,
	l1_name varchar NULL,
	l2_id varchar NOT NULL,
	l2_name varchar NULL,
	l3_id varchar NOT NULL,
	l3_name varchar NULL,
	color_id varchar NULL,
	color_desc varchar NULL,
	color_family_name varchar NULL,
	size_id varchar NULL,
	size_desc varchar NULL,
	brand varchar NULL,
	vendor_id varchar NULL,
	rcl_hash jsonb DEFAULT '{}'::jsonb NULL,
	vendor_name varchar NULL,
	fashion_grade varchar NULL,
	product_life_cycle varchar NULL,
	product_status numeric NULL,
	season_code numeric NULL,
	season_code_desc varchar NULL,
	style_id numeric NULL,
	style_name varchar NULL,
	"type" numeric NULL,
	category_id numeric NULL,
	category_name varchar NULL,
	sub_category_id numeric NULL,
	sub_category_name varchar NULL,
	brand_id varchar NULL,
	product_lifecycle_id numeric NULL,
	l4_id varchar NULL,
	l4_name varchar NULL,
	program_id varchar NULL,
	program_name varchar NULL,
	laenderzuordnung varchar NULL,
	article varchar NOT NULL,
	detail_id numeric NULL,
	detail_desc varchar NULL,
	division_id numeric NULL,
	purchasing_division_id numeric NULL,
	merchandise_group_id numeric NULL,
	merchandise_category_id numeric NULL,
	active bool NULL,
	is_deleted bool NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	replacement_product_codes _varchar NULL,
	reference_product_codes _varchar NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	product_description text NULL,
	receipt_date date NULL,
	clearance bool NULL,
	sammelartikel varchar NULL,
	target_group varchar NULL,
	target_group_description varchar NULL,
	price_strategy varchar NULL,
	merchandising_unit varchar NULL,
	merchandising_unit_description varchar NULL,
	fit_type varchar NULL,
	check_list varchar NULL,
	ak_sa varchar NULL,
	CONSTRAINT product_attributes_filter_pk PRIMARY KEY (product_code, l0_name),
	CONSTRAINT product_attributes_filter_fk FOREIGN KEY (product_code) REFERENCES "global".product_master(product_code) ON DELETE CASCADE
)
PARTITION BY LIST (l0_name);
CREATE INDEX paf_article_combine_idx ON  global.product_attributes_filter USING btree (l0_name, article, product_code) WHERE (active AND (NOT is_deleted));
CREATE INDEX paf_hash_combine_idx ON  global.product_attributes_filter USING btree (l0_name, l1_name, l2_name, l3_name, l4_name, product_code, rcl_hash) WHERE (active AND (NOT is_deleted));
CREATE INDEX product_attributes_filter_product_code_idx ON  global.product_attributes_filter USING btree (product_code);