import { makeStyles } from "@mui/styles";

export const useInfoPanelStyles = makeStyles(() => ({
  triggerBtn: {
    appearance: "none",
    WebkitAppearance: "none",
    margin: 0,
    width: 32,
    height: 32,
    minWidth: 32,
    minHeight: 32,
    maxWidth: 32,
    maxHeight: 32,
    padding: 8,
    boxSizing: "border-box",
    backgroundColor: "#fff",
    border: "1px solid #c3c8d4",
    borderRadius: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    lineHeight: 0,
    "&:hover, &:active, &:focus": {
      backgroundColor: "#eceefd",
      border: "1px solid #3649c6",
      outline: "none",
    },
    "&:hover $triggerIcon path, &:active $triggerIcon path, &:focus $triggerIcon path": {
      fill: "#3649c6",
    },
  },
  triggerIcon: {
    width: 16,
    height: 16,
    display: "block",
    flexShrink: 0,
  },
  body: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
    fontFamily: "Manrope",
  },
  subtitle: {
    fontFamily: "Manrope",
    fontWeight: 500,
    fontSize: 12,
    lineHeight: "16px",
    color: "#60697d",
    margin: 0,
    textTransform: "capitalize",
  },
  sectionList: {
    overflowY: "auto",
    padding: 2,
  },
  sectionBody: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    width: "100%",
    padding: 0,
  },
  item: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 4,
    width: "100%",
    boxSizing: "border-box",
    backgroundColor: "#f5f6fa",
    borderRadius: 8,
    padding: 8,
  },
  itemTerm: {
    fontFamily: "Manrope",
    fontWeight: 800,
    fontSize: 14,
    lineHeight: "21px",
    color: "#60697d",
  },
  itemDefinition: {
    fontFamily: "Manrope",
    fontWeight: 600,
    fontSize: 14,
    lineHeight: "21px",
    color: "#1f2b4d",
    whiteSpace: "pre-line",
  },
}));
